.travis.yml, bundler/Cargo.toml, ecmascript/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/src/react.rs, ecmascript/transforms/src/react/jsx.rs, ecmascript/transforms/src/react/jsx/tests.rs, ecmascript/transforms/src/tests.rs, ecmascript/transforms/tests/common/mod.rs, ecmascript/transforms/tests/es2015_classes.rs, src/config.rs
swc_ecma_transforms
- Support jsx pragma (Closes #107, Closes #838)
=> Support jsx pragma

ecmascript/src/lib.rs
Forgot to expose `dep_graph` crate root in #1010 🤦
=> fix: expose dep_graph crate

ecmascript/transforms/Cargo.toml, ecmascript/transforms/src/compat/es2015/block_scoping.rs
swc_ecma_transforms
- block_scoping: Handle this (Closes #1021)
- block_scoping: Handle variable mutation in for loops (Closes #1022)
=> Fix block scoping

ecmascript/transforms/src/fixer.rs, package.json
=> fixer: Handle binary expression in callee of new

.github/workflows/publish.yml
Close https://github.com/swc-project/swc/issues/1039
=> Fix macos 10.13 compatible problem

package.json
`--dry-run` and tested on local
=> Fix artifacts scripts

bundler/src/lib.rs, ecmascript/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/src/resolver.rs, ecmascript/transforms/src/resolver/tests.rs
Required by https://github.com/denoland/deno_lint/pull/304
=> Fix ts_resolver

ecmascript/transforms/Cargo.toml, ecmascript/transforms/src/fixer.rs
=> fixer: Handle conditional expression in callee

ecmascript/transforms/Cargo.toml, ecmascript/transforms/src/resolver.rs
Related: https://github.com/denoland/deno_lint/pull/307
=> resolver: Handle constructor properly

ecmascript/transforms/Cargo.toml, ecmascript/transforms/src/modules/common_js.rs, ecmascript/transforms/tests/modules_common_js.rs
=> common_js: Change order of exports

.github/workflows/integration.yml, .github/workflows/publish-node.yml, .github/workflows/publish-wasm.yml, ecmascript/ast/src/lib.rs, wasm/Cargo.toml, wasm/src/lib.rs
=> wasm: Automatic deployment

ecmascript/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/src/typescript/strip.rs, ecmascript/transforms/tests/typescript_strip.rs
Closes #1065.
Closes #1094.
@kdy1 Could you cut a release after this?
=> fix(strip): Fix Config::import_not_used_as_values

bundler/Cargo.toml, bundler/src/bundler/chunk/export.rs
=> bundler: Fix reexports

bundler/Cargo.toml, bundler/src/bundler/chunk/circular.rs, ecmascript/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/src/hygiene/ops.rs, spack/tests/pass/circular/complex-class-function/output/entry.js, spack/tests/pass/circular/top-level-idents/output/entry.js, spack/tests/pass/issue-1138/example-3/input/.swcrc, spack/tests/pass/issue-1138/example-3/input/a.ts, spack/tests/pass/issue-1138/example-3/input/entry.js, spack/tests/pass/issue-1138/example-3/input/l.ts, spack/tests/pass/issue-1138/example-3/output/entry.js, spack/tests/pass/issue-1139/example-1/output/entry.js, spack/tests/pass/issue-1139/example-2/output/entry.js
swc_bundler:
- Change order of execution of modules with circular imports. (#1139)
swc_ecma_transforms:
- hygiene: Fix handling of default in object patterns. (#1138)
=> Fix hygiene and bundler

common/Cargo.toml, common/src/syntax_pos.rs, common/src/syntax_pos/hygiene.rs, ecmascript/ast/Cargo.toml, ecmascript/ast/src/class.rs, ecmascript/ast/src/decl.rs, ecmascript/ast/src/expr.rs, ecmascript/ast/src/function.rs, ecmascript/ast/src/ident.rs, ecmascript/ast/src/jsx.rs, ecmascript/ast/src/lib.rs, ecmascript/ast/src/lit.rs, ecmascript/ast/src/module.rs, ecmascript/ast/src/module_decl.rs, ecmascript/ast/src/operators.rs, ecmascript/ast/src/pat.rs, ecmascript/ast/src/prop.rs, ecmascript/ast/src/stmt.rs, ecmascript/ast/src/typescript.rs
swc_common:
- Add support for fuzzing.
swc_ecma_ast:
- Add support for fuzzing.
=> ast: Add support for fuzzing

bundler/Cargo.toml, bundler/src/bundler/chunk/mod.rs, bundler/src/bundler/finalize.rs, bundler/tests/deno.rs, ecmascript/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/src/resolver/tests.rs, package.json
swc_bundler:
- Fix for https://deno.land/x/oak@v6.3.1/examples/sseServer.ts
=> bundler: Fix ordering

visit/Cargo.toml, visit/macros/src/lib.rs, visit/src/lib.rs
swc_visit:
- Add `VisitAll`, which always visits all children.
=> Visitor refinements

ecmascript/transforms/src/helpers/_type_of.js
=> Fix: _typeof helper throws in environments where Symbol is not defined

ecmascript/Cargo.toml, ecmascript/codegen/Cargo.toml, ecmascript/codegen/src/stmt.rs, ecmascript/codegen/src/util.rs
=> Preserve space for postfix unary operators

bundler/Cargo.toml, bundler/src/bundler/chunk/merge.rs, bundler/src/bundler/chunk/plan/lca.rs, bundler/src/bundler/chunk/plan/mod.rs, bundler/src/bundler/chunk/plan/tests.rs, bundler/src/id.rs, bundler/tests/deno.rs, bundler/tests/fixture/deno-8211-1/input/entry.ts, bundler/tests/fixture/deno-8211-1/input/fixedOffsetZone.ts, bundler/tests/fixture/deno-8211-1/input/zone.ts, bundler/tests/fixture/deno-8211-1/output/entry.ts, bundler/tests/fixture/deno-8211-2/input/entry.ts, bundler/tests/fixture/deno-8211-2/input/fixedOffsetZone.ts, bundler/tests/fixture/deno-8211-2/input/info.ts, bundler/tests/fixture/deno-8211-2/input/zone.ts, bundler/tests/fixture/deno-8211-2/output/entry.ts
swc_bundler:
Fixes https://github.com/denoland/deno/issues/8211
=> Fix bundler: luxon.js

bundler/examples/path.rs, bundler/src/bundler/chunk/merge.rs, bundler/src/bundler/tests.rs, bundler/src/hook.rs, bundler/src/lib.rs, bundler/tests/deno.rs, bundler/tests/fixture.rs, native/Cargo.toml, native/src/bundle.rs, spack/tests/fixture.rs, spack/tests/pass/pr-1105/example-7/input/entry.js, spack/tests/pass/pr-1105/example-7/output/entry.js
Addresses https://github.com/denoland/deno/issues/8088.
=> BREAKING(bundler): Change Hook API to get_import_meta_props()

ecmascript/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/src/resolver.rs, ecmascript/transforms/src/resolver/tests.rs
swc_ecma_transforms:
- resolver: Handle class declarations (Fixes denoland/deno_lint#463)
=> resolver: handle class declarations

bundler/src/bundler/chunk/merge.rs, spack/tests/pass/pr-1105/example-7/output/entry.js
Addresses https://github.com/swc-project/swc/pull/1195#discussion_r515356646. Supports mutations on `import.meta`.
=> fix(bundler): Use a local variable for import.meta

bundler/Cargo.toml, bundler/examples/path.rs, bundler/src/bundler/chunk/export.rs, bundler/src/bundler/chunk/merge.rs, bundler/src/bundler/finalize.rs, bundler/src/bundler/helpers/mod.rs, bundler/src/bundler/load.rs, bundler/src/bundler/tests.rs, bundler/src/lib.rs, bundler/src/load.rs, bundler/tests/deno.rs, bundler/tests/fixture.rs, ecmascript/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/src/helpers.rs, ecmascript/transforms/src/optimization/simplify/dce/mod.rs, ecmascript/transforms/src/quote.rs, ecmascript/transforms/tests/optimization_simplify_dce.rs, spack/src/loaders/swc.rs, spack/tests/pass/helpers/simple/input/.swcrc, spack/tests/pass/helpers/simple/input/entry.js, spack/tests/pass/helpers/simple/output/entry.js, src/builder.rs, src/config.rs
swc_bundler:
- Handle helpers from `swc_ecma_transforms`.
swc_ecma_transforms:
- dce: Remove unused self-referential functions.
=> bundler: Handle swc helpers

bundler/Cargo.toml, bundler/src/bundler/chunk/computed_key.rs, bundler/src/bundler/chunk/export.rs, bundler/src/bundler/mod.rs, bundler/tests/deno.rs, bundler/tests/deno/deno-8211-1/input/entry.ts, spack/tests/pass/pr-1105/example-2/output/entry.js
=> Fix bundler

Cargo.toml, bundler/Cargo.toml, ecmascript/Cargo.toml, ecmascript/ast/Cargo.toml, ecmascript/ast/src/lib.rs, ecmascript/codegen/Cargo.toml, ecmascript/dep-graph/Cargo.toml, ecmascript/ext-transforms/Cargo.toml, ecmascript/jsdoc/Cargo.toml, ecmascript/parser/Cargo.toml, ecmascript/parser/src/lib.rs, ecmascript/preset_env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/proposal/Cargo.toml, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/testing/Cargo.toml, ecmascript/transforms/typescript/Cargo.toml, ecmascript/utils/Cargo.toml, ecmascript/visit/Cargo.toml
swc_ecma_ast:
- Add `EsVersion`.
- Remove `JscTarget`.
- Reexport `EsVersion` as `JscTarget`.
=> fix(es): Move and rename JscTarget

.github/workflows/compilation.yml, Cargo.toml, bundler/Cargo.toml, ecmascript/Cargo.toml, ecmascript/ast/Cargo.toml, ecmascript/ast/src/decl.rs, ecmascript/codegen/Cargo.toml, ecmascript/dep-graph/Cargo.toml, ecmascript/ext-transforms/Cargo.toml, ecmascript/jsdoc/Cargo.toml, ecmascript/parser/Cargo.toml, ecmascript/preset_env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/proposal/Cargo.toml, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/testing/Cargo.toml, ecmascript/transforms/typescript/Cargo.toml, ecmascript/utils/Cargo.toml, ecmascript/visit/Cargo.toml
swc_ecma_ast:
- Fix compilation.
---
Closes #1312
=> fix(es/ast): Compilation

Cargo.toml, bundler/Cargo.toml, ecmascript/Cargo.toml, ecmascript/ast/Cargo.toml, ecmascript/ast/src/lit.rs, ecmascript/codegen/Cargo.toml, ecmascript/dep-graph/Cargo.toml, ecmascript/ext-transforms/Cargo.toml, ecmascript/jsdoc/Cargo.toml, ecmascript/parser/Cargo.toml, ecmascript/preset_env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/proposal/Cargo.toml, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/testing/Cargo.toml, ecmascript/transforms/typescript/Cargo.toml, ecmascript/utils/Cargo.toml, ecmascript/visit/Cargo.toml
swc_ecma_ast:
- Make `EqIgnoreSpan`  impl of` StrKind` always return true .
=> fix(es/ast): Fix EqIgnoreSpan

bundler/Cargo.toml, bundler/src/bundler/finalize.rs
Related to https://github.com/denoland/deno/pull/9291.
swc_bundler:
- Invoke iife handler before fixer.
=> fix(bundler): Fix pass ordering

Cargo.toml, bundler/Cargo.toml, ecmascript/Cargo.toml, ecmascript/codegen/Cargo.toml, ecmascript/dep-graph/Cargo.toml, ecmascript/ext-transforms/Cargo.toml, ecmascript/jsdoc/Cargo.toml, ecmascript/parser/Cargo.toml, ecmascript/parser/src/error.rs, ecmascript/preset_env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/proposal/Cargo.toml, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/testing/Cargo.toml, ecmascript/transforms/typescript/Cargo.toml
Right now there doesn't seem to be a way to take a look at the error kind without converting the `Error` into a `SyntaxError`.
Thoughts on this? (I did not run tests because so this may fail on the CI)
=> Ability to look at the kind of an error

spack/src/resolvers/mod.rs
=> Default Path as root for resolver without allocate

ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/base/src/ext.rs, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/react/src/jsx/mod.rs
- Implement `MapWithMut` for more types.
swc_ecma_transforms_react:
- Migrate to `VisitMut`.
=> fix(es/transforms/react): Use VisitMut instead of Fold

CONTRIBUTING.md, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/base/src/resolver/mod.rs, ecmascript/transforms/base/src/resolver/tests.rs
=> fix(es/transforms/base): Fix span hygiene of type elements

.github/workflows/cargo.yml, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/base/src/fixer.rs
=> fix(es/transforms/fixer): Fix await expressions.

.github/workflows/cargo.yml, deny.toml, ecmascript/transforms/base/src/fixer.rs, tests/fixture/issue-1309/case1/input/.swcrc, tests/fixture/issue-1309/case1/input/index.ts, tests/fixture/issue-1309/case1/output/index.map, tests/fixture/issue-1309/case1/output/index.ts, tests/projects.rs
=> fix(es/transforms/base): Fix fixer

.vscode/settings.json, ecmascript/transforms/typescript/src/strip.rs, ecmascript/transforms/typescript/tests/strip.rs
=> fix(strip): Precompute class field keys

bundler/tests/fixture/deno-9591/output/entry.inlined.ts, bundler/tests/fixture/deno-9591/output/entry.ts, ecmascript/codegen/src/lib.rs, ecmascript/transforms/tests/decorators.rs, ecmascript/transforms/typescript/Cargo.toml, ecmascript/transforms/typescript/src/strip.rs, ecmascript/transforms/typescript/tests/strip.rs
=> fix(strip): Expand class expressions as sequences

Cargo.toml, bundler/Cargo.toml, ecmascript/Cargo.toml, ecmascript/ast/Cargo.toml, ecmascript/ast/src/lib.rs, ecmascript/ast/src/typescript.rs, ecmascript/codegen/Cargo.toml, ecmascript/codegen/src/typescript.rs, ecmascript/dep-graph/Cargo.toml, ecmascript/ext-transforms/Cargo.toml, ecmascript/jsdoc/Cargo.toml, ecmascript/loader/Cargo.toml, ecmascript/parser/Cargo.toml, ecmascript/parser/tests/span.rs, ecmascript/preset_env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/base/src/resolver/mod.rs, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/proposal/Cargo.toml, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/testing/Cargo.toml, ecmascript/transforms/typescript/Cargo.toml, ecmascript/utils/Cargo.toml, ecmascript/visit/Cargo.toml, ecmascript/visit/src/lib.rs, node-swc/src/types.ts
I don't need this, so feel free to merge whenever.
Closes #1251.
=> Remove unused TsSignatureDecl

ecmascript/transforms/module/src/common_js.rs, ecmascript/transforms/module/src/import_analysis.rs, ecmascript/transforms/module/src/util.rs, ecmascript/transforms/module/tests/common_js.rs, ecmascript/transforms/react/src/refresh/tests.rs, node-swc/__tests__/transform/issue_1581_test.js, node-swc/tests/issue-1581/.swcrc, node-swc/tests/issue-1581/foo.ts, tests/fixture/issue-1525/case1/input/.swcrc, tests/fixture/issue-1525/case1/input/index.ts, tests/fixture/issue-1525/case1/input/index.tsx, tests/fixture/issue-1525/case1/output/index.tsx, tests/fixture/issue-1568/case1/input/.swcrc, tests/fixture/issue-1568/case1/input/index.ts, tests/fixture/issue-1568/case1/output/index.ts
swc_ecma_transforms_module:
swc:
=> fix: Fix various bugs

ecmascript/parser/Cargo.toml, ecmascript/parser/src/parser/class_and_fn.rs, ecmascript/parser/tests/typescript/issue-1454/case2/input.ts, ecmascript/parser/tests/typescript/issue-1454/case2/input.ts.json, ecmascript/parser/tests/typescript/issue-1454/case3/input.ts, ecmascript/parser/tests/typescript/issue-1454/case3/input.ts.json, ecmascript/transforms/compat/src/es2020/export_namespace_from.rs, ecmascript/utils/Cargo.toml, tests/fixture/issue-1454/case2/input/.swcrc, tests/fixture/issue-1454/case2/input/index.ts, tests/fixture/issue-1454/case2/output/index.ts, tests/fixture/issue-1454/case3/input/index.ts, tests/fixture/issue-1454/case3/output/index.ts, tests/fixture/issue-1457/case1/output/index.ts, tests/fixture/issue-1457/case3-es2019/output/index.ts, tests/fixture/issue-1457/case4-es2018/output/index.ts, tests/fixture/issue-1457/case5-es2017/output/index.ts, tests/fixture/issue-1457/case6-es2016/output/index.ts, tests/fixture/issue-1457/case7-es2015/output/index.ts, tests/fixture/issue-1457/case8-es5/output/index.ts, tests/fixture/issue-1457/case9-es3/output/index.ts
=> fix(swc): Fix bugs

.github/workflows/cargo.yml, bundler/Cargo.toml, bundler/src/bundler/chunk/merge.rs, bundler/src/bundler/chunk/mod.rs, bundler/src/bundler/chunk/plan/mod.rs, bundler/src/bundler/import/mod.rs, bundler/src/bundler/keywords.rs, bundler/src/modules/mod.rs, bundler/src/modules/sort/chunk.rs, bundler/src/modules/sort/graph.rs, bundler/src/modules/sort/stmt.rs, bundler/tests/common/mod.rs, bundler/tests/fixture/deno-9591/output/entry.inlined.ts, bundler/tests/fixture/deno-9591/output/entry.ts
=> fix(bundler): Improve performance

Cargo.toml, bundler/Cargo.toml, ecmascript/Cargo.toml, ecmascript/preset_env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/typescript/Cargo.toml, ecmascript/transforms/typescript/src/strip.rs, ecmascript/transforms/typescript/tests/strip.rs, native/babel-ast/Cargo.toml, native/babel-compat/Cargo.toml, native/babel-compat/src/typescript.rs, native/babel-visit/Cargo.toml
swc_ecma_transforms_typescript:
=> fix(swc): Fix various bugs.

ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/react/src/lib.rs
swc_ecma_transforms_react:
- Expose `RefreshOptions`. (Closes #1634)
- Expose `Runtime`.
=> fix(es/transforms/react): Expose `RefreshOptions`

ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/base/src/resolver/mod.rs, ecmascript/transforms/base/src/resolver/tests.rs
swc_ecma_transorms_base:
- Handle parameters of a setter property correctly.
=> fix(es/transforms/resolver): Fix setter properties

ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/base/src/resolver/mod.rs, ecmascript/transforms/base/src/resolver/tests.rs, ecmascript/transforms/compat/Cargo.toml, package.json, wasm/Cargo.toml
=> fix(es/transforms/base): Fix resolver

.github/workflows/publish-wasm-web.yml, ecmascript/parser/Cargo.toml, ecmascript/parser/src/parser/class_and_fn.rs, ecmascript/parser/tests/typescript/deno-1671/case1/input.ts, ecmascript/parser/tests/typescript/deno-1671/case1/input.ts.json, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/optimization/src/simplify/expr/mod.rs, ecmascript/transforms/optimization/src/simplify/expr/tests.rs, ecmascript/utils/Cargo.toml, ecmascript/utils/src/lib.rs, package.json, wasm/Cargo.toml
swc_ecma_transforms_optimization:
wasm/web:
=> fix(es): Fix various bugs

bundler/Cargo.toml, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/base/src/fixer.rs
=> fix(es): Fix bugs

.github/workflows/cargo.yml, bundler/Cargo.toml, bundler/src/bundler/chunk/plan/mod.rs, bundler/src/bundler/chunk/plan/tests.rs, bundler/src/bundler/mod.rs, bundler/tests/fixture/deno-10820/case1/input/data.ts, bundler/tests/fixture/deno-10820/case1/input/entry.ts, bundler/tests/fixture/deno-10820/case1/input/page1.ts, bundler/tests/fixture/deno-10820/case1/input/page2.ts, bundler/tests/fixture/deno-10820/case1/input/router.ts, bundler/tests/fixture/deno-10820/case1/output/entry.inlined.ts, bundler/tests/fixture/deno-10820/case1/output/entry.ts
=> fix(bundler): Fix cycle detection

Cargo.toml, bundler/Cargo.toml, ecmascript/Cargo.toml, ecmascript/minifier/Cargo.toml, ecmascript/minifier/tests/terser/compress/numbers/unary_binary_parenthesis/output.js, ecmascript/preset_env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/base/src/fixer.rs, ecmascript/transforms/classes/Cargo.toml, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/module/src/common_js.rs, ecmascript/transforms/module/tests/common_js.rs, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/proposal/Cargo.toml, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/testing/Cargo.toml, ecmascript/transforms/typescript/Cargo.toml
=> fix(es/transforms): Fix bugs

ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/optimization/src/simplify/branch/mod.rs, ecmascript/transforms/optimization/src/simplify/branch/tests.rs
swc_ecma_transforms_optimization:
=> fix(es/transforms/optimizer): Fix dead_branch_remover

Cargo.toml, bundler/Cargo.toml, ecmascript/Cargo.toml, ecmascript/codegen/Cargo.toml, ecmascript/dep-graph/Cargo.toml, ecmascript/ext-transforms/Cargo.toml, ecmascript/jsdoc/Cargo.toml, ecmascript/minifier/Cargo.toml, ecmascript/parser/Cargo.toml, ecmascript/parser/src/error.rs, ecmascript/parser/src/lexer/number.rs, ecmascript/parser/src/parser/tests.rs, ecmascript/parser/tests/typescript/issue-1454/case4/input.tsx, ecmascript/parser/tests/typescript/issue-1454/case4/input.tsx.json, ecmascript/parser/tests/typescript/issue-1454/case5/input.ts, ecmascript/parser/tests/typescript/issue-1454/case5/input.ts.json, ecmascript/preset-env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/classes/Cargo.toml, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/proposal/Cargo.toml, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/testing/Cargo.toml, ecmascript/transforms/typescript/Cargo.toml
=> fix(es/parser): Fix panic on debug mode

package.json, wasm/Cargo.toml
wasm:
- Use spdx-compatible license. (Closes #1798)
=> chore(wasm): Fix license

ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/react/src/refresh/mod.rs, ecmascript/transforms/react/src/refresh/tests.rs
=> fix(es/transform/react): Handle TypeScript declare module

common/Cargo.toml, ecmascript/transforms/proposal/Cargo.toml, ecmascript/transforms/proposal/src/decorators/legacy.rs, ecmascript/transforms/tests/decorators.rs, ecmascript/transforms/typescript/tests/strip.rs, package.json, tests/fixture/issue-1278/input/.swcrc, tests/fixture/issue-1278/input/index.ts, tests/fixture/issue-1278/output/index.ts, tests/fixture/issue-1345/output/index.ts, tests/fixture/issue-1421/case1/output/index.ts, wasm/Cargo.toml
=> fix(es/transforms): Fix decorator bugs

src/builder.rs, tests/fixture/issue-1924/case1/input/.swcrc, tests/fixture/issue-1924/case1/input/index.js, tests/fixture/issue-1924/case1/output/index.js
=> fix(builder):  move import_analyzer after  regenerator-runtime transform

Cargo.toml, common/Cargo.toml, common/src/source_map.rs, ecmascript/loader/Cargo.toml, ecmascript/loader/src/resolvers/tsc.rs, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/module/src/path.rs, node-swc/__tests__/paths_test.mjs, node-swc/src/types.ts, src/config.rs
=> fix(node/swc): Fix bugs

ecmascript/transforms/typescript/Cargo.toml, ecmascript/transforms/typescript/src/strip.rs, ecmascript/transforms/typescript/tests/strip.rs, tests/fixture/deno-10684/case1/input/entry.ts, tests/fixture/deno-10684/case1/output/entry.ts
swc_ecma_transforms_typescript:
=> fix(es/transforms/ts): Fix typescript stripper

ecmascript/transforms/typescript/Cargo.toml, ecmascript/transforms/typescript/src/strip.rs, ecmascript/transforms/typescript/tests/strip.rs
Will fix https://github.com/denoland/deno/issues/11550
=> fix: private method overloads should be removed when type stripping

Cargo.lock, ecmascript/minifier/Cargo.toml, ecmascript/minifier/src/analyzer/mod.rs, ecmascript/minifier/src/compress/mod.rs, ecmascript/minifier/src/compress/optimize/conditionals.rs, ecmascript/minifier/src/lib.rs, ecmascript/minifier/src/pass/hygiene/mod.rs, ecmascript/minifier/src/pass/mangle_names/mod.rs, ecmascript/minifier/src/pass/mangle_props.rs, ecmascript/minifier/src/timing.rs, ecmascript/minifier/src/util/base54.rs, ecmascript/minifier/src/util/mod.rs, package.json, tests/projects.rs, wasm/Cargo.toml
=> fix(es/minifier): Fix minifier

ecmascript/codegen/tests/test262.rs
---
I'll merge this before other PRs, to ensure that CI is passing.
=> fix(ci): Fix CI

Cargo.lock, Cargo.toml, ecmascript/Cargo.toml, ecmascript/src/lib.rs, ecmascript/transforms/classes/Cargo.toml, src/lib.rs
swc_ecmascript:
- Expose `swc_ecma_preset_env`.
swc:
- Expose `swc_atoms`.
- Expose `swc_common`.
- Expose `swc_ecmascript`.
=> feat(swc): Improve swc as a crate

ecmascript/minifier/tests/compress/fixture/projects/wmr/archive-1/chunks/prerender.93c6f601/output.js, ecmascript/minifier/tests/mangle.rs, ecmascript/minifier/tests/terser/compress/export/dynamic_import/output.js, ecmascript/parser/src/lib.rs, ecmascript/parser/tests/span/js/expr/dynamic-import.js, ecmascript/parser/tests/span/js/expr/dynamic-import.js.spans, node-swc/src/types.ts
Enables ECMAScript features in default for parser.
Should I add some tests for this?
=> feat(es/parser): enable ECMAScript features in default

Cargo.lock, Cargo.toml, benches/typescript.rs, ecmascript/minifier/src/compress/hoist_decls.rs, ecmascript/minifier/src/compress/mod.rs, ecmascript/minifier/src/compress/pure/ctx.rs, ecmascript/minifier/src/compress/pure/mod.rs, node/binding/src/bundle.rs, node/binding/src/print.rs, node/bundler/tests/fixture.rs, package.json, src/config/mod.rs, src/config/util.rs, src/lib.rs, tests/fixture/issue-2011/reduced/output/index.js, tests/fixture/minify/comments/false-01/input/.swcrc, tests/fixture/minify/comments/false-01/input/index.js, tests/fixture/minify/comments/false-01/output/index.js, tests/fixture/minify/comments/some-01/input/.swcrc, tests/fixture/minify/comments/some-01/input/index.js, tests/fixture/minify/comments/some-01/output/index.js, tests/fixture/minify/comments/true-01/input/.swcrc, tests/fixture/minify/comments/true-01/input/index.js, tests/fixture/minify/comments/true-01/output/index.js, tests/projects.rs, wasm/Cargo.toml, wasm/src/lib.rs
swc:
- `minify`: Support `format.comments`.
- `process_js`: Support `jsc.minify.format.comments`.
=> feat(swc): Implement `format.comments` of terser

Cargo.lock, Cargo.toml, bundler/Cargo.toml, ecmascript/Cargo.toml, ecmascript/codegen/Cargo.toml, ecmascript/dep-graph/Cargo.toml, ecmascript/ext-transforms/Cargo.toml, ecmascript/jsdoc/Cargo.toml, ecmascript/minifier/Cargo.toml, ecmascript/parser/Cargo.toml, ecmascript/parser/src/error.rs, ecmascript/parser/src/parser/stmt.rs, ecmascript/parser/tests/typescript-errors/custom/top-level-await-jsc-target/input.ts.stderr, ecmascript/preset-env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/classes/Cargo.toml, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/proposal/Cargo.toml, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/testing/Cargo.toml, ecmascript/transforms/typescript/Cargo.toml
top level await is only allowed in module context
=> fix(es/parser): emit error for top-level await in script

.cargo/config.toml, Cargo.lock, package.json, wasm/Cargo.toml
node/swc:
- Disable `aes`. (Closes #1807)
=> fix(swc): Disable `aes` feature

Cargo.lock, common/Cargo.toml, common/src/eq.rs
swc_common:
- Implement `TypeEq` and `EqIgnoreSpan` for tuples.
=> feat(common): Implement TypeEq and EqIgnoreSpan for tuples

ecmascript/parser/src/lib.rs, ecmascript/transforms/typescript/tests/strip_correctness.rs
This was accidentally left over and doesn't do anything.
=> fix: remove `static_blocks` from `TsConfig`

Cargo.lock, Cargo.toml, bundler/Cargo.toml, ecmascript/Cargo.toml, ecmascript/minifier/Cargo.toml, ecmascript/preset-env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/proposal/Cargo.toml, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/testing/Cargo.toml, ecmascript/transforms/testing/src/lib.rs, ecmascript/transforms/typescript/Cargo.toml, package.json, src/lib.rs, wasm/Cargo.toml
swc_ecma_transforms_testing:
- Make `expected` not affect source map of input.
swc:
- Accept `before` pass.
=> fix(swc): Improve rust apis

Cargo.lock, ecmascript/parser/Cargo.toml, ecmascript/parser/src/parser/class_and_fn.rs, ecmascript/parser/src/parser/stmt.rs, ecmascript/parser/tests/span/js/decl/static-blocks-with-line-breaks.js, ecmascript/parser/tests/span/js/decl/static-blocks-with-line-breaks.js.spans, ecmascript/parser/tests/span/js/decl/static-blocks.js, ecmascript/parser/tests/span/js/decl/static-blocks.js.spans
=> Fix parsing static blocks with line breaks

.github/workflows/publish-node.yml
=> fix(ci): Publish

Cargo.lock, ecmascript/codegen/Cargo.toml, ecmascript/codegen/src/lib.rs
Fixes:
I will add a test in a second. Edit: Actually, I couldn't get it to pick it up and gave up quickly 😅
=> fix: emit static before readonly

Cargo.lock, css/parser/Cargo.toml, css/parser/src/parser/at_rule.rs, css/parser/tests/fixture/at-rule/import/input.css, css/parser/tests/fixture/at-rule/import/output.json, css/parser/tests/fixture/at-rule/import/span.rust-debug
Name thing in CSS can be lowercased, I can fix more here and in other PRs
=> fix(css/parser): at-rules can be lowercased

css/parser/tests/fixture/selector/comments/input.css, css/parser/tests/fixture/selector/comments/output.json, css/parser/tests/fixture/selector/comments/span.rust-debug
Just tests for comments in selectors
=> test(css/parser): comments in selectors

Cargo.lock, ecmascript/minifier/tests/projects/output/react-dom-17.0.2.js, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/base/src/hygiene/mod.rs, ecmascript/transforms/base/src/hygiene/tests.rs, ecmascript/transforms/compat/tests/es2015_classes.rs, ecmascript/transforms/module/tests/fixture/commonjs/issue-2297/input.js, ecmascript/transforms/module/tests/fixture/commonjs/issue-2297/output.js, package.json, wasm/Cargo.toml
- `hygiene`: Support usage-def conflict where def comes first. (Closes #2297)
=> fix(es/transforms/base): Fix `hygiene`

Cargo.lock, Cargo.toml, package.json, src/lib.rs, wasm/Cargo.toml
swc:
- `try_with_handler`: Return `Err` on errors.
=> fix(swc): Fix `try_with_handler`

Cargo.lock, Cargo.toml, bundler/Cargo.toml, ecmascript/Cargo.toml, ecmascript/minifier/Cargo.toml, ecmascript/minifier/src/compress/mod.rs, ecmascript/minifier/src/eval.rs, ecmascript/minifier/tests/compress/fixture/issues/2257/full/output.js, ecmascript/minifier/tests/compress/fixture/issues/vercel/002/output.js, ecmascript/preset-env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/optimization/src/simplify/branch/tests.rs, ecmascript/transforms/optimization/src/simplify/expr/mod.rs, ecmascript/transforms/optimization/src/simplify/expr/tests.rs, ecmascript/transforms/optimization/src/simplify/mod.rs, ecmascript/transforms/optimization/tests/fixture.rs, ecmascript/transforms/optimization/tests/simplify.rs, node/bundler/src/loaders/swc.rs
swc_ecma_transforms_optimization:
- Don't optimize calls like `new String`.
=> fix(es/minifier): Don't optimize `new String`.

Cargo.lock, ecmascript/minifier/Cargo.toml, ecmascript/minifier/src/compress/optimize/inline.rs, ecmascript/minifier/src/compress/optimize/mod.rs, ecmascript/minifier/tests/compress/fixture/issues/vercel/003/input.js, ecmascript/minifier/tests/compress/fixture/issues/vercel/003/output.js, ecmascript/minifier/tests/golden.txt, ecmascript/minifier/tests/ignored.txt
swc_ecma_minifer:
- Fix inlining of bindings into shorthand properties.
=> fix(es/minifier): Fix inlining into shorthand properties

css/parser/Cargo.toml, css/parser/src/parser/value/mod.rs, css/parser/tests/fixture/function/url/input.css, css/parser/tests/fixture/function/url/output.json, css/parser/tests/fixture/function/url/span.rust-debug
avoid `SpaceValues` in `url` function, `url` is special in `CSS`, here a lot of other improvements inside value parser (there we can improve logic and speed), but let's them in future
=> fix(css/parser): Fix url parsing

Cargo.lock, common/Cargo.toml
swc_common:
- Add `dylib` to `crate-type`.
=> feat(swc_common): Allow `dylib`

Cargo.lock, Cargo.toml, benches/typescript.rs, node-swc/__tests__/error_test.mjs, node/bundler/src/loaders/swc.rs, src/config/mod.rs, src/lib.rs, tests/projects.rs, tests/rust_api.rs
swc:
- Use `impl |prorgram: &Program| -> impl Fold` instead of `impl Fold`. (Closes https://github.com/swc-project/swc/issues/2664)
=> feat(swc): Provide `&Program` to pass creator

ecmascript/transforms/compat/src/es2017/async_to_generator.rs
This PR partially migrates `async_to_generator`'s fold into visit_mut. For easier migration there are some naive choices to copy few things. This may need to be revisited depends on the nature of the copy.
=> refactor(es/transforms/compat): visitmut for async_to_generator part1

crates/swc_ecma_transforms_compat/src/es2015/new_target.rs, crates/swc_ecma_transforms_compat/tests/fixture/new-target/exec/block/exec.js, crates/swc_ecma_transforms_compat/tests/fixture/new-target/general/block/input.js, crates/swc_ecma_transforms_compat/tests/fixture/new-target/general/block/output.js, crates/swc_ecma_transforms_compat/tests/fixture/new-target/general/iiaf-class/input.js, crates/swc_ecma_transforms_compat/tests/fixture/new-target/general/iiaf-class/output.js
Fixes https://github.com/swc-project/swc/issues/2308
=> Fix for new target hoisting

crates/swc_ecma_parser/src/parser/input.rs, crates/swc_ecma_transforms_compat/src/es2015/block_scoping.rs, crates/swc_ecma_transforms_compat/src/es2015/regenerator/case.rs, crates/swc_ecma_transforms_compat/src/es2015/spread.rs, crates/swc_ecma_transforms_compat/src/es2015/template_literal.rs, crates/swc_ecma_transforms_compat/src/es2020/opt_chaining.rs, crates/swc_ecma_transforms_compat/src/es2022/class_properties/private_field.rs, crates/swc_ecma_transforms_proposal/src/decorators/legacy.rs, crates/swc_ecma_transforms_react/src/jsx/mod.rs, crates/swc_ecma_transforms_react/src/lib.rs, crates/swc_ecma_transforms_react/src/refresh/mod.rs, crates/swc_ecma_transforms_testing/src/lib.rs, crates/swc_ecma_utils/src/constructor.rs
- Use `take` instead of `replace`.
=> refactor: Cleanup

crates/swc_ecma_minifier/package.json, crates/swc_ecma_minifier/scripts/next/add-test.sh, crates/swc_ecma_minifier/scripts/next/evaluate.js, crates/swc_ecma_minifier/yarn.lock
---
Usage: 
From the root directory of a next.js app
`~/projects/s-min/crates/swc_ecma_minifier/scripts/next/add-test.sh`
=> chore(es/minifier): Add a script to copy tests from a next.js app

.github/workflows/cargo.yml, crates/swc_ecma_utils/src/lib.rs
- `collect_decls`: Handle assignment pattern property. (Closes #2785)
=> fix(es/utils): Fix `collect_decls`

crates/swc_ecma_transforms_compat/src/es2015/parameters.rs
relates to https://github.com/swc-project/swc/issues/2370
This PR refactors Param to use visit_mut instead of fold. Code may need to be updated depends on review, but conversion itself is straightforward.
=> refactor(es/transforms/compat): visit_mut for parameters

crates/swc_ecma_transforms_base/src/resolver/mod.rs, crates/swc_ecma_transforms_base/tests/ts-resolver/namepsace/hoisting/1/input.ts, crates/swc_ecma_transforms_base/tests/ts-resolver/namepsace/hoisting/1/output.ts
- `ts_resolver`: Hoist interface declarations.
=> fix(es/transforms/base): Fix `ts_resolver`

crates/swc_ecma_transforms_compat/src/es2015/block_scoping.rs
relates to #2370
This PR refactors block_scoping to use visit_mut instead of fold. Same as other work, this is straightforward conversion.
=> refactor(es/transforms/compat): visit_mut for block_scoping

crates/ast_node/src/lib.rs
=> Fixed typo

Cargo.lock, Cargo.toml, crates/node/Cargo.toml, crates/node/src/lib.rs, crates/swc_bundler/scripts/instrument.sh, crates/swc_ecma_codegen/scripts/instrument.sh, crates/swc_ecma_minifier/scripts/instrument.sh, crates/swc_ecma_minifier/src/debug.rs, crates/swc_ecma_parser/scripts/instrument.sh, crates/swc_timer/Cargo.toml, crates/swc_timer/src/lib.rs, crates/swc_timer/tests/timer.rs, crates/wasm/Cargo.toml, scripts/instrument.sh
swc_timer:
- Add `Timer`.
- Add `timer!()`.
- 
node:
- Enable logging.
=> feat: Enable logging of timings

crates/swc_bundler/src/bundler/chunk/cjs.rs, crates/swc_bundler/src/bundler/import/mod.rs, crates/swc_bundler/src/bundler/mod.rs, crates/swc_bundler/tests/fixture/external-require/input/entry.ts, crates/swc_bundler/tests/fixture/external-require/output/entry.inlined.ts, crates/swc_bundler/tests/fixture/external-require/output/entry.ts
May be this fix will help with https://github.com/swc-project/swc/issues/2275. But it is for shure helps me
=> [swc_bundler] Ignore external require

crates/swc_css_parser/src/parser/selector/mod.rs, crates/swc_css_parser/tests/fixture/esbuild/misc/Loy9sX2qaylR2OySt7N-BQ/output.json, crates/swc_css_parser/tests/fixture/esbuild/misc/Loy9sX2qaylR2OySt7N-BQ/span.rust-debug, crates/swc_css_parser/tests/fixture/esbuild/misc/Pkkf0GfuA1VzI7L4dGjS-A/output.json, crates/swc_css_parser/tests/fixture/esbuild/misc/Pkkf0GfuA1VzI7L4dGjS-A/span.rust-debug, crates/swc_css_parser/tests/fixture/esbuild/misc/Sy2aOxINv1bvZmbK_Pc5Mg/output.json, crates/swc_css_parser/tests/fixture/esbuild/misc/Sy2aOxINv1bvZmbK_Pc5Mg/span.rust-debug, crates/swc_css_parser/tests/fixture/esbuild/misc/UeHn9b5w6R3dVjrtRCGxkA/output.json, crates/swc_css_parser/tests/fixture/esbuild/misc/UeHn9b5w6R3dVjrtRCGxkA/span.rust-debug, crates/swc_css_parser/tests/fixture/esbuild/misc/hYoP2sEvEyLualMll8L_RQ/output.json, crates/swc_css_parser/tests/fixture/esbuild/misc/hYoP2sEvEyLualMll8L_RQ/span.rust-debug, crates/swc_css_parser/tests/fixture/selector/type/output.json, crates/swc_css_parser/tests/fixture/selector/type/span.rust-debug
Small fix for span and resolve todo
=> fix(css/parser): span for type selector

crates/swc_ecma_transforms_compat/src/es2015/spread.rs
relates to #2370
This PR refactors spread to use visit_mut instead of fold. Mostly straightforward conversion except one place match returns Some() only it needs to create a new expr, and other uses .take() for the existing callee value.
concat_args has not been touched as well since there are few places actually need to rely on returned value. It may need revisit later.
=> refactor(es/transforms/compat): visit_mut for spread

Cargo.lock, crates/swc/Cargo.toml, crates/swc/src/config/mod.rs, crates/wasm/Cargo.toml, package.json
swc:
- Merge `jsc.transforms.hidden.jest`.
=> fix(swc): Fix handling of `jest` option

.cargo/config.toml, crates/swc_ecma_visit/src/lib.rs
This workarounds https://github.com/rust-lang/rust/issues/91128
---
Clsoes #2872
=> chore: Reduce compile time

Cargo.lock, crates/swc_ecma_visit/Cargo.toml, crates/swc_ecma_visit/src/lib.rs, crates/swc_webpack_ast/Cargo.toml, crates/swc_webpack_ast/src/reducer.rs, crates/swc_webpack_ast/tests/fixture.rs, crates/swc_webpack_ast/tests/fixture/regenerator/input.js, crates/swc_webpack_ast/tests/fixture/regenerator/output.js
- Implement more rules.
- Test using typescript test suites.
=> fix(webpack/ast): Fix ast reducer

crates/swc_webpack_ast/src/reducer.rs, crates/swc_webpack_ast/tests/fixture/css-escape/1/input.js, crates/swc_webpack_ast/tests/fixture/css-escape/1/output.js
- Preserve original spans for injected `null` literals
=> fix(webpack/ast): Fix span of null literals

crates/swc_webpack_ast/src/lib.rs, crates/swc_webpack_ast/src/reducer.rs, crates/swc_webpack_ast/tests/fixture/amd/define-required/1/input.js, crates/swc_webpack_ast/tests/fixture/amd/define-required/1/output.js, crates/swc_webpack_ast/tests/fixture/react-dom/dev/output.js, crates/swc_webpack_ast/tests/fixture/react-dom/prod/output.js
- Support `define` calls with `require` .
=> fix(webpack/ast): Fix handling of `define`

crates/swc_ecma_transforms_compat/src/es2022/static_blocks.rs
Continuing #2370.
:Ez: one
I thought I picked file to continue https://github.com/swc-project/swc/pull/2966 but realized it's not after complete it. Anyway, this is small module so I took a stab before going back to #2966. PR applies few refactorings as visit_mut didn't need to follow strictly same path what fold does for this case.
=> refactor(es/transforms/compat): visit_mut for static_blocks

crates/swc/tests/fixture/issue-2990/1/input/.swcrc, crates/swc/tests/fixture/issue-2990/1/input/index.ts, crates/swc/tests/fixture/issue-2990/1/output/index.ts, crates/swc/tests/fixture/issue-2990/2/input/.swcrc, crates/swc/tests/fixture/issue-2990/2/input/index.ts, crates/swc/tests/fixture/issue-2990/2/output/index.ts, crates/swc_ecma_parser/src/parser/typescript.rs, crates/swc_ecma_parser/tests/typescript/issue-1514/case1/input.ts.json
=> fix(ecma/parser): allow Assignment Assertions in typescript class

crates/swc_bundler/tests/common/mod.rs, crates/swc_bundler/tests/fixture/issue-3043/case1/input/entry.ts, crates/swc_bundler/tests/fixture/issue-3043/case1/input/two.ts, crates/swc_bundler/tests/fixture/issue-3043/case1/output/entry.inlined.ts, crates/swc_bundler/tests/fixture/issue-3043/case1/output/entry.ts, crates/swc_bundler/tests/fixture/issue-3043/case2/input/entry.ts, crates/swc_bundler/tests/fixture/issue-3043/case2/input/foo.js.ts, crates/swc_bundler/tests/fixture/issue-3043/case2/input/foo.ts, crates/swc_bundler/tests/fixture/issue-3043/case2/output/entry.inlined.ts, crates/swc_bundler/tests/fixture/issue-3043/case2/output/entry.ts, crates/swc_bundler/tests/fixture/issue-3043/case3/input/entry.ts, crates/swc_bundler/tests/fixture/issue-3043/case3/input/foo.mts, crates/swc_bundler/tests/fixture/issue-3043/case3/input/foo.ts, crates/swc_bundler/tests/fixture/issue-3043/case3/output/entry.inlined.ts, crates/swc_bundler/tests/fixture/issue-3043/case3/output/entry.ts, crates/swc_ecma_loader/src/resolvers/node.rs
=> fix(swcpack): Fully-Specified ESM Import Specifier

crates/swc_ecma_transforms_compat/src/es2020/opt_chaining.rs, crates/swc_ecma_transforms_compat/tests/es2020_optional_chaining.rs, crates/swc_ecma_utils/src/factory.rs, crates/swc_ecma_utils/src/lib.rs
fix https://github.com/swc-project/swc/issues/2735
=> fix(es/transforms/compat): transform optional eval call to indirect eval call

crates/node/build.rs, crates/node/src/lib.rs
This PR contains two proposals.
First, move feature checks to build script. The `compile_error` error message won't be mixed with other errors that are consequences. What do you think of that ?
Second, add a check that insures that features `swc_v1` and `swc_v2` are not being used at the same time.
https://github.com/swc-project/swc/issues/3079
=> feat(node): update features check

Cargo.lock, crates/swc/scripts/instrument.sh, crates/swc_bundler/examples/bundle.rs, crates/swc_bundler/src/bundler/finalize.rs, crates/swc_bundler/src/bundler/mod.rs, crates/swc_bundler/src/bundler/tests.rs, crates/swc_bundler/tests/fixture.rs, crates/swc_ecma_minifier/Cargo.toml, crates/swc_ecma_minifier/src/lib.rs, crates/swc_node_bundler/tests/fixture.rs, crates/swc_timer/src/lib.rs
swc_bundler:
- Add `Config.disable_fixer`.
- Add `Config.disable_hygiene`.
- Use `swc_timer`.
=> refactor(es/minifier): Use `swc_timer`

crates/swc/tests/tsc-references/ES5For-of19_es5.1.normal.js, crates/swc_bundler/tests/fixture/deno-9219/case1/output/entry.inlined.ts, crates/swc_bundler/tests/fixture/deno-9219/case1/output/entry.ts, crates/swc_bundler/tests/fixture/deno-9591/output/entry.inlined.ts, crates/swc_bundler/tests/fixture/deno-9591/output/entry.ts, crates/swc_ecma_loader/src/resolvers/node.rs, crates/swc_ecma_minifier/tests/compress/fixture/issues/2257/full/output.js, crates/swc_ecma_minifier/tests/compress/fixture/issues/firebase-core/1/output.js, crates/swc_ecma_minifier/tests/compress/fixture/issues/firebase-firestore/1/output.js, crates/swc_ecma_minifier/tests/compress/fixture/issues/moment/1/output.js, crates/swc_ecma_minifier/tests/projects/output/react-dom-17.0.2.js, crates/swc_ecma_transforms_base/src/hygiene/usage_analyzer.rs
- `hygiene`: Skip checking a symbol if we are sure that it will be discarded.
swc_ecma_laoder:
- Optimize `NodeModulesResolver` by trying `.js` first.
=> perf(es/hygiene): Fix performance bug

crates/swc_ecma_dep_graph/src/lib.rs
=> feat: Add DependencyDescriptor::dynamic_import_assertions

crates/swc/tests/fixture/issue-2858/1/input/.swcrc, crates/swc/tests/fixture/issue-2858/1/input/index.js, crates/swc/tests/fixture/issue-2858/1/output/index.js, crates/swc/tests/fixture/issue-2858/2/input/.swcrc, crates/swc/tests/fixture/issue-2858/2/input/index.js, crates/swc/tests/fixture/issue-2858/2/output/index.js, crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs, crates/swc_ecma_transforms_compat/tests/es2015_destructuring.rs
=> fix(ecma/transforms): correct export ref in object descructuring

.github/ISSUE_TEMPLATE/bug_report.yml
Add "Actual behavior" to the bug report template. It will help to report bugs related parser and transformer. What do you think?
=> chore: add actual behavior to the bug report template

crates/swc_bundler/examples/bundle.rs, crates/swc_bundler/src/bundler/mod.rs, crates/swc_bundler/src/bundler/optimize.rs, crates/swc_bundler/src/bundler/tests.rs
Adding an option `disable_dce` to bundler's config to disable tree-shaking.
**Related issue (if exists):** #3094
=> feat(es/bundler): Option to disable tree-shaking

crates/swc_ecma_ast/src/decl.rs, crates/swc_ecma_transforms_compat/src/es2015/regenerator/hoist.rs, crates/swc_ecma_transforms_compat/src/es2015/regenerator/mod.rs, crates/swc_ecma_transforms_compat/tests/es2015_regenerator.rs, crates/swc_ecma_transforms_compat/tests/es2017_async_to_generator.rs, crates/swc_ecma_transforms_compat/tests/fixture/async-to-generator/issue-2556/1/exec.js, crates/swc_ecma_transforms_compat/tests/fixture/async-to-generator/issue-2556/2/exec.js, crates/swc_ecma_transforms_compat/tests/fixture/async-to-generator/issue-2556/3/exec.js
=> fix(es/transforms): hoist functions in regenerator

crates/swc/tests/fixture/issue-3055/1/input/.swcrc, crates/swc/tests/fixture/issue-3055/1/input/index.ts, crates/swc/tests/fixture/issue-3055/1/output/index.ts, crates/swc_ecma_transforms_compat/src/es2022/class_properties/private_field.rs, crates/swc_ecma_transforms_compat/tests/es2022_class_properties.rs
=> fix(es/transforms): class private method

.github/workflows/cargo.yml
---
This PR tries to reduce CI time.
=> chore(ci): Reduce CI time

crates/swc/tests/tsc-references/computedPropertyNames51_ES5_es5.1.normal.js, crates/swc/tests/tsc-references/computedPropertyNames51_ES6_es5.1.normal.js, crates/swc/tests/tsc-references/computedPropertyNames8_ES5_es5.1.normal.js, crates/swc/tests/tsc-references/computedPropertyNames8_ES6_es5.1.normal.js, crates/swc/tests/tsc-references/destructuringObjectBindingPatternAndAssignment6_es5.1.normal.js, crates/swc/tests/tsc-references/destructuringObjectBindingPatternAndAssignment6_es5.2.minified.js, crates/swc/tests/tsc-references/destructuringObjectBindingPatternAndAssignment7_es5.1.normal.js, crates/swc/tests/tsc-references/destructuringObjectBindingPatternAndAssignment7_es5.2.minified.js, crates/swc/tests/tsc-references/destructuringObjectBindingPatternAndAssignment8_es5.1.normal.js, crates/swc/tests/tsc-references/destructuringObjectBindingPatternAndAssignment8_es5.2.minified.js, crates/swc/tests/tsc-references/generatorTypeCheck44_es5.1.normal.js, crates/swc/tests/tsc-references/generatorTypeCheck44_es5.2.minified.js, crates/swc/tests/tsc-references/parserComputedPropertyName17_es5.1.normal.js, crates/swc/tests/tsc-references/parserComputedPropertyName17_es5.2.minified.js, crates/swc/tests/tsc-references/parserComputedPropertyName4_es5.1.normal.js, crates/swc/tests/tsc-references/parserComputedPropertyName4_es5.2.minified.js, crates/swc/tests/tsc-references/parserES5ComputedPropertyName4_es5.1.normal.js, crates/swc/tests/tsc-references/parserES5ComputedPropertyName4_es5.2.minified.js, crates/swc/tests/vercel/full/react-instantsearch/2/output/index.js, crates/swc/tests/vercel/loader-only/react-instantsearch/1/output/index.js, crates/swc_ecma_transforms_compat/src/es2015/computed_props.rs, crates/swc_ecma_transforms_compat/tests/es2015_computed_props.rs
=> fix(es/transforms): init obj when using computed props

crates/swc_ecma_transforms_react/src/refresh/hook.rs, crates/swc_ecma_transforms_react/src/refresh/mod.rs, crates/swc_ecma_transforms_react/src/refresh/tests.rs, crates/swc_ecma_transforms_react/src/refresh/util.rs
migrate react refresh transform to `VisitMut`
closes #2261 too
=> refact(ecma/transform/react): use VisitMut for refresh

crates/swc_ecma_ast/src/expr.rs, crates/swc_ecma_ast/src/lit.rs, crates/swc_ecma_transforms_module/src/rewriter.rs, crates/swc_ecma_transforms_typescript/examples/ts_to_js.rs
swc_ecma_ast:
- Document `Str.kind`.
- Document `TpleElement.cooked`.
=> doc(es/ast): Improve rustdoc

crates/swc_ecma_preset_env/src/lib.rs, crates/swc_ecma_transforms_compat/tests/es2015_arrow.rs, crates/swc_ecma_transforms_compat/tests/es2015_new_target.rs, crates/swc_ecma_utils/src/function.rs
closes #2885 
Also why `new_target` transform not in `preset_env`?
=> fix(ecma/transform/compat): transform new.target in arrow

.github/workflows/bench.yml
Hi,
I'm the original author of github-action-benchmark action. Recently I moved the action repository to benchmark-action org to develop it by multiple maintainers. Though GitHub redirects rhysd to benchmark-action, using an action at the new org would be cleaner.
This PR updates the slug of action in the CI workflow.
Nothing
Nothing
=> `rhysd/github-action-benchmark` was moved to `benchmark-action/github-action-benchmark`

crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs, crates/swc_ecma_transforms_compat/tests/es2022_class_properties.rs
=> fix(es/transforms): visit private method in class

crates/swc_ecma_transforms_compat/src/es2015/new_target.rs, crates/swc_ecma_transforms_compat/tests/fixture/new-target/exec/class-property/exec.js
=> fix(es/transforms): `new.target` should return undefined from `class_prop`

crates/swc_ecma_transforms_typescript/src/strip.rs, crates/swc_ecma_transforms_typescript/tests/fixture/issue-3001/1/input.ts, crates/swc_ecma_transforms_typescript/tests/fixture/issue-3001/1/output.js, crates/swc_ecma_transforms_typescript/tests/fixture/issue-3001/2/input.ts, crates/swc_ecma_transforms_typescript/tests/fixture/issue-3001/2/output.js
=> fix(es/typescript): Correct TypeScript Enum Reference

crates/swc/tests/tsc-references/classWithStaticFieldInParameterBindingPattern.2_es5.1.normal.js, crates/swc/tests/tsc-references/classWithStaticFieldInParameterBindingPattern.2_es5.2.minified.js, crates/swc/tests/tsc-references/classWithStaticFieldInParameterBindingPattern.3_es5.1.normal.js, crates/swc/tests/tsc-references/classWithStaticFieldInParameterBindingPattern.3_es5.2.minified.js, crates/swc/tests/tsc-references/classWithStaticFieldInParameterBindingPattern_es5.1.normal.js, crates/swc/tests/tsc-references/classWithStaticFieldInParameterBindingPattern_es5.2.minified.js, crates/swc/tests/tsc-references/nullishCoalescingOperatorInParameterBindingPattern.2_es5.1.normal.js, crates/swc/tests/tsc-references/optionalChainingInParameterBindingPattern.2_es5.1.normal.js, crates/swc/tests/tsc-references/parameterInitializersForwardReferencing1_es5.1.normal.js, crates/swc/tests/tsc-references/parameterInitializersForwardReferencing1_es6_es5.1.normal.js, crates/swc/tests/tsc-references/unionsOfTupleTypes1_es2015.1.normal.js, crates/swc/tests/tsc-references/unionsOfTupleTypes1_es5.1.normal.js, crates/swc_bundler/tests/fixture/deno-8211-3/output/entry.inlined.ts, crates/swc_bundler/tests/fixture/deno-9212/case1/output/entry.inlined.ts, crates/swc_bundler/tests/fixture/deno-9591/output/entry.inlined.ts, crates/swc_ecma_minifier/tests/compress/fixture/issues/2257/full/output.js, crates/swc_ecma_minifier/tests/compress/fixture/issues/firebase-core/1/output.js, crates/swc_ecma_minifier/tests/compress/fixture/issues/firebase-firestore/1/output.js, crates/swc_ecma_minifier/tests/compress/fixture/issues/quagga2/1.4.2/1/output.js, crates/swc_ecma_minifier/tests/compress/fixture/issues/react-countup/1/output.js, crates/swc_ecma_minifier/tests/compress/fixture/issues/react-countup/2/output.js, crates/swc_ecma_minifier/tests/compress/fixture/projects/angular/2/output.js, crates/swc_ecma_minifier/tests/compress/fixture/projects/jquery/10/output.js, crates/swc_ecma_minifier/tests/projects/output/angular-1.2.5.js, crates/swc_ecma_minifier/tests/projects/output/jquery-1.9.1.js, crates/swc_ecma_minifier/tests/projects/output/underscore-1.5.2.js, crates/swc_ecma_minifier/tests/projects/output/yui-3.12.0.js, crates/swc_ecma_transforms_base/src/hygiene/usage_analyzer.rs
=> fix(ecma/transform/base): visit computed prop in usage analyzer

Cargo.lock, crates/swc_bundler/Cargo.toml, crates/swc_css_ast/Cargo.toml, crates/swc_ecma_ast/Cargo.toml, crates/swc_ecma_minifier/src/compress/optimize/conditionals.rs, crates/swc_ecma_transforms_compat/Cargo.toml, crates/swc_node_bundler/Cargo.toml
swc_ecma_ast:
- Add `as_*` for ast enums.
=> feat(es/ast): Update `is-macro`

crates/node/Cargo.toml, crates/swc/Cargo.toml, crates/swc/src/builder.rs, crates/swc/tests/projects.rs, crates/swc/tests/tsc.rs
=> fix(swc): Remove `wrong-target`

CONTRIBUTING.md, crates/swc/tests/error_msg.rs
Starting from a fresh pull, it can be difficult to get up and running. The changes I've proposed here represent findings from digging around the discord channel and a few closed issues.
I think it'd also be nice to call out a high-level explanation of what the difference between `svc_v1` and `svc_v2` is, but I don't know enough about the features. Happy to add it here if someone would give some guidence.
=> feat: update contributing docs

crates/swc_css_parser/src/parser/at_rule.rs, crates/swc_css_parser/tests/recovery/at-rule/keyfram-number/output.json, crates/swc_css_parser/tests/recovery/at-rule/layer/block/output.json, crates/swc_css_parser/tests/recovery/at-rule/layer/empty/output.json, crates/swc_css_parser/tests/recovery/at-rule/layer/string-name-block/output.json, crates/swc_css_parser/tests/recovery/at-rule/layer/string-name-statement/output.json, crates/swc_css_parser/tests/recovery/at-rule/media/condition-1/output.json, crates/swc_css_parser/tests/recovery/at-rule/media/condition-and-or/output.json, crates/swc_css_parser/tests/recovery/at-rule/media/condition/output.json, crates/swc_css_parser/tests/recovery/at-rule/media/feature-name-1/output.json, crates/swc_css_parser/tests/recovery/at-rule/media/feature-name-2/output.json, crates/swc_css_parser/tests/recovery/at-rule/media/feature-name/output.json, crates/swc_css_parser/tests/recovery/at-rule/media/feature-range-1/output.json, crates/swc_css_parser/tests/recovery/at-rule/media/feature-range-2/output.json, crates/swc_css_parser/tests/recovery/at-rule/media/feature-range-3/output.json, crates/swc_css_parser/tests/recovery/at-rule/media/feature-range-4/input.css, crates/swc_css_parser/tests/recovery/at-rule/media/feature-range-4/output.json, crates/swc_css_parser/tests/recovery/at-rule/media/feature-range-5/input.css, crates/swc_css_parser/tests/recovery/at-rule/media/feature-range-5/output.json, crates/swc_css_parser/tests/recovery/at-rule/media/feature-range-6/input.css, crates/swc_css_parser/tests/recovery/at-rule/media/feature-range-6/output.json, crates/swc_css_parser/tests/recovery/at-rule/media/feature-range/output.json, crates/swc_css_parser/tests/recovery/at-rule/media/feature/output.json, crates/swc_css_parser/tests/recovery/at-rule/media/ratio/output.json
fixes:
- todo
- error recovering for unknown at-rules
No
No
=> Fix at rules

crates/swc/tests/tsc-references/destructuringObjectAssignmentPatternWithNestedSpread_es5.1.normal.js, crates/swc/tests/tsc-references/destructuringObjectAssignmentPatternWithNestedSpread_es5.2.minified.js, crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs, crates/swc_ecma_transforms_compat/tests/es2015_destructuring.rs
It is a regression introduced in #3104 .
- fix #3315
=> fix(es/compat): Fix `destructuring`

crates/swc_css_ast/src/at_rule/support.rs, crates/swc_css_codegen/src/lib.rs, crates/swc_css_parser/src/parser/at_rule.rs, crates/swc_css_parser/tests/fixture.rs, crates/swc_css_parser/tests/fixture/at-rule/supports/input.css, crates/swc_css_parser/tests/fixture/at-rule/supports/output.json, crates/swc_css_parser/tests/fixture/at-rule/supports/span.rust-debug, crates/swc_css_parser/tests/fixture/rome/supports/output.json, crates/swc_css_parser/tests/fixture/rome/supports/span.rust-debug, crates/swc_css_parser/tests/recovery/at-rule/supports/no-parens/input.css, crates/swc_css_parser/tests/recovery/at-rule/supports/no-parens/output.json, crates/swc_css_parser/tests/recovery/at-rule/supports/wrong-or-and/input.css, crates/swc_css_parser/tests/recovery/at-rule/supports/wrong-or-and/output.json, crates/swc_css_visit/src/lib.rs
Refactor `@supports`:
1. fix AST
2. fix parsing `or` and `and` and parens
3. fix bugs with spaces
4. support spec https://www.w3.org/TR/css-conditional-3/#at-supports 
Yes, new nodes
No
=> refactor: @supports

.github/workflows/docs.yml, crates/swc_ecma_minifier/src/compress/optimize/inline.rs, crates/swc_ecma_minifier/src/util/mod.rs, crates/swc_ecma_minifier/tests/compress/fixture/next/.gitignore, crates/swc_ecma_minifier/tests/compress/fixture/next/33265/static/chunks/d6e1aeb5-38a8d7ae57119c23/output.js, crates/swc_ecma_minifier/tests/exec/next/config.json, crates/swc_ecma_minifier/tests/exec/next/feedback-1/capture/1/input.js, crates/swc_ecma_minifier/tests/projects/output/react-17.0.2.js
- Don't inline functions if it captures the environment.
- https://github.com/vercel/next.js/discussions/30237?sort=new#discussioncomment-1963127
- https://github.com/judemanutd/next-swc-minify-bug
```js
var activeInput = _this2.state.activeInput;
var _this2$props3 = _this2.props,
numInputs = _this2$props3.numInputs,
inputStyle = _this2$props3.inputStyle,
focusStyle = _this2$props3.focusStyle,
separator = _this2$props3.separator,
isDisabled = _this2$props3.isDisabled,
disabledStyle = _this2$props3.disabledStyle,
hasErrored = _this2$props3.hasErrored,
errorStyle = _this2$props3.errorStyle,
shouldAutoFocus = _this2$props3.shouldAutoFocus,
isInputNum = _this2$props3.isInputNum,
isInputSecure = _this2$props3.isInputSecure, …
```
=> fix(es/minifier): Consider capturing while inlining

crates/swc_ecma_transforms_typescript/src/strip.rs, crates/swc_ecma_transforms_typescript/tests/fixture/issue-3338/1/input.ts, crates/swc_ecma_transforms_typescript/tests/fixture/issue-3338/1/output.js
=> fix(es/typescript): value with enum string prop

crates/swc/src/config/mod.rs
swc:
- Fix `Merge` impl of `JscExperimental`.
=> fix(swc): Respect `jsc.experimental.keepImportAssertions`

Cargo.lock
=> chore(ci): Update `thread_local`

crates/swc_ecma_transforms_compat/src/es2022/class_properties/private_field.rs, crates/swc_ecma_transforms_compat/tests/es2022_class_properties.rs
=> fix(ecma/transform/compat): handle nest function in `private_field`

crates/node/src/parse.rs
node-swc:
- Use a worker thread for json serialization.
=> perf(node-swc): Speed up `parse` and `parseFile`

crates/swc/tests/fixture/issue-3381/1/input/index.ts, crates/swc/tests/fixture/issue-3381/1/output/index.ts, crates/swc/tests/tsc-references/optionalChainingInArrow_es2015.1.normal.js, crates/swc/tests/tsc-references/optionalChainingInArrow_es5.1.normal.js, crates/swc_ecma_transforms_compat/src/es2020/opt_chaining.rs
=> fix: add missing span in optional chaining

crates/swc/tests/fixture/issue-3417/1/input/.swcrc, crates/swc/tests/fixture/issue-3417/1/input/index.ts, crates/swc/tests/fixture/issue-3417/1/output/index.ts
=> test(swc): Add tests

crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs, crates/swc_ecma_transforms_compat/tests/es2015_destructuring.rs
=> fix(es/destructuring): handle init hole in array assign

crates/swc_css_ast/src/at_rule/document.rs, crates/swc_css_codegen/src/lib.rs, crates/swc_css_codegen/tests/fixture/at-rules/document/1/output.css, crates/swc_css_codegen/tests/fixture/at-rules/document/1/output.min.css, crates/swc_css_parser/src/parser/at_rule.rs, crates/swc_css_parser/tests/fixture.rs, crates/swc_css_parser/tests/fixture/at-rule/document/input.css, crates/swc_css_parser/tests/fixture/at-rule/document/output.json, crates/swc_css_parser/tests/fixture/at-rule/document/span.rust-debug, crates/swc_css_parser/tests/fixture/esbuild/misc/ElFW4lY06Cb-VFYtK0WX4A/output.json, crates/swc_css_parser/tests/fixture/esbuild/misc/ElFW4lY06Cb-VFYtK0WX4A/span.rust-debug, crates/swc_css_parser/tests/fixture/esbuild/misc/S2Mhk5rU2YxQPgm9rtF9WA/output.json, crates/swc_css_parser/tests/fixture/esbuild/misc/S2Mhk5rU2YxQPgm9rtF9WA/span.rust-debug, crates/swc_css_visit/src/lib.rs
fix `@document` parsing
yes, new types added
No
=> fix: document at-rule parsing

crates/swc_css_ast/src/at_rule/counter_style.rs, crates/swc_css_ast/src/at_rule/mod.rs, crates/swc_css_codegen/src/lib.rs, crates/swc_css_codegen/tests/fixture/at-rules/color-profile/input.css, crates/swc_css_codegen/tests/fixture/at-rules/color-profile/output.css, crates/swc_css_codegen/tests/fixture/at-rules/color-profile/output.min.css, crates/swc_css_codegen/tests/fixture/at-rules/counter-style/input.css, crates/swc_css_codegen/tests/fixture/at-rules/counter-style/output.css, crates/swc_css_codegen/tests/fixture/at-rules/counter-style/output.min.css, crates/swc_css_parser/src/parser/at_rule.rs, crates/swc_css_parser/tests/fixture.rs, crates/swc_css_parser/tests/fixture/at-rule/counter-style/input.css, crates/swc_css_parser/tests/fixture/at-rule/counter-style/output.json, crates/swc_css_parser/tests/fixture/at-rule/counter-style/span.rust-debug, crates/swc_css_visit/src/lib.rs
feat - parse `@counter-style` at-rule https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style
Yes, new types
No
=> feat: parse `@counter-style`

crates/swc/tests/fixture/paths/ext/001/output/index.js, crates/swc/tests/fixture/paths/ext/002/output/index.js, crates/swc/tests/fixture/paths/issue-3447/input/.swcrc, crates/swc/tests/fixture/paths/issue-3447/input/src/index.ts, crates/swc/tests/fixture/paths/issue-3447/input/src/modules/01-moduleA/utils.ts, crates/swc/tests/fixture/paths/issue-3447/input/src/modules/02-moduleB/utils.ts, crates/swc/tests/fixture/paths/issue-3447/output/src/index.ts, crates/swc/tests/fixture/paths/issue-3447/output/src/modules/01-moduleA/utils.ts, crates/swc/tests/fixture/paths/issue-3447/output/src/modules/02-moduleB/utils.ts, crates/swc_ecma_transforms_module/src/rewriter.rs
=> fix(ecma_module): set strkind after rewrite path

crates/swc_css_parser/tests/fixture/at-rule/document/input.css, crates/swc_css_parser/tests/fixture/at-rule/document/output.json, crates/swc_css_parser/tests/fixture/at-rule/document/span.rust-debug, crates/swc_css_parser/tests/fixture/declaration/input.css, crates/swc_css_parser/tests/fixture/declaration/output.json, crates/swc_css_parser/tests/fixture/declaration/span.rust-debug, crates/swc_css_parser/tests/fixture/selector/attribute/input.css, crates/swc_css_parser/tests/fixture/selector/attribute/output.json, crates/swc_css_parser/tests/fixture/selector/attribute/span.rust-debug, crates/swc_css_parser/tests/fixture/selector/list/input.css, crates/swc_css_parser/tests/fixture/selector/list/output.json, crates/swc_css_parser/tests/fixture/selector/list/span.rust-debug, crates/swc_css_parser/tests/fixture/selector/type/input.css, crates/swc_css_parser/tests/fixture/selector/type/output.json, crates/swc_css_parser/tests/fixture/selector/type/span.rust-debug, crates/swc_css_parser/tests/fixture/value/custom-property/input.css, crates/swc_css_parser/tests/fixture/value/custom-property/output.json, crates/swc_css_parser/tests/fixture/value/custom-property/span.rust-debug, crates/swc_css_parser/tests/fixture/value/dimension/input.css, crates/swc_css_parser/tests/fixture/value/dimension/output.json, crates/swc_css_parser/tests/fixture/value/dimension/span.rust-debug, crates/swc_css_parser/tests/fixture/value/quotes/input.css, crates/swc_css_parser/tests/fixture/value/quotes/output.json, crates/swc_css_parser/tests/fixture/value/quotes/span.rust-debug
Just test from postcss, found some cases where we should improve error recovery (no these test here, because they are broken), put in TODO list
No
No
=> Test more from postcss

crates/swc_css_parser/src/parser/base.rs, crates/swc_css_parser/src/parser/mod.rs, crates/swc_css_parser/src/parser/style_rule.rs, crates/swc_css_parser/tests/fixture/hacks/input.css, crates/swc_css_parser/tests/fixture/hacks/output.json, crates/swc_css_parser/tests/fixture/hacks/span.rust-debug, crates/swc_css_parser/tests/fixture/selector/pseudo-class/not/input.css, crates/swc_css_parser/tests/fixture/selector/pseudo-class/not/output.json, crates/swc_css_parser/tests/fixture/selector/pseudo-class/not/span.rust-debug, crates/swc_css_parser/tests/recovery/hacks/input.css, crates/swc_css_parser/tests/recovery/hacks/output.json, crates/swc_css_parser/tests/recovery/hacks/output.swc-stderr, crates/swc_css_parser/tests/recovery/ie-progid/input.css, crates/swc_css_parser/tests/recovery/ie-progid/output.json, crates/swc_css_parser/tests/recovery/ie-progid/output.swc-stderr
Recovery mode and refactor:
- fixes https://github.com/swc-project/swc/issues/3472
- move stylesheet to base, because it is base structure of parsing https://www.w3.org/TR/css-syntax-3/#parse-stylesheet, we will have more them for recovery mode in future
No
No
=> Improve recovery mode

crates/swc_css_parser/src/parser/base.rs, crates/swc_css_parser/src/parser/value/mod.rs, crates/swc_css_parser/tests/errors/rome/invalid/fit-content/invalid-call/output.stderr, crates/swc_css_parser/tests/errors/rome/invalid/grid/repeat/unclosed-lint-name/output.stderr, crates/swc_css_parser/tests/errors/rome/invalid/min-or-max/output.stderr, crates/swc_css_parser/tests/fixture/declaration/output.json, crates/swc_css_parser/tests/fixture/declaration/span.rust-debug, crates/swc_css_parser/tests/recovery/function/output.json, crates/swc_css_parser/tests/recovery/function/output.swc-stderr
Refactor logic and simplify, we are small aggression in error reporting, but we will improve this in future, also it allows to use remove simplify `parse_property_values` and improve error recovery
No
No
=> Refactor simple block

crates/swc_css_codegen/tests/fixture/at-rules/keyframes/3/input.css, crates/swc_css_codegen/tests/fixture/at-rules/keyframes/3/output.css, crates/swc_css_codegen/tests/fixture/at-rules/keyframes/3/output.min.css
Just test case for multiple keyframe selectors
No
No
=> test: case for multiple keyframe selectors

crates/swc_css_parser/src/parser/base.rs
Just refactor for https://github.com/swc-project/swc/issues/3496 (future better recovery)
No
No
=> refactor: code

packages/swc-helpers/src/_construct.js
=> fix: _setPrototypeOf is not defined

Cargo.lock, crates/swc_cli/Cargo.toml, crates/swc_cli/src/commands/plugin.rs
=> chore(ci): Remove `cargo-uttil` from dependency

crates/swc/tests/tsc-references/derivedClassConstructorWithoutSuperCall_es5.1.normal.js, crates/swc/tests/tsc-references/derivedClassConstructorWithoutSuperCall_es5.2.minified.js, crates/swc/tests/tsc-references/errorSuperPropertyAccess_es5.1.normal.js, crates/swc/tests/tsc-references/errorSuperPropertyAccess_es5.2.minified.js, crates/swc/tests/tsc-references/parserAstSpans1_es5.1.normal.js, crates/swc/tests/tsc-references/parserAstSpans1_es5.2.minified.js, crates/swc/tests/tsc-references/superCallParameterContextualTyping3_es5.1.normal.js, crates/swc/tests/tsc-references/superCallParameterContextualTyping3_es5.2.minified.js, crates/swc/tests/tsc-references/superPropertyAccessNoError_es5.1.normal.js, crates/swc/tests/tsc-references/superPropertyAccessNoError_es5.2.minified.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers1_es5.1.normal.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers1_es5.2.minified.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers2_es5.1.normal.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers2_es5.2.minified.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers3_es5.1.normal.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers3_es5.2.minified.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers4_es5.1.normal.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers4_es5.2.minified.js, crates/swc_ecma_ast/src/expr.rs, crates/swc_ecma_transforms_classes/src/super_field.rs, crates/swc_ecma_transforms_compat/src/es2015/classes/constructor.rs, crates/swc_ecma_transforms_compat/src/es2015/classes/mod.rs, crates/swc_ecma_transforms_compat/tests/es2015_classes.rs, crates/swc_ecma_transforms_compat/tests/es2022_class_properties.rs
=> fix(ecma/transform/compat): constructor

crates/swc/Cargo.toml, crates/swc_bundler/Cargo.toml, crates/swc_common/Cargo.toml, crates/swc_ecma_codegen/Cargo.toml, crates/swc_ecma_loader/Cargo.toml, crates/swc_ecma_minifier/Cargo.toml, crates/swc_ecma_preset_env/Cargo.toml, crates/swc_ecma_transforms_base/Cargo.toml, crates/swc_ecma_transforms_optimization/Cargo.toml, crates/swc_ecma_transforms_react/Cargo.toml, crates/swc_ecma_utils/Cargo.toml, crates/swc_node_bundler/Cargo.toml, crates/swc_plugin_runner/Cargo.toml, crates/testing/Cargo.toml, crates/wasm/Cargo.toml
=> build(swc): dedupe once_cell

crates/swc_ecma_transforms_compat/tests/es2015_parameters.rs, crates/swc_ecma_utils/src/function/fn_env_hoister.rs
=> fix(ecma/utils): keep super call params

node-swc/src/types.ts
Let's provide typed configuration options for experimental plugin for easier configuration.
=> refactor(node): provide typed configuration for plugins

crates/swc_ecma_parser/tests/typescript/issue-2417/input.ts, crates/swc_ecma_parser/tests/typescript/issue-2417/input.ts.json, crates/swc_ecma_transforms_typescript/tests/strip_correctness.rs
- Closes https://github.com/swc-project/swc/issues/2417
=> test(es/parser): Add a test for #2417

node-swc/src/types.ts
Fix mistakenly missing optional flag for plugins.
=> fix(swc/types): fix experimental config options

crates/swc_common/src/errors/mod.rs
=> doc(common): Document error reporting using `HANDLER`

crates/swc_cli/src/commands/plugin.rs
This PR tries to improve two minor developer experience issues:
1.  `swc plugin new` is surprisingly fast!  
the instant feedback which also told us we should not forget about `rustup target add` made us believe something went wrong 😄
maybe we could add an emoji for future beginners?
2. to develop our first visitor the list of possible methods was extremely helpful  
what do you think about adding a link to it?
=> improve experience for new plugin authors

scripts/ci/test-concurrent.sh
I have fixed a typo in a CI script output. 
=> Fixup typo

crates/swc_ecma_ast/src/expr.rs, crates/swc_ecma_ast/src/ident.rs, crates/swc_ecma_transforms_classes/src/super_field.rs, crates/swc_ecma_transforms_compat/src/bugfixes/template_literal_caching.rs, crates/swc_ecma_transforms_compat/src/es2015/block_scoping.rs, crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs, crates/swc_ecma_transforms_compat/src/es2015/object_super.rs, crates/swc_ecma_transforms_compat/src/es2015/regenerator/case.rs, crates/swc_ecma_transforms_compat/src/es2015/regenerator/mod.rs, crates/swc_ecma_transforms_compat/src/es2015/spread.rs, crates/swc_ecma_transforms_compat/src/es2015/template_literal.rs, crates/swc_ecma_transforms_compat/src/es2020/opt_chaining.rs, crates/swc_ecma_transforms_compat/src/es2022/class_properties/class_name_tdz.rs, crates/swc_ecma_transforms_compat/src/es2022/class_properties/private_field.rs, crates/swc_ecma_transforms_compat/src/es2022/static_blocks.rs, crates/swc_ecma_transforms_module/src/amd.rs, crates/swc_ecma_transforms_module/src/common_js.rs, crates/swc_ecma_transforms_module/src/umd.rs, crates/swc_ecma_transforms_module/src/util.rs, crates/swc_ecma_transforms_react/src/jsx/mod.rs, crates/swc_ecma_transforms_react/src/refresh/hook.rs, crates/swc_ecma_transforms_react/src/refresh/mod.rs, crates/swc_ecma_transforms_react/src/refresh/util.rs, crates/swc_ecma_utils/src/factory.rs
=> refactor(es): Refactor AST API

clippy.toml, crates/swc_css_codegen/src/writer/basic.rs, crates/swc_css_minifier/src/compress/selector.rs, crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/src/typescript.rs, crates/swc_ecma_minifier/src/compress/optimize/arguments.rs, crates/swc_ecma_parser/src/error.rs, crates/swc_ecma_parser/src/lib.rs, crates/swc_ecma_preset_env/src/corejs3/usage.rs, crates/swc_ecma_transforms_compat/src/es2015/template_literal.rs, crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs, crates/swc_ecma_transforms_compat/src/es2022/class_properties/private_field.rs, crates/swc_ecma_transforms_compat/src/lib.rs, crates/swc_ecma_transforms_typescript/src/strip.rs, crates/swc_estree_compat/src/swcify/stmt.rs
To make PRs more reviewable, I added some configs.
=> chore(repo): Improve clippy config

crates/swc/tests/fixture/issue-3694/1/input/.swcrc, crates/swc/tests/fixture/issue-3694/1/input/index.ts, crates/swc/tests/fixture/issue-3694/1/output/index.ts, crates/swc_ecma_parser/src/parser/typescript.rs, crates/swc_ecma_parser/tests/typescript/issue-3694/input.ts, crates/swc_ecma_parser/tests/typescript/issue-3694/input.ts.json
=> fix(parser/ts): allow TsInstantiation in extends clause

crates/swc_ecma_ast/src/lit.rs, crates/swc_ecma_transforms_compat/src/es2015/regenerator/case.rs, crates/swc_ecma_transforms_compat/src/es2015/regenerator/mod.rs, crates/swc_ecma_transforms_compat/src/es2015/typeof_symbol.rs, crates/swc_ecma_transforms_compat/src/es2017/async_to_generator.rs, crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs, crates/swc_ecma_transforms_module/src/amd.rs, crates/swc_ecma_transforms_module/src/common_js.rs, crates/swc_ecma_transforms_module/src/umd.rs, crates/swc_ecma_transforms_module/src/util.rs, crates/swc_ecma_transforms_optimization/src/simplify/expr/mod.rs, crates/swc_ecma_transforms_proposal/src/decorators/legacy/metadata.rs, crates/swc_ecma_transforms_proposal/src/decorators/legacy/mod.rs, crates/swc_ecma_transforms_proposal/src/decorators/mod.rs, crates/swc_ecma_transforms_react/src/jsx/mod.rs, crates/swc_ecma_transforms_react/src/jsx_src/mod.rs, crates/swc_ecma_transforms_react/src/refresh/hook.rs
=> refactor(es): Use recommended ast apis

crates/swc_ecma_transforms_module/src/util.rs, crates/swc_visit_macros/src/lib.rs
- This is part of https://github.com/swc-project/swc/pull/3741
=> feat(visit): Allow using `?Sized` as visitor

crates/swc/src/config/mod.rs, crates/swc/src/lib.rs, crates/swc_ecma_minifier/src/option/terser.rs, crates/swc_ecma_parser/src/lib.rs, crates/swc_ecma_transforms/Cargo.toml, crates/swc_ecma_transforms_base/src/helpers/mod.rs, crates/swc_ecma_transforms_module/src/umd/config.rs, crates/swc_ecma_transforms_optimization/src/const_modules.rs, crates/swc_ecma_transforms_proposal/Cargo.toml, crates/swc_ecma_transforms_react/src/jsx/mod.rs, crates/swc_ecma_transforms_typescript/Cargo.toml
Descriptions are written to the code itself, using rustdoc.
---
- Start: 24.8 MB
- After 76c85275a6d6cbaeee46e12dcdcd360f316e0bb5: 22.5MB
- After 119e7e6343e2fcb7f960ee7e4243729fc551eda0: 21.7MB
=> feat(es/parser): Provide more api for reducing binary size

Cargo.lock, crates/swc/src/lib.rs, crates/swc_cli/Cargo.toml, crates/swc_cli/src/commands/compile.rs, crates/swc_cli/src/commands/mod.rs, crates/swc_cli/src/commands/plugin.rs
This PR enables trace for the cli as well, via `--experimental-trace` boolean flag.
- https://github.com/swc-project/swc/issues/3071
=> feat(swc/cli): add trace configuration for compile

.github/workflows/bot.yml, scripts/bot/src/auto-rebase.ts, scripts/bot/src/cargo/bump.ts, scripts/bot/src/util/git.ts
=> chore: Skip CI

.github/workflows/cargo.yml, .github/workflows/docs.yml, scripts/bot/src/auto-rebase.ts, scripts/bot/src/cargo/bump.ts, scripts/bot/src/util/git.ts
=> chore: Skip CI for automated commits

.github/workflows/bot.yml, .github/workflows/cargo.yml, Cargo.lock, crates/swc_ecma_parser/src/parser/stmt.rs, crates/swc_ecma_quote/Cargo.toml, crates/swc_ecma_quote/src/clone.rs, crates/swc_ecma_quote/src/lib.rs, crates/swc_ecma_quote/tests/simple.rs, crates/swc_ecma_quote_macros/src/ast/id.rs, crates/swc_ecma_quote_macros/src/ast/lit.rs, crates/swc_ecma_quote_macros/src/ctxt.rs, crates/swc_ecma_quote_macros/src/input.rs, crates/swc_ecma_quote_macros/src/lib.rs, crates/swc_ecma_quote_macros/src/ret_type.rs
We support implicit cloning, but it's restricted only to support some cheap-to-clone types.
We can improve error messages for using non-clonable type multiple times **if** we use nightly features.
- Closes #3146
=> feat(es/quote): Support variables

docs/adr/00001-support-transformation-plugin-native.md, docs/adr/00002-support-event-trace-profiling.md
We have basic setups for trace now and started to expand it. Think it's good time to compile some of decision factors into adr for keeping references / history.
=> docs(adr): adr-00002 for event trace profiling

Cargo.lock, crates/swc_ecma_quote/Cargo.toml, crates/swc_plugin/Cargo.toml, crates/swc_plugin/src/lib.rs
I presume new feature is for the plugin authors? 
PR exposes it via swc_plugin package.
=> feat(swc/plugin): expose swc_ecma_quote

crates/swc_ecma_dep_graph/src/lib.rs
My previous https://github.com/swc-project/swc/pull/3758.
I found another [case](https://github.com/depcheck/depcheck/blob/3d1a45fe8ceb4d7d38c34e99d61b327aa97f65d3/test/fake_modules/require_resolve/index.js#L1) which tests `require.resolve` [member expression](https://nodejs.org/api/modules.html#requireresolverequest-options) as dependency.
=> feat(es/dep-graph): Implement require.resolve expression in visit_call_expr for DependencyCollector

crates/swc_css_codegen/tests/fixture/declaration/important/output.css, crates/swc_css_codegen/tests/fixture/declaration/important/output.min.css, crates/swc_css_codegen/tests/fixture/list_of_declarations/3/input.css, crates/swc_css_codegen/tests/fixture/list_of_declarations/3/output.css, crates/swc_css_codegen/tests/fixture/list_of_declarations/3/output.min.css, crates/swc_css_parser/src/parser/base.rs, crates/swc_css_parser/tests/recovery/declaration/basic/output.json, crates/swc_css_parser/tests/recovery/declaration/important/output.json, crates/swc_css_parser/tests/recovery/delim-token/bang/output.json, crates/swc_css_parser/tests/recovery/hacks/output.json, crates/swc_css_parser/tests/recovery/value/custom-properties/exclamation/output.json, crates/swc_css_parser/tests/recovery/vercel/004/input.css, crates/swc_css_parser/tests/recovery/vercel/004/output.json, crates/swc_css_parser/tests/recovery/vercel/004/output.swc-stderr
fix codegen with semicolon
No
No
=> fix(css/codegen): semicolon

Cargo.lock, crates/swc/Cargo.toml, crates/swc/src/config/mod.rs, crates/swc_cached/Cargo.toml, crates/swc_cached/src/lib.rs, crates/swc_cached/src/regex.rs, crates/swc_ecma_loader/Cargo.toml, crates/swc_ecma_loader/src/resolvers/tsc.rs, crates/swc_ecma_minifier/Cargo.toml, crates/swc_ecma_minifier/src/option/mod.rs, crates/swc_stylis/tests/prefixer.rs
- `CachedRegex` implements `Serialize`
- `CachedRegex` implements `Deserialize`
- `CachedRegex` implements `Deref<Target = Regex>`
=> feat(swc/config): Add a dedicated cached regex type

crates/swc_ecma_transforms_compat/src/es2017/async_to_generator.rs, crates/swc_ecma_transforms_compat/src/es2017/mod.rs, crates/swc_ecma_transforms_compat/src/es2018/mod.rs, crates/swc_ecma_transforms_compat/src/es2018/object_rest_spread.rs, crates/swc_ecma_transforms_compat/src/es2019/mod.rs, crates/swc_ecma_transforms_compat/src/es2019/optional_catch_binding.rs
Continuing trace implementations for the transforms.
=> feat(trace): add trace spans for es2017-19 transforms

Cargo.lock, crates/swc_cli/Cargo.toml, crates/swc_cli/src/commands/bundle.rs, crates/swc_cli/src/commands/compile.rs, crates/swc_cli/src/commands/lint.rs, crates/swc_cli/src/commands/minify.rs, crates/swc_cli/src/commands/mod.rs, crates/swc_cli/src/commands/plugin.rs, crates/swc_cli/src/main.rs, crates/swc_cli/src/util/mod.rs, crates/swc_cli/src/util/trace.rs
Minor refactor with new empty subcommands we'll support.
=> refactor(swc/cli): setup subcommands for the features

crates/swc_ecma_transforms_compat/src/es2015/block_scoped_fn.rs, crates/swc_ecma_transforms_compat/src/es2015/block_scoping/mod.rs, crates/swc_ecma_transforms_compat/src/es2015/block_scoping/operator.rs, crates/swc_ecma_transforms_compat/src/es2015/block_scoping/vars.rs, crates/swc_ecma_transforms_compat/src/es2015/classes/constructor.rs, crates/swc_ecma_transforms_compat/src/es2015/classes/mod.rs, crates/swc_ecma_transforms_compat/src/es2015/computed_props.rs, crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs, crates/swc_ecma_transforms_compat/src/es2015/duplicate_keys.rs, crates/swc_ecma_transforms_compat/src/es2015/for_of.rs, crates/swc_ecma_transforms_compat/src/es2015/function_name.rs, crates/swc_ecma_transforms_compat/src/es2015/instanceof.rs, crates/swc_ecma_transforms_compat/src/es2015/mod.rs, crates/swc_ecma_transforms_compat/src/es2015/new_target.rs, crates/swc_ecma_transforms_compat/src/es2015/object_super.rs, crates/swc_ecma_transforms_compat/src/es2015/parameters.rs, crates/swc_ecma_transforms_compat/src/es2015/regenerator/case.rs, crates/swc_ecma_transforms_compat/src/es2015/regenerator/hoist.rs, crates/swc_ecma_transforms_compat/src/es2015/regenerator/leap.rs, crates/swc_ecma_transforms_compat/src/es2015/regenerator/mod.rs, crates/swc_ecma_transforms_compat/src/es2015/shorthand_property.rs, crates/swc_ecma_transforms_compat/src/es2015/spread.rs, crates/swc_ecma_transforms_compat/src/es2015/sticky_regex.rs, crates/swc_ecma_transforms_compat/src/es2015/template_literal.rs, crates/swc_ecma_transforms_compat/src/es2015/typeof_symbol.rs, crates/swc_ecma_transforms_compat/src/es2016/exponentation.rs, crates/swc_ecma_transforms_compat/src/es2016/mod.rs
Adding spans for es2015. Now es3 / bugfixs are left - once it's done and https://github.com/swc-project/swc/pull/3801 gets checked in, we can share this as experimental release.
=> feat(trace): add trace spans for es2015 transform

crates/node/src/util.rs
This PR filters out cranelift and other log records from trace generation. I feel there maybe better, effecient way - but couldn't find it for now. Will try to dig time to time. Also I realized release build doesn't generate any trace due to compile time loglevel flag. PR changes it to runtime level to allow trace to be collected.
- https://github.com/swc-project/swc/issues/3799
=> fix(trace): filter cranelift, log events

crates/swc/src/builder.rs, crates/swc/tests/fixture/issue-1799/case1/output/index.js, crates/swc/tests/fixture/issue-1799/case2/output/index.js, crates/swc/tests/fixture/issue-1799/case3/output/index.js, crates/swc/tests/fixture/issue-1799/case6-no-jsx/output/index.js, crates/swc_ecma_preset_env/src/lib.rs, crates/swc_ecma_transforms_base/src/assumptions.rs, crates/swc_ecma_transforms_compat/src/es2017/async_to_generator.rs, crates/swc_ecma_transforms_compat/src/es2017/mod.rs, crates/swc_ecma_transforms_compat/tests/es2015_block_scoping.rs, crates/swc_ecma_transforms_compat/tests/es2015_classes.rs, crates/swc_ecma_transforms_compat/tests/es2015_parameters.rs, crates/swc_ecma_transforms_compat/tests/es2015_regenerator.rs, crates/swc_ecma_transforms_compat/tests/es2017_async_to_generator.rs, crates/swc_ecma_transforms_compat/tests/es2022_class_properties.rs, crates/swc_ecma_transforms_optimization/tests/simplify.rs, crates/swc_ecma_transforms_typescript/benches/compat.rs, crates/swc_ecma_transforms_typescript/tests/strip.rs, crates/swc_ecma_utils/src/function/function_wrapper.rs
=> feat(es/compat): loose mode for `async_to_generator`

crates/swc_ecma_parser/src/parser/expr/ops.rs, crates/swc_ecma_parser/src/parser/stmt.rs
=> fix(es/parser): allow `await` in non-strict mode

crates/swc/tests/fixture/issue-2336/input/.swcrc, crates/swc/tests/fixture/issue-2336/input/input.tsx, crates/swc/tests/fixture/issue-2336/output/input.tsx
=> test(es): Add a test for a fixed issue

crates/swc/tests/fixture/issue-2423/input/.swcrc, crates/swc/tests/fixture/issue-2423/input/index.ts, crates/swc/tests/fixture/issue-2423/output/index.map, crates/swc/tests/fixture/issue-2423/output/index.ts, crates/swc/tests/fixture/issue-2636/input/.swcrc, crates/swc/tests/fixture/issue-2636/input/index.ts, crates/swc/tests/fixture/issue-2636/output/index.ts
- Closes #2423 
- Closes #2636
=> test(es): Add tests for fixed issues

crates/swc_ecma_minifier/.gitignore, crates/swc_ecma_minifier/examples/minifier.rs, crates/swc_ecma_minifier/src/pass/merge_exports.rs
=> perf(es/minifier): Add a fast-path for export merger

crates/swc_common/src/rustc_data_structures/stable_hasher.rs, crates/swc_common/src/syntax_pos.rs
=> chore(common): align stable_hasher to latest rustc

crates/swc_ecma_parser/src/error.rs, crates/swc_ecma_parser/src/parser/class_and_fn.rs, crates/swc_ecma_parser/src/parser/stmt.rs, crates/swc_ecma_parser/src/parser/stmt/module_item.rs, crates/swc_ecma_parser/src/parser/typescript.rs, crates/swc_ecma_parser/tests/typescript-errors/class/abstract/input.ts, crates/swc_ecma_parser/tests/typescript-errors/class/abstract/input.ts.stderr, crates/swc_ecma_parser/tests/typescript-errors/class/duplicated-modifiers/input.ts.stderr
And also don't allow abstarct prop to have initializer and abstarct member to have body
=> feat(es/parser): only allow abstract member in abstract class

crates/swc_ecma_transforms_module/src/amd.rs, crates/swc_ecma_transforms_module/src/common_js.rs, crates/swc_ecma_transforms_module/src/umd.rs, crates/swc_ecma_transforms_module/src/util.rs, crates/swc_ecma_transforms_module/tests/amd.rs, crates/swc_ecma_transforms_module/tests/common_js.rs, crates/swc_ecma_transforms_module/tests/fixture/commonjs/export-update/1/output.js, crates/swc_ecma_transforms_module/tests/umd.rs
A regression is introduced in #3909.
This pull request correct the return value of exported suffix update expression.
=> fix(es/module): correct return value of suffix update expression

crates/swc/tests/tsc-references/jsxJsxsCjsTransformChildren_es2015.2.minified.js, crates/swc/tests/tsc-references/jsxJsxsCjsTransformChildren_es5.2.minified.js, crates/swc/tests/tsc-references/jsxReactTestSuite_es2015.2.minified.js, crates/swc/tests/tsc-references/jsxReactTestSuite_es5.2.minified.js, crates/swc/tests/tsc-references/tsxReactComponentWithDefaultTypeParameter1_es5.2.minified.js, crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/src/compress/pure/misc.rs
- https://github.com/swc-project/swc/pull/3925
This PR is folllow-up PR for #3925
=> perf(es/minifier): Make optimization of pure calls parallel

crates/swc_ecma_transforms_compat/src/es2015/classes/constructor.rs, crates/swc_ecma_transforms_compat/src/es2015/classes/mod.rs, crates/swc_ecma_transforms_compat/tests/es2015_classes.rs
=> fix(es/transforms/compat): refer this in constructor when set `super_is_callable_constructor`

node-swc/src/types.ts
**Description:** This PR adds `reserved` to `TerserMangleOptions`. Currently, the `reserved` feature is implemented, but typescript declaration is missing.
**Related issue (if exists):** none
=> fix: add `reserved` to `TerserMangleOptions`

crates/swc/tests/errors/lints/const-assign/1/output.swc-stderr, crates/swc/tests/errors/lints/duplicate-bindings/import-import/output.swc-stderr, crates/swc/tests/errors/lints/duplicate-bindings/module/export/output.swc-stderr, crates/swc/tests/errors/lints/duplicate-bindings/module/import/output.swc-stderr, crates/swc/tests/errors/lints/duplicate-bindings/var/1/output.swc-stderr, crates/swc/tests/errors/lints/duplicate-bindings/var/2/output.swc-stderr, crates/swc/tests/errors/lints/duplicate-exports/1/output.swc-stderr, crates/swc/tests/errors/lints/duplicate-exports/2/output.swc-stderr, crates/swc/tests/errors/lints/duplicate-exports/3/output.swc-stderr, crates/swc/tests/errors/lints/no-dupe-args/1/output.swc-stderr, crates/swc/tests/errors/lints/no-dupe-args/2/output.swc-stderr, crates/swc/tests/errors/lints/no-dupe-args/3/output.swc-stderr, crates/swc/tests/errors/lints/no-dupe-args/4/output.swc-stderr, crates/swc/tests/errors/lints/no-loop-func/default/output.swc-stderr, crates/swc_common/src/errors/emitter.rs, crates/swc_ecma_lints/src/rules/const_assign.rs, crates/swc_ecma_lints/src/rules/duplicate_bindings.rs, crates/swc_ecma_lints/src/rules/duplicate_exports.rs, crates/swc_ecma_lints/src/rules/no_dupe_args.rs
=> chore: refine error report text

crates/swc/src/lib.rs, crates/wasm/src/lib.rs, node-swc/__tests__/error_test.mjs
=> fix(es): Change error message as it can be misleading

.gitattributes
=> chore: update linguist

crates/swc/tests/exec.rs, crates/swc/tests/exec/.issue-2624/exec.js, crates/swc/tests/exec/.issue-2834/exec.js, crates/swc/tests/exec/.issue-2865/exec.js, crates/swc/tests/exec/.issue-2948/exec.js, crates/swc/tests/exec/.issue-3006/exec.js, crates/swc/tests/exec/.issue-3660/exec.ts, crates/swc/tests/exec/.issue-3700/exec.js, crates/swc/tests/exec/.issue-3965/.swcrc, crates/swc/tests/exec/.issue-3965/exec.js
Description:
This PR adds ignored execution tests for various issues.
=> test(es): Add auto-closable tests

crates/swc/tests/fixture/decorators/issue-4021/input/.swcrc, crates/swc/tests/fixture/decorators/issue-4021/input/index.ts, crates/swc/tests/fixture/decorators/issue-4021/output/index.ts, crates/swc_ecma_transforms_proposal/src/decorators/legacy/mod.rs
=> fix(es/decorator): Remove `noop_fold_type`

crates/swc_ecma_transforms_base/src/helpers/mod.rs
This PR adds support for helpers in script mode. For now, we does not support `externalHelpers` for scripts, as there is no standard for importing other files from a script.
- Closes https://github.com/swc-project/swc/issues/2385
=> fix(es/helpers): Inject helpers for scripts

crates/swc_ecma_parser/src/lexer/number.rs
Hi!
This is my first PR to swc (and hopefully not the last 👍 ) so let me know if I did anything wrong for the contribution process :)
I'm currently trying to build Parcel (it uses swc_ecma_parser) and it currently fails on https://github.com/swc-project/swc/issues/4004 -- so I figured: Let's put up a PR!
Closes https://github.com/swc-project/swc/issues/4004
=> fix(ecma/parser): Reorder read_digits parameters

crates/swc_ecma_transforms/tests/decorators.rs, crates/swc_ecma_transforms_proposal/src/decorators/legacy/mod.rs
=> fix(ecma/transform/decorator): insert initializer to constructor with body

crates/swc/src/config/mod.rs, crates/swc_ecma_transforms_base/src/fixer.rs, crates/swc_ecma_transforms_optimization/tests/expr-simplifier/issue-3115/input.js, crates/swc_ecma_transforms_optimization/tests/expr-simplifier/issue-3115/output.js, crates/swc_ecma_transforms_optimization/tests/fixture.rs
This pass should be applied as the first pass.
- Closes #3115
=> feat(es/transforms/base): Add `paren_remover`

package.json
Partial revert to https://github.com/swc-project/swc/pull/4035/commits/68247642254e3a3e9cef96dcac3cb22d668caceb#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R62, this works locally but Ci's publish workflow fails somehow 🤔 
We can dig this later, for now unblock CI failure by revert it.
=> ci(publish): revert pkg script to fix publish

tsconfig.json
Minor fix to tsconfig's incremental build as it tries to traverse upward.
=> build(tsconfig): set tsbuildinfo filename

crates/swc/tests/errors/lints/no-new-symbol/default/.swcrc, crates/swc/tests/errors/lints/no-new-symbol/default/input.js, crates/swc/tests/errors/lints/no-new-symbol/default/output.swc-stderr, crates/swc_ecma_lints/src/config.rs, crates/swc_ecma_lints/src/rules/mod.rs, crates/swc_ecma_lints/src/rules/no_new_symbol.rs
implement no-new-symbol rule
No
=> feat(es/lint): implement no-new-symbol rule

crates/swc_ecma_parser/tests/typescript-errors/issue-3262/input.ts, crates/swc_ecma_parser/tests/typescript-errors/issue-3262/input.ts.stderr
- Closes https://github.com/swc-project/swc/issues/3262
=> test(es/parser): Add a test for a fixed issue

crates/swc_ecma_transforms_module/src/common_js.rs, crates/swc_ecma_transforms_module/src/util.rs, crates/swc_ecma_transforms_module/tests/common_js.rs, crates/swc_ecma_transforms_module/tests/fixture/commonjs/issue-1201/1/input.js, crates/swc_ecma_transforms_module/tests/fixture/commonjs/issue-1201/1/output.js
- Closes https://github.com/swc-project/swc/issues/1202
=> feat(es/module/cjs): Support `import.meta.url`

crates/swc_ecma_preset_env/src/lib.rs, crates/swc_ecma_transforms_compat/src/es2015/object_super.rs, crates/swc_ecma_transforms_compat/tests/es2015_object_super.rs
=> fix(es/transforms/compat): visit non method prop in nested object literal

Cargo.lock, crates/swc_bundler/Cargo.toml, crates/swc_bundler/tests/common/mod.rs, crates/swc_ecma_codegen/src/lib.rs
=> fix(es/codegen): Emit decorators on class methods

crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_parser/src/parser/ident.rs, crates/swc_ecma_parser/tests/typescript-errors/issue-1391/case2/input.ts.stderr, crates/swc_ecma_parser/tests/typescript-errors/let/index.ts, crates/swc_ecma_parser/tests/typescript-errors/let/index.ts.stderr
=> fix(es/parser): let should be reserved word in strict mode

Cargo.lock, crates/node/Cargo.toml, crates/swc_cli/Cargo.toml, crates/swc_plugin_runner/Cargo.toml, crates/wasm/Cargo.toml, tests/rust-plugins/swc_internal_plugin/Cargo.lock
Minor bump fixes some panics (https://github.com/wasmerio/wasmer/blob/master/CHANGELOG.md#fixed)
=> build(cargo): bump up wasmer-*

crates/swc/tests/fixture/issue-3686/1/input/.swcrc, crates/swc/tests/fixture/issue-3686/1/input/index.ts, crates/swc/tests/fixture/issue-3686/1/output/index.ts, crates/swc_ecma_minifier/tests/eval.rs, crates/swc_ecma_transforms_typescript/src/strip.rs
- Closes https://github.com/swc-project/swc/issues/3686
=> fix(es/typescript): Collect all bindings in `strip`

crates/swc/tests/errors/lints/use-is-nan/js/default/output.swc-stderr, crates/swc/tests/errors/lints/use-is-nan/js/disable-index-of-check/output.swc-stderr, crates/swc/tests/errors/lints/use-is-nan/js/disable-switch-check/output.swc-stderr, crates/swc/tests/errors/lints/use-is-nan/ts/default/output.swc-stderr, crates/swc/tests/errors/lints/use-is-nan/ts/disable-any-cast/output.swc-stderr, crates/swc_ecma_lints/src/lib.rs, crates/swc_ecma_lints/src/rules/eqeqeq.rs, crates/swc_ecma_lints/src/rules/use_is_nan.rs
I wanted to check if CST is required to create a good linter, but it seems like the current api is enough for good error messages.
=> feat(es/lints): Improve error messages

.github/workflows/publish-node.yml
Attempt to fix permission issues for the executable.
=> fix(swc/cli): fix executable permission

crates/swc_plugin/Cargo.toml, crates/swc_plugin/src/lib.rs
This greatly reduces the compile time.
=> feat(es/plugin): Make `quote` optional

crates/swc/tests/errors/lints/symbol-description/allow-any-as-symbol-description/.swcrc, crates/swc/tests/errors/lints/symbol-description/allow-any-as-symbol-description/input.js, crates/swc/tests/errors/lints/symbol-description/allow-any-as-symbol-description/output.swc-stderr, crates/swc/tests/errors/lints/symbol-description/default/.swcrc, crates/swc/tests/errors/lints/symbol-description/default/input.js, crates/swc/tests/errors/lints/symbol-description/default/output.swc-stderr, crates/swc_ecma_lints/src/config.rs, crates/swc_ecma_lints/src/rules/mod.rs, crates/swc_ecma_lints/src/rules/symbol_description.rs
feat(es/lint): implement symbol-description rule
No
=> feat(es/lint): implement symbol-description rule

Cargo.lock, crates/swc_atoms/Cargo.toml, crates/swc_common/Cargo.toml
- related with https://github.com/swc-project/swc/issues/3591
=> build(cargo): bump up string-cache

crates/swc/tests/errors/lints/no-obj-calls/default/.swcrc, crates/swc/tests/errors/lints/no-obj-calls/default/input.js, crates/swc/tests/errors/lints/no-obj-calls/default/output.swc-stderr, crates/swc_ecma_lints/src/config.rs, crates/swc_ecma_lints/src/rules/mod.rs, crates/swc_ecma_lints/src/rules/no_obj_calls.rs
Implement no-obj-calls rule
No
=> feat(es/lint): implement no-obj-calls rule

crates/swc_ecma_minifier/src/compress/optimize/switches.rs, crates/swc_ecma_minifier/tests/TODO.txt, crates/swc_ecma_minifier/tests/golden.txt, crates/swc_ecma_minifier/tests/terser/compress/switch/issue_1663/output.js, crates/swc_ecma_transforms_optimization/src/simplify/branch/mod.rs
=> feat(es/minifier): Optimize switches more correctly

crates/swc/tests/tsc-references/callChain_es5.1.normal.js, crates/swc/tests/tsc-references/callChain_es5.2.minified.js, crates/swc/tests/tsc-references/callWithSpread4_es5.1.normal.js, crates/swc/tests/tsc-references/callWithSpread4_es5.2.minified.js, crates/swc/tests/tsc-references/keyofAndIndexedAccess_es5.1.normal.js, crates/swc_ecma_transforms_compat/src/es2015/spread.rs, crates/swc_ecma_transforms_compat/tests/es2015_spread.rs
=> fix(es/compat): handle string literial spread

crates/swc_ecma_transforms_compat/src/es2015/new_target.rs, crates/swc_ecma_transforms_compat/tests/es2015_new_target.rs
=> fix(es/compat): handle `new.target` in getter/setter prop

crates/swc/tests/fixture/issues-3xxx/issue-3417/1/output/index.ts, crates/swc_ecma_transforms_compat/src/es2015/block_scoping/mod.rs, crates/swc_ecma_transforms_compat/tests/es2015_block_scoping.rs
It seems like `continue` is not needed in this scenario, tsc has a better output.
closes #4196
=> fix(es/compat): remove `continue` in block scoping

crates/swc_ecma_parser/src/lib.rs, crates/swc_ecma_parser/src/parser/class_and_fn.rs, crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_parser/tests/typescript/issue-4178/index.ts, crates/swc_ecma_parser/tests/typescript/issue-4178/index.ts.json
Fixes https://github.com/swc-project/swc/issues/4178 by checking if we are the child of a braceless arrow fn
Fixes https://github.com/swc-project/swc/issues/4178
=> fix(ecma_parser): Update arrow fn parsing in TS to test if direct child of braceless arrow fn

Cargo.lock
- https://github.com/swc-project/swc/issues/4188
=> feat(common/preset-env): Dedup `arrayvec`

.github/workflows/integration.yml, crates/swc_ecma_minifier/src/compress/optimize/sequences.rs
We don't dig into `b` needlessly.
- https://github.com/swc-project/swc/pull/4216: This is extracted from #4216 to make reviewing easier
=> perf(es/minifier): Add fast-path for sequences pass

crates/swc_cli/src/commands/plugin.rs
This PR updates the plugin template to match the changes from https://github.com/swc-project/swc/pull/4206
=> Update plugin lib.rs template

crates/swc_css_ast/src/at_rule.rs, crates/swc_css_ast/src/base.rs, crates/swc_css_ast/src/selector.rs, crates/swc_css_ast/src/token.rs, crates/swc_css_ast/src/value.rs
=> feat(css/ast): derive attributes

crates/swc_common/src/plugin.rs, crates/swc_plugin/src/lib.rs, crates/swc_plugin_comments/src/plugin_comments_proxy.rs, crates/swc_plugin_runner/src/host_environment.rs, crates/swc_plugin_runner/src/imported_fn/comments.rs, crates/swc_plugin_runner/src/imported_fn/handler.rs, crates/swc_plugin_runner/src/imported_fn/hygiene.rs, crates/swc_plugin_runner/src/imported_fn/mod.rs, crates/swc_plugin_runner/src/imported_fn/set_transform_result.rs, tests/rust-plugins/swc_internal_plugin/Cargo.lock
PR implements remaining comments interfaces along with some refactor to reduce repeated codes for the implementations. Also separate hostenvironment for each impl to not to expose too much details for other features.
- closes https://github.com/swc-project/swc/issues/4182
=> Feat plugin mutable comment

crates/swc/tests/fixture/issues-4xxx/issue-4233/1/input/.swcrc, crates/swc/tests/fixture/issues-4xxx/issue-4233/1/input/index.ts, crates/swc/tests/fixture/issues-4xxx/issue-4233/1/output/index.ts, crates/swc_ecma_codegen/src/lib.rs
- Closes https://github.com/swc-project/swc/issues/4233
=> fix(es/codegen): Handle comments on the argument of `throw`

crates/swc/tests/fixture/issues-1xxx/issue-1682/case1/output/index.ts, crates/swc/tests/fixture/issues-1xxx/issue-1682/case2/output/index.ts, crates/swc_bundler/src/bundler/chunk/computed_key.rs, crates/swc_bundler/src/bundler/finalize.rs, crates/swc_ecma_transforms_module/src/common_js.rs, crates/swc_ecma_transforms_module/src/util.rs, crates/swc_ecma_transforms_module/tests/common_js.rs, crates/swc_ecma_utils/src/lib.rs
I initially thought check if it contains await expr would be enough, but later I realize it may cause evalution order problem...
closes #4253
=> fix(es/module): TLA in dynamic import

crates/swc_css_prefixer/src/prefixer.rs, crates/swc_css_prefixer/tests/fixture/writing-mode/input.css, crates/swc_css_prefixer/tests/fixture/writing-mode/output.css
Bug fix + some help functions to future improvements
No
No
=> fix(css/prefixer): bug with writing-mode

crates/swc_plugin_runner/src/load_plugin.rs
This PR enables `wasm32-wasi` target plugin to have limited filesystem access to cwd, under the `/cwd` alias.
Since this relies on wasi binding to syscall, practically only `@swc/core` would enable actual filesystem support. Wasm, or other runtime environment's sandbox will still limit access.
Primary reason for exposing this is for the cases plugin need some side effect to the filesystem: for some cases, plugin 1. may read from arbitary metadata other than precompiled value (node_modules, or package.json, etcs) 2. may need to emit output other than transformed program. 
Still, this is implicitly enabled to cwd only and does not expose any copnfigurable value yet. As noted in comments, we may need some feedback if we really want to make this as public interface. …
=> feat(swc/plugin_runner): allow cwd fs access from wasi plugin

crates/swc_plugin_comments/src/plugin_comments_proxy.rs
Minor improvement to allow copy, clone for the proxy. Currently it's overly restrictive to pass references only within plugin.
=> feat(swc/plugin): supports copy, clone for the comments proxy

.github/workflows/cargo.yml
=> chore(ci): Fix CI

crates/swc_ecma_parser/src/parser/typescript.rs
Remove unnecessary method `parse_ts_non_conditional_type_within_ctx`.
=> refactor(es/parser): Simplify logic

crates/swc_ecma_loader/tests/node_resolver.rs, crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/src/compress/optimize/unused.rs, crates/swc_ecma_minifier/src/compress/pure/mod.rs, crates/swc_ecma_minifier/tests/TODO.txt, crates/swc_ecma_minifier/tests/golden.txt, crates/swc_ecma_minifier/tests/terser/compress/dead-code/dead_code_const_annotation/input.js, crates/swc_ecma_minifier/tests/terser/compress/dead-code/dead_code_const_annotation_complex_scope/input.js, crates/swc_ecma_minifier/tests/terser/compress/dead-code/dead_code_const_declaration/output.js, crates/swc_ecma_minifier/tests/terser/compress/dead-code/dead_code_constant_boolean_should_warn_more/output.js, crates/swc_ecma_minifier/tests/terser/compress/dead-code/dead_code_constant_boolean_should_warn_more_strict/output.js, crates/swc_ecma_utils/src/lib.rs
=> fix(es/minifier): Respect `dead_code`

crates/swc/src/builder.rs, crates/swc/src/config/mod.rs, crates/swc_ecma_codegen/src/tests.rs, crates/swc_ecma_parser/src/lib.rs, crates/swc_ecma_parser/src/parser/class_and_fn.rs, crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_parser/src/parser/stmt.rs, crates/swc_ecma_parser/src/parser/stmt/module_item.rs, crates/swc_ecma_parser/tests/comments.rs, crates/swc_ecma_parser/tests/span.rs, crates/swc_ecma_preset_env/tests/test.rs, crates/swc_ecma_transforms_compat/tests/es2022_static_blocks.rs, crates/swc_ecma_transforms_module/tests/common_js.rs, crates/swc_ecma_transforms_typescript/tests/strip_correctness.rs, crates/swc_estree_compat/tests/convert.rs, crates/swc_estree_compat/tests/flavor.rs
- Closes https://github.com/swc-project/swc/issues/4317
=> fix(es/parser): Enable static blocks by default

crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/src/compress/pure/misc.rs, crates/swc_ecma_minifier/tests/TODO.txt, crates/swc_ecma_minifier/tests/golden.txt, crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/issue_2954_2/output.js, crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/issue_2954_3/output.js
- We now skip more expressions.
=> feat(es/minifier): Improve sequential inliner

crates/swc_ecma_codegen/src/decl.rs, crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/tests/fixture.rs, crates/swc_ecma_codegen/tests/fixture/issues/4344/input.ts, crates/swc_ecma_codegen/tests/fixture/issues/4344/output.ts
- Closes https://github.com/swc-project/swc/issues/4344
=> fix(es/codegen): Emit decorators before export

.husky/pre-commit, CONTRIBUTING.md
We now uses `fd` instead of `find`
=> chore(repo): Make git commit faster

crates/swc/benches/bugs.rs, crates/swc/benches/minify.rs, crates/swc/benches/typescript.rs, crates/swc_ecma_codegen/benches/bench.rs, crates/swc_ecma_codegen/benches/with_parse.rs, crates/swc_ecma_minifier/benches/full.rs, crates/swc_ecma_parser/benches/compare.rs, crates/swc_ecma_parser/benches/lexer.rs, crates/swc_ecma_parser/benches/parser.rs, crates/swc_ecma_preset_env/benches/polyfills.rs, crates/swc_ecma_transforms_base/benches/base.rs, crates/swc_ecma_transforms_base/benches/deps.rs, crates/swc_ecma_transforms_base/benches/time_complexity.rs, crates/swc_ecma_transforms_typescript/benches/compat.rs, crates/swc_estree_compat/benches/babelify.rs
This will improve https://swc.rs/docs/benchmarks
=> chore(es): Rename benchmarks

crates/swc_ecma_minifier/src/compress/optimize/strings.rs, crates/swc_ecma_minifier/src/compress/pure/evaluate.rs, crates/swc_ecma_minifier/src/compress/pure/misc.rs, crates/swc_ecma_minifier/src/compress/pure/mod.rs, crates/swc_ecma_minifier/src/compress/pure/strings.rs, crates/swc_ecma_minifier/tests/TODO.txt, crates/swc_ecma_minifier/tests/golden.txt, crates/swc_ecma_minifier/tests/terser/compress/template-string/template_string_with_predefined_constants/output.js
- We now handle nested template literals.
- We now drop expressions in template literals if it's ignored.
=> feat(es/minifier): Implement all template literal evaluation rules

node-swc/src/types.ts
(as minification documentation https://swc.rs/docs/configuration/minification says)
=> chore(node/types): Add `unsafe` to compress options

crates/swc/src/builder.rs, crates/swc/src/config/mod.rs, crates/swc_ecma_minifier/src/option/mod.rs, crates/swc_ecma_minifier/tests/compress.rs
=> fix(es/minifier): Fix default values of `toplevel`

crates/swc_ecma_minifier/scripts/next/start.sh, crates/swc_ecma_minifier/src/pass/mangle_names/real_impl.rs
=> fix(es/minifier): Apply name mangler even more

crates/swc_cli/src/commands/compile.rs
add --out-file-extension and --keep-file-extension for native swc cli
#3067 #4017
=> feat(cli): support set output file extension

crates/swc/tests/fixture/issues-4xxx/issue-4314/1/input/.swcrc, crates/swc/tests/fixture/issues-4xxx/issue-4314/1/input/input.js, crates/swc/tests/fixture/issues-4xxx/issue-4314/1/output/input.js, crates/swc/tests/fixture/issues-4xxx/issue-4314/2/input/.swcrc, crates/swc/tests/fixture/issues-4xxx/issue-4314/2/input/input.js, crates/swc/tests/fixture/issues-4xxx/issue-4314/2/output/input.js, crates/swc_ecma_parser/src/lexer/state.rs
=> fix(es/parser): Lexer error when object prop is named function

crates/swc_common/src/source_map.rs
Tries to solve https://github.com/swc-project/swc/issues/4379.
- Closes https://github.com/swc-project/swc/issues/4379
=> #4379: Ignore extraneous mapping at 1, 0 => 0, 0

crates/swc/tests/vercel/loader-only/next-36251/1/input/index.ts, crates/swc/tests/vercel/loader-only/next-36251/1/input/index.tsx, crates/swc/tests/vercel/loader-only/next-36251/1/output/index.tsx, crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/tests/fixture.rs, crates/swc_ecma_codegen/tests/fixture/next-36251/input.tsx, crates/swc_ecma_codegen/tests/fixture/next-36251/output.tsx
- https://github.com/vercel/next.js/issues/36151
=> fix(es/codegen): Allow non-ascii character in more places

crates/swc/src/config/issue-4390.json, crates/swc/src/config/tests.rs, crates/swc/src/lib.rs
- https://github.com/swc-project/swc/discussions/4390
=> test(es): Add tests for `.swcrc`

Cargo.lock, crates/swc_ecma_minifier/Cargo.toml, crates/swc_ecma_minifier/README.md, crates/swc_ecma_minifier/examples/minify-all.rs, crates/swc_ecma_minifier/scripts/instrument/all.sh
=> chore(es/minifier): Add a script to instrument real-world inputs

.github/workflows/cargo.yml, Cargo.lock, crates/swc_html_minifier/Cargo.toml, crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/tests/fixture.rs, crates/swc_html_minifier/tests/fixture/attribute/boolean/input.html, crates/swc_html_minifier/tests/fixture/attribute/boolean/output.min.html, crates/swc_html_minifier/tests/fixture/attribute/quote/input.html, crates/swc_html_minifier/tests/fixture/attribute/quote/output.min.html, crates/swc_html_minifier/tests/fixture/comment/input.html, crates/swc_html_minifier/tests/fixture/comment/output.min.html, crates/swc_html_parser/src/parser/mod.rs
Initial minifier with couple rules + fix bugs in parser
No
No
=> feat(html/minifier): initial crate

.github/workflows/cargo.yml
=> chore(ci): Use `yarn` instead of `npm`

crates/swc_ecma_minifier/src/compress/pure/bools.rs, crates/swc_ecma_minifier/tests/TODO.txt, crates/swc_ecma_minifier/tests/golden.txt, crates/swc_ecma_minifier/tests/terser_exec.rs
I'll rebase this once https://github.com/swc-project/swc/pull/4428 is merged
=> fix(es/minifier): Remove wrong logic for optimizing `delete`s

crates/swc_ecma_minifier/tests/terser_exec.rs
=> chore(es/minifier): don't run tests with infinite loops

crates/swc_html_minifier/tests/fixture/attribute/form/input.html, crates/swc_html_minifier/tests/fixture/attribute/form/output.min.html, crates/swc_html_parser/src/parser/open_elements_stack.rs, crates/swc_html_parser/tests/fixture/tag/form/input.html, crates/swc_html_parser/tests/fixture/tag/form/output.json, crates/swc_html_parser/tests/fixture/tag/form/span.rust-debug, crates/swc_html_parser/tests/fixture/tag/svg/output.json, crates/swc_html_parser/tests/fixture/tag/svg/span.rust-debug
We should not pop last element, otherwise we will ahve broken AST
No
No
=> fix(html/parser): parsing bug with nested tags

crates/swc_ecma_minifier/scripts/next/evaluate.js, crates/swc_ecma_minifier/scripts/test.sh, crates/swc_ecma_minifier/scripts/update-list.sh, crates/swc_ecma_minifier/src/debug.rs
=> chore(es/minifier): Update debugging utils

crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/tests/fixture/attribute/javascript-prefix/input.html, crates/swc_html_minifier/tests/fixture/attribute/javascript-prefix/output.min.html
Remove unencessary `javascript:` prefix
No
No
=> feat(html/minifier): remove `javascript:` prefix

crates/swc_ecma_transforms_base/src/helpers/_interop_require_wildcard.js, crates/swc_ecma_transforms_module/tests/common_js.rs, packages/swc-helpers/src/_interop_require_wildcard.js
since we don't have `importInterop: "node"`, I didn't update to the latest version in babel.
fix #4284
=> fix(helper): update _interopRequireWildcard

crates/swc_ecma_minifier/scripts/next/start.sh, crates/swc_ecma_minifier/src/compress/mod.rs, crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/src/compress/optimize/util.rs, crates/swc_ecma_minifier/src/compress/pure/ctx.rs, crates/swc_ecma_minifier/src/compress/pure/mod.rs, crates/swc_ecma_minifier/src/compress/pure/strings.rs, crates/swc_ecma_minifier/src/eval.rs, crates/swc_ecma_minifier/src/lib.rs
This is extracted from https://github.com/swc-project/swc/pull/4475
=> refactor(es/minifier): Cleanup

crates/swc_ecma_transforms_compat/src/bugfixes/async_arrows_in_class.rs, crates/swc_ecma_transforms_compat/src/bugfixes/edge_default_param.rs, crates/swc_ecma_transforms_compat/src/bugfixes/safari_id_destructuring_collision_in_function_expression.rs, crates/swc_ecma_transforms_compat/src/bugfixes/template_literal_caching.rs, crates/swc_ecma_transforms_testing/src/lib.rs
=> fix(es/bugfixes): Fix handling of syntax context

crates/swc_ecma_parser/src/error.rs, crates/swc_ecma_parser/src/parser/class_and_fn.rs, crates/swc_ecma_parser/tests/typescript-errors/class/private-constructor/method/input.ts, crates/swc_ecma_parser/tests/typescript-errors/class/private-constructor/method/input.ts.stderr, crates/swc_ecma_parser/tests/typescript-errors/class/private-constructor/property/input.ts, crates/swc_ecma_parser/tests/typescript-errors/class/private-constructor/property/input.ts.stderr
Reject the code below:
```js
class C {
#constructor() {}
}
```
=> feat(es/parser): Reject private field called `constructor`

crates/swc_ecma_preset_env/data/@babel/compat-data/data/plugins.json, crates/swc_ecma_preset_env/data/core-js-compat/data.json, crates/swc_ecma_preset_env/data/core-js-compat/entries.json, yarn.lock
=> feat(es/preset-env): Update data

crates/swc_css_prefixer/src/prefixer.rs, crates/swc_css_prefixer/tests/fixture/print-color-adjust/input.css, crates/swc_css_prefixer/tests/fixture/print-color-adjust/output.css
=> fix(css/prefixer): prefix for `print-color-adjust`

crates/swc_ecma_transforms_compat/src/es2022/static_blocks.rs, crates/swc_ecma_transforms_compat/tests/static-blocks/basic/export-default/input.js, crates/swc_ecma_transforms_compat/tests/static-blocks/basic/export-default/output.js
=> fix(es/compat): visit export default in `static_block`

crates/swc/tests/tsc-references/superInStaticMembers1_es2015.1.normal.js, crates/swc/tests/tsc-references/superInStaticMembers1_es2015.2.minified.js, crates/swc/tests/tsc-references/superInStaticMembers1_es5.1.normal.js, crates/swc/tests/tsc-references/superInStaticMembers1_es5.2.minified.js, crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs, crates/swc_ecma_transforms_compat/tests/es2022_class_properties.rs
=> fix(es/compat): insert statements position `class_properties`

.github/workflows/bench.yml, .github/workflows/bot-pr.yml, .github/workflows/bot.yml, .github/workflows/cargo-lints.yml, .github/workflows/cargo.yml, .github/workflows/crev.yml, .github/workflows/docs.yml, .github/workflows/integration.yml, .github/workflows/publish-node.yml, .github/workflows/publish-wasm.yml, .github/workflows/wasm.yml, Cargo.lock, package.json, yarn.lock
Fix https://github.com/swc-project/swc/issues/4107
https://github.com/Brooooooklyn/swc/runs/6286599487?check_suite_focus=true passed
=> fix(node): tls allocation issue by updating linux gnu build image

crates/swc_html_parser/src/lexer/mod.rs, crates/swc_html_parser/src/parser/input.rs, crates/swc_html_parser/src/parser/mod.rs, crates/swc_html_parser/tests/recovery/element/svg-1/input.html, crates/swc_html_parser/tests/recovery/element/svg-1/output.json, crates/swc_html_parser/tests/recovery/element/svg-1/output.stderr, crates/swc_html_parser/tests/recovery/element/svg-1/span.rust-debug
=> fix(html/parsing): parsing cdata in foreign context

crates/swc_ecma_minifier/tests/TODO.txt, crates/swc_ecma_minifier/tests/postponed.txt
=> test(es/minifier): Categorize more tests

Cargo.lock, crates/swc_plugin/Cargo.toml
Description:
Attempt to include https://github.com/swc-project/swc/pull/4541 in the published version, somehow version not updated after this change.
BREAKING CHANGE:
Related issue (if exists):
=> build(cargo): update swc_plugin

crates/swc_ecma_transforms_base/src/resolver/mod.rs
- https://discord.com/channels/889779439272075314/889780890098610176/972247365085954128
=> doc(es/resolver): Add docs for top-level mark

crates/swc_ecma_minifier/tests/TODO.txt, crates/swc_ecma_minifier/tests/compress.rs, crates/swc_ecma_minifier/tests/golden.txt, crates/swc_ecma_minifier/tests/postponed.txt, crates/swc_ecma_minifier/tests/terser/compress/async/async_function_declaration/output.js, crates/swc_ecma_minifier/tests/terser/compress/issue_1704/mangle_catch_redef_1_ie8/output.js, crates/swc_ecma_minifier/tests/terser/compress/issue_1704/mangle_catch_redef_2_ie8/output.js, crates/swc_ecma_minifier/tests/terser/compress/issue_1750/case_1/output.js, crates/swc_ecma_minifier/tests/terser/compress/issue_1750/case_2/output.js, crates/swc_ecma_minifier/tests/terser/compress/properties/computed_property/output.js, crates/swc_ecma_minifier/tests/terser/compress/rename/mangle_catch_redef_1_ie8/output.js, crates/swc_ecma_minifier/tests/terser/compress/rename/mangle_catch_redef_2_ie8/output.js, crates/swc_ecma_minifier/tests/terser_exec.rs, crates/swc_ecma_minifier/tests/terser_exec_base.js
=> test(es/minifier): Fix test system

crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/tests/terser/compress/blocks/issue_1672_for/output.js, crates/swc_ecma_minifier/tests/terser_exec.rs
Extracted from https://github.com/swc-project/swc/pull/4583 to make it reviewable
=> fix(es/minifier): Unwrap blocks more carefully

crates/swc_ecma_minifier/src/compress/optimize/switches.rs, crates/swc_ecma_minifier/tests/terser_exec.rs
=> fix(es/minifier): Fix switch with a unknown case

crates/swc_ecma_minifier/tests/terser_exec.rs, crates/swc_ecma_transforms_base/src/fixer.rs
This is part of minifier stabilization.
=> fix(es/fixer): Handle `new yield`

crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_minifier/tests/golden.txt, crates/swc_ecma_minifier/tests/postponed.txt, crates/swc_ecma_minifier/tests/terser_exec.rs, crates/swc_ecma_transforms_optimization/src/simplify/expr/mod.rs
=> fix(es/minifier): Fix optimization of spread

crates/swc_css_parser/src/error.rs
- Closes https://github.com/swc-project/swc/issues/4635
=> fix(css/parser): Remove a wrong assertion

Cargo.lock, crates/swc_html_minifier/Cargo.toml, crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/tests/fixture/element/script/input.html, crates/swc_html_minifier/tests/fixture/element/script/output.min.html
Compress JSON in application/ld-json (microdata)
In future we will built-in ECMA and CSS minifiers too
No
No
=> feat(html/minifier): compress `application/ld+json`

Cargo.lock, Cargo.toml, crates/dbg-swc/Cargo.toml, crates/dbg-swc/src/bundle.rs, crates/dbg-swc/src/main.rs, crates/dbg-swc/src/minify.rs, crates/dbg-swc/src/test.rs, crates/dbg-swc/src/util/mod.rs, crates/swc_ecma_minifier/examples/minify-all.rs
=> feat(debug): Inline `dbg-swc`

crates/swc_common/src/input.rs, crates/swc_ecma_parser/scripts/instrument.sh, crates/swc_ecma_parser/src/lexer/mod.rs
=> perf(es/parser): Optimize for cpu code cache

crates/swc_ecma_codegen/src/config.rs
https://discord.com/channels/889779439272075314/889780890098610176/975340185149669417
=> doc(es/codegen): Document `ascii_only`

crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/tests/fixture/element/script/input.html, crates/swc_html_minifier/tests/fixture/element/script/output.min.html
Compress more JSON content in HTML files
No
No
=> feat(html/minifier): compress more json content

crates/swc_html_codegen/tests/fixture/broken-svg/input.html, crates/swc_html_codegen/tests/fixture/broken-svg/output.html, crates/swc_html_codegen/tests/fixture/broken-svg/output.min.html, crates/swc_html_codegen/tests/fixture/object/input.html, crates/swc_html_codegen/tests/fixture/object/output.html, crates/swc_html_codegen/tests/fixture/object/output.min.html
Check broken cases from https://github.com/kangax/html-minifier/issues/45 to ensure we don't need extra options for minifier, because we already parse and print it in recovery, so you will get valid HTML output
No
No
=> test(html/codegen): broken html/svg

Cargo.lock, crates/swc_html_parser/Cargo.toml, crates/swc_html_parser/benches/compare.rs, crates/swc_html_parser/benches/files/css_2021_spec.html, crates/swc_html_parser/benches/files/github_com_17_05_2022.html, crates/swc_html_parser/benches/files/stackoverflow_com_17_05_2022.html, crates/swc_html_parser/benches/parser.rs, crates/swc_html_parser/src/lexer/mod.rs
Initial benches.
Should I update something in CI?
Also no lexer benches currently - added `TODO` for public API (implement iterator), because it can be useful.
No
No
=> perf(html): Setup benchmarks

crates/swc_ecma_minifier/src/compress/pure/properties.rs
=> fix(es/minifier): Don't create keys with negative number

crates/swc_ecma_transforms_react/src/jsx/mod.rs, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-4703/1/input.js, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-4703/1/options.json, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-4703/1/output.mjs, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-4703/1/output.stderr, crates/swc_ecma_transforms_react/tests/jsx/fixture/pure/true-pragma-comment-automatic-runtime/output.stderr, crates/swc_ecma_transforms_react/tests/jsx/fixture/pure/unset-pragma-comment-automatic-runtime/output.stderr
- Closes https://github.com/swc-project/swc/issues/4703
=> fix(es/react): Fix span of error messages

crates/swc/tests/fixture/issues-1xxx/1721/case1/output/index.js, crates/swc/tests/fixture/issues-1xxx/1918/es2016/output/index.js, crates/swc/tests/fixture/issues-1xxx/1918/es5/output/index.js, crates/swc/tests/tsc-references/emitter.forAwait_es2015.1.normal.js, crates/swc/tests/tsc-references/emitter.forAwait_es5.1.normal.js, crates/swc/tests/tsc-references/generatorAssignability_es2015.1.normal.js, crates/swc/tests/tsc-references/generatorAssignability_es5.1.normal.js, crates/swc/tests/tsc-references/types.forAwait.es2018.1_es2015.1.normal.js, crates/swc/tests/tsc-references/types.forAwait.es2018.1_es5.1.normal.js, crates/swc/tests/tsc-references/types.forAwait.es2018.2_es2015.1.normal.js, crates/swc/tests/tsc-references/types.forAwait.es2018.2_es5.1.normal.js, crates/swc/tests/tsc-references/types.forAwait.es2018.3_es2015.1.normal.js, crates/swc/tests/tsc-references/types.forAwait.es2018.3_es5.1.normal.js, crates/swc_ecma_transforms_compat/src/es2017/async_to_generator.rs, crates/swc_ecma_transforms_compat/tests/es2017_async_to_generator.rs
=> fix: `break` in for await loop

crates/swc/src/lib.rs, crates/swc_common/src/source_map.rs
=> fix(es/codegen): Exclude synthesized files from sourcemap

crates/swc/src/config/mod.rs, crates/swc/tests/fixture/deno/paths/issue-2753/2-cjs/output/src/command/restore.ts, crates/swc/tests/fixture/deno/paths/issue-2753/2-esm/output/src/command/restore.ts, crates/swc/tests/fixture/issues-1xxx/1165/case1/output/index.ts, crates/swc/tests/fixture/issues-1xxx/1279/case1/output/index.ts, node-swc/__tests__/transform/issue_4621_test.mjs, node-swc/__tests__/transform/issue_4734_test.mjs, node-swc/tests/issue-4621/1/.swcrc, node-swc/tests/issue-4734/1/.swcrc, node-swc/tests/issue-4734/1/index.ts
- Closes https://github.com/swc-project/swc/issues/4734
=> fix(es/config): Respect `.swcrc`

crates/swc_ecma_transforms_compat/src/es2015/block_scoping/mod.rs, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-4238/1/input.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-4238/1/output.js
=> fix(es/compat): nested for loop with break

crates/swc_ecma_transforms_compat/src/es2015/block_scoping/mod.rs, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-4238/2/input.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-4238/2/output.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-4238/3/input.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-4238/3/output.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-4238/4/input.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-4238/4/output.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-4238/5/input.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-4238/5/output.js
closes #4238, this time really
=> fix(es/compat): nested for loop with break/continue

.github/workflows/publish-node.yml, crates/swc_node_base/Cargo.toml, crates/swc_node_base/src/lib.rs
=> Fix jemalloc

crates/swc/tests/exec/issues-4xxx/4839/1/exec.js, crates/swc_ecma_minifier/src/pass/mangle_names/real_impl.rs, crates/swc_ecma_minifier/tests/fixture/issues/issue-2604/1/output.mangleOnly.js, crates/swc_ecma_minifier/tests/fixture/next/feedback-util-promisify/chunks/pages/_app-72ad41192608e93a/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/drop_unused/issue_3146_1/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/drop_unused/issue_3146_2/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/issue_1105/check_drop_unused_in_peer_function/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/issue_1105/compress_with_with_in_other_scope/output.mangleOnly.js, crates/swc_ecma_transforms_base/tests/resolver/minifier/17/input.js, crates/swc_ecma_transforms_base/tests/resolver/minifier/17/output.js
- Closes https://github.com/swc-project/swc/issues/4839
=> fix(es/minifier): Apply name mangler for more cases

packages/swc-helpers/package.json
- Closes https://github.com/swc-project/swc/issues/4854
=> fix(es/helpers): Update `@swc/core` of `@swc/helpers`

Cargo.lock, crates/swc_html_parser/Cargo.toml
=> chore(html/parser): remove unused deps

crates/swc_html_codegen/src/ctx.rs, crates/swc_html_codegen/src/lib.rs, crates/swc_html_codegen/tests/fixture/attribute/output.html, crates/swc_html_codegen/tests/fixture/element/textarea/output.html, crates/swc_html_codegen/tests/fixture/pre-tag/input.html, crates/swc_html_codegen/tests/fixture/pre-tag/output.html, crates/swc_html_codegen/tests/fixture/pre-tag/output.min.html, crates/swc_html_parser/tests/fixture/element/pre-3/dom.rust-debug, crates/swc_html_parser/tests/fixture/element/pre-3/input.html, crates/swc_html_parser/tests/fixture/element/pre-3/output.json, crates/swc_html_parser/tests/fixture/element/pre-3/span.rust-debug
Bug fix for newline in pre and textarea
No
No
=> fix(html/codegen): newline in textarea/pre

crates/swc/tests/errors/lints/default-case-last/default/.swcrc, crates/swc/tests/errors/lints/default-case-last/default/input.js, crates/swc/tests/errors/lints/default-case-last/default/output.swc-stderr, crates/swc_ecma_lints/src/config.rs, crates/swc_ecma_lints/src/rules/default_case_last.rs, crates/swc_ecma_lints/src/rules/mod.rs
default-case-last rule implementation
No
=> feat(es/lint): add default-case-last rule implementation

crates/swc_html_parser/benches/compare.rs, crates/swc_html_parser/benches/lexer.rs, crates/swc_html_parser/benches/parser.rs
For future research for improvements
No
No
=> perf(html/parser): bench document fragment

crates/swc_ecma_transforms_base/src/fixer.rs
=> fix(es/base): preserve paren in opt call

crates/swc_ecma_parser/src/parser/typescript.rs, crates/swc_ecma_parser/tests/typescript/issue-4937/index.ts, crates/swc_ecma_parser/tests/typescript/issue-4937/index.ts.json
=> fix(es/parser): negative bigint literal in type

Cargo.lock, crates/swc_atoms/Cargo.toml, crates/swc_atoms/src/lib.rs
See https://github.com/swc-project/swc/issues/4946 for the context.
=> perf(common): Add `Atom` type

crates/swc/tests/tsc-references/ExportVariableOfGenericTypeWithInaccessibleTypeAsTypeArgument_es2015.2.minified.js, crates/swc/tests/tsc-references/ExportVariableOfGenericTypeWithInaccessibleTypeAsTypeArgument_es5.2.minified.js, crates/swc/tests/tsc-references/arrayLiterals2ES5_es5.1.normal.js, crates/swc/tests/tsc-references/arrayLiterals2ES5_es5.2.minified.js, crates/swc/tests/tsc-references/arrayLiterals2ES6_es5.1.normal.js, crates/swc/tests/tsc-references/arrayLiterals2ES6_es5.2.minified.js, crates/swc/tests/tsc-references/genericCallWithConstraintsTypeArgumentInference2_es2015.2.minified.js, crates/swc/tests/tsc-references/genericCallWithConstraintsTypeArgumentInference2_es5.2.minified.js, crates/swc/tests/tsc-references/genericCallWithGenericSignatureArguments3_es2015.2.minified.js, crates/swc/tests/tsc-references/genericCallWithGenericSignatureArguments3_es5.2.minified.js, crates/swc/tests/tsc-references/parser15.4.4.14-9-2_es2015.2.minified.js, crates/swc/tests/tsc-references/parser15.4.4.14-9-2_es5.2.minified.js, crates/swc/tests/tsc-references/subtypingWithOptionalProperties_es2015.2.minified.js, crates/swc/tests/tsc-references/subtypingWithOptionalProperties_es5.2.minified.js, crates/swc_ecma_ast/src/list.rs, crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/src/compress/pure/misc.rs, crates/swc_ecma_minifier/src/compress/pure/mod.rs, crates/swc_ecma_minifier/tests/fixture/issues/2257/full/output.js, crates/swc_ecma_minifier/tests/fixture/issues/quagga2/1.4.2/1/output.js, crates/swc_ecma_minifier/tests/fixture/next/react-pdf-renderer/output.js, crates/swc_ecma_minifier/tests/terser/compress/array_constructor/array_constructor/output.js, crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/issue_1605_1/output.js, crates/swc_ecma_minifier/tests/terser/compress/destructuring/unused_destructuring_decl_2/output.js, crates/swc_ecma_minifier/tests/terser/compress/destructuring/unused_destructuring_decl_3/output.js, crates/swc_ecma_minifier/tests/terser/compress/destructuring/unused_destructuring_decl_4/output.js, crates/swc_ecma_minifier/tests/terser/compress/destructuring/unused_destructuring_decl_5/output.js
=> fix(es/minifier): turn `Array` `Object` call into literal

crates/swc_html_parser/src/parser/input.rs
We don't peek somthing in html, so we don't need extra chech
No
No
=> refactor(html/parser): remove unused code

crates/swc_ecma_transforms_base/src/hygiene/mod.rs, crates/swc_ecma_transforms_base/src/hygiene/ops.rs, crates/swc_ecma_transforms_base/src/hygiene/unique_scope.rs
=> perf(es/transforms): Make rename operator parallel

README.md
=> docs(*): Add more badges

crates/swc/benches/bugs.rs, crates/swc/benches/typescript.rs, crates/swc/src/config/mod.rs, crates/swc/tests/error_msg.rs, crates/swc/tests/projects.rs, crates/swc/tests/rust_api.rs, crates/swc/tests/simple.rs, crates/swc/tests/source_map.rs, crates/swc/tests/tsc.rs, crates/swc_node_bundler/src/loaders/swc.rs
- Closes https://github.com/swc-project/swc/issues/4989
=> feat(es/config): Add `isModule` to `.swcrc`

crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_parser/tests/errors/issue-4991/1/input.js, crates/swc_ecma_parser/tests/errors/issue-4991/1/input.js.stderr, crates/swc_ecma_parser/tests/errors/issue-4991/2/input.js, crates/swc_ecma_parser/tests/errors/issue-4991/2/input.js.stderr, crates/swc_ecma_parser/tests/errors/issue-4991/3/input.js, crates/swc_ecma_parser/tests/errors/issue-4991/3/input.js.stderr, crates/swc_ecma_parser/tests/errors/issue-4991/4/input.js, crates/swc_ecma_parser/tests/errors/issue-4991/4/input.js.stderr
=> fix(es/parser): Invalid Meta Property

README.md
**Description:** Add link for discord badge in README :)
=> docs(readme): Add link for discord badge in README

crates/swc_ecma_transforms_base/src/rename/mod.rs
We need `Send` and `Sync` which should be enabled when `swc_common/concurrent` is not enabled
- Closes #5015
=> fix(es/transforms): Add custom `Sync` + `Send` for the renamer

crates/swc_ecma_parser/tests/typescript/instantiation-expr/bin-op/input.ts, crates/swc_ecma_parser/tests/typescript/instantiation-expr/bin-op/input.ts.json
Added a test case about instantiation expression.
- https://github.com/microsoft/TypeScript/issues/49551
=> test(es/parser): Add a test case for instantiation expr

crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/src/option.rs, crates/swc_html_minifier/tests/fixture/comment/disable-remove-comment/config.json, crates/swc_html_minifier/tests/fixture/comment/disable-remove-comment/input.html, crates/swc_html_minifier/tests/fixture/comment/disable-remove-comment/output.min.html
Allow to disable comment removing
Yes
No
=> feat(html/minifier): add `remove_comments` option

crates/swc_ecma_parser/src/parser/stmt.rs, crates/swc_ecma_parser/src/parser/tests.rs, crates/swc_ecma_parser/tests/test262.rs
=> fix(es/parser): allow for-in loop init with non-strict mode

crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/src/option.rs, crates/swc_html_minifier/tests/fixture/attribute/disabled-normalize_attributes/config.json, crates/swc_html_minifier/tests/fixture/attribute/disabled-normalize_attributes/input.html, crates/swc_html_minifier/tests/fixture/attribute/disabled-normalize_attributes/output.min.html
Allow to keep values as is
Yes
No
=> feat(html/minifier): add `normalize_attributes` to disable normalization

crates/swc/tests/errors/lints/const-assign/2/input.js, crates/swc/tests/errors/lints/const-assign/2/output.swc-stderr, crates/swc_ecma_lints/src/rules/const_assign.rs
=> feat(es/lint): report reassign import binding error at lint pass

node-swc/src/types.ts
=> fix(node-swc): add nodenext config type

crates/swc/tests/fixture/deno/paths/issue-2724/output/src/index.ts, crates/swc/tests/fixture/issues-1xxx/1614/case1/output/index.ts, crates/swc_ecma_transforms_module/src/common_js.rs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-1018/1/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-1480/1/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-1614/1/output.cjs, node-swc/__tests__/transform/issue_4730_test.mjs
It is bundler friendly if the require path is literal.
=> feat(es/module): Optimize for dynamic import with literal path

crates/swc_ecma_minifier/src/compress/pure/misc.rs
- Closes https://github.com/swc-project/swc/issues/4893
=> feat(es/minifier): Handle pure annotations on member expressions

crates/swc_ecma_transforms_module/src/module_ref_rewriter.rs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-332/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-332/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-332/output.umd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5054/1/input.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5054/1/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5054/1/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5054/1/output.umd.js
=> fix(es/module): handle module ref in binding ident

crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/src/option.rs, crates/swc_html_minifier/tests/fixture/attribute/custom-attribute/config.json, crates/swc_html_minifier/tests/fixture/element/custom-script-type/config.json, crates/swc_html_minifier/tests/fixture/element/custom-script-type/input.html, crates/swc_html_minifier/tests/fixture/element/custom-script-type/output.min.html
Let's merge after https://github.com/swc-project/swc/pull/5036/
Yes
No
=> feat(html/minifier): allow to minify custom script content

Cargo.lock, crates/swc_atoms/Cargo.toml, crates/swc_common/Cargo.toml, crates/swc_ecma_ast/Cargo.toml, crates/swc_plugin_proxy/Cargo.toml, tests/rust-plugins/swc_internal_plugin/Cargo.lock
Bump up rkyv to latest to include few small fixes.
=> build(cargo): bump rkyv

crates/swc_ecma_transforms_compat/src/es2015/block_scoping/mod.rs, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-5048/1/input.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-5048/1/output.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-5048/2/input.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-5048/2/output.js
One could see that [babel](https://github.com/babel/babel/blob/main/packages/babel-plugin-transform-block-scoping/src/index.ts#L768) uses `unwrapFunctionEnvironment` here too.
closes #5048
=> fix(es/compat): this in function with block scoped vars

crates/ast_node/src/lib.rs, crates/swc_atoms/Cargo.toml, crates/swc_atoms/src/lib.rs, crates/swc_common/src/plugin.rs, crates/swc_ecma_ast/Cargo.toml, crates/swc_ecma_ast/src/expr.rs, crates/swc_ecma_ast/src/ident.rs, crates/swc_plugin_proxy/src/memory_interop/read_returned_result_from_host.rs
=> perf(atoms): More groundwork for replacing `JsWord` with `Atom`

CONTRIBUTING.md
The existing instructions fail to build swc with this error:
```
error: Plugin_runner should enable either filesystem, or memory cache
```
Fixes https://github.com/swc-project/swc/issues/4838
=> docs: Add '--features memory_cache' to test steps

crates/swc_ecma_parser/src/error.rs, crates/swc_ecma_parser/src/parser/stmt.rs, crates/swc_ecma_parser/tests/errors/label/input.js, crates/swc_ecma_parser/tests/errors/label/input.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/320eade064b2c635.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/944ea2478d838026.js.stderr
=> fix(es/parser): labelled function

crates/swc_ecma_transforms_react/src/jsx/mod.rs, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-5099/1/input.js, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-5099/1/output.mjs, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-5099/2/input.js, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-5099/2/output.mjs, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-5099/2/output.stderr, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-5099/empty-pragma/input.js, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-5099/empty-pragma/output.mjs
=> fix(es/react): error report of react pragma

node-swc/src/types.ts
`OptimizerConfig` lost `simplify` type define, docs link is https://swc.rs/docs/configuration/compilation#jsctransformoptimizersimplify
=> fix: lose simplify type

crates/swc_ecma_lints/src/rules/duplicate_bindings.rs, crates/swc_ecma_lints/tests/pass/issue-5115/1/input.ts
=> fix(es/lints): allow overload in ts

crates/swc_ecma_parser/src/parser/stmt/module_item.rs, crates/swc_ecma_parser/tests/typescript/import/export-import-type-require/input.ts, crates/swc_ecma_parser/tests/typescript/import/export-import-type-require/input.ts.json
=> fix(es/parser): parse type-only export-import declaration

crates/swc/tests/errors/lints/duplicate-bindings/import-require/input.ts, crates/swc/tests/errors/lints/duplicate-bindings/import-require/output.swc-stderr, crates/swc_ecma_lints/src/rules/duplicate_bindings.rs
=> fix(es/lint): Handle import-require duplicate bindings

crates/swc_visit_macros/src/lib.rs
=> feat(visit): Implement `Eq` for `AstKind`

crates/swc_visit_macros/src/lib.rs
=> feat(visit): Implement more traits for `AstKind`

crates/swc_visit/src/lib.rs, crates/swc_visit_macros/src/lib.rs
=> doc(visit): Add docs for visitors

crates/swc_cli/src/commands/compile.rs
- closes #5124
Minor fix, `config-file` should create `ConfigFile` enum instead of reading file by itself.
=> fix(swc/cli): correctly constructs config-file

crates/swc_ecma_transforms_module/src/module_ref_rewriter.rs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5157/2/input.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5157/2/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5157/2/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5157/2/output.umd.js
Note:
I can't construct `PrivateName` test case that contains `this`. But technically it is indeed top level.
- fix https://github.com/swc-project/swc/pull/5159#issuecomment-1179478734
=> fix(es/module): Handle top level this really

crates/swc/tests/fixture/interop/babel/output/index.js, crates/swc/tests/fixture/interop/node/output/index.js, crates/swc/tests/fixture/interop/none/output/index.js, crates/swc/tests/fixture/interop/swc/output/index.js, crates/swc_ecma_transforms_module/src/module_decl_strip.rs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-1568/2/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-1568/2/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-1568/2/output.umd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-3439/2/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-3439/2/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-3439/2/output.umd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-3439/4/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-3439/4/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-3439/4/output.umd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-3439/5/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-3439/5/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-3439/5/output.umd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-369/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-369/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-369/output.umd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-4456/1/output.amd.ts, crates/swc_ecma_transforms_module/tests/fixture/common/issue-4456/1/output.cts, crates/swc_ecma_transforms_module/tests/fixture/common/issue-4456/1/output.umd.ts, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5063/2/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5063/2/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5063/2/output.umd.js, crates/swc_ecma_transforms_module/tests/fixture/common/pull-4688/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/pull-4688/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/pull-4688/output.umd.js
=> fix(es/module): add missing span for `export default`

.github/workflows/bench.yml
=> chore(ci): Fix benchmark action

crates/swc_css_parser/src/parser/base.rs
Remove wrong skipping whitespaces + more comments from spec
No
No
=> fix(css/parser): avoid skip whitespaces where unnecessary

Cargo.lock, crates/swc_css_visit/Cargo.toml, crates/swc_ecma_visit/Cargo.toml, crates/swc_html_visit/Cargo.toml, crates/swc_visit_macros/src/lib.rs
=> feat(visit): Implement serde for `AstParentKind`

node-swc/e2e/fixtures/plugin_transform_schema_v1/Cargo.lock, node-swc/e2e/fixtures/plugin_transform_schema_vtest/Cargo.lock, node-swc/e2e/plugins/plugins.schema.test.js
This was root cause i686 CI was hanging indefinitely. We do not run test anymore, but still this need to be fixed for some CI / local dev env.
=> test(swc): fix e2e tests on windows

crates/swc_visit_macros/Cargo.toml
This [PR](https://github.com/swc-project/swc/pull/5185/files#diff-fa0e7ccb2db6cb82c4a30a5b8c8e9046a92d6e44d3864f60536d7f12c4d1ddd4R8) introduced changes to the `swc_visit_macros` crate that imported a newly added function [`make_doc_attr`](https://github.com/swc-project/swc/pull/5185/files#diff-7500d7fc214c3bae709a8ebed44b88e67d45218b48a1cd7b93a850c5ede7fecdR83) to `swc_macros_common`. That change was published to  `swc_macros_common@0.3.6`, but `swc_visit_macros` depends on `0.3.4`
Update the dependency
=> chore(swc_visit_macros): Update swc_macros_common dependency

crates/testing_macros/src/fixture.rs
=> fix(testing): Allow space in file names

crates/swc_visit_macros/src/lib.rs
=> typo: VisitWith

crates/swc_ecma_transforms_base/src/hygiene/mod.rs
transform rename should be consists of three phases.
no
no
=> docs(transform/hygiene): hygiene consists of [four -> three] phases.

.github/workflows/publish-node.yml
=> chore(ci): Fix publish script

crates/testing_macros/Cargo.toml, crates/testing_macros/src/fixture.rs
This PR applies a regex that converts non-alphanumeric characters into underscores to test_name.
It resolves the error that occurs when the path of the fixture file contains special characters the existing source did not process individually.
**BREAKING CHANGE: X**
=> feat(testing): Generalize test_name with regex

crates/swc_ecma_transforms_optimization/Cargo.toml
=> chore: Fix CI

node-swc/src/index.ts
Similar to https://github.com/vercel/next.js/pull/38780, coerce async interface of bindings to sync for the fallback binding (wasm) to make most of code works seamlessly. There are some non existent interfaces (like bundle) we can't support still.
=> feat(swc): coerce fallback bindings async interface to sync

crates/swc_common/src/syntax_pos.rs, crates/swc_ecma_transforms_module/src/module_decl_strip.rs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5260/input.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5260/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5260/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5260/output.umd.js
=> fix(es/module): Private context for `export from`

crates/ast_node/src/lib.rs
Remove unnecessary comments.
Nope.
#5303
=> docs(crates/ast_node): remove unnecessary comments

crates/swc/tests/fixture/issues-5xxx/5313/1/input/.swcrc, crates/swc/tests/fixture/issues-5xxx/5313/1/input/index.js, crates/swc/tests/fixture/issues-5xxx/5313/1/output/index.js, crates/swc/tests/fixture/issues-5xxx/5313/2/input/.swcrc, crates/swc/tests/fixture/issues-5xxx/5313/2/input/index.js, crates/swc/tests/fixture/issues-5xxx/5313/2/output/index.js, crates/swc/tests/tsc-references/awaitCallExpression4_es2017_es2015.1.normal.js, crates/swc/tests/tsc-references/awaitCallExpression4_es5_es2015.1.normal.js, crates/swc/tests/tsc-references/awaitCallExpression4_es6_es2015.1.normal.js, crates/swc_ecma_transforms_base/src/fixer.rs
=> fix(es/base): Wrap await and yield callee

crates/swc_ecma_preset_env/src/corejs3/usage.rs, crates/swc_ecma_preset_env/tests/fixtures/corejs3/usage-static-methods/output.mjs
=> fix(es/preset-env): don't add instance properties when there's static properties

.github/workflows/publish-node.yml
Ref: https://github.com/actions/virtual-environments/issues/5879
=> ci: fix build for Android platforms

crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/tests/fixture/issues/5328/input.ts, crates/swc_ecma_codegen/tests/fixture/issues/5328/output.ts, crates/swc_ecma_transforms_base/tests/ts-resolver/ts_resolver_import_and_extends/output.ts
=> fix(es/codegen): Emit class super type params

crates/swc_css_prefixer/data/prefixes_and_browsers.json, crates/swc_css_prefixer/src/prefixer.rs, crates/swc_css_prefixer/tests/fixture/background-img-opts/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/background-size/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/calc/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/filter/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/flex/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/forced-color-adjust/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/image-rendering/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/multicolumn/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/nested/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/placeholder-shown/input.css, crates/swc_css_prefixer/tests/fixture/placeholder-shown/output.css, crates/swc_css_prefixer/tests/fixture/placeholder-shown/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/prefixed/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/recovery/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/style-block/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/text-decoration/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/text-orientation/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/text-size-adjust/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/transition/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/user-select/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/writing-mode/output.defaults-not-ie-11.css
All prefixed properties, it remains to collect the values I will do it in another pr
No
No
=> fix(css/prefixer): more properties

node-swc/src/index.ts
We can use async intefaces for the fallback bindings now.
=> refactor(swc): use async interfaces for fallback bindings

crates/swc/src/lib.rs, node-swc/__tests__/minify_test.mjs, node-swc/e2e/fixtures/plugin_transform_schema_vtest/Cargo.lock
- https://github.com/vercel/next.js/discussions/30237?sort=new#discussioncomment-3303141
=> fix(es/minifier): Drop more comments

crates/swc/tests/tsc-references/exportAssignmentOfExportNamespaceWithDefault_es2015.1.normal.js, crates/swc/tests/tsc-references/exportAssignmentOfExportNamespaceWithDefault_es2015.2.minified.js, crates/swc/tests/tsc-references/exportAssignmentOfExportNamespaceWithDefault_es5.1.normal.js, crates/swc/tests/tsc-references/exportAssignmentOfExportNamespaceWithDefault_es5.2.minified.js, crates/swc/tests/tsc-references/tsxPreserveEmit1_es2015.1.normal.js, crates/swc/tests/tsc-references/tsxPreserveEmit1_es2015.2.minified.js, crates/swc/tests/tsc-references/tsxPreserveEmit1_es5.1.normal.js, crates/swc/tests/tsc-references/tsxPreserveEmit1_es5.2.minified.js, crates/swc_ecma_lints/src/rules/duplicate_exports.rs
=> fix(es/lint): Ignore TS module declare block

.github/workflows/docs.yml, crates/swc_core/Cargo.toml
=> doc(rustdoc): FIx CI

.taplo.toml, crates/ast_node/Cargo.toml
This is pure cosmetic changes, enable few options for the formatter (taplo) for toml formatting. Mostly I wanted to enable align entries, so I can easily compare each entry's values. See formatted Cargo.toml in PR as an example.
=> build(cargo): update toml formatting

Cargo.lock, crates/binding_core_wasm/Cargo.toml, crates/binding_core_wasm/src/lib.rs, crates/swc_cli/Cargo.toml, crates/swc_cli/src/commands/bundle.rs, crates/swc_cli/src/commands/compile.rs, crates/swc_cli/src/commands/lint.rs, crates/swc_cli/src/commands/minify.rs, crates/swc_core/Cargo.toml, crates/swc_core/build.rs, crates/swc_core/src/lib.rs, crates/swc_plugin/Cargo.toml, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/Cargo.lock, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/src/lib.rs, node-swc/e2e/fixtures/plugin_transform_schema_vtest/Cargo.lock, node-swc/e2e/fixtures/plugin_transform_schema_vtest/src/lib.rs
PR improves feature surface bit more, then wasm / cli actually started to import this. (Not completed)
Since I'm not intend to create huge dent to existing package structure immediately, this change are conservative & progressive - i.e proc macro with its deps, etcs -.  Hope to move forward to reach point all bindings refer swc_core only, then do internal refactor for the dependency tree more heavily.
=> feat(swc/core): expand features, update ref to wasm / cli

crates/swc_ecma_minifier/scripts/instrument/all.sh, crates/swc_ecma_minifier/scripts/instrument/bench.sh, crates/swc_ecma_minifier/scripts/instrument/file.sh, crates/swc_ecma_minifier/src/pass/postcompress.rs
=> perf(es/minifier): Make postcompress pass parallel

crates/swc_core/src/quote.rs, crates/swc_ecma_quote_macros/src/ast/enums.rs
Minor fix to quote macro to update reference accordingly to avoid compilation error.
=> fix(swc/core): update references for quote

crates/swc_core/Cargo.toml, crates/swc_ecma_quote_macros/Cargo.toml
Looks like bump script didn't work correctly for this PR? swc_ecma_quote_macros missing new versions for the fix.
=> fix(swc/core): fix quote_macros dep

crates/dbg-swc/src/minify/ensure_size.rs
=> feat(dbg-swc): Improve minifier comparator

crates/ast_node/src/lib.rs, crates/swc_atoms/src/lib.rs, crates/swc_common/src/comments.rs, crates/swc_common/src/errors/diagnostic.rs, crates/swc_common/src/errors/mod.rs, crates/swc_common/src/errors/snippet.rs, crates/swc_common/src/plugin/serialized.rs, crates/swc_common/src/syntax_pos.rs, crates/swc_common/src/syntax_pos/hygiene.rs, crates/swc_common/tests/attr_interop.rs, crates/swc_ecma_ast/src/class.rs, crates/swc_ecma_ast/src/decl.rs, crates/swc_ecma_ast/src/expr.rs, crates/swc_ecma_ast/src/ident.rs, crates/swc_ecma_ast/src/operators.rs, crates/swc_ecma_ast/src/typescript.rs, crates/swc_plugin_proxy/src/memory_interop/read_returned_result_from_host.rs
Reverts https://github.com/swc-project/swc/pull/5062 partially to amend https://github.com/swc-project/swc/issues/5406 as a workaround.
**This is not a correct fix**, since issue itself is quite tricky it requires time to investigate & create some reliable repro steps - meanwhile this PR unblocks existing users. This means potential delay to AST schema version support.
=> fix(swc): temporarily disable bytecheck

crates/swc/tests/fixture/issues-5xxx/5417/input/.swcrc, crates/swc/tests/fixture/issues-5xxx/5417/input/index.js, crates/swc/tests/fixture/issues-5xxx/5417/output/index.js, crates/swc_ecma_transforms_base/src/fixer.rs
=> fix(es/fixer): remove useless parentheses around `**`

crates/swc_ecma_ast/src/operators.rs, crates/swc_ecma_transforms_base/src/fixer.rs, crates/swc_ecma_transforms_optimization/src/simplify/branch/mod.rs
=> fix(es/base): extra parens for `??`

crates/swc_common/src/plugin/serialized.rs, crates/swc_ecma_ast/src/expr.rs, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/Cargo.lock
There are few places have bytecheck remaining, trying to disable it.
=> fix(swc/plugin): disable remaining bytecheck

Cargo.lock, crates/swc_plugin_proxy/Cargo.toml, crates/swc_plugin_proxy/src/comments/plugin_comments_proxy.rs, crates/swc_plugin_proxy/src/memory_interop/read_returned_result_from_host.rs, crates/swc_plugin_proxy/src/metadata/transform_plugin_metadata.rs, crates/swc_plugin_proxy/src/source_map/plugin_source_map_proxy.rs, crates/swc_plugin_runner/src/cache.rs, crates/swc_plugin_runner/src/imported_fn/comments.rs, crates/swc_plugin_runner/src/imported_fn/handler.rs, crates/swc_plugin_runner/src/imported_fn/hygiene.rs, crates/swc_plugin_runner/src/imported_fn/metadata_context.rs, crates/swc_plugin_runner/src/imported_fn/set_transform_result.rs, crates/swc_plugin_runner/src/imported_fn/source_map.rs, crates/swc_plugin_runner/src/memory_interop.rs, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/Cargo.lock
Add few more traces for the plugin's proxy runs on host side. We still can't instrument inside of plugin though.
=> feat(swc/plugin): add few plugin hosts traces

.github/workflows/docs.yml, crates/swc_core/Cargo.toml
=> doc(swc_core): Fix rustdoc
