swc-project/swc

ecmascript/transforms/src/hygiene.rs
The assertion became wrong after recent hygiene performance patch.
Closes #1038.
=> Remove wrong assertion in hygiene

ecmascript/transforms/Cargo.toml, ecmascript/transforms/src/resolver.rs
Currently constructor parameters have syntax context before `visit_mut_param` is called.
--- 
Related to https://github.com/denoland/deno_lint/pull/304 and https://github.com/denoland/deno_lint/pull/307
=> resolver: Fix handling of constructor parameters

Cargo.toml, ecmascript/ext-transforms/Cargo.toml, ecmascript/ext-transforms/src/jest.rs, ecmascript/ext-transforms/src/lib.rs, ecmascript/ext-transforms/src/util.rs, node-swc/__tests__/transform/hidden_jest.js, spack/src/loaders/swc.rs, src/config.rs
cc @Brooooooklyn 
Because definitions of ast nodes change over time, I think this is the easiest way for end-users.
(TypeScript introduces new feature, ecmascript spec evolves)
---
Closes #1048.
=> Extension for jest

bundler/Cargo.toml, bundler/tests/fixture/issue-1156-1/input/entry.ts, bundler/tests/fixture/issue-1156-1/input/q.ts, bundler/tests/fixture/issue-1156-1/output/entry.ts, bundler/tests/fixture/issue-1156-2/input/entry.ts, bundler/tests/fixture/issue-1156-2/input/q.ts, bundler/tests/fixture/issue-1156-2/output/entry.ts, ecmascript/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/src/optimization/simplify/dce/mod.rs, ecmascript/transforms/src/optimization/simplify/dce/side_effect.rs, ecmascript/transforms/src/resolver.rs, ecmascript/transforms/src/resolver/tests.rs, ecmascript/transforms/tests/optimization_simplify.rs, ecmascript/transforms/tests/optimization_simplify_dce.rs, ecmascript/transforms/tests/optimization_simplify_inlining.rs
swc_bundler:
- Fix dce bug. (Closes #1156)
swc_ecma_transforms:
- resolver: Ignore non-computed class properties.
- dce: Handle usages in class property initializers.
---
```js
function d#4() {
let methods#5;
const promise#5 = new Promise#4((resolve#6, reject#6)=>{
methods#5 = {
resolve#6,
reject#6
};
});
return Object#4.assign#0(promise#5, methods#5);
}
class A#3 {
s#3 = d#4();
a#0() {
this.s#0.resolve#0();
}
b#0() {
this.s#0 = d#4();
}
}
new A#3();
```
=> bundler: Fix dead code elimination

ecmascript/Cargo.toml, ecmascript/ast/src/typescript.rs, ecmascript/parser/Cargo.toml, ecmascript/parser/src/parser/typescript.rs, ecmascript/parser/tests/typescript/es2019/from-entries/input.ts.json, ecmascript/parser/tests/typescript/types/mapped/input.ts, ecmascript/parser/tests/typescript/types/mapped/input.ts.json, ecmascript/visit/src/lib.rs
Syntax:
```ts
let map: { [P in string as string]: number };
```
=> [typescript] 4.1 mapped type 'as' clause

bundler/Cargo.toml, bundler/src/bundler/chunk/computed_key.rs, bundler/src/bundler/chunk/export.rs, bundler/src/bundler/chunk/merge.rs, bundler/src/bundler/chunk/mod.rs, bundler/src/bundler/chunk/plan/mod.rs, bundler/src/bundler/chunk/plan/tests.rs, bundler/src/bundler/chunk/remark.rs, bundler/src/bundler/export.rs, bundler/src/bundler/import/mod.rs, bundler/src/bundler/import/tests.rs, bundler/src/bundler/load.rs, bundler/src/bundler/mod.rs, bundler/src/bundler/scope.rs, bundler/src/bundler/tests.rs, bundler/src/debug/mod.rs, bundler/src/util.rs, bundler/tests/deno.rs, bundler/tests/fixture/issue-1155-1-fn/output/entry.ts, bundler/tests/fixture/issue-1155-2-var/output/entry.ts, bundler/tests/fixture/issue-1155-3-class/output/entry.ts, spack/Cargo.toml, spack/tests/pass/deno-001/simple-4/output/entry.js, spack/tests/pass/pr-1105/example-5/output/entry.js
swc_bundler:
- Handle computed accesses to imports correctly.
- Make planning deterministic.
- Prefer exports over imports while planning.
- Fix https://deno.land/x/oak@v6.3.1/examples/server.ts
=> bundler: Handle computed accesses correctly

ecmascript/parser/src/lexer/mod.rs
`c` can never be a question mark at this point since the match arm doesn't include it.
=> Remove unnecessary question mark

bundler/Cargo.toml, ecmascript/Cargo.toml, ecmascript/codegen/Cargo.toml, ecmascript/dep-graph/Cargo.toml, ecmascript/jsdoc/Cargo.toml, ecmascript/parser/Cargo.toml, ecmascript/parser/src/lexer/mod.rs, ecmascript/parser/src/lexer/state.rs, ecmascript/parser/src/lexer/tests.rs, ecmascript/parser/src/parser/expr.rs, ecmascript/parser/src/token.rs, ecmascript/transforms/Cargo.toml, visit/src/lib.rs
Fixes #78.
When there's an error reading escaped characters, we return `None` for the cooked value and continue reading.
I think I'm on the right track here, but this is my first pull of any size so please let me know if I should do things differently. I'm happy to change it up.
=> Invalid template escape in ES2018+

ecmascript/codegen/src/decl.rs, ecmascript/codegen/src/expr.rs, ecmascript/codegen/src/lib.rs, ecmascript/codegen/src/util.rs
I started with a TODO and found a few minify improvements.
* Remove parens from arrow functions when possible
* Remove space after prop keys when minifying
* Remove line break after expressions when minifying
* Remove space after generator `*` when minifying
Plenty more to do, but this is a good start!
=> Single argument arrow functions

src/lib.rs
This bug results in an out-of-bound error when using `inputSourceMap: true`.
=> fix(source map): fix inline source map comment slicing

.github/workflows/publish-wasm-web.yml
As described by #1291, right now `@swc/wasm-web` cannot be used after installation because `@swc/wasm-web` does not include files that wasm-bindgen produces when it gets published.
This happens due to a bug in wasm-pack (https://github.com/rustwasm/wasm-pack/issues/837).
Therefore, the simplest solution would just be including the `files` manually in `package.json` before publishing.
Initially I thought the only file that needs to be included would be `wasm_bg.js`, but `wasm_bg.wasm.d.ts` comes along with the build output too, so there's no reason not to include it as a part of API.
This would allow #50 to get going too.
Would close #1291 if it gets merged
cc @kdy1
=> fix(ci): insert *_bg files in @swc/wasm-web (#1291)

common/Cargo.toml, common/src/eq.rs, common/src/lib.rs, ecmascript/ast/Cargo.toml, ecmascript/ast/src/class.rs, ecmascript/ast/src/decl.rs, ecmascript/ast/src/expr.rs, ecmascript/ast/src/function.rs, ecmascript/ast/src/ident.rs, ecmascript/ast/src/jsx.rs, ecmascript/ast/src/lib.rs, ecmascript/ast/src/lit.rs, ecmascript/ast/src/module.rs, ecmascript/ast/src/module_decl.rs, ecmascript/ast/src/operators.rs, ecmascript/ast/src/pat.rs, ecmascript/ast/src/prop.rs, ecmascript/ast/src/stmt.rs, ecmascript/ast/src/typescript.rs, macros/eq_ignore/Cargo.toml, macros/eq_ignore/src/lib.rs
---
Note: TypeEq is not used by swc itself.
=> feat(ecmascript/ast): Add EqIgnoreSpan and TypeEq

bundler/Cargo.toml, bundler/src/bundler/import/mod.rs, bundler/tests/common/mod.rs, bundler/tests/fixture/dynamic/input/dep.ts, bundler/tests/fixture/dynamic/input/entry.ts, bundler/tests/fixture/dynamic/output/entry.ts
I'll reenable this after implementing an option to make `swc_bundler` to include them.
---
swc_bundler:
- Do not load dynamically imported files.
=> fix(bundler): Don't load dynamic imports

.github/workflows/integration.yml, Cargo.toml, benches/typescript.rs, ecmascript/transforms/typescript/Cargo.toml, ecmascript/transforms/typescript/src/strip.rs, ecmascript/transforms/typescript/tests/strip.rs, spack/src/loaders/swc.rs, src/config.rs, src/lib.rs, tests/projects.rs
swc_ecma_transforms_typescript:
swc:
=> fix(es/transforms): Handle enum in namespaces

.github/workflows/integration.yml
To prevent regression related to cli updates, we ensure that cli ignores errors with specific error mesages.
=> v1.2.46: Prevent regression.

.github/workflows/publish-node.yml, package.json, scripts/npm/android-arm64/package.json, scripts/npm/darwin-arm64/package.json, scripts/npm/linux-arm-gnueabihf/package.json, scripts/npm/linux-arm64-gnu/package.json, scripts/npm/linux-x64-gnu/package.json, scripts/npm/linux-x64-musl/package.json, scripts/npm/win32-ia32-msvc/README.md, scripts/npm/win32-ia32-msvc/package.json, scripts/npm/win32-x64-msvc/package.json
Build and tests for node addons passed: https://github.com/swc-project/swc/actions/runs/519840643
Ready to merge
=> Support windows ia32 arch

bundler/tests/fixture/deno-8574/output/entry.inlined.ts, bundler/tests/fixture/deno-8574/output/entry.ts, ecmascript/preset_env/src/lib.rs, ecmascript/preset_env/tests/test.rs, node-swc/src/types.ts
This allows a path to be passed where preset-env will look for the `browserslist` node module and any browserslist config files (e.g. `.browserslistrc`, `package.json`, etc)
This is useful when your build system and/or some of your node_modules aren't in your project (current) directory.
If not specified, then it will default to the current directory of the process, which was the default behaviour before this change.
=> Allow preset-env to take a config path

node-swc/src/index.ts
When trying out the rollup swc-plugin I got confused why my `options.plugin` would dissapear during concurrent runs
=> avoid removing plugin

node-swc/src/Visitor.ts
This currently crashes https://github.com/preactjs/wmr/pull/321/files#diff-fd4936a99dc4faf7e48aac7b7ee5624bfea4cd45e225ddae7c5ed73a3e08eddeR20 when calling `super.visitModule`
=> account for empty pattern properties

common/src/syntax_pos/analyze_source_file.rs
swc_common uses `is_x86_feature_detected!("sse2")` inside which makes it impossible to use swc_common with MIRI together. This is needed for example in [starlight](https://github.com/Starlight-JS/starlight) to verify JS interpreter,GC and other stuff.
=> Support using swc_common with MIRI

.github/workflows/publish-node.yml
https://github.com/Brooooooklyn/swc/runs/1962777574?check_suite_focus=true
Linux docker testing passed, safe to ignore the failed result in windows and macos, because I forgot to add `if: matrix.os == 'ubuntu-18.04'` condition in the linked job.
Close https://github.com/swc-project/swc/issues/1430
=> Fix Glibc compatible issue with Node.js official docker images

Cargo.toml, ecmascript/parser/tests/typescript/issue-1441/input.ts, ecmascript/parser/tests/typescript/issue-1441/input.ts.json, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/base/src/ext.rs, ecmascript/transforms/base/src/fixer.rs, ecmascript/transforms/base/src/helpers/mod.rs, ecmascript/transforms/base/src/hygiene/mod.rs, ecmascript/transforms/base/src/hygiene/tests.rs, ecmascript/transforms/base/src/resolver/tests.rs, ecmascript/transforms/base/src/tests.rs, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/compat/src/es2015/block_scoping.rs, node-swc/src/types.ts, src/builder.rs, src/config.rs, tests/fixture/issue-1279/case1/input/.swcrc, tests/fixture/issue-1279/case1/input/index.ts, tests/fixture/issue-1279/case1/output/index.ts, tests/fixture/issue-1441/input/.swcrc, tests/fixture/issue-1441/input/index.ts, tests/fixture/issue-1441/output/index.ts
=> fix(swc): Fix various bugs

ecmascript/parser/src/error.rs, ecmascript/parser/src/parser/pat.rs, ecmascript/parser/tests/typescript-errors/issue-1209/input.ts, ecmascript/parser/tests/typescript-errors/issue-1209/input.ts.stderr
Fixes #1209.
I was not sure if I was supposed to return a syntax error or just emit it. 
Also TS does not have specific error for this and shows very unhelpful message, so went with this new error.
=> fix(es/parser): don't allow type annotation after assign

ecmascript/preset_env/src/lib.rs, ecmascript/preset_env/src/transform_data.rs, ecmascript/preset_env/src/transform_data_bugfixes.json, ecmascript/preset_env/tests/test.rs, ecmascript/transforms/compat/src/bugfixes.rs, ecmascript/transforms/compat/src/bugfixes/async_arrows_in_class.rs, ecmascript/transforms/compat/src/bugfixes/edge_default_param.rs, ecmascript/transforms/compat/src/bugfixes/template_literal_caching.rs, ecmascript/transforms/compat/src/lib.rs, ecmascript/transforms/react/src/jsx/mod.rs, ecmascript/transforms/react/src/jsx/tests.rs, src/config.rs
This is a port of [@babel/preset-modules](https://github.com/babel/preset-modules) to SWC. As with the original, this produces smaller output when targeting browsers supporting esmodules that just works around browser bugs as opposed to compiling to ES5. This was later [integrated](https://babeljs.io/blog/2020/03/16/7.9.0#babelpreset-envs-bugfixes-option-11083httpsgithubcombabelbabelpull11083) into `@babel/preset-env`, and I think that would be a good idea for SWC's preset-env as well.
This is just an initial PR to get feedback on the approach and whether this would even be accepted into SWC. Also left some questions below.
cc. @developit
=> Port @babel/preset-modules to SWC

common/Cargo.toml, common/src/source_map.rs
I noticed that all mappings were pointing to column zero in the original source. This was because the result of `calc_extra_bytes` was used rather than subtracting from the original position. I copied this logic from the `bytepos_to_file_charpos_with` function in the same file.
Before:
After:
Notice the red mappings point to the corresponding source in the original rather than a single mapping for the whole line.
I'm happy to add tests, but I didn't see an existing one to base it off of. Let me know.
=> Fix column positions in generated sourcemaps

Cargo.toml, bundler/Cargo.toml, bundler/src/bundler/import/mod.rs, ecmascript/Cargo.toml, ecmascript/preset_env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/compat/src/es2020.rs, ecmascript/transforms/compat/src/es2020/class_properties.rs, ecmascript/transforms/compat/tests/es2020_class_properties.rs, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/proposal/Cargo.toml, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/tests/decorators.rs, ecmascript/transforms/typescript/Cargo.toml, ecmascript/transforms/typescript/benches/compat.rs, ecmascript/transforms/typescript/src/strip.rs, ecmascript/transforms/typescript/tests/strip.rs, spack/tests/pass/deno-001/full/output/entry.js, spack/tests/pass/deno-001/simple-1/output/entry.js, src/config.rs, tests/fixture/issue-1160/output/entry.ts, tests/fixture/issue-1345/output/index.ts, tests/fixture/issue-1421/case1/output/index.ts
Fixes #1483.
Also ensures that every test applies the `decorator()` pass before `strip()`. This is necessary now, and it makes sense because there shouldn't be decorators in JS.
=> fix(strip): Transform static class fields to assignments

bundler/Cargo.toml, bundler/src/inline.rs, bundler/tests/fixture/deno-9868/case1/input/entry.ts, bundler/tests/fixture/deno-9868/case1/input/temp2.ts, bundler/tests/fixture/deno-9868/case1/output/entry.inlined.ts, bundler/tests/fixture/deno-9868/case1/output/entry.ts
=> fix(bundler): Fix inlining pass

ecmascript/codegen/Cargo.toml, ecmascript/codegen/src/comments.rs, ecmascript/codegen/src/text_writer/basic_impl.rs
Before:
After:
Again, happy to add tests if you point me where they should go. 😄
=> Fix sourcemaps of multi line block comments

ecmascript/codegen/Cargo.toml, ecmascript/codegen/src/typescript.rs, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/base/src/hygiene/mod.rs, ecmascript/transforms/base/src/resolver/tests.rs, ecmascript/transforms/base/tests/ts_resolver.rs
=> fix(es): Fix for the type checker

ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/react/src/jsx/mod.rs, ecmascript/transforms/react/src/lib.rs, ecmascript/transforms/react/src/refresh/mod.rs, ecmascript/transforms/react/src/refresh/options.rs, ecmascript/transforms/react/src/refresh/tests.rs, ecmascript/transforms/react/src/refresh/util.rs
Add config for react refresh. This feature is disabled by default since it's considered experimental.
I don't quite know how to write doc for swc so it would be great if you could do that for me. Config should be something like 
```json
{
"refresh": true
}
```
or
```
{
"refresh": {
"emitFullSignatures": true
}
}
```
Also this pr would require version 0.10 of `react-refresh` as a dependency to work
=> feat(es/transforms/react): Fast refresh config

ecmascript/transforms/optimization/src/simplify/branch/mod.rs, ecmascript/transforms/optimization/src/simplify/branch/tests.rs, spack/tests/pass/issue-1328/case1/output/entry.js
This fixes an issue where the branch simplifier would inline single statement blocks too aggressively, resulting in broken code. For example:
```js
if (Date.now() < 0) {
for(let i = 0; i < 10; i++){
if (Date.now() < 0) {
console.log(1);
}
}
} else {
console.log(2);
}
```
gets turned into
```js
if (Date.now() < 0) for(let i = 0; i < 10; i++) if (Date.now() < 0) console.log(1);
else console.log(2);
```
This results in the `else` being applied to the second `if` rather than the first.
I've attempted to solve this by computing the depth of statements in the block's first statement until hitting another block statement. If the depth is greater than 1, then it's not safe to inline the block.
Perhaps there's a better way to solve this? i.e. should the printer be handling this based on …
=> Fix inlining nested block statements in branch simplifier

node-swc/src/types.ts
=> fix(node-swc): type `Argument.spread` should be optional

node-swc/src/types.ts
```ts
export type VariableDeclarationKind = "get" | "let" | "const";
```
obviously should be
```ts
export type VariableDeclarationKind = "var" | "let" | "const";
```
=> Fix wrong VariableDeclarationKind typescript definition

ecmascript/transforms/base/src/resolver/mod.rs, ecmascript/transforms/base/src/resolver/tests.rs, ecmascript/transforms/optimization/tests/simplify_inlining.rs
Code like the following was broken, because the function expression name was added to the outer scope rather than the inner scope.
```js
export default function foo() {
foo = function foo(x) {
return x === 0 ? 1 : 1 + foo(x - 1);
};
return foo(10);
}
```
resulted in
```js
export default function foo() {
foo = function foo1(x) {
return x === 0 ? 1 : 1 + foo1(x - 1);
};
return foo1(10); // <- this is wrong
};
```
Fixed by applying the function expression name to the inner scope instead.
(As a side note, I found it weird that `export default function foo() {}` parses as an `FnExpr` instead of a `FnDecl`. Same with classes. Babel parses them as declarations rather than expressions. Is this intentional?)
=> Fix named function expression handling in resolver

Cargo.toml, bundler/Cargo.toml, ecmascript/Cargo.toml, ecmascript/codegen/Cargo.toml, ecmascript/dep-graph/Cargo.toml, ecmascript/ext-transforms/Cargo.toml, ecmascript/jsdoc/Cargo.toml, ecmascript/parser/Cargo.toml, ecmascript/parser/src/error.rs, ecmascript/parser/src/lib.rs, ecmascript/parser/src/parser/class_and_fn.rs, ecmascript/parser/tests/typescript-errors/class/duplicated-modifiers/input.ts, ecmascript/parser/tests/typescript-errors/class/override-in-non-subclass/input.ts, ecmascript/parser/tests/typescript-errors/class/override-in-non-subclass/input.ts.stderr, ecmascript/parser/tests/typescript-errors/class/override-on-constructor/input.ts, ecmascript/parser/tests/typescript-errors/class/override-with-static/input.ts, ecmascript/preset_env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/proposal/Cargo.toml, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/testing/Cargo.toml, ecmascript/transforms/typescript/Cargo.toml
With this PR, the code below will be invalid:
```ts
class C {
override t() {}
}
```
=> fix(es): disallow `override` in non-subclass

ecmascript/parser/src/error.rs, ecmascript/parser/src/parser/class_and_fn.rs, ecmascript/parser/tests/typescript-errors/class/implements-before-extends/input.ts, ecmascript/parser/tests/typescript-errors/class/implements-before-extends/input.ts.stderr
For this case:
```ts
class C implements A extends B {}
```
It should be TS1173, not TS1175.
=> fix(es): fix error message with TS1173

bundler/tests/fixture/deno-9212/case1/output/entry.inlined.ts, bundler/tests/fixture/deno-9212/case1/output/entry.ts, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/base/src/fixer.rs, ecmascript/transforms/compat/src/es2015/block_scoping.rs
This fixes an issue where parentheses would be removed around sequence expressions when they shouldn't, specifically in the case of a call expression callee, and a default value for a function param.
For example:
```ts
let x = ({}, () => 2)();
```
was compiling to:
```ts
let x = {
}, ()=>2
();
```
which is a syntax error.
A similar issue was seen with default assignment patterns in parameters. The fix was to ensure the correct context is set when visiting a sequence expression so that parentheses are added when needed. I checked a bunch of other places where commas are allowed and these were the ones I found, but there could be more.
=> Fix parenthesization of sequence expressions in callee and function params

ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/optimization/src/simplify/branch/tests.rs, ecmascript/transforms/optimization/src/simplify/expr/mod.rs
In general, `{}.foo` shouldn't be replaced with `undefined` because
1. the properties on the object prototype aren't undefined (`{}.constructor` itself, `{}.hasOwnProperty`, ...) and
2. hypothetically, the object's prototype could have been modified: `({}.__proto__).foo = 2; console.log({}.foo)`
Instead, only member accesses for properties that actually exists should be replaced
The fix seems to work, but I'm not so sure about the added test: reverting the change to the simplifier, this is the test output:
```
---- simplify::branch::tests::test_object_literal stdout ----
----- Actual -----
----- Actual -----
----- Actual -----
----- Actual -----
----- Actual -----
>>>>> Orig <<<<<
({}).foo
>>>>> Code <<<<<
thread 'simplify::branch::tests::test_object_literal' panicked at 'assertion …
```
=> Don't replace missing object members with undefined

ecmascript/transforms/base/src/fixer.rs, ecmascript/transforms/compat/tests/es2015_destructuring.rs, ecmascript/transforms/compat/tests/es2020_class_properties.rs, ecmascript/transforms/compat/tests/es2020_optional_chaining.rs, ecmascript/transforms/module/src/util.rs, ecmascript/transforms/module/tests/amd.rs, ecmascript/transforms/module/tests/common_js.rs, ecmascript/transforms/module/tests/umd.rs, ecmascript/transforms/react/src/refresh/mod.rs, ecmascript/transforms/react/src/refresh/tests.rs, ecmascript/transforms/tests/decorators.rs, ecmascript/transforms/tests/es2015_function_name.rs, tests/fixture/issue-1333/case3/output/index.js, tests/fixture/issue-1449/case1/output/index.js, tests/fixture/issue-1477/case1/output/index.js, tests/projects.rs
=> fix(es/transforms/module): transform esmodule import to sequence expression

ecmascript/transforms/base/src/resolver/mod.rs, ecmascript/transforms/base/src/resolver/tests.rs
This fixes an issue where class declarations were not properly block scoped.
```js
const g = 20;
function baz() {
{
class g {}
}
return g;
}
```
was compiling to:
```js
const g1 = 20; // <- this is wrong
function baz() {
{
class g1 {}
}
return g;  // <- this is wrong
}
```
This was caused by the resolver hoisting class declarations when it shouldn't. Now they are ignored if within a block statement, just like `let`/`const` var declarations.
=> Fix block scoping of class declarations

ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/base/src/fixer.rs
The `yield` expression has a lower precedence than the conditional operator, so needs parentheses.
=> Fix precedence of yield expression inside ternary

ecmascript/transforms/base/src/quote.rs, tests/fixture/issue-1557/case1/output/index.js, tests/fixture/pr-1579/checkingExtend/input/.swcrc, tests/fixture/pr-1579/checkingExtend/input/index.js, tests/fixture/pr-1579/checkingExtend/output/index.js
Hello,
I've made a typo in #1557 in the expected output since `@swc/helpers` exports a `typeOf` function (note the capital `O`).
Also the `_extends` does not exists. It is exposed as `extends` instead.
I can't find what source code triggers the use of `extends` ... I've tried object spread (uses `objectSpread`), Object.assign (unchanged), class inheritance doesn't seem to fit what the code was written for.
I cannot run the tests as of now to make sure nothing broke. I'll have to do that in a later day.
=> @swc/helpers exports typeOf instead of typeof

ecmascript/transforms/compat/src/es2015/regenerator/case.rs, ecmascript/transforms/compat/tests/es2015_regenerator.rs, ecmascript/transforms/module/tests/common_js.rs
This fixes an issue in the regenerator transform, where the context variable member expression was passed to `delegateYield` rather than the name of that variable. This broke yield expressions where the result was used. See the added test for details: previously it output `[5, NaN]` instead of `[5, 8]`.
=> Fix regenerator transform for yield* expressions

ecmascript/transforms/compat/src/es2015.rs, ecmascript/transforms/compat/src/es2015/classes/mod.rs, ecmascript/transforms/compat/tests/es2015_classes.rs, ecmascript/transforms/compat/tests/es2020_class_properties.rs, node-swc/__tests__/module_test.js, tests/fixture/issue-1490/full/output/index.js, tests/fixture/issue-1505/case1/output/index.ts, tests/fixture/issue-1505/case2/output/index.ts, tests/fixture/issue-1505/case3/output/index.tsx, tests/fixture/issue-1505/tsx-default/output/index.ts
When transforming classes, the super class is passed as a parameter to the iife wrapper for the class. However, this parameter should have a separate syntax context from the original identifier of the super class passed to the call. Currently, re-assigning the super binding has no effect within the class body because of this. For example:
```js
class Foo {}
class Test extends Foo {
foo() {
console.log(Foo);
}
}
Foo = 3;
new Foo().foo();
```
should log `3` but it currently logs the original `Foo` function. This is now transformed to:
```js
let Test = function(Foo1) {
'use strict';
_inherits(Test, Foo1);
function Test() {
_classCallCheck(this, Test);
return _possibleConstructorReturn(this, _getPrototypeOf(Test).apply(this, arguments));
}
_createClass(Test, [
{
key: 'foo',
value: function …
```
=> Fix syntax context of super in class transform

ecmascript/transforms/optimization/src/simplify/branch/mod.rs, ecmascript/transforms/optimization/src/simplify/branch/tests.rs
This prevents the simplify pass from folding do-while loops with constant conditions when the body has a conditional stoppers. Previously, this folded the loop but left behind `break;` and `continue;` statements, creating invalid JavaScript.
I'm not sure it's possible to rewrite all possible loops to behave identically as when they had these stoppers, so this skips folding entirely.
Test Plan: Added unit test.
=> feat(es/transforms) simplify: do not fold do-while loops with conditional stoppers

ecmascript/transforms/optimization/src/simplify/expr/mod.rs, ecmascript/transforms/optimization/src/simplify/expr/tests.rs
An example where `... instanceof Object` isn't `true`:
```js
let x = undefined;
if (x instanceof Object) {
console.log(x.obj);
}
```
previously, this was simplified to `if(true)`
=> Don't simplify `x instanceof Object`

ecmascript/transforms/react/src/lib.rs
Closes #1638
`jsx_src`, `jsx_self` and `refresh` visit the JSX nodes, so they need to run before the JSX transpliation.
=> Change order of transforms in react preset

ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/compat/src/es2015/classes/mod.rs, tests/fixture/issue-1490/full/output/index.js, tests/fixture/issue-1505/case1/output/index.ts, tests/fixture/issue-1505/case2/output/index.ts, tests/fixture/issue-1505/case3/output/index.tsx, tests/fixture/issue-1505/case4/output/index.tsx, tests/fixture/issue-1505/case5/output/index.tsx, tests/fixture/issue-1505/tsx-default/output/index.ts, tests/fixture/next.js/slack-2/es5/output/index.js
=> fix(es/transforms/compat): Fix span for comments in classes transform.

ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/base/src/resolver/mod.rs, ecmascript/transforms/base/src/resolver/tests.rs
=> fix(es/tranforms/base): resolver: Handle function declarations in ts modules

Cargo.toml, babel/compat/Cargo.toml, bundler/Cargo.toml, common/Cargo.toml, ecmascript/Cargo.toml, ecmascript/codegen/Cargo.toml, ecmascript/dep-graph/Cargo.toml, ecmascript/ext-transforms/Cargo.toml, ecmascript/jsdoc/Cargo.toml, ecmascript/parser/Cargo.toml, ecmascript/parser/src/parser/class_and_fn.rs, ecmascript/parser/tests/typescript-errors/class/override-with-static/input.ts, ecmascript/parser/tests/typescript-errors/class/override-with-static/input.ts.stderr, ecmascript/parser/tests/typescript/class/modifier-override/input.ts, ecmascript/parser/tests/typescript/class/modifier-override/input.ts.json, ecmascript/preset_env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/proposal/Cargo.toml, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/testing/Cargo.toml, ecmascript/transforms/typescript/Cargo.toml
Previously, TypeScript didn't allow `override` with `static`, but it seems that it was changed later: [TypeScript playground](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210508#code/MYGwhgzhAEBC0G8BQ1oQC5nQS2NdAFAJSIC+S5SokMAwgIzQCmAHukwHYAmM8yqAewBuTAE6jsXJmkw48hEgnKVqUaLQBMzNpx5xEKGVlzRhYiVPzEyFIA).
Also, this PR enforces order between `override` and `static`.
=> fix(es/parser/typescript): allow `override` with `static`

atoms/src/lib.rs, common/src/syntax_pos.rs, ecmascript/parser/benches/parser.rs, ecmascript/transforms/base/src/helpers/mod.rs, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/compat/src/es2015/block_scoped_fn.rs, ecmascript/transforms/compat/src/es2015/classes/mod.rs, ecmascript/transforms/compat/src/es2015/destructuring.rs, ecmascript/transforms/compat/src/es2015/duplicate_keys.rs, ecmascript/transforms/compat/src/es2015/instanceof.rs, ecmascript/transforms/compat/src/es2015/shorthand_property.rs, ecmascript/transforms/compat/src/es2015/spread.rs, ecmascript/transforms/compat/src/es2015/sticky_regex.rs, ecmascript/transforms/compat/src/es2015/typeof_symbol.rs, ecmascript/transforms/compat/src/reserved_words.rs, ecmascript/utils/src/lib.rs
```
test base                          ... bench:     111,254 ns/iter (+/- 13,235) = 97 MB/s
test common_reserved_word          ... bench:     121,888 ns/iter (+/- 16,508) = 89 MB/s
test common_typescript             ... bench:     269,342 ns/iter (+/- 30,072) = 40 MB/s
test es2015                        ... bench:   1,766,677 ns/iter (+/- 125,103) = 6 MB/s
test es2015_arrow                  ... bench:     162,651 ns/iter (+/- 19,908) = 66 MB/s
test es2015_block_scoped_fn        ... bench:     203,907 ns/iter (+/- 25,950) = 53 MB/s
test es2015_block_scoping          ... bench:     190,847 ns/iter (+/- 22,505) = 57 MB/s
test es2015_classes                ... bench:     451,819 ns/iter (+/- 48,700) = 24 MB/s
test es2015_computed_props         ... bench: …
```
=> fix(es/transforms/compat): Improve performance

ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/compat/src/es2020/class_properties.rs, ecmascript/transforms/compat/tests/es2020_class_properties.rs
=> fix(es/transforsm/compat): Transform private field access in private methods

common/src/private/mod.rs, ecmascript/codegen/Cargo.toml, ecmascript/codegen/src/decl.rs, ecmascript/codegen/src/lib.rs
Fix: #1764 
I fixed the error that with minify option and es2016 ~ 2020 target option `swc` outputs invalid javascript code due to removed space before `extends` keyword on class declaration.
if something wrong (incorrect approach or not enough test case...), please feel free to close this PR or point it out 🙏
=> Fix: removed space before extends keyword on class declaration

ecmascript/transforms/base/tests/ts-resolver/tsc/generatedContextualTyping/1/input.ts, ecmascript/transforms/base/tests/ts-resolver/tsc/generatedContextualTyping/1/output.ts, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/compat/src/es2017/async_to_generator.rs, ecmascript/transforms/compat/tests/es2017_async_to_generator.rs, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/module/src/util.rs, ecmascript/transforms/module/tests/common_js.rs, tests/fixture/issue-1752/case1/input/.swcrc, tests/fixture/issue-1752/case1/input/index.js, tests/fixture/issue-1752/case1/output/index.js, tests/fixture/issue-1757/case1/input/.swcrc, tests/fixture/issue-1757/case1/input/index.js, tests/fixture/issue-1757/case1/output/index.js
=> fix(es/transforms): Fix bugs

.github/workflows/publish-node.yml
Close https://github.com/Brooooooklyn/swc-node/issues/480
=> build(node-swc): Support lower version glibc linux on non-x64 arch

ecmascript/Cargo.toml, ecmascript/transforms/typescript/tests/strip.rs, ecmascript/utils/Cargo.toml, ecmascript/utils/src/var.rs
Currently when there's an import item share the same name with object destructuring in variable declaration like
```ts
import { A } from "./a";
import { B } from "./b";
const { A: AB } = B;
console.log(A, AB);
```
the first import will be striped because `swc` would consider it being shadowed by local variable, which is wrong
=> fix(transform/typescript): incorrectly strip import

ecmascript/parser/Cargo.toml, ecmascript/parser/src/parser/stmt/module_item.rs, ecmascript/parser/src/parser/typescript.rs, ecmascript/parser/tests/typescript/tsc/classes/classDeclarations/classAbstractKeyword/classAbstractSingleLineDecl/input.ts.json
- Don't allow `abstract` and `class` to be on different lines.
=> fix(es/parser): Fix parsing of abstract class over multiple lines

ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/compat/src/es2020/opt_chaining.rs, ecmascript/transforms/compat/tests/es2020_optional_chaining.rs
- closes #1882
This PR attempts to fix #1882 when optional chain ends with member call, does not fold optional chain and leaves it behind.
I tried to follow suggestion https://github.com/swc-project/swc/issues/1882#issuecomment-874552592 but I may place it incorrectly, while test _seems_ correctly resolves optional chain. Will update changes if this is not expected behavior.
=> fix(opt_chain): fold optional chain when chain includes member call at the end

ecmascript/parser/Cargo.toml, ecmascript/parser/src/lexer/state.rs, ecmascript/parser/src/parser/tests.rs
Caused by #1879. I missed this scenario earlier.
Luckily, nobody is going to write files like this.
=> fix: put comments in file with only shebang and comments in the correct map

ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/compat/src/es2015/regenerator/case.rs, ecmascript/transforms/compat/src/es2015/regenerator/leap.rs, ecmascript/transforms/compat/tests/es2015_regenerator.rs
- closes #1892
This PR attempts to handle if regenerator loop includes labeld `continue` statements.
=> fix(regenerator): handle labeled continue jumps

ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/module/src/import_analysis.rs, ecmascript/transforms/module/src/util.rs, tests/fixture/issue-1938/cjs/input/.swcrc, tests/fixture/issue-1938/cjs/input/index.js, tests/fixture/issue-1938/cjs/output/index.js, tests/fixture/issue-1938/esm/input/.swcrc, tests/fixture/issue-1938/esm/input/index.js, tests/fixture/issue-1938/esm/output/index.js
- closes #1938 
This PR attempts to allow named wildcard imports when there are multiple import specifiers. Currently it is unreachable code paths, but it is possible to have imports like
```
import foo, * as actions from '...'
```
to have default import with named imports. PR treats namespace same as single import with namespace case. 
I feel this may not be feasible approach, or brings redundant code paths and would like to update as needed.
=> fix(import): allow namespace import with default import 

ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/base/src/hygiene/mod.rs, ecmascript/transforms/compat/tests/es2015_destructuring.rs
Another attempt to close #1948 
Originate from PR https://github.com/swc-project/swc/pull/1961, this PR attempt to apply same changes partially for the class method params by creating separate scope since param identifier does not collide to other method / prop declarations. 
This _seems_ working, new test case passes without changing existing fixture update. But suggested recommendation (https://github.com/swc-project/swc/pull/1961#issuecomment-886156602) is updating `_mut_class_method` and `_mut_class_prop` both, while this one only touches class_method this may not be still legit approach. Also bit unsure using new folder is right approach to consider.
=> fix(transform): calculate class member fn args identifier collision

common/Cargo.toml, common/src/comments.rs
This is instead of my change in #1996.
Basically what I'm doing is using `single_threaded_comments.take_all()` to get the comment maps, then pulling the maps out of the `Rc` and `RefCell`. I'm then using these maps in my own implementation of `Comments` that's multi-threaded and immutable for analysis purposes. Then for transforming, I'm going to take these maps, clone them, then provide them them to this new method to create a `SingleThreadedComments` for transforming in which case it's ok for the emitting code to mutate the comment maps. Does that make sense?
=> feat: add `SingleThreadedComments::from_leading_and_trailing`

Cargo.lock, Cargo.toml, bundler/Cargo.toml, ecmascript/Cargo.toml, ecmascript/codegen/Cargo.toml, ecmascript/dep-graph/Cargo.toml, ecmascript/ext-transforms/Cargo.toml, ecmascript/jsdoc/Cargo.toml, ecmascript/minifier/Cargo.toml, ecmascript/parser/Cargo.toml, ecmascript/parser/src/error.rs, ecmascript/parser/src/parser/stmt.rs, ecmascript/preset-env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/base/Cargo.toml, ecmascript/transforms/classes/Cargo.toml, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/proposal/Cargo.toml, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/testing/Cargo.toml, ecmascript/transforms/typescript/Cargo.toml
With the current parser, parsing `import.meta` in script mode does not generate an error. In ECMAScript, `import.meta` cannot be used in scripts. So this PR occurs a syntax error when parsing `import.meta` in script mode.
=> fix(es/parser): error for `import.meta` in script

Cargo.lock, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/react/src/jsx/mod.rs, ecmascript/transforms/react/src/jsx/tests.rs, ecmascript/transforms/react/tests/jsx/fixture/react-automatic/should-escape-xhtml-jsxattribute/output.mjs, ecmascript/transforms/react/tests/jsx/fixture/react/should-escape-xhtml-jsxattribute-babel-7/output.js, ecmascript/transforms/react/tests/jsx/fixture/react/should-escape-xhtml-jsxattribute/output.js
=> fix(es/transforms/react): Handle escape correctly

node-swc/__tests__/transform/sourcemap_test.js, node-swc/src/index.ts, node/binding/src/parse.rs
- closes #2023 
This PR attempts to support sourcemapped stack with provided filename for `transform*` interfaces. When there are plguins specified, it goes through path to parse into module / program first to pass into plugin. When those occur, it always assigns filename to `FileName::Anon` even though transform option specifies it.
PR pass through `filename` as optional param to compiler's `parse*` and use it if it's specified, otherwise falls back to default behavior. Note PR did not make any public interface exposure to exported `pasre*` in node-swc, instead just passes down to compiler's fn via transform. This is mostly I am not sure if it's desired usecases to parse* allows to specify by default.
=> feat(transform): allow to specify filename when parse module

Cargo.lock, ecmascript/parser/Cargo.toml, ecmascript/parser/src/lib.rs, ecmascript/parser/src/parser/expr.rs, ecmascript/parser/src/parser/mod.rs, ecmascript/parser/src/parser/stmt.rs
- Recover from `import.meta` in scripts. (Closes #2041)
- Allow `import.meta` when using `parse_program`.
=> fix(es/parser): Recover from `import.meta` in scripts

Cargo.lock, Cargo.toml, bundler/Cargo.toml, common/src/lib.rs, ecmascript/Cargo.toml, ecmascript/ast/Cargo.toml, ecmascript/ast/src/lib.rs, ecmascript/loader/Cargo.toml, ecmascript/loader/src/resolvers/node.rs, ecmascript/minifier/Cargo.toml, ecmascript/preset-env/Cargo.toml, ecmascript/transforms/Cargo.toml, ecmascript/transforms/module/Cargo.toml, ecmascript/transforms/module/tests/path_node.rs, ecmascript/transforms/optimization/Cargo.toml, ecmascript/transforms/proposal/Cargo.toml, ecmascript/transforms/react/Cargo.toml, ecmascript/transforms/typescript/Cargo.toml, node-swc/src/spack.ts, node/binding/src/bundle.rs, spack/Cargo.toml, spack/src/config/mod.rs, spack/tests/fixture.rs, src/config/mod.rs, src/lib.rs
Update NodeResolver so it only special cases built in modules when
`TargetEnv::Node`.
This is the preliminary work to fix #1955. All we need to do now is thread the target environment (`TargetEnv`) from `spack` command line arguments into `NodeResolver::new` for proper support.
This is a breaking change as it now expects the browser to be the default target so builtin modules are no longer special-cased by default. I think it is reasonable to assume that the browser should be the default target for compiling/bundling.
=> Support target runtime environment.

Cargo.lock, Cargo.toml, babel/compat/Cargo.toml, babel/compat/benches/babelify.rs, babel/compat/tests/convert.rs, benches/typescript.rs, common/Cargo.toml, common/src/errors.rs, common/src/errors/emitter.rs, examples/usage.rs, node/binding/Cargo.toml, node/binding/src/lib.rs, node/binding/src/minify.rs, node/binding/src/parse.rs, node/binding/src/transform.rs, spack/src/loaders/swc.rs, spack/tests/fixture.rs, src/lib.rs, tests/error_msg.rs, tests/projects.rs, tests/simple.rs, tests/source_map.rs, wasm/Cargo.toml, wasm/src/lib.rs
swc_common:
- Add some utilities for `Handler`.
swc:
- Remove `Compiler.handler`.
- Accept `handler` for each operations. (Closes #2035)
=> fix(swc): Report error correctly

Cargo.lock, ecmascript/ast/src/module_decl.rs, ecmascript/transforms/compat/Cargo.toml, ecmascript/transforms/compat/src/es2020/opt_chaining.rs, ecmascript/transforms/compat/tests/es2020_optional_chaining.rs, ecmascript/transforms/compat/tests/fixture/opt-chain/issue-2063/1/exec.js, ecmascript/transforms/compat/tests/fixture/opt-chain/issue-2063/2/exec.js, ecmascript/transforms/testing/Cargo.toml, ecmascript/transforms/testing/src/lib.rs, node-swc/src/types.ts, testing/Cargo.toml, testing/macros/Cargo.toml, testing/macros/src/fixture.rs, testing/src/lib.rs, tests/fixture/issue-2063/input/index.js, tests/fixture/issue-2063/output/index.js
- Fix optional chaining. (Closes #2063)
node/swc:
- Fix definition of `ImportDeclaration`. (Closes #2059)
testing:
- Allow using `testing` with stable `rustc`.
testing_macros:
- Add `#[inline(never)]`.
=> fix(swc): Fix bugs

package.json
In @swc/core package, types path in package.json is `./lib/index.d.ts`, but it should be` ./index.d.ts`
=> fix(swc): fix incorrect types path in package.json

Cargo.lock, ecmascript/parser/Cargo.toml, ecmascript/parser/src/parser/object.rs, ecmascript/parser/tests/jsx/basic/issue-2075/case1/input.js, ecmascript/parser/tests/jsx/basic/issue-2075/case1/input.js.json, ecmascript/parser/tests/jsx/basic/issue-2075/not-keyword/input.js, ecmascript/parser/tests/jsx/basic/issue-2075/not-keyword/input.js.json
- Use correct token context when `function` is used as the name of a property. (Closes #2075)
=> fix(es/parser): Fix parsing of `function` in property names

Cargo.lock, ecmascript/parser/Cargo.toml, ecmascript/parser/src/lib.rs
- Don't use `#![feature]` for non-test builds. (Closes #2083)
=> fix(es/parser): Allow using parser with stable rustc

node-swc/src/types.ts
this option is actually `strictMode` instead of `strict_mode`
=> types: fix typo with strictMode

node-swc/src/Visitor.ts, node-swc/src/types.ts
There's a typo in the `ExportNamespaceSpecifier` which means TypeScript errors occur when spelling it correctly. 
This might be a breaking change.
=> Fix typo `ExportNamespaceSpecifier`

node-swc/src/spack.ts
Typo when using TypeScript for the `SpackConfig`.
=> Fix typo ~~`extenalModules`~~ to `externalModules`

Cargo.lock, css/parser/Cargo.toml, css/parser/src/lib.rs, css/parser/src/parser/input.rs, css/parser/src/parser/selector/mod.rs, css/parser/tests/fixture.rs
swc_css_parser:
- Add `parse_tokens`.
- Implement `Parse<CompoundSelector>` for the parser.
=> feat(css/parser): Improve parser api

ecmascript/parser/src/error.rs, ecmascript/parser/tests/typescript-errors/class/declare-class-method/input.ts.stderr, ecmascript/parser/tests/typescript-errors/class/override-with-declare/input.ts.stderr
tsc's TS1031 error message was updated in https://github.com/microsoft/TypeScript/pull/40889, but TS1031 error message in swc still be an old version. 
I update and fix it.
TypeScript Playground URL: https://www.typescriptlang.org/play?#code/MYGwhgzhAEASD2BzAptA3gKGt6ATZoYATqmGQBQCUAXNBAC5ECWAdogNwYC+GQA
=> Chore: update TS1031 error message

ecmascript/loader/src/resolvers/node.rs
Incorrectly passing the parent of the base directory would cause
some modules not to be found.
=> Fix bug resolving node modules.

ecmascript/parser/src/parser/stmt.rs
Follow up #2130
Add tests for multiple static blocks.
=> test(es/parser): add tests for multiple static blocks

ecmascript/loader/src/resolvers/node.rs
This allows passing `base_dir` as either a directory or a file and the behavior should be correct either way.
Typically when walking the module graph we have a *calling file* that performs the `import` (or `require`) so it makes sense to pass the file and automatically use the parent however there are times when it is convenient to resolve packages outside of the module graph and then it is more appropriate to use `std::env::current_dir()` for `base_dir`.
=> Node base directory handling

Cargo.lock, css/Cargo.toml, css/codegen/Cargo.toml, css/parser/Cargo.toml, css/parser/src/parser/selector/mod.rs, css/parser/tests/fixture.rs, css/parser/tests/fixture/styled-jsx/selector/1/input.css, css/parser/tests/fixture/styled-jsx/selector/1/output.json, css/parser/tests/fixture/styled-jsx/selector/1/span.rust-debug, css/parser/tests/fixture/styled-jsx/selector/2/input.css, css/parser/tests/fixture/styled-jsx/selector/2/output.json, css/parser/tests/fixture/styled-jsx/selector/2/span.rust-debug, css/stylis/Cargo.toml
swc_css_parser:
- Remove `Parse<CompoundSelector>` implementation.
- Add `Parse<ComplexSelector>` implementation.
- Add `Parse<Vec<ComplexSelector>>` implementation.
- Verify tokens input.
=> fix(css/parser): Fix parsing of selectors

Cargo.lock, ecmascript/transforms/typescript/Cargo.toml, ecmascript/transforms/typescript/src/strip.rs, ecmascript/transforms/typescript/tests/strip.rs, ecmascript/utils/Cargo.toml, ecmascript/utils/src/lib.rs
- Don't panic on jsx.
swc_ecma_transforms_typescript:
- Drop type-only reexports. (Closes #2219)
=> fix: Fix simple bugs

Cargo.lock, ecmascript/codegen/Cargo.toml, ecmascript/codegen/src/lib.rs
swc_ecma_codegen:
- Fix codegen of ` in template string literals.
=> fix(es/codegen): Fix codegen of ` in synthesized template literals

Cargo.lock, Cargo.toml
The `swc` crate currently has two features that cause issues when used as a library:
- `log/release_max_level_info`. This feature silences `debug` and `trace` logs globally in *all* crates that depend on the `log` crate.
- `swc_node_base` which depends on the `mimalloc-rust` crate and sets a custom allocator. Users of the `swc` crate may want to provide their own allocator, and the global allocator feature requires a nightly compiler.
This pull request makes these two features optional, while leaving them enabled by default to preserve the current behavior.
=> fix: Make crate features with global effects optional.

Cargo.lock, ecmascript/minifier/Cargo.toml, ecmascript/minifier/src/compress/optimize/mod.rs, ecmascript/minifier/tests/compress/fixture/issues/2262/1/input.js, ecmascript/minifier/tests/compress/fixture/issues/2262/1/output.js, ecmascript/minifier/tests/terser/compress/block-scope/do_not_hoist_let/output.js
This reproduces #2262, though I'm not sure how to fix
---
Closes #2262
=> fix(es/minifier): Don't drop used variables

node-swc/src/types.ts
Following the documentation ["Configuring js minifier"](https://swc.rs/docs/config-js-minify/), seems some minifier options can be put into `jsc.minify`, but type signature isn't.
Note: I'm not sure this is the only thing I have to fix.
=> fix(node/swc): Allow `JsMinifyOptions` type for `JscConfig.minify`

node-swc/__tests__/transform/sourcemap_test.js, node-swc/tests/issue-2120/.swcrc, node-swc/tests/issue-2120/input.js, src/config/mod.rs, tests/fixture/issue-2154/case1/input/.swcrc, tests/fixture/issue-2154/case1/input/index.js, tests/fixture/issue-2154/case1/output/index.js
swc:
- Ensure that #2154 is not the case. (Closes #2154)
node_swc:
- Verify `sourceMaps: true` in `.swcrc`. (#2120, Closes #2194)
=> fix(swc): Fix simple bugs

ecmascript/parser/src/parser/stmt.rs, ecmascript/parser/src/parser/stmt/module_item.rs, ecmascript/parser/tests/test262-error-references/fail/26c0710a6449872a.module.js.stderr, ecmascript/parser/tests/typescript-errors/multiple-specifiers/export/input.ts, ecmascript/parser/tests/typescript-errors/multiple-specifiers/export/input.ts.stderr, ecmascript/parser/tests/typescript-errors/multiple-specifiers/import/input.ts, ecmascript/parser/tests/typescript-errors/multiple-specifiers/import/input.ts.stderr
Before this PR, the code below should be invalid:
```js
import { a b c } from 'mod'
export { a b c }
```
but swc didn't report. This PR fixes it.
=> fix(es/parser): multiple import/export specifiers without comma

node-swc/src/Visitor.ts
In some environment, default exporting can be problematic.
=> feat(node/swc): support for named export `Visitor`

Cargo.lock, css/Cargo.toml, css/parser/Cargo.toml, css/parser/src/parser/mod.rs, css/parser/src/parser/style_rule.rs, css/parser/src/parser/value/mod.rs, css/parser/tests/fixture.rs, css/parser/tests/recovery/styled-jsx/1/input.css, css/parser/tests/recovery/styled-jsx/1/output.json
swc_css_parser:
- Recover from wrong properties like `flex-basis: __styled-jsx-placeholder__2%;`.
=> feat(css/parser): Implement more error recovery

common/Cargo.toml, common/src/source_map.rs
From the doc for `fs::read_to_string`:
> It pre-allocates a buffer based on the file size when available, so it is generally faster than reading into a string created with String::new()
=> perf(ecmascript/parser): avoid string re-allocation

node-swc/src/spack.ts
This PR prevent spreading string typed `config` into the return of `compileBundleOptions`
In this syntax
```js
return Object.assign({}, configFromFile, config);
```
`config` can be of type string referencing the config's file path.
Example:
If `config` is a file path = `"/app/c.js"`, the function will do
```js
Object.assign({}, configFromFile, "/app/c.js");
```
and the resultant return becomes
```js
{
"0": "/",
"1": "a",
"2": "p",
"3": "p",
"4": "/",
"5": "c",
"6": ".",
"7": "j",
"8": "s",
...configFromFile,
}
```
=> fix(spack): prevent spreading string into return

Cargo.lock, testing/Cargo.toml, testing/src/output.rs
A few tests were failing when the repository is checked out with native windows line endings (so the expected content actually has CRLF in it)
I could have changed my git setup but might as well fix it for everyone a the change is simple and seems harmless.
=> Fix tests failing due to CRLF on windows

Cargo.lock, ecmascript/utils/Cargo.toml, ecmascript/utils/src/lib.rs, ecmascript/utils/src/macros.rs
- Allow using macros from crates using `swc_ecmascript`.
=> fix(es/utils): Fix macros

.vscode/settings.json, Cargo.lock, Cargo.toml, benches/typescript.rs, node/bundler/src/loaders/swc.rs, src/builder.rs, src/config/mod.rs, src/lib.rs, tests/projects.rs, tests/rust-users.rs
swc:
- Invoke `resolver` and `typescript::strip` before applying user passes.
=> fix(swc): Fix order of custom passes

Cargo.lock, css/Cargo.toml, css/ast/Cargo.toml, css/ast/src/value.rs, css/codegen/Cargo.toml, css/codegen/src/lib.rs, css/parser/Cargo.toml, css/parser/src/parser/value/mod.rs, css/parser/tests/fixture.rs, css/parser/tests/fixture/rome/custom-properties/output.json, css/parser/tests/fixture/rome/custom-properties/span.rust-debug, css/parser/tests/fixture/rome/grid/repeat/line-name/output.json, css/parser/tests/fixture/rome/grid/repeat/line-name/span.rust-debug, css/parser/tests/fixture/rome/grid/repeat/multi-values/output.json, css/parser/tests/fixture/rome/grid/repeat/multi-values/span.rust-debug, css/parser/tests/fixture/value/custom-property/output.json, css/parser/tests/fixture/value/custom-property/span.rust-debug, css/parser/tests/fixture/value/square-brackets/input.css, css/parser/tests/fixture/value/square-brackets/output.json, css/parser/tests/fixture/value/square-brackets/span.rust-debug, css/stylis/Cargo.toml, css/utils/Cargo.toml, css/visit/Cargo.toml, css/visit/src/lib.rs
Added `SquareBracketBlock`, we have big problems with parsing `simple block`s https://www.w3.org/TR/css-syntax-3/#ref-for-simple-block%E2%91%A3
Shortly:
- We have three types of blocks - `(`/`)`, `[`/`]`, `{`/`}` in CSS (i.e simple block in spec)
- Each `simple block` can contain `component value`
- `Component value` can contain another `simple blocks`
- There are no commas/spaces or other values inside blocks, so we should remove empty (i.e. `SpacedValue`/ `CommaValue`)
- Also here fix when we can't parse grid multiple lines with whitespaces inside
- Also `simple blocks` can be part of `at-rules` value, so when we finish `simple blocks` we will simplify at-rules logic vey well 
Future fixes:
- I will content `(` and `)` to block too
- We should have two functions `parse_simple_block` and …
=> feat(css/ast): Add `SquareBracketBlock`

ecmascript/parser/src/lexer/mod.rs
Hello, I'm new to this codebase, During code reading, I found this strange code, and I think this is the correct implementation. Why is there an infinite loop?
=> fix(es/lexer): Fix parsing of interpreter

.github/workflows/cargo.yml, node/binding/src/minify.rs, node/binding/src/parse.rs, node/binding/src/print.rs, node/binding/src/transform.rs, node/binding/src/util.rs
node_swc:
- Make `transform` parse the options in background.
- Make `transform` analyze the input file in background.
- Make `minify` parse the options in background.
- Make `minify` deserialize the input in background.
- Make `parse` parse the options in background.
- Make `parse` analyze the input file in background.
- Make `print` parse the options in background.
- Make `print` deserialize the input file in background.
=> perf(node/swc): Parse input using worker thread

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Issue forms can't be adopted successfully due to invalid syntax:
This PR fixes it.
=> chore: Fix issue form syntax

.github/ISSUE_TEMPLATE/bug_report.yml
The playground was assigned a new domain name, so this PR updates corresponding URL.
=> chore: Update playground link in issue form

ecmascript/transforms/module/src/amd.rs, ecmascript/transforms/module/src/common_js.rs, ecmascript/transforms/module/src/umd.rs, ecmascript/transforms/module/src/util.rs, ecmascript/transforms/module/tests/common_js.rs, tests/fixture/issue-1714/case1/output/index.js, tests/fixture/issue-1859/case1-js/output/index.js, tests/fixture/issue-1859/case2-ts/output/index.ts, tests/fixture/issue-1859/case3/output/lib.ts, tests/fixture/issue-2548/case2/output/index.js, tests/fixture/issue-2548/case3/output/index.js
- closes #2594.
This PR attempts to order of the imports / reexports in transpiled runtime codebase. #2594 itself sufficiently explains the issue itself. It could be an implementation detail but so far based on observation tsc / babel works in the same way, which makes think it'd better to align as well. As issue described normally this won't appear but if there's some sort of circular dependencies, or reexports have dependencies across each other it may reveal different behavior.
For the change itself, PR changes the order of injecting handled export_all stmt by putting it after require stmt is created. In result, export_all stmt doesn't use extra_stmt (which appends to stmt at the end). Also changed `exports_alls` to map to stmt itself - when encountering ExportAll stmt it is gauranteed …
=> fix(es/transforms/cjs): Preserve order of imports for reexports

ecmascript/transforms/typescript/src/strip.rs, tests/fixture/issue-2606/1/input/.swcrc, tests/fixture/issue-2606/1/input/index.ts, tests/fixture/issue-2606/1/output/index.ts
- closes https://github.com/swc-project/swc/issues/2606
This PR attempts to allow reassign fn when it is wrapped with `as` casting paren, like `(warn as any) = v`.
Change follows suggestion to coerece Pat::Ident if given Pat is wrapped paren expr - but instead of after visiting does check and coerece before to distinguish between plain assignment like `(x) = v`.
Peeking emitted output when we try to treat both as same it seems possible to treat both as same but can't 100% sure around minified outputs. For now, choose safest path to not regress existing fixtures.
=> fix(es/transforms/tsc): coerce bindingident with tsasexpr

ecmascript/transforms/compat/src/es2015/arrow.rs, ecmascript/transforms/compat/src/es2015/parameters.rs, ecmascript/utils/src/lib.rs, tests/vercel/loader-only/next-30592/1/input/index.js, tests/vercel/loader-only/next-30592/1/output/index.js
- `contains_this_expr`: Exclude `this` in object properties.
- `arrow`: Exclude `this` in object properties. (https://github.com/vercel/next.js/issues/30592)
- `parameters`: Exclude `this` in object properties.
=> fix(es/transforms): Fix detection of `this`

css/parser/src/parser/selector/mod.rs, css/parser/tests/fixture/rome/selectors/output.json, css/parser/tests/fixture/rome/selectors/span.rust-debug, css/parser/tests/fixture/selector/comments/output.json, css/parser/tests/fixture/selector/comments/span.rust-debug, css/parser/tests/recovery/vercel/001/output.json
Small fix, we should not include spaces before
=> fix(css/parser): Exclude whitespace from span

bundler/src/modules/sort/tests.rs, css/codegen/macros/src/lib.rs, ecmascript/codegen/macros/src/lib.rs, ecmascript/jsdoc/src/lib.rs, ecmascript/minifier/tests/eval.rs, ecmascript/parser/src/parser/expr/tests.rs, ecmascript/preset-env/benches/polyfills.rs, ecmascript/transforms/base/src/hygiene/tests.rs, ecmascript/transforms/compat/src/bugfixes/async_arrows_in_class.rs, ecmascript/transforms/compat/src/es2015/typeof_symbol.rs, ecmascript/transforms/compat/src/es2020/nullish_coalescing/tests.rs, ecmascript/transforms/compat/tests/es2015_block_scoping.rs, ecmascript/transforms/compat/tests/es2015_classes.rs, ecmascript/transforms/compat/tests/es2015_regenerator.rs, ecmascript/transforms/compat/tests/es2015_template_literals.rs, ecmascript/transforms/compat/tests/es2017_async_to_generator.rs, ecmascript/transforms/compat/tests/es2020_optional_chaining.rs, ecmascript/transforms/compat/tests/es2021_logcal_assignments.rs, ecmascript/transforms/compat/tests/es2022_class_properties.rs, ecmascript/transforms/module/tests/umd.rs, ecmascript/transforms/optimization/src/simplify/branch/tests.rs, ecmascript/transforms/optimization/tests/simplify.rs, ecmascript/transforms/optimization/tests/simplify_dce.rs, ecmascript/transforms/optimization/tests/simplify_inlining.rs, ecmascript/transforms/react/src/refresh/tests.rs, ecmascript/transforms/tests/decorators.rs, tests/rust_api.rs
from discussion https://github.com/swc-project/swc/pull/2667#pullrequestreview-799506549
This PR removes trailing whitespace from codes in the repo. Note PR only touches src codes (*.rs). Some of fixture test will fail if fixture strips whitespace as it'll change spans.
=> refactor: Remove trailing whitespace

ecmascript/transforms/compat/src/es2017/async_to_generator.rs, ecmascript/transforms/compat/tests/es2017_async_to_generator.rs
Attempt to close
- Closes #2402 
- Closes #2305 
This PR attempts to amend behavior around generator for the async fn to avoid bind to `this` context if given async fn is assignment to prototype. There was some other approach suggestion like https://github.com/swc-project/swc/issues/2305#issuecomment-927588761 , but doesn't seem to work as issue is prototype doesn't have proper context to attach from beginning.
As similar to existing flag `in_object_prop`, this PR introduces new flag `in_prototype_assignment` to indicate if given assign expr is for the prototype.
=> fix(es/async_to_generator): Do not bind `this` to generator for prototype

css/ast/src/selector.rs, css/parser/tests/fixture.rs, css/visit/src/lib.rs
Remove `UniversalSelector`, we don't use it in code (maybe we forgot to remove it when we do refactor), also `UniversalSelector` is subtype of `TypeSelector`.
=> refactor(css/ast): remove `UniversalSelector`

ecmascript/transforms/compat/src/bugfixes/edge_default_param.rs
Context: https://discordapp.com/channels/889779439272075314/889785438938726441/906736454737219614
This PR attempts to replace existing fold in `edge_default_param` bugfix to visitor. The only reason I choose this module is this looks one of the smallest path I could try to migrate. 
Change's mostly straightforward, except couple of changes: 1. uses `as_folder` to plug migrated visitor to existing logics 2. instead of mapping `props` to reassign, directly replace elements in the vec.
=> refactor(es/transforms/bugfix): visit_mut for edge_default_param

ecmascript/transforms/module/src/common_js.rs, ecmascript/transforms/module/tests/fixture/commonjs/issue-2678/input.js, ecmascript/transforms/module/tests/fixture/commonjs/issue-2678/output.js
- closes #2678 
This PR attempt to fix #2678, one of the edge cases of #2549.
As same as fix for #2549, this PR sets scope to the exported. The only difference is it doesn't set scope to name of the declaration (or FnExpr's) as default export uses fixed name `default` for the export. Given current fold already creates default export member expr, reuses created one to assign into scope.
=> fix(es/transforms/cjs): bind reassign scope to default export fn

crates/swc/tests/fixture/issue-2162/case1/input/.swcrc, crates/swc/tests/fixture/issue-2162/case1/input/index.js, crates/swc/tests/fixture/issue-2162/case1/output/index.js, crates/swc/tests/fixture/issue-2162/case2/input/.swcrc, crates/swc/tests/fixture/issue-2162/case2/input/index.js, crates/swc/tests/fixture/issue-2162/case2/output/index.js, crates/swc/tests/fixture/issue-2162/case3/input/.swcrc, crates/swc/tests/fixture/issue-2162/case3/input/index.js, crates/swc/tests/fixture/issue-2162/case3/output/index.js, crates/swc/tests/fixture/issue-2162/case4/input/.swcrc, crates/swc/tests/fixture/issue-2162/case4/input/index.js, crates/swc/tests/fixture/issue-2162/case4/output/index.js, crates/swc/tests/fixture/issue-2162/case5/input/.swcrc, crates/swc/tests/fixture/issue-2162/case5/input/index.js, crates/swc/tests/fixture/issue-2162/case5/output/index.js, crates/swc/tests/fixture/issue-2162/case6/input/.swcrc, crates/swc/tests/fixture/issue-2162/case6/input/index.js, crates/swc/tests/fixture/issue-2162/case6/output/index.js, crates/swc_ecma_parser/src/lexer/jsx.rs
attempt to fix #2162 
maybe relate to #299
I think babel only escape `\` to `\\` [babel playground](https://babeljs.io/repl#?browsers=IE%208&build=&builtIns=false&corejs=false&spec=true&loose=true&code_lz=MYewdgzgLgBAhjAvDAPAPgFAoIIwEaIDkAOoTAPRoDcWuBJArgKwAsApgGxmU075HEAHgCYAjN2q1-JUhUl96xDDAm9KQA&debug=false&forceAllTransforms=true&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Creact%2Ctypescript&prettier=true&targets=&version=7.16.3&externalPlugins=&assumptions=%7B%7D)
=> fix(ecma/lexer/jsx): jsx back slash escape parse

crates/swc_ecma_parser/src/parser/class_and_fn.rs
attemp to fix #1218
js allow any identifier be a class name (I think), 
and ts disallow "any", "unknown", "never", "number", "bigint", "boolean", "string", "symbol", "void", "object".
=> fix(ecma/parser): check ts class name

README.md
Currently, the swc project's README incorrectly points to https://swc.rs/docs/comparison-babel for a Babel comparison.
The link should point to https://swc.rs/docs/migrating-from-babel
The broken link can either be resolved via direct change here or via redirect in the website's `next.config.js` file. I have made pull requests for both and will create an issue here linking to those pull requests.
---
Closes #2738
=> Repair broken Babel comparison link in README

ARCHITECTURE.md, CONTRIBUTING.md, README.md, crates/swc_babel_compat/README.md, crates/swc_babel_compat/tests/README.md, crates/swc_bundler/README.md, crates/swc_css_parser/README.md, crates/swc_ecma_minifier/README.md, crates/swc_plugin/README.md
As discussed with @kdy1
- Renames `swc` to `SWC` in written text
- Updates `ast` -> `AST`
- Updates `architecture.md` to be in line with the changes to the directory structure, I think we need to rewrite more of it though. This is a start 👍
=> Update markdown files to use "SWC" instead of "swc"

CONTRIBUTING.md
`CONTRIBUTING.md` has incorrect paths in environment setup.
- Update paths in instructions from `ecmascript/transforms` to `crates/swc_ecma_transforms`
- Fix a few missing markdown links I discovered while I was in here (`development-models` and `lru`)
Resolves #2772
=> Fix links and paths in CONTRIBUTING.md

crates/swc_css_parser/src/lexer/mod.rs, crates/swc_css_parser/src/parser/at_rule.rs, crates/swc_css_parser/src/parser/input.rs, crates/swc_css_parser/src/parser/style_rule.rs, crates/swc_css_parser/tests/fixture/at-rule/charset/invalid/output.json, crates/swc_css_parser/tests/fixture/at-rule/charset/invalid/span.rust-debug, crates/swc_css_parser/tests/fixture/at-rule/unknown/output.json, crates/swc_css_parser/tests/fixture/at-rule/unknown/span.rust-debug, crates/swc_css_parser/tests/fixture/comment/output.json, crates/swc_css_parser/tests/fixture/comment/span.rust-debug, crates/swc_css_parser/tests/fixture/rome/comment/output.json, crates/swc_css_parser/tests/fixture/rome/comment/span.rust-debug, crates/swc_css_parser/tests/fixture/rome/smoke/output.json, crates/swc_css_parser/tests/fixture/rome/smoke/span.rust-debug, crates/swc_css_parser/tests/recovery/comments/input.css, crates/swc_css_parser/tests/recovery/comments/output.json, crates/swc_css_parser/tests/recovery/comments/output.swc-stderr
@kdy1 Very important fix, because we handle whitespaces incorrectly, look at example:
```css
a { 
color: /* comment */ /*comment*/ red;
^             ^           ^
/* whitespace tokens */
}
```
Before we eat whitespaces tokens between comments, so tokens in recovery mode was wrong, after this PR now we have valid count of whitespace tokens.
I remove `skip_whitespaces`, we should not rely on whitespaces inside file, lexer generates whitespace tokens, tokens input - already have whitespace tokens inside, also this logic is invalid, because whitespaces can be between comments.
Also we have broken `span` in some cases because they did not take into account whitespaces and comments at the beginning and at the end of the file, so `span` for `Stylesheet` has incorrect values, but `Stylesheet` …
=> Refactor parser and lexer

crates/swc_ecma_parser/src/lexer/mod.rs, crates/swc_ecma_parser/src/lexer/state.rs, crates/swc_ecma_parser/tests/shifted/empty-with-comments/input.ts.comments, crates/swc_ecma_parser/tests/typescript.rs
- Use correct span for storing comments when module is empty.
=> fix(es/parser): Fix comments of empty modules

crates/swc/tests/tsc-references/es6/destructuring/declarationsAndAssignments/input.ts/es5.1.normal/output.js, crates/swc/tests/tsc-references/es6/destructuring/destructuringArrayBindingPatternAndAssignment1ES5/input.ts/es5.1.normal/output.js, crates/swc/tests/tsc-references/es6/destructuring/destructuringArrayBindingPatternAndAssignment1ES5iterable/input.ts/es5.1.normal/output.js, crates/swc/tests/tsc-references/es6/destructuring/destructuringArrayBindingPatternAndAssignment1ES6/input.ts/es5.1.normal/output.js, crates/swc/tests/tsc-references/es6/destructuring/destructuringVariableDeclaration2/input.ts/es5.1.normal/output.js, crates/swc/tests/tsc-references/es6/destructuring/destructuringVariableDeclaration2/input.ts/es5.2.minified/output.js, crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs, crates/swc_ecma_transforms_compat/tests/es2015_destructuring.rs
fix #2819 fix #2821 fix #2843 
ps: 
I don't think write javascript like ```const [x, y, ...z] = [1];``` is a good practice.
may be swc should throw a warning for this case at compile time.
=> fix(ecma/transform): deconstruct array

crates/swc_ecma_parser/src/lexer/jsx.rs, crates/swc_ecma_parser/src/lexer/mod.rs, crates/swc_ecma_parser/tests/jsx/errors/unterminated-string/input.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/0ffb1c3ecf85660e.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/5427bdf48f3eb6d9.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/575367951ac8635d.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/89036b2edb64c00c.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/b3fc8ced7ce28c35.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/b61406dafcaab4b7.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/dc431bcf293513a0.js.stderr
This is part of #1178 for improving SWC support in editors. It allows getting an AST in spite of a unterminated string literal similar to the TypeScript compiler: https://ts-ast-viewer.com/#code/OQFwpgziCWB2DmAoR4oG5kCIRA
In Deno, this will help us do import completions when the user hasn't yet added a quote on a module specifier:
```ts
import * as something from "./
```
=> feat(es/parser): non-fatal unterminated string parsing

crates/swc/tests/fixture/issue-1734/case1-B/output/index.js, crates/swc/tests/fixture/issue-2856/1/input/.swcrc, crates/swc/tests/fixture/issue-2856/1/input/index.js, crates/swc/tests/fixture/issue-2856/1/output/index.js, crates/swc_ecma_transforms_module/src/import_analysis.rs
- closes #2856
As commented in issue, crux is depends on import order import_analysis does not flag wildcard interop need to be used correctly. PR includes a scoped property to contain import sets to determine which interop is requred regardless of import order.
=> fix(es/transforms/module): fix helper injection detection across import order

crates/swc_ecma_transforms_compat/src/es2015/arrow.rs, crates/swc_ecma_transforms_compat/src/es2017/async_to_generator.rs, crates/swc_ecma_transforms_compat/tests/es2015_arrow.rs, crates/swc_ecma_utils/src/function.rs
=> fix(es/transforms/compat): handle arrow in subclass constructor

crates/node/src/parse.rs
- closes #2878 
minor fix to parseFile, per its interface https://github.com/swc-project/swc/blob/2462b9941f94bc475cf9ff9c67e3b7c1f98739cc/node-swc/src/index.ts#L237-L248 option is always an object but parse_file trying to read it as string and deserialize later.
=> fix(node/swc): correctly deserialize parsefile options

crates/swc_css_parser/src/parser/mod.rs, crates/swc_css_parser/src/parser/value/mod.rs, crates/swc_css_parser/tests/fixture.rs, crates/swc_css_parser/tests/recovery/declaration/input.css, crates/swc_css_parser/tests/recovery/declaration/output.json, crates/swc_css_parser/tests/recovery/declaration/output.swc-stderr, crates/swc_css_parser/tests/recovery/delim-token/bang/output.swc-stderr, crates/swc_css_parser/tests/recovery/whitespaces/output.json, crates/swc_css_parser/tests/recovery/whitespaces/output.swc-stderr
Better recovery mode, we don't need `is_in_delimited_value`.
To be honestly we don't need `Ctx` (but it requires more refactor too), every time when you want to use `Ctx`, it means you missed something from spec, because all css can be parsed using https://www.w3.org/TR/css-syntax-3/#parsing
`Ctx` is only valid to parse non standard js, but right now we support `// comment` only, also we want to support Nesting selectors (we already parse some simple cases, but we need more tests and fixes)
=> feat(css/parser): Better recovery mode

crates/swc_ecma_transforms_compat/src/es2015/block_scoping.rs, crates/swc_ecma_transforms_compat/tests/es2015_for_of.rs, crates/swc_ecma_transforms_compat/tests/fixture/for-of/issue-2622/1/exec.js, crates/swc_ecma_transforms_compat/tests/fixture/for-of/issue-2799/1/exec.js, crates/swc_ecma_transforms_compat/tests/fixture/for-of/issue-2915/1/exec.js, crates/swc_ecma_transforms_compat/tests/fixture/for-of/next-31757/1/exec.js, crates/swc_ecma_transforms_compat/tests/fixture/for-of/next-31757/2/exec.js
- `block_scoping`: Track if we are in nested loops.
- `block_scoping`: Don't treat `break` nor `continue` in nested loops as leaper. (https://github.com/vercel/next.js/issues/31757, Closes #2799, Closes #2915)
- `block_scoping`: Don't recurse into nested loops while looking for functions. (Closes #2622)
=> fix(es/transforms/compat): Fix block scoping

Cargo.lock, crates/swc_webpack_ast/Cargo.toml, crates/swc_webpack_ast/src/reducer.rs, crates/swc_webpack_ast/tests/fixture/libs/1/input.js, crates/swc_webpack_ast/tests/fixture/libs/1/output.js, crates/swc_webpack_ast/tests/fixture/react-dom/dev/output.js
- Preserve string literals in `require`
=> fix(webpack/ast): Fix ast reducer

Cargo.lock, crates/swc_webpack_ast/Cargo.toml, crates/swc_webpack_ast/src/reducer.rs, crates/swc_webpack_ast/tests/fixture/amd/define-required/1/output.js, crates/swc_webpack_ast/tests/fixture/css-escape/1/output.js, crates/swc_webpack_ast/tests/fixture/react-dom/dev/output.js, crates/swc_webpack_ast/tests/fixture/react-dom/prod/output.js
- `ast_reducer`: Preserve array literals in `define` calls.
=> fix(webpack/ast): Fix amd support

.vscode/settings.json, Cargo.lock, crates/testing_macros/Cargo.toml, crates/testing_macros/src/lib.rs
testing_macros:
- Skip generating test functions if cargo feature `rust-analyzer` is enabled.
=> chore: Make `rust-analyzer` faster

.npmignore
This is chore for the aesthetics  to exclude few more non-runtime files from the pkg. 
if you peek latest pkg https://unpkg.com/browse/@swc/core@1.2.117/ there are few non-required files are packed in pkg tarball.
In a long run, I'd like to suggest to use allowlist instead - see examples at https://github.com/ReactiveX/rxjs/blob/master/package.json#L209-L227
This'll allow explicit list of files to be included pkg.
=> build(package): update exclude list for the pkg

node-swc/src/types.ts
Closes #2967.
`baseUrl` and `paths` first being introduced in swc back in #2227, being fixed in #2712. But only `paths` added to the type definition.
=> fix(node-swc/types): add missing baseUrl to JscConfig

crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs, crates/swc_ecma_transforms_compat/src/es2022/class_properties/private_field.rs
Continuing https://github.com/swc-project/swc/issues/2370.
This PR refactors class_properties. As first part, updates private_field first. PR tries straightforward update as much, not touching existing logics.
=> refactor(es/transforms/compat): visit_mut for class_prop:private_field

node-swc/src/types.ts
https://play.swc.rs/?version=1.2.115&code=H4sIAAAAAAAAA0utKMgvKlGodsvPV0gsVnBKLKrl4kpFCBrVAgDstLzyIgAAAA%3D%3D&config=H4sIAAAAAAAAA0VOOw7DIAy9i%2BcMbcbcoYdA1ImI%2BMl2qiLE3WsQVTa%2FvyucbGGrkA0xUr%2B4RDFf2EBKRrbkssACwkrtxjM2BYYOFLUgr4%2F1qbJPiXEaFgguur30MptCJmS%2BJRMP%2F3c27QrpfXWijj3t1EhI8WRod9EMO35Nt9ClGONnBMc7ugHQ2g%2FWQohQ0gAAAA%3D%3D
=> type(node-swc): `exported` field could be null for `NamedExportSpecifier`

.github/workflows/cargo.yml, .github/workflows/integration.yml
context: https://discord.com/channels/889779439272075314/889780890098610176/919288953490780181
To workaround the recent CI flaky failure caused by npm pkg installation, I tried pnp. It was mostly working, but some of bundler-related tests expected physical layout of node_modules to resolve its deps.
This PR instead took easy win by setting up dep cache supported by gh actions by default: https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
If we're lucky global cache may reduce network related failures.
=> ci(actions): setup yarn cache

crates/swc_ecma_codegen/src/text_writer/basic_impl.rs
swc_ecma_codegen:
- Compute line starts in multi-line comments.
- Closes https://github.com/swc-project/swc/issues/3013
=> fix(es/codegen): Fix sourcemap bug related to multi-line comments

.github/workflows/cargo.yml, crates/swc_ecma_parser/Cargo.toml, crates/swc_ecma_parser/src/lib.rs, crates/swc_ecma_parser/src/parser/expr/verifier.rs, crates/swc_ecma_parser/tests/jsx.rs, crates/swc_ecma_parser/tests/test262.rs
- Make dependency on `swc_ecma_visit` optional.
=> refactor(es/parser): Make some verification logic optional

crates/swc/tests/tsc-references/jsx/tsxReactEmitEntitiesx/input.tsx/es2015.1.normal/output.js, crates/swc/tests/tsc-references/jsx/tsxReactEmitEntitiesx/input.tsx/es2015.2.minified/output.js, crates/swc/tests/tsc-references/jsx/tsxReactEmitEntitiesx/input.tsx/es5.1.normal/output.js, crates/swc/tests/tsc-references/jsx/tsxReactEmitEntitiesx/input.tsx/es5.2.minified/output.js, crates/swc_ecma_parser/src/lexer/util.rs, crates/swc_ecma_parser/src/lib.rs, crates/swc_ecma_parser/src/parser/mod.rs, crates/swc_ecma_parser/src/parser/typescript.rs, crates/swc_ecma_parser/tests/typescript/issue-2896/input.tsx, crates/swc_ecma_parser/tests/typescript/issue-2896/input.tsx.json
- Share backtracking state with the lexer.
- Don't report lexing errors while backtracking (Closes #2896)
=> fix(es/lexer): Don't report lexer errors while backtracking

crates/swc_ecma_transforms_compat/src/es2015/block_scoping.rs, crates/swc_ecma_transforms_compat/tests/es2015_block_scoping.rs
This PR attempts to fix #2998 by assigning a new ident if same one found in loop nodes. To avoid re-renaming loop node's init, PR introduces new flag to let visit_mut_var_decl indicate if it's in loop's body or not and only reassign new ident in loop body and there are existing ident.
- closes #2998
=> test(es/transforms/compat): update test cases for block_scoping

crates/swc/tests/fixture/issue-3073/1/input/.swcrc, crates/swc/tests/fixture/issue-3073/1/input/index.ts, crates/swc/tests/fixture/issue-3073/1/output/index.ts, crates/swc/tests/fixture/issue-3073/2/input/.swcrc, crates/swc/tests/fixture/issue-3073/2/input/index.ts, crates/swc/tests/fixture/issue-3073/2/output/index.ts, crates/swc_ecma_transforms_typescript/src/strip.rs, crates/swc_ecma_transforms_typescript/tests/fixture/issue-3073/1/input.ts, crates/swc_ecma_transforms_typescript/tests/fixture/issue-3073/1/output.js, crates/swc_ecma_transforms_typescript/tests/fixture/issue-3073/2/input.ts, crates/swc_ecma_transforms_typescript/tests/fixture/issue-3073/2/output.js, crates/swc_ecma_transforms_typescript/tests/fixture/issue-3073/3/input.ts, crates/swc_ecma_transforms_typescript/tests/fixture/issue-3073/3/output.js, crates/swc_ecma_transforms_typescript/tests/fixture/issue-3073/4/input.ts, crates/swc_ecma_transforms_typescript/tests/fixture/issue-3073/4/output.js
=> fix(ecma/transform): export destructured properties in TypeScript namespace

crates/swc_bundler/examples/bundle.rs, crates/swc_ecma_loader/src/resolvers/node.rs
swc_ecma_loader:
- Check for `module` field and prefer it over `main`.
=> fix(es/loader): Prefer ESM

.github/workflows/publish-node.yml, .gitignore, .npmignore, scripts/cli_artifacts.sh, scripts/npm/android-arm64/package.json, scripts/npm/darwin-arm64/package.json, scripts/npm/darwin-x64/package.json, scripts/npm/freebsd-x64/package.json, scripts/npm/linux-arm-gnueabihf/package.json, scripts/npm/linux-arm64-gnu/package.json, scripts/npm/linux-arm64-musl/package.json, scripts/npm/linux-x64-gnu/package.json, scripts/npm/linux-x64-musl/package.json, scripts/npm/win32-arm64-msvc/package.json, scripts/npm/win32-ia32-msvc/package.json, scripts/npm/win32-x64-msvc/package.json
This PR continues CLI implementation, update publish script to each platform specific optional dep to include cli binary as well. Main entrypoint (@swc/cli) and optional dep doesn't point to those binary yet, so this is safe from any breaking changes. 
To conform with existing artifact packaging I did small bend over to copy release binary into specific platform path side by side to node bindings.
- https://github.com/swc-project/swc/issues/1589
=> ci(actions): include swc_cli into optional deps package

Cargo.lock, crates/swc_ecma_ast/Cargo.toml, crates/swc_ecma_ast/src/ident.rs, crates/swc_ecma_transforms_compat/src/es2015/classes/mod.rs, crates/swc_ecma_transforms_compat/tests/fixture/classes/issue-3106/1/exec.js
swc_ecma_ast:
- Add `Ident::verify_symbol`.
- Don't generate invalid identifiers. (Closes #3106)
=> fix(es/compat): Fix `classes` pass

node-swc/src/binding.js
There are linux environments where LDD does not exist (for example, think of a `node` binary that is linked statically and it built `FROM scratch`)
In order to support those environments, in case `LDD` doesn't exist, the code will use the `gnu` binary.
=> fix(binding): recover on non existing ldd

Cargo.lock, crates/swc_ecma_preset_env/Cargo.toml
- Added support of querying `cover 99% in XX`
- This release contains a notable fix about WebAssembly support, because previous versions broke the playground.
=> feat(es/preset-env): Upgrade `browserslist-rs`

crates/swc/tests/fixture/iissue-2118/input/.swcrc, crates/swc/tests/fixture/iissue-2118/input/index.js, crates/swc/tests/fixture/iissue-2118/output/index.js, crates/swc_ecma_preset_env/tests/fixtures/corejs3/usage-determanated-instance-methods/output.mjs, crates/swc_ecma_utils/src/lib.rs
- Fix `is_valid_ident`. (Closes #2118)
=> fix(es/utils): Fix `is_valid_ident`

crates/node/src/lib.rs, crates/swc/tests/fixture/issue-2108/input/.swcrc, crates/swc/tests/fixture/issue-2108/input/index.js, crates/swc/tests/fixture/issue-2108/output/index.js, crates/swc_ecma_transforms_optimization/src/simplify/inlining/mod.rs, crates/swc_ecma_transforms_optimization/src/simplify/inlining/scope.rs
swc_ecma_transforms_optimization:
- `inlining`: Mark all usages as modification. (Closes #2108)
=> fix(es/optimization): Fix inlining

crates/swc_ecma_codegen/tests/fixture/issues/3110/input.js, crates/swc_ecma_codegen/tests/fixture/issues/3110/output.js, crates/swc_ecma_codegen/tests/fixture/issues/3110/output.min.js, crates/swc_ecma_parser/src/parser/stmt/module_item.rs, crates/swc_ecma_parser/tests/typescript/import-assertions/stmt/test2/input.ts, crates/swc_ecma_parser/tests/typescript/import-assertions/stmt/test2/input.ts.json, crates/swc_ecma_transforms_proposal/tests/import_assertions.rs
* Support import assertions in specifier-less imports.
swc_ecma_codegen:
* Add tests for codegen of import assertions in specifier-less imports.
swc_ecma_transforms_proposal:
* Add tests for stripping import assertions in specifier-less imports.
Specifier-less import assertions are not currently supported by the parser, even though the spec proposal allows them.
None
Fixes #3103.
=> fix(es/parser): Support import assertions in specifier-less imports

crates/swc/tests/tsc-references/typeofOperatorWithAnyOtherType_es5.2.minified.js, crates/swc/tests/tsc-references/typeofOperatorWithBooleanType_es5.2.minified.js, crates/swc/tests/tsc-references/typeofOperatorWithNumberType_es5.2.minified.js, crates/swc/tests/tsc-references/typeofOperatorWithStringType_es5.2.minified.js, crates/swc_ecma_minifier/src/compress/optimize/ops.rs, crates/swc_ecma_minifier/tests/compress/fixture/issues/2257/full/output.js, crates/swc_ecma_minifier/tests/compress/fixture/issues/lit_comparisons/config.json, crates/swc_ecma_minifier/tests/compress/fixture/issues/lit_comparisons/input.js, crates/swc_ecma_minifier/tests/compress/fixture/issues/lit_comparisons/output.js
Description:
optimize_lit_cmp does not compare `number` and `string` correctly.
input
```js
const a = 3;
const b = 4;
const c = "3";
const d = "4";
const e = {};
const f = {};
const g = true;
const h = false;
const j = null;
console.log(a === b, c === d, e === f, g === h, h === j);
```
previous out
```js
const a = 3;
const b = 4;
const c = "3";
const d = "4";
const e = {};
const f = {};
const g = true;
const h = false;
const j = null;
console.log(true, true, true, false, false);
```
current out
```js
const a = 3;
const b = 4;
const c = "3";
const d = "4";
const e;
const f;
const g = true;
const h = false;
const j = null;
console.log(false, false, false, ({}) === {}, false);
```
=> fix(es/minifier): obj, num and str comparison

Cargo.lock, crates/swc/Cargo.toml, crates/swc/src/config/mod.rs, crates/swc/src/plugin.rs, crates/swc_macros_common/Cargo.toml, crates/swc_plugin_runner/Cargo.toml, crates/swc_plugin_runner/src/lib.rs, crates/swc_plugin_runner/src/resolve.rs, crates/swc_plugin_runner/tests/integration.rs, deny.toml
This PR is part 1 of #3167. PR contains a minimal set of changes, including
- deprecates abi_stable usage (in swc/plugins)
- revise plugin_runner to load wasm binary with cache support.
PR doesn't run actual transforms from loaded binary yet, only `loading` and compiling part are included.
Techinically this is breaking changes to abi_stable based plugin, but under experimental flag we expected that'll occur.
#3167
=> refactor(swc/plugins): load wasm plugin with cache (#3167 part 1)

Cargo.lock, crates/swc_ecma_dep_graph/Cargo.toml, crates/swc_ecma_dep_graph/src/lib.rs
This makes the `DependencyDescriptor` interface a little less error prone by combining `import_assertions` with `dynamic_import_assertions`.
**BREAKING CHANGE:** Combines `dynamic_import_assertiosn` with `import_assertions` in `DependencyDescriptor`
**Related issue (if exists):** https://github.com/swc-project/swc/issues/3137
Closes #3137
=> feat: improve DependencyDescriptor to combine import_assertions with dynamic_import_assertions

.github/workflows/publish-node.yml, Cargo.lock, Cargo.toml
Deployment of `swc` is failing because the thread-local storage size is too big.
I used methods in https://fasterthanli.me/articles/a-dynamic-linker-murder-mystery to debug it.
I found that `cranelift-codegen` is using too much thread-local storage space.
=> chore(ci): Fix publish script

crates/swc_ecma_minifier/src/compress/drop_console.rs, crates/swc_ecma_minifier/src/compress/pure/if_return.rs, crates/swc_ecma_minifier/src/compress/pure/mod.rs, crates/swc_ecma_minifier/tests/compress/fixture/issues/2257/full/output.js, crates/swc_ecma_minifier/tests/compress/fixture/issues/3173/1/input.js, crates/swc_ecma_minifier/tests/compress/fixture/issues/3173/1/output.js, cspell.json
- `pure`: Drop unreachable statements. (Closes #3173)
=> fix(es/minifier): Drop unreachable statements eagerly

crates/swc_ecma_ast/src/lib.rs
Hello.
Updated the `EsVersion::latest()` method to return `EsVersion::Es2022`.
Latest ECMAScript version set to 2022.
Best wishes,
Sergey.
=> feat: update `EsVersion::latest()` to `EsVersion::Es2022`

crates/swc_css_parser/src/lexer/mod.rs
resolve todo, first todo was due problems with spaces around legacy `url` parsing, now we avoid `reset_to`, and just use `last_pos` (it was design for this goals) and it should be faster
No
No
=> fix: resolve todo

crates/swc_ecma_minifier/src/compress/mod.rs, crates/swc_ecma_minifier/src/eval.rs, crates/swc_ecma_transforms_optimization/src/simplify/expr/mod.rs, crates/swc_ecma_transforms_optimization/src/simplify/expr/tests.rs
After removing the `preserve_string_call` setting, `ExprSimplifierConfig` is actually empty now. Not sure if that should be removed as well or left as is
The API changed did change..
Closes https://github.com/swc-project/swc/issues/3283
=> fix(es/transforms): Remove unsafe `new String("...")` optimization

crates/swc_ecma_minifier/src/analyzer/mod.rs, crates/swc_ecma_minifier/tests/compress/fixture/issues/3256/1/input.js, crates/swc_ecma_minifier/tests/compress/fixture/issues/3256/1/output.js, crates/swc_ecma_minifier/tests/compress/fixture/issues/3256/2/input.js, crates/swc_ecma_minifier/tests/compress/fixture/issues/3256/2/output.js, crates/swc_ecma_minifier/tests/projects/output/jquery-1.9.1.js
- Mark update as usage and assignment. (Closes #3265)
=> fix(es/minifier): Fix analysis of unary expressions

crates/swc_bundler/src/bundler/chunk/cjs.rs, crates/swc_bundler/src/bundler/keywords.rs, crates/swc_bundler/src/inline.rs, crates/swc_ecma_minifier/src/compress/optimize/util.rs, crates/swc_ecma_minifier/src/compress/util/mod.rs, crates/swc_ecma_minifier/src/metadata/mod.rs, crates/swc_ecma_minifier/src/pass/hygiene/vars.rs, crates/swc_ecma_minifier/src/pass/mangle_names/preserver.rs, crates/swc_ecma_minifier/src/util/mod.rs, crates/swc_ecma_transforms_base/src/helpers/mod.rs, crates/swc_ecma_transforms_base/src/hygiene/usage_analyzer.rs, crates/swc_ecma_transforms_base/src/resolver/mod.rs, crates/swc_ecma_transforms_base/tests/fixture.rs, crates/swc_ecma_transforms_base/tests/ts_resolver.rs, crates/swc_ecma_transforms_compat/src/es2015/block_scoping.rs, crates/swc_ecma_transforms_compat/src/es2015/regenerator/hoist.rs, crates/swc_ecma_transforms_compat/src/es2022/class_properties/private_field.rs, crates/swc_ecma_transforms_compat/src/es2022/private_in_object.rs, crates/swc_ecma_transforms_compat/src/reserved_words.rs, crates/swc_ecma_transforms_optimization/src/inline_globals.rs, crates/swc_ecma_transforms_optimization/src/simplify/const_propgation.rs, crates/swc_ecma_transforms_optimization/src/simplify/inlining/mod.rs, crates/swc_ecma_transforms_react/src/jsx/mod.rs, crates/swc_ecma_transforms_typescript/src/strip.rs, crates/swc_ecma_utils/src/function/fn_env_hoister.rs, crates/swc_ecma_utils/src/lib.rs, crates/swc_ecma_visit/src/lib.rs, crates/swc_webpack_ast/src/reducer/mod.rs
There're lots of code like this in swc
```rust
visit_member_prop() {
obj.visit_with(self);
if let MemeberProp::Computed(c) = &e.prop {
c.visit_with(self)
}
}
```
this pr add a macro to simplify it
=> reface(ecma): add `visit_obj_and_computed` macro

crates/swc_css_ast/src/style_rule.rs, crates/swc_css_ast/src/value.rs, crates/swc_css_codegen/src/lib.rs, crates/swc_css_parser/src/parser/style_rule.rs, crates/swc_css_parser/src/parser/value/mod.rs, crates/swc_css_parser/tests/fixture.rs, crates/swc_css_parser/tests/fixture/at-rule/unknown/span.rust-debug, crates/swc_css_parser/tests/fixture/declaration/output.json, crates/swc_css_parser/tests/fixture/declaration/span.rust-debug, crates/swc_css_parser/tests/fixture/esbuild/misc/L0mEf41IMkWcP7NotllkAg/span.rust-debug, crates/swc_css_parser/tests/fixture/esbuild/misc/_-29x4xnx6IaJMmYrOsypA/span.rust-debug, crates/swc_css_parser/tests/fixture/rome/calc/output.json, crates/swc_css_parser/tests/fixture/rome/calc/span.rust-debug, crates/swc_css_parser/tests/fixture/rome/grid/repeat/line-name/output.json, crates/swc_css_parser/tests/fixture/rome/grid/repeat/line-name/span.rust-debug, crates/swc_css_parser/tests/fixture/rome/grid/repeat/multi-values/output.json, crates/swc_css_parser/tests/fixture/rome/grid/repeat/multi-values/span.rust-debug, crates/swc_css_parser/tests/fixture/value/square-brackets/output.json, crates/swc_css_parser/tests/fixture/value/square-brackets/span.rust-debug, crates/swc_css_visit/src/lib.rs
Refactor from https://github.com/swc-project/swc/pull/2922/, start to union all blocks in `SimpleBlock` https://www.w3.org/TR/css-syntax-3/#consume-simple-block, i.e. all things in `{}`/`()`/`[]` is `SimpleBlock`.
Next things:
- Refactor `@page` at-rule, because we use `Block` here and it is invalid, there are bugs in parsing
- Union `Block` and `SimpleBlock`
Yes, we union all in `SimpleBlock`
No
=> Refactor block

crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/tests/golden.txt, crates/swc_ecma_minifier/tests/ignored.txt, crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/collapse_vars_array/output.js
- `sequences`: Implement more rule for array literals.
<details>
<summary>
Bug 1 (fixed)
</summary>
```
INFO [SWC_RUN]
var a = {};
(function(global) {
function fail(o) {
var result = {};
function inner() {
return outer({
one: o.one,
two: o.two
});
}
result.inner = function() {
return inner();
};
return result;
}
function outer(o) {
var ret;
if (o) {
ret = o.one;
} else {
ret = o.two;
}
return ret;
}
global.fail = fail;
})(a);
var b = a.fail({
one: "PASS"
});
console.log(b.inner());
PASS
at crates/swc_ecma_minifier/src/debug.rs:120
in compress ast
in minify
INFO Done in 255.375µs, kind: "perf"
at crates/swc_timer/src/lib.rs:32
in analyze
in optimize with , pass: 0
in compress ast
in minify
DEBUG ===== Start =====
var a = …
```
=> feat(es/minifier): Handle array literals in `sequences`

crates/swc/tests/tsc-references/arrowFunctionExpressions_es5.2.minified.js, crates/swc/tests/tsc-references/exportCodeGen_es5.2.minified.js, crates/swc/tests/tsc-references/genericCallToOverloadedMethodWithOverloadedArguments_es2015.2.minified.js, crates/swc/tests/tsc-references/genericCallToOverloadedMethodWithOverloadedArguments_es5.2.minified.js, crates/swc_ecma_minifier/src/compress/optimize/iife.rs, crates/swc_ecma_minifier/src/compress/optimize/mod.rs
- Add some assertions for injections.
- Fix prepend/append logic of statements.
=> fix(es/minifier): Prepend/append correctly

crates/swc_ecma_transforms_module/src/util.rs, crates/swc_ecma_transforms_module/tests/common_js.rs
```js
import { foo }from 'bar';
import(foo);
```
to 
```js
var _bar = require("bar");
Promise.resolve().then(function() {
return _interopRequireWildcard(require(_bar.foo)); // not return _interopRequireWildcard(require(foo));
});
```
babel generates like 
```js
Promise.resolve("" + _bar.foo).then(function (s) {
return _interopRequireWildcard(require(s));
});
```
But I think they work the same.
fix #3246
=> fix(ecma): dynamic import with name from another import

crates/swc_css_ast/src/at_rule/media.rs, crates/swc_css_codegen/src/lib.rs, crates/swc_css_codegen/tests/fixture/at-rules/media/3/input.css, crates/swc_css_codegen/tests/fixture/at-rules/media/3/output.css, crates/swc_css_codegen/tests/fixture/at-rules/media/3/output.min.css, crates/swc_css_parser/src/parser/at_rule.rs, crates/swc_css_parser/tests/fixture/at-rule/media/input.css, crates/swc_css_parser/tests/fixture/at-rule/media/output.json, crates/swc_css_parser/tests/fixture/at-rule/media/span.rust-debug, crates/swc_css_visit/src/lib.rs
Bugfix - empty `@media {}`
Yes, type changed
No
=> fix: empty `@media` parsing

crates/swc/tests/fixture/jest/sourcemap-1/input/.swcrc, crates/swc/tests/fixture/jest/sourcemap-1/input/index.ts, crates/swc/tests/fixture/jest/sourcemap-1/output/index.ts, crates/swc_ecma_transforms_module/src/util.rs
swc_ecma_transforms_module:
- `common_js`: Use original span with the syntax conext of an import specifier.
- Closes #3416
=> fix(es/modules): Fix span of imports

crates/swc_ecma_transforms_base/src/fixer.rs
swc generates broken result from the following input.
[REPL](https://play.swc.rs/?version=1.2.136&code=H4sIAAAAAAAAA0vOSSwuVnDLz1dIrShJzUspVtBwSixSsFVIBktU12oCMRdXMkyZEaq6mhqcKo1RVaqp4VRpgqrS3h6nSlOEypKi0lQFewWQBisgWQVWCQBaJNOTzgAAAA%3D%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1F8WLLnKHHkK4SnDxD0mBGuO71w4u2Q0zb16DjzjYGhRkIZ5JalL8wgbkIopjXxTMwEa1YxDqBhT5IJ2I2Ie1Yw45Cy3AQPTJ73XKXI6FSeSeMB3hT%2Fbhivl9zqKB1kKX8wn9dqyfl9cClU%2FqPxrFaXe4AAAA)
```javascript
class Foo extends (Bar = class {}) {}
class Foo2 extends (Bar ||= class {}) {}
class Foo3 extends (Bar &&= class {}) {}
class Foo4 extends (Bar ??= class {}) {}
class Foo5 extends (true ? Bar : Baz) {}
```
=> fix(es/fixer): handle more extends expr

crates/swc_css_ast/src/style_rule.rs, crates/swc_css_codegen/src/lib.rs, crates/swc_css_codegen/tests/fixture.rs, crates/swc_css_codegen/tests/fixture/declaration/important/input.css, crates/swc_css_codegen/tests/fixture/declaration/important/output.css, crates/swc_css_codegen/tests/fixture/declaration/important/output.min.css, crates/swc_css_parser/src/parser/style_rule.rs, crates/swc_css_parser/tests/errors/custom-properties/exclamation/output.stderr, crates/swc_css_parser/tests/errors/important/basic/output.stderr, crates/swc_css_parser/tests/fixture.rs, crates/swc_css_parser/tests/fixture/at-rule/import/output.json, crates/swc_css_parser/tests/fixture/at-rule/import/span.rust-debug, crates/swc_css_parser/tests/fixture/at-rule/supports/output.json, crates/swc_css_parser/tests/fixture/at-rule/supports/span.rust-debug, crates/swc_css_parser/tests/fixture/important/basic/input.css, crates/swc_css_parser/tests/fixture/important/basic/output.json, crates/swc_css_parser/tests/fixture/important/basic/span.rust-debug, crates/swc_css_parser/tests/fixture/rome/keyframe/output.json, crates/swc_css_parser/tests/fixture/rome/keyframe/span.rust-debug, crates/swc_css_parser/tests/fixture/value/custom-property/output.json, crates/swc_css_parser/tests/fixture/value/custom-property/span.rust-debug, crates/swc_css_parser/tests/recovery/declaration/output.swc-stderr, crates/swc_css_parser/tests/recovery/delim-token/bang/output.swc-stderr, crates/swc_css_visit/src/lib.rs, crates/swc_stylis/src/prefixer.rs
Fix AST of `!important`, because `important` work is identifier we should use Ident AST node here, also it allows to parse and keep how important was written
Yes
No
=> Fix `!important` ast

crates/swc_css_ast/src/selector.rs, crates/swc_css_codegen/src/lib.rs, crates/swc_css_parser/src/parser/mod.rs, crates/swc_css_parser/src/parser/selector/mod.rs, crates/swc_css_parser/tests/fixture.rs, crates/swc_css_visit/src/lib.rs
Refactor code - remove `AtSelector`, no grammar for `@` in selector spec, we use it before for parsing nested at-rules in `@page`, but now we refactor code and don't need it anymore
Yes
No
=> refactor: remove unused code

crates/swc_ecma_parser/src/error.rs, crates/swc_ecma_parser/src/parser/util.rs, crates/swc_ecma_parser/tests/test262-error-references/fail/0eb4ed330b5d7e2f.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/12a3250154ea8ef5.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/15de970e269ae56f.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/168502012959421f.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/23368c25ea374e2f.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/2884c585d2f035a5.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/2e8378f658290622.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/3a3e59edfed719b0.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/4f0b15bd78646107.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/581bedbbce2541be.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/5ab1050053c11514.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/66abd1d09c28ada8.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/75b52e0f57aab958.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/783aeb8c90c3775d.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/851bfeb09635c752.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/939b16a89d0e8704.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/95682e688db64065.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/a793dd27762c8ec8.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/a8beb1480f385441.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/ab9d14c2ef38f180.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/d012888b0c720723.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/dc14ac854168468f.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/dfc6f1cc5533e0bb.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/f4c0cdc8d5782f3f.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/f51aea0352bb03f3.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/f6cc48c72caf2e32.js.stderr
Only identifier and property access is valid assignment target
No
=> fix(ecma/parser): disallow opt chain as assign target

crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs, crates/swc_ecma_transforms_compat/tests/es2015_destructuring.rs
Similar to #3433 but without default value.
Input([REPL](https://play.swc.rs/?version=1.2.139&code=H4sIAAAAAAAAA0vOzysuUYiuiFWwVYjWiQUAmTwjhw8AAAA%3D&config=H4sIAAAAAAAAA0WOSw7DIAwFr1J5zaKbdJE79BCIOikVP9mkKkLcPQZRZWf7zRu5wocNrBWSJkbqE5eQ9Q9WQOM1G7IpgxJMTpt2jE1B1rRj7ggvkrkYGWeqwNtgt9JNJvpEyHxFOuzuTzYR%2Bfg6%2BqFCLgmH8AHtcsye5ecEMx2yY%2FiOznhD9GDeFD3elju0dgI3ydbB0wAAAA%3D%3D)):
```javascript
const [x] = [,];
```
swc output:
```javascript
const x;
```
=> fix(es/compat): fix const array destructing with init hole

crates/swc_css_ast/src/value.rs, crates/swc_css_parser/src/parser/value/mod.rs, crates/swc_css_parser/tests/errors/rome/invalid/fit-content/invalid-call/output.stderr, crates/swc_css_parser/tests/errors/rome/invalid/grid/repeat/unclosed-lint-name/output.stderr, crates/swc_css_parser/tests/errors/rome/invalid/min-or-max/output.stderr, crates/swc_css_parser/tests/fixture/function/mix/input.css, crates/swc_css_parser/tests/fixture/function/mix/output.json, crates/swc_css_parser/tests/fixture/function/mix/span.rust-debug, crates/swc_css_visit/src/lib.rs
Fix `;` is delim in new spec, example - https://www.w3.org/TR/css-values-4/#interpolate
yes, new types
no
=> fix: semicolon is delim in new spec

crates/swc/tests/fixture/new-target/output/class-extends-error.ts, crates/swc/tests/tsc-references/newTarget.es5_es5.1.normal.js, crates/swc/tests/tsc-references/newTarget.es5_es5.2.minified.js, crates/swc/tests/tsc-references/newTarget.es6_es5.1.normal.js, crates/swc/tests/tsc-references/newTarget.es6_es5.2.minified.js, crates/swc_ecma_transforms_compat/src/es2015/mod.rs
A proper fix is impossible, since the only other way to get `new.target` is by `this.constructor`, however in this situation any access to `this` would throw an error. The following code would also generate wrong output
```js
class A {
constructor() {
Object.setPrototypeOf(this, null)
console.log(new.target)
}
}
```
But consider original issue, apply `new.target` transform later would generate correct result because after class transformation, access `this` in normal function would not throw. If `new.target` is applied first, `this` would be transpiled to `_this` in `classes` which would be `undefined`. The result is **technically incorrect**, but there's no better way. Babel behaves the same, and so does in current swc's `preset-env`
fixes …
=> fix(ecma/transform/compat): apply `new.target` before `classes`

crates/swc_ecma_transforms_compat/src/es2015/parameters.rs, crates/swc_ecma_transforms_compat/tests/es2015_parameters.rs
=> fix(ecma/transform/compat): arrow parameters in class field

Cargo.lock, crates/swc_plugin/Cargo.toml, crates/swc_plugin/src/handler.rs, tests/rust-plugins/swc_internal_plugin/Cargo.lock
Minor refactor to use reexport onceCell from swc_common instead of direct dependency.
=> refactor(swc/plugin): remove direct dep to oncecell

crates/swc_css_codegen/tests/fixture.rs, crates/swc_css_codegen/tests/fixture/preserved-token/input.css, crates/swc_css_codegen/tests/fixture/preserved-token/output.css, crates/swc_css_codegen/tests/fixture/preserved-token/output.min.css, crates/swc_css_parser/src/parser/value/mod.rs, crates/swc_css_parser/tests/errors/rome/invalid/min-or-max/output.stderr, crates/swc_css_parser/tests/recovery/delim-token/minus/output.json, crates/swc_css_parser/tests/recovery/delim-token/plus/output.json, crates/swc_css_parser/tests/recovery/function/output.json, crates/swc_css_parser/tests/recovery/ie-progid/output.json, crates/swc_css_parser/tests/recovery/vercel/002/input.css, crates/swc_css_parser/tests/recovery/vercel/002/output.json, crates/swc_css_parser/tests/recovery/vercel/002/output.swc-stderr
Fix recovery mode for `function` (regression in next.js)
Ideally we should refactor this logic more and consume components values firstly, when try to resolve to `Vec<Value>`, if failed keep them as is, if not failed apply `Vec<Value>` nodes, but it requires more refactor and can take a time (I will focus on it in this week, so we will not have such regressions in future)
No
No
=> fix: recovery mode for function

Cargo.lock, crates/better_scoped_tls/Cargo.toml, crates/better_scoped_tls/README.md, crates/better_scoped_tls/src/lib.rs, crates/swc_common/Cargo.toml, crates/swc_common/src/errors/mod.rs, crates/swc_common/src/syntax_pos.rs, crates/swc_ecma_transforms_base/Cargo.toml, crates/swc_ecma_transforms_base/src/helpers/mod.rs, crates/swc_estree_ast/Cargo.toml, crates/swc_estree_ast/src/flavor.rs
`scoped-tls` is used various places in swc, but it does not provides meaningful error message on wrong usages.
```
cannot access a scoped thread local variable without calling set first
```
This is all of the error messages. This is not useful, so I created a new wrapper crate, which panics with
```
You should perform this operation in the closure passed to `set` of better_scoped_tls::tests::TESTTLS
```
Note that this wrapper is actually noop on release builds. It will still panic with a bad error message on release builds.
=> feat(api/rust): Improve error messages for wrong usages of scoped thread-local variables

.husky/pre-push, Cargo.lock, crates/swc_common/Cargo.toml, crates/swc_ecma_codegen/Cargo.toml, crates/swc_ecma_preset_env/Cargo.toml, crates/swc_ecma_preset_env/tests/test.rs, crates/swc_plugin_runner/Cargo.toml
git/push-hook:
- Allow skipping `cargo clippy` while pushing.
=> build(swc): Remove unused dependencies

.cargo/config.toml
This PR attempts to try new linker for the builds. As first step, replaces x64 windows build to use lld. Instead of using separate llvm installation for lld which can be verbose to setup this uses out-of-the box lld comes with rustc.
Consider this as an expriment, this may not improve performance drastically. Guess we can try & see.
- https://github.com/swc-project/swc/discussions/3637
=> build(cargo): use lld for win x64 build

crates/swc/tests/projects.rs, crates/swc_ecma_transforms_typescript/src/strip.rs
In fixing issue https://github.com/swc-project/swc/issues/1869 in PR https://github.com/swc-project/swc/pull/1950, class-name identifiers of decorated
classes were renamed to the `_class` hard-coded identifier.
https://github.com/swc-project/swc/pull/1950/files#diff-aee7604a9d35c517e7e1637b34d66b7ce8de17cc407ba6236d314471d00d4b5eR265-R267
For decorated classes, the generated code is a class expression
This makes sense for static attributes of decorated classes, since the
generated code is a class expression, such that
```js
@dec
class TestClass {}
```
would produce, roughly:
```js
var _class;
let TestClass = _class = dec(_class = class TestClass {})
```
In function expressions, the right-hand class is only available within
the class block.
Adding static properties would show the issue: …
=> Fix: Issue 2224

crates/swc/src/config/mod.rs, crates/swc_ecma_transforms_module/src/amd.rs, crates/swc_ecma_transforms_module/src/common_js.rs, crates/swc_ecma_transforms_module/src/lib.rs, crates/swc_ecma_transforms_module/src/path.rs, crates/swc_ecma_transforms_module/src/umd.rs, crates/swc_ecma_transforms_module/src/util.rs
We don't need to store the code for transforming modules twice.
- https://github.com/swc-project/swc/pull/3741
=> perf(es/modules): Reduce usage of generics

.gitignore, Cargo.lock, crates/node/src/util.rs, crates/swc/src/plugin.rs, crates/swc_ecma_transforms_compat/Cargo.toml, crates/swc_plugin_runner/Cargo.toml, crates/swc_plugin_runner/src/lib.rs
Finally, I can connect the pieces together. 🎉 
One of the major reason I tried to push forward runtime tracing support is to diagnost user-level execution. Plugin is an exact fit, I wanted to have some answers like `swc is being slow cause plugin xxxx taking too long`. I added initial trace for those in this PR.
This tells us
- What plugin module takes X time for total execution
- Serialization cost (loading, json serialization for config, context..)
- Actual plugin transformation cost
and we can add more gradually.
=> feat(swc/plugin): support trace for plugin execution

crates/swc_ecma_dep_graph/src/lib.rs
I'd like to port [depcheck](https://github.com/depcheck/depcheck) using swc. I found `analyze_dependencies` in `swc_ecma_dep_graph` crate. Depcheck has the [test](https://github.com/depcheck/depcheck/blob/3d1a45fe8ceb4d7d38c34e99d61b327aa97f65d3/test/fake_modules/typescript/index.ts#L1) which checks [TsImportEqualsDecl](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require). But now `DependencyCollector` doesn't impl `visit_ts_import_equals_decl`. 
I'm not sure about correct names for new `DependencyKind` variants and  `kind` for `DependencyDescriptor` in `visit_ts_import_equals_decl`.
Thank you for your work :)
=> feat(es/dep-graph): add TsImportEqualsDecl for DependencyCollector

crates/swc_css_lints/src/rule.rs, crates/swc_css_lints/src/rules/at_rule_no_unknown.rs, crates/swc_css_lints/src/rules/block_no_empty.rs, crates/swc_css_lints/src/rules/color_hex_length.rs, crates/swc_css_lints/src/rules/color_no_invalid_hex.rs, crates/swc_css_lints/src/rules/declaration_no_important.rs, crates/swc_css_lints/src/rules/keyframe_declaration_no_important.rs, crates/swc_css_lints/src/rules/mod.rs, crates/swc_css_lints/src/rules/no_empty_source.rs, crates/swc_css_lints/src/rules/no_invalid_position_at_import_rule.rs, crates/swc_css_lints/src/rules/selector_max_class.rs, crates/swc_css_lints/src/rules/selector_max_combinators.rs, crates/swc_css_lints/src/rules/unit_no_unknown.rs
Skip running rules that are disabled in config.
It seems no.
=> refactor(css/lints): Skip running rule if disabled

crates/swc_css_lints/src/config.rs, crates/swc_css_lints/src/rules/color_hex_alpha.rs, crates/swc_css_lints/src/rules/mod.rs, crates/swc_css_lints/tests/rules/fail/color-hex-alpha/always/config.json, crates/swc_css_lints/tests/rules/fail/color-hex-alpha/always/input.css, crates/swc_css_lints/tests/rules/fail/color-hex-alpha/always/output.stderr, crates/swc_css_lints/tests/rules/fail/color-hex-alpha/never/config.json, crates/swc_css_lints/tests/rules/fail/color-hex-alpha/never/input.css, crates/swc_css_lints/tests/rules/fail/color-hex-alpha/never/output.stderr, crates/swc_css_lints/tests/rules/pass/color-hex-alpha/always/config.json, crates/swc_css_lints/tests/rules/pass/color-hex-alpha/always/input.css, crates/swc_css_lints/tests/rules/pass/color-hex-alpha/never/config.json, crates/swc_css_lints/tests/rules/pass/color-hex-alpha/never/input.css
Implemented [`color-hex-alpha`](https://stylelint.io/user-guide/rules/list/color-hex-alpha/) rule.
No.
=> feat(css/lints): Add `color-hex-alpha` rule

crates/swc/tests/fixture/issue-2606/1/output/index.ts, crates/swc_ecma_transforms_module/src/common_js.rs, crates/swc_ecma_transforms_module/src/util.rs, crates/swc_ecma_transforms_module/tests/fixture/commonjs/issue-2549/output.js, crates/swc_ecma_transforms_module/tests/fixture/commonjs/issue-2678/output.js, crates/swc_ecma_transforms_module/tests/fixture/commonjs/issue-3843/1/input.js, crates/swc_ecma_transforms_module/tests/fixture/commonjs/issue-3843/1/output.js
=> fix(es/module): Fix `jest.spyOn`

crates/swc_css_lints/src/rules/no_invalid_position_at_import_rule.rs, crates/swc_css_lints/tests/rules/fail/no-invalid-position-at-import-rule/default/at-layer-rule/config.json, crates/swc_css_lints/tests/rules/fail/no-invalid-position-at-import-rule/default/at-layer-rule/input.css, crates/swc_css_lints/tests/rules/fail/no-invalid-position-at-import-rule/default/at-layer-rule/output.stderr, crates/swc_css_lints/tests/rules/pass/no-invalid-position-at-import-rule/default/input.css
According to [spec](https://www.w3.org/TR/css-cascade-5/#at-import), this PR fixes `no-invalid-position-at-import-rule` rule, which allows:
```css
@layer {}
@import "x.css";
```
> Any [@import](https://www.w3.org/TR/css-cascade-5/#at-ruledef-import) rules must precede all other valid at-rules and style rules in a style sheet (ignoring [@charset](https://www.w3.org/TR/css-syntax-3/#at-ruledef-charset) and empty [@layer](https://www.w3.org/TR/css-cascade-5/#at-ruledef-layer) definitions).
No.
=> fix(css/lints): Allow empty `@layer` rule before `@import` rule

crates/swc/src/builder.rs, crates/swc_ecma_minifier/src/lib.rs
Don't invoke `info_marker` if `compress` is `None`.
- Closes #3807
=> fix(es/minifier): Don't remove comments if `compress` is not configured

crates/swc/src/config/mod.rs, crates/swc/tests/fixture/issue-3882/input/.swcrc, crates/swc/tests/fixture/issue-3882/input/types.d.ts, crates/swc/tests/fixture/issue-3882/output/types.d.ts, crates/swc_ecma_parser/src/parser/mod.rs, crates/swc_ecma_parser/src/parser/stmt.rs
=> fix(es/parser): Fix parsing of `const` in ambient context

crates/swc_ecma_transforms_compat/src/bugfixes/async_arrows_in_class.rs, crates/swc_ecma_transforms_compat/src/bugfixes/edge_default_param.rs, crates/swc_ecma_transforms_compat/src/bugfixes/mod.rs, crates/swc_ecma_transforms_compat/src/bugfixes/safari_id_destructuring_collision_in_function_expression.rs, crates/swc_ecma_transforms_compat/src/bugfixes/template_literal_caching.rs, crates/swc_ecma_transforms_compat/src/es3/member_expr_lits.rs, crates/swc_ecma_transforms_compat/src/es3/mod.rs, crates/swc_ecma_transforms_compat/src/es3/prop_lits.rs, crates/swc_ecma_transforms_compat/src/es3/reserved_word.rs
This wraps up initial trace spans for the transforms. May need to add addtional spans for some specific paths, but that's something we need to figure out with testing / feedbacks.
https://github.com/swc-project/swc/issues/3863 is still blocker to enable user testing for this. Once it's resolved, user should be able to try with release build of `@swc/core`. Other features like minifier, bundle, etcs would need traces as well but it looks like we'd better to stablize (especially resolving #3863) before try to add more spans.
=> feat(trace): complete initial trace support for transforms

crates/swc_ecma_parser/src/error.rs
Seems like latest rustc has some regression.
So I reverted rustc upgrade, but it requires some fix of SWC.
- https://github.com/vercel/next.js/pull/35133
- https://github.com/vercel/next.js/runs/5474698598?check_suite_focus=true
=> feat(es/parser): Relax MSRV requirement

Cargo.lock, crates/node/Cargo.toml, crates/swc/Cargo.toml, crates/swc_bundler/Cargo.toml, crates/swc_cli/Cargo.toml, crates/swc_common/Cargo.toml, crates/swc_ecma_codegen/Cargo.toml, crates/swc_ecma_loader/Cargo.toml, crates/swc_ecma_minifier/Cargo.toml, crates/swc_ecma_parser/Cargo.toml, crates/swc_ecma_transforms_base/Cargo.toml, crates/swc_ecma_transforms_compat/Cargo.toml, crates/swc_ecma_transforms_module/Cargo.toml, crates/swc_ecma_transforms_optimization/Cargo.toml, crates/swc_ecma_utils/Cargo.toml, crates/swc_ecma_visit/Cargo.toml, crates/swc_graph_analyzer/Cargo.toml, crates/swc_node_bundler/Cargo.toml, crates/swc_plugin_runner/Cargo.toml, crates/swc_timer/Cargo.toml, crates/swc_webpack_ast/Cargo.toml, crates/testing/Cargo.toml, crates/wasm/Cargo.toml
https://github.com/tokio-rs/tracing/blob/v0.1.x/tracing/CHANGELOG.md#0132-march-8th-2022
> Reduced Drop overhead for disabled spans ([#1974](https://github.com/tokio-rs/tracing/pull/1974))
Related with https://github.com/swc-project/swc/pull/3911, timely upstream update we can try bump & see if it makes diff for us.
=> build(package): bump up tracing

crates/swc/src/config/mod.rs
=> fix(es): Don't create `.swc` if not required

crates/swc_common/src/source_map.rs, crates/swc_common/src/syntax_pos.rs, crates/swc_ecma_codegen/src/text_writer/basic_impl.rs
=> fix(es/codegen): Fix sourcemap issue caused by reserved `BytePos` values

crates/swc_css_codegen/tests/fixture.rs, crates/swc_ecma_lints/src/rules/const_assign.rs, crates/swc_ecma_lints/tests/pass/issue-3956/1/input.ts
=> fix(es/lints): Don't visit types while collecting `const`

.github/workflows/bench.yml, crates/swc/benches/typescript.rs, crates/swc_webpack_ast/benches/webpack_ast.rs
There are few packages we don't need to build run benchmark, updated gh workflow to skip it.
Also, not sure if this is intended or not - but there are failing benchmark cases with `--all`. PR attempts to fix it to run the benchmark properly.
=> build(cargo): skip unnecessary package for the benchmark

Cargo.lock, crates/swc_ecma_minifier/Cargo.toml, crates/swc_ecma_minifier/src/pass/mangle_names/analyzer/mod.rs, crates/swc_ecma_minifier/src/pass/mangle_names/analyzer/scope.rs, crates/swc_ecma_minifier/src/pass/mangle_names/preserver.rs, crates/swc_ecma_minifier/src/pass/mangle_names/rename_map.rs
Description:
- `Id` is treated as integer, as `JsWord` and `SyntaxContext` are both integer.
=> perf(es/minifier): Use fxhash for integers

crates/swc_ecma_minifier/src/pass/mangle_names/analyzer/mod.rs, crates/swc_ecma_minifier/src/pass/mangle_names/analyzer/scope.rs
Currently, we check for child scopes by doing a recursive call, like https://github.com/swc-project/swc/blob/2ad0d801a2a9d84ae2c6df2d15ff8a215f296eec/crates/swc_ecma_minifier/src/pass/mangle_names/analyzer/scope.rs#L112-L114
But this is slow because it results in an enormous amount of calls.
We can optimize this by merging information of child scopes beforehand.
This makes huge difference, so I decided to include this in v1.2.154
=> perf(es/minifier): Merge hashmap for scoping before checking

crates/swc_ecma_minifier/src/util/base54.rs
Description:
We are only using ASCII characters so we can avoid utf8 logics by using `Vec<u8>` as a buffer and converting it into `String` at the end.
=> perf(es/minifier): Use `Vec<u8>` as a buffer for `base54`

.github/workflows/bench.yml, crates/swc_ecma_parser/tests/typescript.rs, crates/testing/src/errors/mod.rs, crates/testing/src/errors/stderr.rs, crates/testing/src/lib.rs, crates/testing/src/string_errors.rs
This will make debugging stack overflow and parser issues easier because it writes to stderrr right away, instead of holding a buffer for it.
=> test(*): Print diagnostics to stderr while testing

packages/swc-helpers/src/_class_private_field_loose_key.js
Should export `default` for `classPrivateFieldLooseKey`
I should have noticed this on previous PR 
No
=> fix(es/helpers): should export `default` for classPrivateFieldLooseKey

crates/swc_ecma_transforms_base/src/helpers/_class_private_field_loose_base.js
Function name was wrong.
- Closes https://github.com/swc-project/swc/issues/4048
=> fix(es/helpers): Fix the name of `_classPrivateFieldLooseBase`

crates/swc_stylis/src/prefixer.rs
Too many local variables break debug wasm build.
- https://github.com/vercel/next.js/pull/35395
=> fix(css/prefixer): Reduce the number of vars in debug build

Cargo.lock, crates/swc/src/config/mod.rs, crates/swc/src/plugin.rs, crates/swc_cli/Cargo.toml, crates/swc_plugin_runner/Cargo.toml, crates/swc_plugin_runner/src/cache.rs, crates/wasm/Cargo.toml, crates/wasm/scripts/build.sh, crates/wasm/scripts/build_nodejs_release.sh, crates/wasm/scripts/build_web_release.sh, crates/wasm/src/lib.rs
This is the initial groundwork for #3934. Mainly, PR attempts to introduce interface to `transformSync` in wasm to accept another param for the plugin's module bytes.
I'm not a huge fan of current approach, honestly. But also wasm-* target is pretty limited to access external system resources - for example, @swc/wasm cannot access filesystem also can't easily use remote-ish interfaces since it implies node.js target.
For now, I'll focus for the primary goal to enable end-to-end workflow to make plugin work in the wasm target. Once it's done, I can come up with proposal for consolidating all interface stablization.
- relates with https://github.com/swc-project/swc/issues/3934
=> feat(swc/wasm): initial plugin support interface

Cargo.lock, crates/swc_cli/Cargo.toml, crates/swc_cli/src/commands/compile.rs
Update few more flags for the compile command.
https://github.com/swc-project/swc/issues/4017
=> feat(swc/cli): implements few compile flags

crates/swc/src/config/mod.rs, crates/swc_ecma_codegen/src/macros.rs
make errorConfig.filename default to true.
this will make @swc/cli always output error with filename, except with `-C error.filename=false`.
when using @swc/cli the value of this field in .swcrc is ignored, since swc use this value before read .swcrc
Closes #3950
=> fix: make errorConfig.filename default to true

crates/swc_ecma_lints/src/rules/duplicate_bindings.rs, crates/swc_ecma_lints/tests/pass/issue-4148/1/input.ts
Note: 
```typescript
import type { Foo } from "./b"; // fixed in this PR
import { type Foo } from "./b"; // it is OK
import { Foo } from "./b"; // cannot be fixed unless we have multifile mode
```
- #4148 partial fixed
=> fix(es/lint): ignore type only import

crates/swc_cli/src/commands/plugin.rs
override
PR replaces plugin scaffolding config to not override build to specific target, instead introduce aliased one. This is due to overriding target defeats all other commands (i.e cargo `test` doesn't work out of the box). 
Name of new alias will likely change.
New plugin template created via cli now need to specify target for `cargo build` or use new alias.
=> refactor(swc/cli): alias plugin build with wasm target instead of

crates/swc_ecma_parser/src/parser/class_and_fn.rs, crates/swc_ecma_parser/src/parser/stmt.rs, crates/swc_ecma_parser/tests/span/js/decl/class-no-close-brace.js, crates/swc_ecma_parser/tests/span/js/decl/class-no-close-brace.js.spans, crates/swc_ecma_parser/tests/test262-error-references/fail/021fb596db81e6d0.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/4d579849c75cfef9.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/50efa1f220e37136.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/77fe5a8d6ae33dd1.js.stderr, crates/swc_ecma_parser/tests/typescript-errors/arrow-function/missing-closing-brace/input.ts, crates/swc_ecma_parser/tests/typescript-errors/arrow-function/missing-closing-brace/input.ts.stderr, crates/swc_ecma_parser/tests/typescript-errors/class/missing-closing-brace/input.ts, crates/swc_ecma_parser/tests/typescript-errors/class/missing-closing-brace/input.ts.stderr
This is a small, but huge improvement for swc to get ASTs in spite of syntax errors. Essentially, it allows parsing even if there's a missing close brace in a section of the code.
For example, the following will now parse, but have two emitted diagnostics for missing `}`:
```ts
class MyClass {
prop: string;
myMethod() {
console.log(5);
```
Part of what's outlined in #1178
A missing close brace token will no longer be a fatal parsing error, but will instead emit diagnostics.
=> feat(parser): allow parsing files with missing close braces

Cargo.lock, Cargo.toml, crates/node/Cargo.toml, crates/node/src/util.rs, crates/swc_cli/Cargo.toml
When fix dropping flush guard global static was removed, and also removed init once logic. PR fixes to init once only, subsequent call do nothing.
=> fix(swc): init custom trace subscriber once

crates/swc_ecma_minifier/src/pass/mangle_names/analyzer/scope.rs, crates/swc_ecma_parser/src/error.rs, crates/swc_ecma_parser/src/lexer/mod.rs, crates/swc_ecma_parser/src/lexer/number.rs, crates/swc_ecma_parser/src/lexer/tests.rs, crates/swc_ecma_parser/src/lexer/util.rs, crates/swc_ecma_parser/src/parser/macros.rs, crates/swc_ecma_parser/src/parser/mod.rs, crates/swc_ecma_parser/src/parser/tests.rs
We emulate `unlikely` for vairous error macros by converting `Error::new` into a cold function.
```
test angular       ... bench:   7,922,906 ns/iter (+/- 284,640) = 90 MB/s
test backbone      ... bench:   1,093,366 ns/iter (+/- 30,800) = 54 MB/s
test colors        ... bench:      14,564 ns/iter (+/- 635) = 79 MB/s
test jquery        ... bench:   6,021,029 ns/iter (+/- 209,889) = 44 MB/s
test jquery_mobile ... bench:   9,654,149 ns/iter (+/- 154,489) = 46 MB/s
test mootools      ... bench:   4,645,033 ns/iter (+/- 117,356) = 34 MB/s
test three         ... bench:  27,476,366 ns/iter (+/- 1,396,719) = 43 MB/s
test underscore    ... bench:     942,445 ns/iter (+/- 12,220) = 46 MB/s
test yui           ... bench:   4,686,897 ns/iter (+/- 180,492) = 72 MB/s
```
```
test angular …
```
=> perf(es/parser): Improve performance by using `#[cold]`

crates/swc_ecma_transforms_optimization/src/simplify/inlining/mod.rs, crates/swc_ecma_transforms_optimization/tests/simplify.rs
Original code would collect ident at
https://github.com/swc-project/swc/blob/e77f0a2a373337181da14826097953e4f1d6b341/crates/swc_ecma_transforms_optimization/src/simplify/inlining/mod.rs#L538
However that's only for stmts, so when branch turn
```js
if (cond) {
aaa
}
// into
if (cond) aaa
```
declaration in `aaa` wouldn't be collected
closes #4173, closes #4174
=> fix(es/optimizer): collect ident in for init first

Cargo.lock, crates/swc_plugin/Cargo.toml, crates/swc_plugin/src/lib.rs
This PR exports `swc_ecma_utils` from `swc_plugin` as `utils`. 
The main reason for this change is to allow the  `swc_ecma_utils::ident::IdentLike` trait to be applied to `swc_plugin::ast::Ident`. 
So that I can use `.to_id()` like `default_specifier.local.to_id()`.
=> Export swc_ecma_utils from swc_plugin as swc_ecma_utils::utils

node-swc/src/types.ts
Type definitions(`isTypeOnly`) are not getting updated at #2309, this PR tries to fix that.
No breaking change, just a bug fix for typescript usage.
#2309
**Workaround without this**
```ts
type PatchedNamedExportSpecifier = {
isTypeOnly: boolean,
} & NamedExportSpecifier;
// some code...
(specifier as unknown as PatchedNamedExportSpecifier).isTypeOnly
```
=> node-swc: add `isTypeOnly` memebr to missing interfaces

crates/swc_ecma_parser/src/lib.rs, crates/swc_ecma_parser/src/parser/typescript.rs, crates/swc_ecma_parser/tests/typescript/types/conditional-infer-extends/basic/input.ts, crates/swc_ecma_parser/tests/typescript/types/conditional-infer-extends/basic/input.ts.json, crates/swc_ecma_parser/tests/typescript/types/conditional-infer-extends/distinguishing/input.ts, crates/swc_ecma_parser/tests/typescript/types/conditional-infer-extends/distinguishing/input.ts.json
Support the new TypeScript syntax below:
```ts
type X3<T> = T extends [infer U extends number] ? MustBeNumber<U> : never;
```
Reference: https://github.com/microsoft/TypeScript/pull/48112
=> feat(es/parser): Support 'extends' clause to 'infer' type

crates/swc_css_prefixer/src/prefixer.rs, crates/swc_css_prefixer/tests/fixture/display/input.css, crates/swc_css_prefixer/tests/fixture/display/output.css, crates/swc_css_prefixer/tests/fixture/duplicate-at-rule/input.css, crates/swc_css_prefixer/tests/fixture/duplicate-at-rule/output.css, crates/swc_css_prefixer/tests/fixture/grouping-rule/output.css, crates/swc_css_prefixer/tests/fixture/keyframes/output.css, crates/swc_css_prefixer/tests/fixture/nested/input.css, crates/swc_css_prefixer/tests/fixture/nested/output.css, crates/swc_css_prefixer/tests/fixture/placeholder/input.css, crates/swc_css_prefixer/tests/fixture/placeholder/output.css, crates/swc_css_prefixer/tests/fixture/prefixed/input.css, crates/swc_css_prefixer/tests/fixture/prefixed/output.css, crates/swc_css_prefixer/tests/fixture/style-block/input.css, crates/swc_css_prefixer/tests/fixture/style-block/output.css
Fixed:
- don't add unnecessary prefixes
- avoid invalid prefixes in prefixed at-rule/rule
- fix perf
- fix prefixes in nested at-rules/rule
- and big code refactor
Autoprefixer mostly ported, currently I want to focus:
1. Adding browserslist option to generate only necessary prefixes
2. Remove outdated prefixes based on browserslist (after first)
3. Finish small TODOs
Hope I will finish it on this/next week
No
No
=> fix(css/prefixer): fix more bugs

crates/swc_ecma_minifier/src/pass/mangle_names/analyzer/scope.rs, crates/swc_ecma_minifier/src/pass/mangle_names/private_name.rs, crates/swc_ecma_minifier/src/pass/mangle_props.rs, crates/swc_ecma_minifier/src/util/base54.rs
This improve performance a bit because of cpu cache.
=> perf(es/minifier): Split frequently used functions

crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/src/compress/pure/evaluate.rs, crates/swc_ecma_minifier/src/compress/pure/misc.rs, crates/swc_ecma_minifier/src/compress/pure/mod.rs, crates/swc_ecma_minifier/tests/TODO.txt, crates/swc_ecma_minifier/tests/golden.txt
- We now handle `array.join` in parallel optimizer.
- We now handle `[].join` of template literals.
- We now optimize a template literal as a string addition, in unsafe mode.
=> feat(es/minifier): Implement more evaluation rules

CONTRIBUTING.md
The link reference `githelp` contains no link since it was made (22b9e08851af5718d5ffa06549615d9b4b44c95c). So this PR removes it, feel free to reject this.
=> chore: remove incorrect link in CONTRIBUTING.md

Cargo.lock, crates/swc/src/config/mod.rs, crates/swc/src/plugin.rs, crates/swc_common/Cargo.toml, crates/swc_common/src/plugin.rs, crates/swc_ecma_ast/Cargo.toml, crates/swc_plugin/src/lib.rs, crates/swc_plugin_macro/src/lib.rs, crates/swc_plugin_proxy/Cargo.toml, crates/swc_plugin_proxy/src/comments/mod.rs, crates/swc_plugin_proxy/src/comments/plugin_comments_proxy.rs, crates/swc_plugin_proxy/src/lib.rs, crates/swc_plugin_proxy/src/memory_interop/mod.rs, crates/swc_plugin_proxy/src/memory_interop/read_returned_result_from_host.rs, crates/swc_plugin_proxy/src/source_map/mod.rs, crates/swc_plugin_proxy/src/source_map/plugin_source_map_proxy.rs, crates/swc_plugin_runner/src/imported_fn/comments.rs, crates/swc_plugin_runner/src/imported_fn/mod.rs, crates/swc_plugin_runner/src/imported_fn/source_map.rs, crates/swc_plugin_runner/src/lib.rs, crates/swc_plugin_runner/src/load_plugin.rs, crates/swc_plugin_runner/src/memory_interop.rs, crates/swc_plugin_runner/src/transform_executor.rs, crates/swc_plugin_runner/tests/integration.rs, tests/rust-plugins/swc_internal_plugin/Cargo.lock
Implements `lookup_char_pos` for the sourcemap proxy.
This PR includes one notable changes around deserialization - adding new `deserialize` interface for `Fallible`. This is due to `SourceMap` struct contains shared pointer. It requires to satisfiy `SharedSerializeRegistry`, which should be `Fallible` and cannot be `Infallible`. 
All of existing struct used Infallible as default deserializer, but in case of new deserialze fn it'll use `SharedDeserializeMap` as deserializer instead.
In practical usecase, this won't make huge difference. Caller need to opt in corresponding deserialization depends on the character of the struct and it is easy to find out since it won't be able to compile. I feel ergonomics, interface around `Serialized` struct might need some touch later. …
=> feat(swc/plugin_proxy): support lookup_char_pos for sourcemap

Cargo.lock, crates/swc_ecma_minifier/Cargo.toml, crates/swc_ecma_minifier/src/util/base54.rs
=> perf(es/minifier): Make `base54` use stack-allocated vector

crates/swc_ecma_parser/src/error.rs, crates/swc_ecma_parser/src/parser/expr/ops.rs, crates/swc_ecma_parser/tests/typescript-errors/await-with-exponentiation/input.ts, crates/swc_ecma_parser/tests/typescript-errors/await-with-exponentiation/input.ts.stderr
Reject the code below:
```js
async () => await a ** b;
```
[Current behavior](https://play.swc.rs/?version=1.2.170&code=H4sIAAAAAAAAA0ssrsxLVtDQVLC1U0gsT8wsUUhU0NJSSLIGAEmKHsUZAAAA&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1FsWLLnKHHsK4SnDxD40CDcZ3rx1cspNmnp4qfeBorVSsgGVMOJPaL62kZ2E48UVpIUWPNhvArS9WdtaOMMzDmF6HnMETWCj65LdzyFyORRi4K5v28Cdbd8X8PkZQr3%2BX80ntdsw7j9cEVQ5uPx%2Bqcl%2B4AAAA)
[Babel REPL](https://babel.dev/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=IYZwngdgxgBAFAShgXgHw2Ad2ASwC4YwBURMARgNxA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.17.9&externalPlugins=&assumptions=%7B%7D)
=> fix(es/parser): Reject await expr with exponentiation op

crates/swc_ecma_minifier/examples/minify-all.rs, crates/swc_ecma_minifier/scripts/instrument/all.sh, crates/swc_ecma_minifier/src/compress/optimize/util.rs
This improves performance in some cases.
```
time:   [722.83 ms 724.42 ms 726.21 ms]
change: [-2.6626% -2.1874% -1.7210%] (p = 0.00 < 0.05)
es/minify/libraries/d3  time:   [205.47 ms 205.84 ms 206.23 ms]
change: [-0.1453% +0.8473% +1.5925%] (p = 0.09 > 0.05)
No change in performance detected.
Found 2 outliers among 10 measurements (20.00%)
1 (10.00%) low mild
Benchmarking es/minify/libraries/echarts: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 8.4s.
es/minify/libraries/echarts
time:   [838.60 ms 840.63 ms 843.00 ms]
change: [-1.1146% -0.8510% -0.5331%] (p = 0.00 < 0.05)
Change within noise threshold.
es/minify/libraries/jquery
time: …
```
=> perf(es/minifier): Add some fast-path to the `MultiReplacer`

crates/swc_ecma_parser/src/parser/class_and_fn.rs, crates/swc_ecma_parser/tests/typescript-errors/use-strict/arrow-fn-expr/input.ts, crates/swc_ecma_parser/tests/typescript-errors/use-strict/arrow-fn-expr/input.ts.stderr, crates/swc_ecma_parser/tests/typescript-errors/use-strict/fn-block/input.ts, crates/swc_ecma_parser/tests/typescript-errors/use-strict/fn-block/input.ts.stderr
This PR lets it check `'use strict'` with non-simple parameters list in TypeScript. Previously it only checks in JavaScript.
=> fix(es/parser): Reject `'use strict'` with non-simple params list in TS

crates/swc_ecma_ast/src/prop.rs
Fix for #4439.
Problem appears to be that node type annotation in `PropName` Enum (`#[tag("BigInt")]`) is out of sync with the annotation for `BigInt` struct (`#[ast_node("BigIntLiteral")]`).
This PR changes that, and it fixes the error.
I had trouble working out where to add a test. Fixtures in [crates/swc_ecma_codegen/tests/fixture](https://github.com/swc-project/swc/tree/main/crates/swc_ecma_codegen/tests/fixture) appear to be parsed as TypeScript, and TypeScript doesn't seem to accept this as valid code.
If someone can let me know where to put tests, I'll add them.
Closes #4439
=> fix(es/codegen): Print BigInt as object property

crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/tests/fixture/attribute/iframe/input.html, crates/swc_html_minifier/tests/fixture/attribute/iframe/output.min.html, crates/swc_html_minifier/tests/fixture/attribute/img/input.html, crates/swc_html_minifier/tests/fixture/attribute/img/output.min.html, crates/swc_html_minifier/tests/fixture/attribute/input/input.html, crates/swc_html_minifier/tests/fixture/attribute/input/output.min.html, crates/swc_html_minifier/tests/fixture/attribute/meter/input.html, crates/swc_html_minifier/tests/fixture/attribute/meter/output.min.html, crates/swc_html_minifier/tests/fixture/attribute/ol/input.html, crates/swc_html_minifier/tests/fixture/attribute/ol/output.min.html, crates/swc_html_minifier/tests/fixture/attribute/progress/input.html, crates/swc_html_minifier/tests/fixture/attribute/progress/output.min.html, crates/swc_html_minifier/tests/fixture/attribute/script-type/output.min.html, crates/swc_html_minifier/tests/fixture/attribute/textarea/input.html, crates/swc_html_minifier/tests/fixture/attribute/textarea/output.min.html, crates/swc_html_minifier/tests/fixture/attribute/track/input.html, crates/swc_html_minifier/tests/fixture/attribute/track/output.min.html
Compress default values.
There are two limitation (so they were not added in default):
1. Some attributes have `default` value in spec, but some browsers don't respect spec and use own values (Safari like it), so they were not added
2. Legacy attributes (like `align`/etc), the same problems for different browsers
In any case, there can be many them, I tried to collect the most popular
No
No
=> feat(html/minifier): compress default values of attributes

crates/swc_ecma_parser/src/parser/class_and_fn.rs, crates/swc_ecma_parser/tests/typescript-errors/missing-fn-expr-body/anonymous/input.ts, crates/swc_ecma_parser/tests/typescript-errors/missing-fn-expr-body/anonymous/input.ts.stderr, crates/swc_ecma_parser/tests/typescript-errors/missing-fn-expr-body/async/input.ts, crates/swc_ecma_parser/tests/typescript-errors/missing-fn-expr-body/async/input.ts.stderr, crates/swc_ecma_parser/tests/typescript-errors/missing-fn-expr-body/named/input.ts, crates/swc_ecma_parser/tests/typescript-errors/missing-fn-expr-body/named/input.ts.stderr, crates/swc_ecma_parser/tests/typescript-errors/missing-fn-expr-body/typed/input.ts, crates/swc_ecma_parser/tests/typescript-errors/missing-fn-expr-body/typed/input.ts.stderr
Throw a syntax error for the code below:
```ts
let f = function ()
```
Note that this bug is only reproducible when `syntax` is `'typescript'`; for `'ecmascript'`, it already works expectedly.
[playground](https://play.swc.rs/?version=1.2.172&code=H4sIAAAAAAAAA8tJLVGoULBVSCvNSy7JzM9T0NDkAgAMz9H4FAAAAA%3D%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1Fm0XpeQOPYRxleDgHxoFGozvXju4ZCfNPD0V2mBpLpSNgKVPOKKaL82kR2ZYcVlpIkWLFuPBtS1GVtaGMB63%2B6vVPiXwACYKLrrl6DKbQhYGrsrE1f%2FJ2lwhffYelPPf6XxSvRzjzuE9QJWd6w%2B6QIF4uAAAAA%3D%3D)
=> fix(es/parser): Throw syntax error for missing function expr body

crates/swc_html_codegen/src/ctx.rs, crates/swc_html_codegen/src/lib.rs, crates/swc_html_minifier/tests/fixture/attribute/script-type/input.html, crates/swc_html_minifier/tests/fixture/attribute/script-type/output.min.html, crates/swc_html_minifier/tests/fixture/attribute/textarea/output.min.html, crates/swc_html_minifier/tests/fixture/comment/output.min.html, crates/swc_html_parser/src/lexer/mod.rs, crates/swc_html_parser/src/parser/mod.rs, crates/swc_html_parser/tests/fixture/element/embed/output.json, crates/swc_html_parser/tests/fixture/tag/script/input.html, crates/swc_html_parser/tests/fixture/tag/script/output.json, crates/swc_html_parser/tests/fixture/tag/script/span.rust-debug, crates/swc_html_parser/tests/recovery/element/embed-closed/output.json
There are two fixes:
1. Lexer bug - we don't emit temporary buffer to restore original context
2. Avoid escaping in some elements because they content should be outputed as is
No
No
=> fix(html/parser): parser and codegen bugs

node-swc/src/types.ts
Uses helper type `ToSnakeCase` to support snake_case property usage.
- #4387
- https://github.com/swc-project/website/commit/7b643838779db47c9329c0efba3b2435eef92584
- Is there some tools for auto-generating these stuffs?
- I want to use Prettier for this file *badly*.
=> fix(node/types): Types for `jsc.minify.format`

Cargo.lock, crates/swc_ecmascript/Cargo.toml, crates/swc_plugin/Cargo.toml, crates/swc_plugin/src/lib.rs, tests/rust-plugins/swc_internal_plugin/Cargo.lock
This is minor bikeshedding for the swc_plugin's deps to use reduced number of deps instead of having individual for the reexport.
This won't make any major differences, but helps to import a visitor aims to be used for the plugin & custom pass both:
```
// visitor
- swc_ecma_script
- ...
// plugin
- swc_plugin
- visitor
// swc/custom-pass
- swc_ecma_script
- visitor
```
plugin / swc both will work by having matching version of swc_ecmascript only, instead of each (ast, visit, etcs) to avoid conflict. This is what I found while try to align versions for the https://github.com/vercel/next.js/pull/36692.
=> refactor(swc/plugin): align deps

crates/swc_ecma_minifier/tests/terser/compress/evaluate/issue_1760_1/output.js, crates/swc_ecma_minifier/tests/terser/compress/issue_597/NaN_and_Infinity_should_not_be_replaced_when_they_are_redefined_evaluate/output.js, crates/swc_ecma_minifier/tests/terser_exec.rs, crates/swc_ecma_transforms_optimization/src/simplify/expr/mod.rs
- `expr_simplifier` now uses `NaN#unresolved` instead of f64 with `NaN` value.
=> fix(es/minifier): Fix handling of `NaN`

crates/binding_core_node/src/bundle.rs, crates/binding_core_node/src/print.rs, crates/binding_core_wasm/src/lib.rs, crates/swc/benches/minify.rs, crates/swc/benches/typescript.rs, crates/swc/examples/minify.rs, crates/swc/src/config/mod.rs, crates/swc/src/lib.rs, crates/swc/tests/exec.rs, crates/swc/tests/projects.rs, crates/swc/tests/source_map.rs, crates/swc_common/src/source_map.rs, crates/swc_node_bundler/tests/fixture.rs
Optionally emit source map columns, use `true` as default value
No breaking changes
closes #4637
=> feat(common): emit source map columns

crates/swc_html_codegen/tests/fixture.rs, crates/swc_html_parser/src/parser/mod.rs, crates/swc_html_parser/tests/fixture.rs, crates/swc_html_parser/tests/iframe_srcdoc/basic/dom.rust-debug, crates/swc_html_parser/tests/iframe_srcdoc/basic/input.html, crates/swc_html_parser/tests/iframe_srcdoc/basic/output.json, crates/swc_html_parser/tests/iframe_srcdoc/basic/span.rust-debug
Support `iframe_srcdoc`, i.e.
https://www.w3schools.com/tags/att_iframe_srcdoc.asp
```
<iframe srcdoc="<p>Hello world!</p>" src="demo_iframe_srcdoc.htm"></iframe>
```
Before today I don't known about this features :confused: Currently we don't parse it by default for better perf and because it has very rare usage, but we add ability to do it because it is part of spec
No
No
=> feat(html/parser): support `iframe_srcdoc`

crates/swc_common/src/input.rs, crates/swc_ecma_parser/scripts/instrument.sh
```
WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.
Benchmarking es/parser/colors
Benchmarking es/parser/colors: Warming up for 3.0000 s
Benchmarking es/parser/colors: Collecting 100 samples in estimated 5.0671 s (333k iterations)
Benchmarking es/parser/colors: Analyzing
es/parser/colors        time:   [14.951 us 14.962 us 14.973 us]
change: [-0.0124% +0.2115% +0.4430%] (p = 0.07 > 0.05)
No change in performance …
```
=> perf(common): Improve performance of `StringInput`

crates/swc/tests/fixture/issues-4xxx/4855/input/1/.swcrc, crates/swc/tests/fixture/issues-4xxx/4855/input/1/input.js, crates/swc_ecma_minifier/src/compress/pure/misc.rs, crates/swc_ecma_transforms_optimization/src/simplify/branch/mod.rs
- Closes https://github.com/swc-project/swc/issues/4855
=> fix(es/minifier): Don't drop `typeof`

crates/swc/tests/fixture/4896/input/.swcrc, crates/swc/tests/fixture/4896/input/index.ts, crates/swc/tests/fixture/4896/output/index.ts, crates/swc_ecma_transforms_module/src/amd.rs
- Closes https://github.com/swc-project/swc/issues/4896
=> fix(es/modules/amd): Support `export * as foo from 'foo'`

crates/swc_visit/src/util/move_map.rs
This code first sets the `len` to 0 in case of panics, and then uses `get_unchecked` to access the elements in the vec.
This is not allowed, since `get_unchecked` must only be used with indexes that are in bounds respective to the length.
Use `as_ptr().add()` instead, which does not care about the length.
Found by debug assertions in `std`  when using `-Zbuild-std`.
=> Don't use `get_unchecked` after having set the len to 0

crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/src/option.rs, crates/swc_html_minifier/tests/fixture/doctype/system-force-set-html5-doctype/config.json, crates/swc_html_minifier/tests/fixture/doctype/system-force-set-html5-doctype/input.html, crates/swc_html_minifier/tests/fixture/doctype/system-force-set-html5-doctype/output.min.html, crates/swc_html_minifier/tests/recovery/doctype/html4-force-html5-doctype/config.json, crates/swc_html_minifier/tests/recovery/doctype/html4-force-html5-doctype/input.html, crates/swc_html_minifier/tests/recovery/doctype/html4-force-html5-doctype/output.min.html
Add option to force set HTML5 doctype, good for legacy systems, ported from https://terser.org/html-minifier-terser/
Yes
No
=> feat(html/minifier): option to set html5 doctype

crates/swc_ecma_lints/src/rules/duplicate_bindings.rs, crates/swc_ecma_lints/tests/pass/issue-4907/1/input.js
So, [per spec](https://tc39.es/ecma262/#sec-static-semantics-lexicallydeclarednames)
> At the top level of a [Module](https://tc39.es/ecma262/#prod-Module), function declarations are treated like lexical declarations rather than like var declarations.
and it's only an error at the top level of module
closes #4907
=> fix(es/lint): allow duplicate function in non top level in module

crates/swc_html_codegen/src/ctx.rs, crates/swc_html_codegen/src/lib.rs, crates/swc_html_codegen/tests/fixture.rs, crates/swc_html_codegen_macros/src/lib.rs, crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/tests/fixture.rs, crates/swc_html_parser/benches/compare.rs, crates/swc_html_parser/benches/parser.rs, crates/swc_html_parser/src/lib.rs, crates/swc_html_parser/src/parser/mod.rs, crates/swc_html_parser/tests/fixture.rs
- Allow to setup document and form element for document fragments
- Context element passed by reference, so no need to clone
I tried to extract tree builder as in TODO, but found less perf and more memory usage, because we need duplicate some things, so I think for perf reasons better to keep parser and tree builder together
Yes
No
=> feat(html/parser): improve API

crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/src/option.rs, crates/swc_html_minifier/tests/fixture/attribute/custom-attribute/config.json, crates/swc_html_minifier/tests/fixture/attribute/custom-attribute/input.html, crates/swc_html_minifier/tests/fixture/attribute/custom-attribute/output.min.html
Here:
- minify `srcdoc` for `iframe`
- allow to setup setup custom JS attributes, i.e. `<div data-click="myFunction("test", 10 *   10)">`
- allow to setup setup custom JSON attributes, i.e. `<div data-json='{ "foo": "bar" }'></div>`
- allow to setup setup custom CSS attributes, i.e. `<div data-style="color: red; background-color: red"></div>`
- allow to setup setup custom HTML attributes, i.e. `<div data-html="<html> <body> <p>test.</p>" src="nosrcdoc.html"></div>`
Yes
No
=> feat(html/minifier): allow to compress additional attributes

Cargo.lock, crates/ast_node/src/lib.rs, crates/swc_atoms/Cargo.toml, crates/swc_atoms/src/lib.rs, crates/swc_common/Cargo.toml, crates/swc_common/src/comments.rs, crates/swc_common/src/errors/diagnostic.rs, crates/swc_common/src/errors/mod.rs, crates/swc_common/src/errors/snippet.rs, crates/swc_common/src/plugin.rs, crates/swc_common/src/syntax_pos.rs, crates/swc_common/src/syntax_pos/hygiene.rs, crates/swc_common/tests/attr_interop.rs, crates/swc_ecma_ast/Cargo.toml, crates/swc_ecma_ast/src/class.rs, crates/swc_ecma_ast/src/decl.rs, crates/swc_ecma_ast/src/expr.rs, crates/swc_ecma_ast/src/ident.rs, crates/swc_ecma_ast/src/operators.rs, crates/swc_ecma_ast/src/typescript.rs, crates/swc_plugin_proxy/Cargo.toml, crates/swc_plugin_proxy/src/memory_interop/read_returned_result_from_host.rs
Related to #5060.
PR introduces a new struct `versioned`, which is a transparent type can be used to carry over different versioned struct. Also PR wraps ast with `bytecheck` to validate serialized byte with each versions.
=> feat(swc/common): add versioned wrapper struct (#5060: Part 1)

crates/swc_ecma_parser/src/lib.rs, crates/swc_ecma_parser/src/parser/stmt.rs, crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/tests/fixture/attribute/javascript-prefix/input.html, crates/swc_html_minifier/tests/fixture/attribute/javascript-prefix/output.min.html, crates/swc_html_minifier/tests/fixture/attribute/onclick/output.min.html
Add `allow_return_outside_function` to parse HTML event handler attributes
Yes
No
=> feat(ecma/parser): add the `allow_return_outside_function` option

crates/swc_ecma_transforms_module/src/amd.rs, crates/swc_ecma_transforms_module/src/common_js.rs, crates/swc_ecma_transforms_module/src/module_ref_rewriter.rs, crates/swc_ecma_transforms_module/src/umd.rs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5063/1/input.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5063/1/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5063/1/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5063/1/output.umd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5063/2/input.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5063/2/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5063/2/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-5063/2/output.umd.js
=> fix(es/module): handle this in class method

Cargo.lock, crates/swc_atoms/src/lib.rs, crates/swc_common/Cargo.toml, crates/swc_common/src/eq.rs
---
```
html/parser_document/css_2021_spec
time:   [14.183 ms 14.218 ms 14.261 ms]
Found 14 outliers among 100 measurements (14.00%)
5 (5.00%) high mild
9 (9.00%) high severe
html/parser_document/github_com_17_05_2022
time:   [5.4104 ms 5.4194 ms 5.4321 ms]
Found 13 outliers among 100 measurements (13.00%)
6 (6.00%) high mild
7 (7.00%) high severe
html/parser_document/stackoverflow_com_17_05_2022
time:   [4.9527 ms 4.9573 ms 4.9625 ms]
Found 13 outliers among 100 measurements (13.00%)
1 (1.00%) low mild
5 (5.00%) high mild
7 (7.00%) high severe
html/parser_document_fragment/css_2021_spec
time:   [14.199 ms 14.219 ms 14.247 ms]
Found 15 outliers among 100 measurements (15.00%)
5 (5.00%) high mild
10 (10.00%) high severe …
```
=> feat(atoms): Improve atoms

crates/swc_common/src/plugin.rs, crates/swc_ecma_ast/src/module.rs
I made this PR intentionally short for the verification of idea (which means I'm not certain about this change and I may wrong 😅)
PR implements `take` for the `VersionedSerializable` to move out value after deserializaiton is done from transform. Pseudocodewise, it'll be used like below:
```
let versioned_program = VersionedSerializable::new(program);
let mut serialized = Serialized::serialize(&versioned_program)?;
//... run plugin transform
// deserialize, return actual inner program
return Serialized::deserialize(&serialized)
.map(|mut v: VersionedSerializable<Program>| v.take())
```
Main thing I'm unsure is implementing `Default` for the `Program` to use `mem::take` in here. It maybe harmless, but I'm not easily able to say default impl for the program is exactly …
=> feat(swc/common): allow to take inner from versioned (#5060: Part 2) 

crates/swc_ecma_transforms_module/src/module_ref_rewriter.rs, crates/swc_ecma_transforms_module/tests/fixture/common/lazy/computed-prop-name/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/lazy/import-all-from-object-config/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/lazy/issue-3081/1/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/lazy/issue-3081/2/output.cjs
It is my mistake to skip the indirect call transforms if the  callee is lazy required.
It still needs to be transformed into indirect call to correct `this`.
=> fix(es/module): indirect call for lazy require

crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_preset_env/src/lib.rs, crates/swc_ecma_transforms_compat/src/es2015/mod.rs, crates/swc_ecma_transforms_compat/src/es2018/mod.rs, crates/swc_ecma_transforms_compat/src/es2022/mod.rs, crates/swc_ecma_transforms_compat/src/regexp.rs
ECMAScript2022 version (ES13) released June 2022 includes a new `d` (hasIndices) RegEx flag according to [the spec](https://262.ecma-international.org/13.0/#sec-regexpbuiltinexec). This PR adds such flag.
Currently, we are throwing a `UnknownRegExpFlags` error because `d` is not included in the known flags. Babel allows this and doesn't alter the RegEx flags.
See [play.swc.rs](https://play.swc.rs/?version=1.2.210&code=H4sIAAAAAAAAA9PXSNTW1EjS1tRP0UutSE3WUE8EgqQkdU1rACH6qKMbAAAA&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D)
None
=> feat(es/parser): adding 'd' regex flag (ES2022)

crates/swc_ecma_parser/src/lib.rs
Description:
The place to use is to turn on the parse ts switch, which seems to be a typo
```rust
if syntax.typescript() {
transform.legacy_decorator = true.into();
}
```
BREAKING CHANGE:
No
Related issue (if exists):
No
=> docs: fix the meaning

node-swc/src/Visitor.ts, node-swc/src/types.ts
This PR fixes various inaccuracies in the TS type definitions for AST nodes. They seem to have got out of sync over time.
These discrepancies were identified programmatically based on the model of the Rust types I've made for #2175. So this PR should be definitive and bring the TS types completely up to date.
NB Some of the changes just re-order fields and enum options. This doesn't make a difference to correctness of the types. But now they're all consistent with field order in the Rust types, which will maybe make it easier to spot when further changes are required in future.
n/a
=> Fix TS types for AST nodes

crates/swc_cli/src/commands/compile.rs
- close #5171
Attempt to close #5171, emits sourcemap if inputs are file instead of dir.
=> fix(swc/cli): emit sourcemap with file inputs

crates/swc_ecma_ast/src/lib.rs, crates/swc_ecma_ast/src/module.rs, crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_lints/tests/fixture.rs, crates/swc_ecma_visit/src/lib.rs, crates/swc_estree_compat/src/babelify/module.rs, node-swc/e2e/fixtures/plugin_transform_schema_v1/Cargo.lock, node-swc/e2e/fixtures/plugin_transform_schema_v1/Cargo.toml, node-swc/e2e/fixtures/plugin_transform_schema_v1/src/lib.rs, node-swc/e2e/fixtures/plugin_transform_schema_vtest/Cargo.lock, node-swc/e2e/fixtures/plugin_transform_schema_vtest/src/lib.rs, node-swc/e2e/plugins/plugins.schema.test.js, package.json, yarn.lock
Continuation of https://github.com/swc-project/swc/pull/5243, where actually establishes versioned schema compatiblity verification. Good new is, it works well. Not good, or somewhat annoying thing is current ergonomics is not elegant for the core devs. (Plugin authors or users are fine!)
First, let's start with compatibility table. `1` and `2` indicate **AST VERSION**, not actual major pkg versions of each.
|   |  plugin@1  | plugin@2  |
|---|---|---|
| @swc/core@1  |  ⭕  | ❌   | 
| @swc/core@2  | ⭕   | ⭕  | 
This is our desired behavior. Say we add a new AST property and it increases AST version to 2, we expect new `@swc/core` can seamleassly use plugin@1, 2 both without asking to rebuild. In case of old version of `@swc/core@`, it won't be able to read newly updated …
=> test(swc): test plugins with different schema versions (#5060 Part 6)

crates/swc/tests/fixture/issues-3xxx/3686/1/output/index.ts, crates/swc/tests/fixture/issues-5xxx/5258/input/.swcrc, crates/swc/tests/fixture/issues-5xxx/5258/input/index.ts, crates/swc/tests/fixture/issues-5xxx/5258/output/index.ts, crates/swc_ecma_transforms_proposal/src/decorators/legacy/mod.rs, crates/swc_ecma_transforms_proposal/src/decorators/mod.rs
=> fix(es/decorators): Use decorated consturctors

crates/swc/src/plugin.rs, crates/swc_ecma_ast/src/module.rs, crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_lints/tests/fixture.rs, crates/swc_ecma_visit/src/lib.rs, crates/swc_estree_compat/src/babelify/module.rs, crates/swc_plugin_macro/src/lib.rs, crates/swc_plugin_runner/benches/invoke.rs, crates/swc_plugin_runner/src/transform_executor.rs, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/Cargo.lock, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/src/lib.rs, crates/swc_plugin_runner/tests/integration.rs, node-swc/e2e/fixtures/plugin_transform_schema_vtest/Cargo.lock, node-swc/e2e/fixtures/plugin_transform_schema_vtest/src/lib.rs, node-swc/e2e/plugins/plugins.schema.test.js
PR actually passes experimental metadata from host to the plugin, even though it's empty hashmap for now.
There is a ugly commit https://github.com/swc-project/swc/commit/5ef7333fbf931aaf3e0bc7e317955fd84d7e1f3f to disable test-only ast changes and some test, for the reason our e2e test is now validly test against latest public and this PR is _technically_ breaking change and our test fails.
It is not great, probably we have to invent something works automatically in the future. For now, dealing with manual approach.
=> feat(swc/plugin): actually pass experimental metadata from host

.github/workflows/bench.yml, .github/workflows/integration.yml, Cargo.lock, crates/binding_core_wasm/Cargo.toml, crates/binding_core_wasm/src/lib.rs, crates/binding_core_wasm/src/types.rs, node-swc/src/index.ts, package.json
This PR improves type definition for `@swc/wasm` by mimicing existing type interface support to `@swc/core`. Unfortunately wasm-bindgen does not support to directly reference types from existing typescript or build-time macro to import it, so had to duplicate those types. Currently it's 100% duplicate, so there are some options can be passed to bindings even if it's not actually supported (i.e plugins). Something to improve further.
This helps to fix `@swc/core`'s fallback binding behavior to prevent pass incorrect params to the fallback bindings functions.
=> feat(swc/wasm): typed interface support for wasm bindings

crates/binding_core_wasm/Cargo.toml
This PR enables interning string feature from wasm-bindgen (https://github.com/rustwasm/wasm-bindgen/blob/062aa5f70a1e8a170d0ae90123ebdeb3242ac782/CHANGELOG.md) . This is not well exposed in the docs somehow.
While it _sounds_ like a nice improvement, it is not clear if it'll give a noticeable gain for us. I felt it's worth trying if we haven't done this before.
I tried quick search but I may miss history if we did this & revert. If that's the case, please feel free to close.
=> feat(swc/wasm): enable interning strings

.rustfmt.toml, Cargo.lock, crates/binding_core_wasm/Cargo.toml, crates/binding_core_wasm/__tests__/simple.js, crates/binding_core_wasm/src/lib.rs, crates/swc/src/config/mod.rs
This PR implements, exposes counterpart of `*Sync` interfaces to `@swc/wasm`, as same as `@swc/core`. It'll allow `@swc/wasm` becomes near-complete drop in replacement to `@swc/core` as much as possible.
One important thing to note is, even though those are async interfaces there aren't any actual async implementation in place. In short, this is pretty much similar to JS-side facade wrap like `new Promise(() => swcSync())`, which only wraps sync interfaces to async. The only difference is it is exposed in bindgen level, so we don't need to come up with some custom binding wrapper to make things work.
Once there is support for the thread / async in wasm with standard support we'll update those internals accordingly. We do not expect to try some workaround approach like …
=> feat(swc/wasm): expose async facade interfaces

crates/swc_ecma_utils/src/lib.rs, crates/swc_ecma_utils/src/macros.rs
This PR allows `quote_ident!` from utils macro works within swc_core, by resolving inner references expansion to its own transitive deps.
=> fix(swc/utils): allow quote_ident works with swc_core

Cargo.lock, Cargo.toml, crates/binding_core_wasm/Cargo.toml, crates/binding_core_wasm/src/lib.rs, crates/binding_macros/Cargo.toml, crates/binding_macros/build.rs, crates/binding_macros/src/lib.rs, crates/binding_macros/src/wasm.rs, crates/swc_core/Cargo.toml, crates/swc_core/src/lib.rs
Partially implements https://github.com/swc-project/swc/issues/5395.
This PR attempts to explore possibility to `swc_core` exposes set of builder macro to create binding functions for the SWC's features. As a first step, PR replaces all existing wasm binding implementation into naive macro-based expansion.
Key takeaway for this approach is, in most cases if someone wants to customize SWC's behavior to create custom binary they'll likely need few customization points only. For example, `transform*`'s `before / custom_pass` is what ppl mostly need if they want custom SWC binary, but it still requires to repeat existing codes compare to SWC's binding those. Macro tries to accept those as customizable param, and then scaffold boilerplate instead.
`binding_core_wasm` in result …
=> feat(binding_macros): wasm binding macro

crates/binding_core_wasm/src/lib.rs, crates/binding_macros/src/wasm.rs
Minor update to import references. 
I'll leave `wasm_bindgen` macro requires direct dep due to proc_macro for now, it may require amount of work compare to gain. Since caller need to assign attribute explicitly if needed, it somewhat makes sense to make it as direct dep anyway.
=> refactor(binding_macros): update import references

crates/swc_ecma_transforms_compat/src/es2017/async_to_generator.rs
- closes https://github.com/swc-project/swc/issues/5469
Personally I'm fine if we can use unstable syntax encapsulated in swc's codebase, but this leaks into user level for the ppl wants to write plugins or custom binary.
=> refactor(swc/transforms): remove unstable syntax

Cargo.lock, crates/swc_common/Cargo.toml, crates/swc_common/src/syntax_pos.rs, crates/swc_core/Cargo.toml, crates/swc_plugin_macro/Cargo.toml, crates/swc_plugin_macro/src/lib.rs, crates/swc_plugin_proxy/Cargo.toml, crates/swc_plugin_proxy/src/source_map/plugin_source_map_proxy.rs, crates/swc_plugin_runner/Cargo.toml, crates/swc_plugin_runner/src/imported_fn/mod.rs, crates/swc_plugin_runner/src/imported_fn/source_map.rs, node-swc/e2e/fixtures/plugin_transform_schema_vtest/Cargo.lock
- closes https://github.com/swc-project/swc/issues/5471
PR improves sourcemap proxy to copy `SourceFile` only once into plugin and reuse it for subsequent calls. This works since plugin is per each transform cycle that we can expect single SourceFile will live.
=> fix(swc/plugin_runner): share SourceFile for the comments

Cargo.lock, crates/swc_core/Cargo.toml, crates/swc_core/build.rs, crates/swc_core/src/lib.rs, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/Cargo.lock
Recent debugging experiences made me feel it'd be easier to have some metadata we can ask in runtime to figure out `what exact code we are running?` Especially this'll be valuable when we try to diagnose host-guest mismatches.
PR introduces build time metadata. previously we have one for the pkg version but it was mostly utility for the cli bootstrap. Newly introduced metadata includes pkg version, as well as some meaningful information like git sha + cargo features enabled at the build time to ensure we're running the codes we want.
Once this goes in, all of bindings (node, wasm, cli) can adapt this to display / or expose interfaces. Previous target triple, or pkg constant will be consolidated into this. 
Vergen have lot more useful variable …
=> feat(swc/core): provide build-time metadata diagnostics

crates/dbg-swc/src/minify/ensure_size.rs, crates/swc_ecma_minifier/tests/golden.txt, crates/swc_ecma_minifier/tests/postponed.txt
```
Total
swc: 32898142 bytes
terser: 32956139 bytes
Size ratio: 0.998240176132283
swc produced smaller or equal output for 897 files out of 999 files, 89.79%
```
=> feat(dbg-swc): Improve minifier comparator

crates/swc_css_ast/src/at_rule.rs, crates/swc_css_codegen/src/lib.rs, crates/swc_css_parser/src/parser/at_rule.rs, crates/swc_css_prefixer/src/prefixer.rs, crates/swc_css_visit/src/lib.rs
`keyword` is like `raw` required only for linter, but we don't need to spend time on it in transformations
Yes
No
=> feat(css/parser): make `keyword` optional

crates/swc/tests/tsc-references/errorSuperPropertyAccess_es5.1.normal.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers1_es2015.1.normal.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers1_es2015.2.minified.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers1_es5.1.normal.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers1_es5.2.minified.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers2_es2015.1.normal.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers2_es2015.2.minified.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers2_es5.1.normal.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers2_es5.2.minified.js, crates/swc_ecma_transforms_base/src/helpers/_update.js, crates/swc_ecma_transforms_base/src/helpers/mod.rs, crates/swc_ecma_transforms_classes/src/super_field.rs, crates/swc_ecma_transforms_compat/src/es2015/classes/mod.rs, crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs, crates/swc_ecma_transforms_compat/tests/es2015_classes.rs, crates/swc_ecma_transforms_compat/tests/es2022_class_properties.rs, crates/swc_ecma_transforms_proposal/src/decorators/mod.rs, packages/swc-helpers/src/_update.mjs
This PR fix the following code.
```JavaScript 
class B {
static a = 1;
}
class C extends B {
static z8 = [super.a] = [0];
static z14 = ++super.a;
static z15 = --super.a;
static z16 = ++super["a"];
}
console.log(B.a, C.a, C.z14, C.z15, C.z16);
```
=> fix(es/compat): Destructuring assignments and updates of super prop

bindings/swc_cli/src/commands/plugin.rs, crates/swc_common/src/plugin/diagnostics.rs, crates/swc_common/src/plugin/mod.rs, crates/swc_plugin_macro/src/lib.rs, crates/swc_plugin_runner/src/imported_fn/diagnostics.rs, crates/swc_plugin_runner/src/imported_fn/mod.rs, crates/swc_plugin_runner/src/load_plugin.rs, crates/swc_plugin_runner/src/transform_executor.rs, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/Cargo.lock, crates/swc_plugin_runner/tests/integration.rs, node-swc/e2e/plugins/plugins.schema.test.js
This PR implements a new interface from plugin to expose it's core engine diag for `swc_core`. 
Host (plugin_runner) will call it immediately once plugin instance is ready. These values can be used to determine plugin's status / incompatiblity in runtime, in case if we need to branch execution depends on the semver major.
As noted in comment, this is considered as `handshake` and we have to extremely careful to not to break those interface - which means we need to reintroduce forward compat schema version again soon.
This is a breaking changes for the plugin. We need to release new `@swc/core` and `swc_core` both. I was thinking if we should make this as non-breaking, while techinically possible I decided to make one another breaking as this'll be …
=> feat(swc/plugin): provide swc_core diag from plugin

packages/swc-helpers/src/_class_static_private_field_spec_set.mjs
=> fix(es/helpers): Fix `_classStaticPrivateFieldSpecSet`

crates/swc/tests/tsc-references/parserForOfStatement23_es2015.1.normal.js, crates/swc/tests/tsc-references/parserForOfStatement23_es2015.2.minified.js, crates/swc/tests/tsc-references/parserForOfStatement23_es5.1.normal.js, crates/swc/tests/tsc-references/parserForOfStatement23_es5.2.minified.js, crates/swc_ecma_parser/src/error.rs, crates/swc_ecma_parser/src/lib.rs, crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_parser/src/parser/stmt.rs, crates/swc_ecma_parser/tests/errors/ts1106/input.js, crates/swc_ecma_parser/tests/errors/ts1106/input.js.stderr
Invalid:
```JavaScript
for (async of []) {}
```
Valid
```JavaScript
for await (async of []) {}
```
=> fix(es/parser): Handle `async` in `for...of`

crates/swc_ecma_minifier/src/alias/mod.rs
I found that `JSON` is treated as an alias and it prevents proper minification
=> feat(es/minifier): Exclude `JSON` from alias list

Cargo.lock, crates/swc_ecma_transforms_optimization/Cargo.toml, crates/swc_ecma_transforms_optimization/src/simplify/dce/mod.rs, crates/swc_fast_graph/src/digraph.rs
```
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 9.8s.
Benchmarking es/minify/libraries/antd: Collecting 10 samples in estimated 9.7858 s (10 iterations)
time:   [973.97 ms 978.17 ms 982.84 ms]
change: [-14.484% -13.774% -13.119%] (p = 0.00 < 0.05)
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target …
```
=> perf(es/minifier): Use faster hash algorithm for DCE

crates/swc_ecma_minifier/src/pass/precompress.rs
We don't use analyzed information.
```
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 9.5s.
Benchmarking es/minify/libraries/antd: Collecting 10 samples in estimated 9.4594 s (10 iterations)
time:   [945.03 ms 959.04 ms 976.73 ms]
change: [-6.7750% -5.3805% -3.9554%] (p = 0.00 < 0.05)
Found 2 outliers among 10 measurements (20.00%)
2 (20.00%) high severe
Warning: Unable to complete 10 samples in …
```
=> perf(es/minifier): Optimize precompress optimizer

crates/swc_ecma_minifier/src/compress/mod.rs
We don't need to run full analyzer if both of options are false
=> perf(es/minifier): Skip useless analysis if not required

Cargo.lock, crates/swc_ecma_transforms_base/Cargo.toml, crates/swc_ecma_transforms_base/src/perf.rs, crates/swc_ecma_utils/Cargo.toml, crates/swc_ecma_utils/src/lib.rs, crates/swc_ecma_utils/src/parallel.rs
This PR moves some of utilities for parallel processing from `swc_ecma_transforms_base` to `swc_ecma_utils`.
=> refactor(es/utils): Move utilities for parallel processing

crates/swc_ecma_transforms_base/src/rename/ops.rs, crates/swc_ecma_transforms_optimization/src/simplify/branch/mod.rs, crates/swc_ecma_transforms_optimization/src/simplify/dce/mod.rs
```
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 9.1s.
Benchmarking es/minify/libraries/antd: Collecting 10 samples in estimated 9.1326 s (10 iterations)
time:   [897.64 ms 900.99 ms 904.84 ms]
change: [-1.9042% -1.3876% -0.8290%] (p = 0.00 < 0.05)
Change within noise threshold.
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 9.0s or enable flat sampling. …
```
=> perf(es/minifier): Make passes more parallel

crates/swc_ecma_minifier/src/analyzer/storage/normal.rs
I'll post the performance diff soon
```
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 9.1s.
Benchmarking es/minify/libraries/antd: Collecting 10 samples in estimated 9.0816 s (10 iterations)
time:   [903.22 ms 906.13 ms 909.13 ms]
change: [-2.2690% -1.7972% -1.3301%] (p = 0.00 < 0.05)
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 8.8s or enable flat sampling.
Benchmarking es/minify/libraries/d3: …
```
=> perf(es/minifier): Pre-allocate in analyzer

crates/swc_ecma_transforms_optimization/src/simplify/dce/mod.rs
We don't need to store it in the graph. Storing it in a fast hash set is enough.
```
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 8.7s.
Benchmarking es/minify/libraries/antd: Collecting 10 samples in estimated 8.6817 s (10 iterations)
time:   [864.75 ms 868.50 ms 871.61 ms]
change: [-3.0474% -2.5227% -2.0182%] (p = 0.00 < 0.05)
1 (10.00%) low mild …
```
=> perf(es/minifier): Use efficient logic for entry tracking in DCE

crates/swc_ecma_minifier/src/compress/mod.rs, crates/swc_ecma_transforms_optimization/src/simplify/dce/mod.rs
```
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 8.6s.
Benchmarking es/minify/libraries/antd: Collecting 10 samples in estimated 8.6131 s (10 iterations)
time:   [859.87 ms 863.75 ms 867.53 ms]
change: [-15.382% -9.3986% -5.5054%] (p = 0.00 < 0.05)
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 9.3s or enable flat sampling.
Benchmarking …
```
=> perf(es/minifier): Cache the list of bindings for DCE

crates/swc_ecma_codegen/src/text_writer.rs, crates/swc_ecma_minifier/src/pass/mangle_names/mod.rs
We don't need char-related operations
```
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 8.2s.
Benchmarking es/minify/libraries/antd: Collecting 10 samples in estimated 8.1602 s (10 iterations)
time:   [805.67 ms 808.53 ms 811.18 ms]
change: [-0.9558% -0.4031% +0.1414%] (p = 0.19 > 0.05)
No change in performance detected.
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 8.9s or enable …
```
=> perf(es/minifier): Improve codegen of name mangler

crates/swc/tests/tsc-references/conflictingCommonJSES2015Exports.2.minified.js, crates/swc/tests/tsc-references/jsDeclarationsEnumTag.2.minified.js, crates/swc/tests/tsc-references/jsDeclarationsFunctionJSDoc.2.minified.js, crates/swc/tests/tsc-references/jsDeclarationsFunctions.2.minified.js, crates/swc/tests/tsc-references/namedTupleMembers.2.minified.js, crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/src/option/terser.rs, crates/swc_ecma_minifier/tests/fixture/issues/4515/output.js, crates/swc_ecma_minifier/tests/fixture/issues/react/hooks/3/output.js
Terser has since fixed this bug and it's no longer needed.
=> fix(es/minifier): don't drop params in exported function

crates/swc_ecma_codegen/src/text_writer/basic_impl.rs
The column is used only for sourcemap, so we can skip `chars().count()` if we are not generating source maps.
=> perf(es/codegen): Skip useless operations if not required

crates/swc_css_codegen/src/writer/basic.rs
The column is used only for sourcemap, so we can skip `chars().count()` if we are not generating source maps.
=> perf(css/codegen): Skip useless operations if not required

crates/swc_css_parser/src/parser/at_rule.rs, crates/swc_css_parser/src/parser/value/mod.rs
We don't need unicode handling in these cases.
=> perf(css/parser): Use ascii operations

node-swc/src/types.ts
Fix the type definition of `jsc.paths`.
=> fix(node/types): correct type for jsc.paths

crates/swc_css_ast/src/at_rule.rs, crates/swc_css_ast/src/base.rs, crates/swc_css_ast/src/selector.rs, crates/swc_css_ast/src/value.rs, crates/swc_css_codegen/src/lib.rs, crates/swc_css_lints/src/lib.rs, crates/swc_css_lints/src/rules/at_rule_no_unknown.rs, crates/swc_css_lints/src/rules/declaration_no_important.rs, crates/swc_css_lints/src/rules/keyframe_declaration_no_important.rs, crates/swc_css_lints/src/rules/no_duplicate_at_import_rules.rs, crates/swc_css_lints/src/rules/no_invalid_position_at_import_rule.rs, crates/swc_css_minifier/src/compress/at_rule.rs, crates/swc_css_minifier/src/compressor/empty.rs, crates/swc_css_minifier/src/compressor/keyframes.rs, crates/swc_css_minifier/src/compressor/selector.rs, crates/swc_css_minifier/src/compressor/url.rs, crates/swc_css_minifier/src/lib.rs, crates/swc_css_parser/src/parser/at_rule.rs, crates/swc_css_parser/src/parser/value/mod.rs, crates/swc_css_prefixer/src/lib.rs, crates/swc_css_prefixer/src/prefixer.rs, crates/swc_css_visit/src/lib.rs, crates/swc_html_minifier/src/lib.rs
```
Benchmarking css/minify/libraries/bootstrap
Benchmarking css/minify/libraries/bootstrap: Warming up for 3.0000 s
Benchmarking css/minify/libraries/bootstrap: Collecting 10 samples in estimated 5.2997 s (825 iterations)
Benchmarking css/minify/libraries/bootstrap: Analyzing
css/minify/libraries/bootstrap
time:   [6.4418 ms 6.4475 ms 6.4558 ms]
change: [-21.738% -21.403% -21.047%] (p = 0.00 < 0.05)
```
=> perf(css): Optimize memory layout of ast types

Cargo.lock, crates/swc_atoms/Cargo.toml, crates/swc_atoms/src/lib.rs
This patch reduces the memory footprint
---
```
heap stats:    peak      total      freed    current       unit      count
reserved:  512.1 MiB  512.1 MiB  256.0 MiB  256.1 MiB                        not all freed!
committed:  512.1 MiB  512.1 MiB  256.0 MiB  256.1 MiB                        not all freed!
reset:   13.2 MiB  775.2 MiB  896.9 MiB -121.7 MiB                        ok
touched:      0          0       53.9 GiB  -53.9 GiB                        ok
segments:     40        1.5 Ki     1.5 Ki       5                            not all freed!
-abandoned:      0          0          0          0                            ok
-cached:      0          0          0          0                            ok
pages:    2.0 Ki   956.6 Ki   956.5 Ki      28 …
```
=> perf(atoms): Reduce size of `Atom`

crates/swc_ecma_parser/src/lexer/number.rs, crates/swc_ecma_parser/src/lexer/state.rs, crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_parser/src/parser/object.rs, crates/swc_ecma_parser/src/parser/typescript.rs, crates/swc_ecma_parser/src/token.rs
I boxed `BigIntValue` in `Token` type to make `TokenAndSpan` smaller and made the parser use `Vec` instead of `SmallVec` for token contexts.
```
es/parser/colors        time:   [15.251 us 15.258 us 15.265 us]
es/parser/angular       time:   [7.8481 ms 7.8576 ms 7.8684 ms]
es/parser/backbone      time:   [1.1110 ms 1.1124 ms 1.1143 ms]
es/parser/jquery        time:   [6.1279 ms 6.1357 ms 6.1458 ms]
es/parser/jquery mobile time:   [9.6091 ms 9.6207 ms 9.6346 ms]
es/parser/mootools      time:   [4.6403 ms 4.6483 ms 4.6582 ms]
es/parser/underscore    time:   [949.03 us 949.69 us 950.50 us]
es/parser/three         time:   [27.706 ms 27.747 ms 27.795 ms]
es/parser/yui           time:   [4.6905 ms 4.6970 ms 4.7049 ms]
```
```
es/parser/colors        time:   [14.922 us 14.932 us …
```
=> perf(es/parser): Optimize memory layout

crates/swc/tests/fixture/issues-5xxx/5189/1/input/.swcrc, crates/swc/tests/fixture/issues-5xxx/5189/1/input/index.ts, crates/swc/tests/fixture/issues-5xxx/5189/1/output/index.ts, crates/swc_ecma_transforms/tests/fixture/legacy-only/issues/swc-node-210/output.ts, crates/swc_ecma_transforms_proposal/src/decorators/legacy/mod.rs
- Closes https://github.com/swc-project/swc/issues/5189.
=> fix(es/compat): Fix the order of initialization for decorators on computed keys

crates/swc_ecma_minifier/src/compress/optimize/iife.rs, crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/src/compress/optimize/util.rs
This PR splits the `MultiReplacer` into two variants. The first one is the cloning version, and this is parallel. The other one is the non-cloning version, which is not parallel.
=> perf(es/minifier): Optimize `MultiReplacer`

.github/workflows/cargo.yml, crates/swc/benches/typescript.rs, crates/swc/src/lib.rs, crates/swc/tests/error_msg.rs, crates/swc/tests/exec.rs, crates/swc/tests/tsc-references/importTypeInJSDoc.1.normal.js, crates/swc/tests/tsc.rs, crates/swc_common/src/syntax_pos.rs, crates/swc_estree_compat/tests/convert.rs, crates/swc_node_bundler/tests/fixture.rs
We don't need to share one instance of `Globals`.
---
Added log: 
```
DEBUG  ===== Before pure =====
"use strict";
function _checkPrivateRedeclaration(obj, privateCollection) {
if (privateCollection.has(obj)) {
throw new TypeError("Cannot initialize the same private elements twice on an object");
}
}
function _classApplyDescriptorGet(receiver, descriptor) {
if (descriptor.get) {
return descriptor.get.call(receiver);
}
return descriptor.value;
}
function _classExtractFieldDescriptor(receiver, privateMap, action) {
if (!privateMap.has(receiver)) {
throw new TypeError("attempted to " + action + " private field on non-instance");
}
return privateMap.get(receiver);
}
function _classPrivateFieldGet(receiver, privateMap) {
var descriptor = _classExtractFieldDescriptor(receiver, …
```
=> perf(es): Don't share `Globals`

crates/swc_ecma_minifier/src/compress/optimize/evaluate.rs, crates/swc_ecma_minifier/src/compress/pure/misc.rs, crates/swc_ecma_minifier/tests/exec.rs, crates/swc_ecma_minifier/tests/fixture/next/feedback-regex/input.js, crates/swc_ecma_minifier/tests/fixture/next/feedback-regex/output.js, crates/swc_ecma_minifier/tests/fixture/next/react-pdf-renderer/output.js, crates/swc_ecma_minifier/tests/fixture/next/syncfusion/933-e9f9a6bf671b96fc/output.js
- https://github.com/vercel/next.js/discussions/30237#discussioncomment-3793184
=> fix(es/minifier): Don't evaluate `String.fromCharCode` for non-ascii values

crates/swc/tests/exec.rs, crates/swc/tests/exec/issues-6xxx/6029/exec.js, crates/swc_ecma_transforms_compat/src/es2018/object_rest_spread.rs, crates/swc_ecma_transforms_compat/tests/es2018_object_rest_spread.rs
- Closes https://github.com/swc-project/swc/issues/6029
=> fix(es/compat): Fix handling of deep array pattern of object rest pass

crates/swc/Cargo.toml, crates/swc_bundler/Cargo.toml, crates/swc_config/Cargo.toml, crates/swc_ecma_minifier/Cargo.toml, crates/swc_ecma_preset_env/Cargo.toml, crates/swc_ecma_transforms_module/Cargo.toml, crates/swc_ecma_utils/Cargo.toml, crates/swc_fast_graph/Cargo.toml
We are experiencing https://github.com/tkaitchuck/aHash/issues/95 when we try to bring some deps into next-swc. Looks like using indexmap 1.6.1 seems most straightforward way to avoid, I'd like to try this as first step. 
=> build(cargo): dedupe indexmap with known version

.github/workflows/bot.yml
=> chore(ci): Extract bot action to a separate repository

Cargo.lock, crates/swc_core/Cargo.toml, crates/swc_core/src/lib.rs
Allow users of the swc_core crate to access swc_ecma_preset_env
Test Plan: Referenced a local checkout and imported and used several structures + the fold fn from the preset_env module.
=> Export swc_ecma_preset_env through swc_core

crates/swc_ecma_minifier/src/option/mod.rs, crates/swc_ecma_minifier/src/option/terser.rs
This is to align with terser. There's no test change, though.
I'll merge this so we can see diff of real-world test cases when working on `reduce_fucs`.
=> feat(es/minifier): Enable `reduce_funcs` by default

crates/swc_core/src/lib.rs
=> fix(swc_core): Reexport `swc_css_compat` correctly

crates/swc_css_ast/src/selector.rs, crates/swc_css_codegen/src/lib.rs, crates/swc_css_parser/src/parser/selector/mod.rs, crates/swc_css_parser/tests/fixture/selector/pseudo-element/highlight/input.css, crates/swc_css_parser/tests/fixture/selector/pseudo-element/highlight/output.json, crates/swc_css_parser/tests/fixture/selector/pseudo-element/highlight/span.rust-debug, crates/swc_css_visit/src/lib.rs
[](https://www.w3.org/TR/css-highlight-api-1/#typedef-custom-highlight-name)
Yes
No
=> feat(css/parser): parse highlight

crates/dbg-swc/src/util/minifier.rs
This PR removes comments by parsing and printing using swc APIs because the comments disturb looking at diffs.
=> feat(dbg-swc): Remove comments from the output of `terser`

crates/swc_ecma_quote_macros/src/ast/expr.rs
Just find out that there is a missing field `span` in Tpl when I'm using quote macro, when I use quote!("\`Hello\`" as Box<Expr>) macro expansion failed because missing field span here.
It seems that there are no tests for this macro right ? If there are, please let me know so I can add test about it.
=> fix(quote_macros/expr): fix quote macro with template string struct

.cargo/config.toml, Cargo.lock, crates/swc_plugin_runner/Cargo.toml, crates/swc_plugin_runner/src/cache.rs
This PR disables SIMD for all hosts because wasmer cache is not portable.
=> fix(es/plugin): Disable SIMD

crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/tests/fixture/issues/6146/input.js, crates/swc_ecma_minifier/tests/fixture/issues/6146/output.js, crates/swc_ecma_minifier/tests/fixture/issues/vercel/007/output.js, crates/swc_ecma_minifier/tests/terser/compress/template_string/tagged_call_with_invalid_escape_2/output.js, crates/swc_ecma_transforms_optimization/src/simplify/expr/mod.rs
- Closes https://github.com/swc-project/swc/issues/6146
=> fix(es/minifier): Preserve `this` of tagged template literals

crates/swc_ecma_codegen/src/typescript.rs, crates/swc_ecma_codegen/tests/fixture/issues/6171/input.ts, crates/swc_ecma_codegen/tests/fixture/issues/6171/output.ts
This change updates `swc_ecma_codegen` so that it emits a `readonly` modified on index signatures when appropriate.
This is a minor bug fix and people shouldn't have been relying on the current behaviour.
Closes #6171
=> fix(es/codegen): Ensure 'readonly' modified included when emitting TsIndexSignature

.github/workflows/lock.yml
Lefting a comment on an old issue does not help at all, so I'm adding an action to lock them.
=> chore(ci): Lock old issues automatically

crates/swc_css_minifier/src/compressor/mod.rs, crates/swc_css_minifier/tests/fixture/compress-calc/supports-condition/input.css, crates/swc_css_minifier/tests/fixture/compress-calc/supports-condition/output.min.css
Don't tocuh `@supports`, because it can be used for check a support of `calc`, so
```css
// Will not work in old browser
@supports (width: calc(100px + 100px)) {
div {
background: red;
}
}
```
will be
```css
// Will work in odl browser
@supports (width: 200px) {
div {
background: red;
}
}
```
But some styles can be used for old browser (and verca vise), this is definitely not the expected behavior
No
No
=> fix(css/minifier): don't touch `@supports`

crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/tests/fixture/element/style-group-2/config.json, crates/swc_html_minifier/tests/fixture/element/style-group-2/input.html, crates/swc_html_minifier/tests/fixture/element/style-group-2/output.min.html, crates/swc_html_minifier/tests/fixture/element/style-group/output.min.html
=> fix(html/minifier): bug with merging and removing metadata elements

crates/swc_html_ast/src/base.rs, crates/swc_html_ast/src/token.rs
=> fix(html/ast): Fix compilation

crates/swc_ecma_transforms_classes/src/super_field.rs, crates/swc_ecma_transforms_compat/tests/es2015_classes.rs, crates/swc_ecma_transforms_compat/tests/es2022_class_properties.rs
Seems like to be caused by #5576 cc @magic-akari 
closes #5936
=> fix(es/compat): Super method call in loose mode

crates/swc/tests/tsc-references/privateNameAndPropertySignature.1.normal.js, crates/swc/tests/tsc-references/privateNameAndPropertySignature.2.minified.js, crates/swc_ecma_parser/src/error.rs, crates/swc_ecma_parser/tests/test262-error-references/fail/665ab370012f20cf.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/6cd36f7e68bdfb7a.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/971cf622ebaef28e.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/c7ad2478fd72bffe.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/e808e347646c2670.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/efcb54b62e8f0e06.js.stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/f2db53245b89c72f.js.stderr, crates/swc_ecma_parser/tests/typescript-errors/issue-1211-1/input.ts.stderr
No functional changes.
Fix a typo in error messages.
=> Fix typo in 'now->not allowed'

crates/swc/src/config/mod.rs
Options missing unresolved_mark field
It's a breaking change I know but the usage of current implementation is hard to use, or maybe I did it wrong.
It's very easily to encounter lifetime limitation.
```rust
compiler.process_js_with_custom_pass(..., |_, comments| { build_pass(comments) });
-----------------------------------------------^^^^^^^ compile error
```
I believe this is a common pattern, `build_pass` should hold the comments' lifetime, but borrow checker would not allow this.
So I think maybe pass `comments` to it should be a better idea.
If anything wrong with my point of view, please tell me
=> fix: change process_js_with_custom_pass api

crates/swc/tests/fixture/deno/paths/cjs-001/output/index.ts, crates/swc/tests/fixture/deno/paths/ext/002/output/index.js, crates/swc/tests/fixture/deno/paths/issue-2126/output/src/index.ts, crates/swc/tests/fixture/deno/paths/issue-2724/output/src/index.ts, crates/swc/tests/fixture/deno/paths/issue-2844/output/src/index.ts, crates/swc/tests/fixture/deno/paths/issue-3447/output/src/index.ts, crates/swc/tests/fixture/issues-2xxx/2050/output/index.ts, crates/swc/tests/fixture/issues-5xxx/5214/1/output/input1.js, crates/swc/tests/fixture/issues-6xxx/6209/1/input/.swcrc, crates/swc/tests/fixture/issues-6xxx/6209/1/input/index.js, crates/swc/tests/fixture/issues-6xxx/6209/1/input/src/sum.ts, crates/swc/tests/fixture/issues-6xxx/6209/1/output/index.js, crates/swc/tests/fixture/issues-6xxx/6209/1/output/src/sum.ts, crates/swc_ecma_transforms_module/src/path.rs, crates/swc_ecma_transforms_module/tests/fixture-manual/issue-4730/output/index.js, crates/swc_ecma_transforms_module/tests/paths/issue-4532/output/index.ts, crates/swc_ecma_transforms_module/tests/paths/issue-4585/output/index.ts, crates/swc_ecma_transforms_module/tests/paths/issue-4605/1/output/index.ts, crates/swc_ecma_transforms_module/tests/paths/issue-4605/2/output/index.ts, crates/swc_ecma_transforms_module/tests/paths/issue-4619/1/output/index.ts, crates/swc_ecma_transforms_module/tests/paths/issue-4619/2/output/index.ts, packages/swc-helpers/package.json
- Closes https://github.com/swc-project/swc/issues/6209.
=> fix(es/modules): Preserve extensions

crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_transforms_base/src/resolver/mod.rs, crates/swc_ecma_transforms_base/tests/ts-resolver/stc/1/input.ts, crates/swc_ecma_transforms_base/tests/ts-resolver/stc/1/output.ts, crates/swc_ecma_transforms_base/tests/ts-resolver/ts_resolver_import_and_implements/output.ts, crates/swc_ecma_transforms_base/tests/ts-resolver/ts_resolver_parameter_property/output.ts
- https://github.com/dudykr/stc/pull/245.
=> fix(es/resolver): Resolve interfaces correctly

crates/swc/tests/fixture/issues-6xxx/6420/input/input.js, crates/swc/tests/fixture/issues-6xxx/6420/output/input.js, crates/swc_ecma_utils/src/lib.rs
=> fix(es/utils): Verify alias ident name

crates/swc_plugin_proxy/src/memory_interop/mod.rs, crates/swc_plugin_proxy/src/memory_interop/read_returned_result_from_host.rs, crates/swc_plugin_proxy/src/source_map/plugin_source_map_proxy.rs, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/Cargo.lock, crates/swc_plugin_runner/tests/fixture/swc_noop_plugin/Cargo.lock
Trying to apply some changes for https://github.com/swc-project/swc/issues/6404, but before doing it attempts to simplify control flows mostly for the readers (human). `read_returned_result_from_host_*` is supposed to be called from plugin binary only, changes conditional to be applied into whole fn itself instead of inner partial logic to easily read through whole flows.
=> refactor(swc/plugin_proxy): simplify read_result_* control flow

crates/swc_ecma_transforms_module/src/path.rs
- Closes https://github.com/swc-project/swc/issues/6432.
---
https://github.com/Nickersoft/swc-paths/blob/main/package.json
I verified that it's fixed by using `npm link`
=> fix(es/modules): Fix `jsc.paths` of `.ts` imports

Cargo.lock, bindings/Cargo.lock, bindings/binding_core_wasm/Cargo.toml, bindings/binding_core_wasm/src/lib.rs, crates/binding_macros/Cargo.toml, crates/binding_macros/src/wasm.rs
Refactor wasm binding to not to use `JsValue::*_serde`. It is effectively deprecated (https://github.com/rustwasm/wasm-bindgen/pull/3031) , and also one of the reason to create circular dependencies around indexmap.
=> refactor(bindings/wasm): deprecate jsvalue::*_serde

crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/tests/fixture/element/script-group/input.html, crates/swc_html_minifier/tests/fixture/element/script-group/output.min.html, crates/swc_html_minifier/tests/fixture/element/style-group/input.html, crates/swc_html_minifier/tests/fixture/element/style-group/output.min.html
=> fix(html/minifier): small merge fix

crates/swc/tests/errors/lints/const-assign/3/input.js, crates/swc/tests/errors/lints/const-assign/3/output.swc-stderr, crates/swc/tests/tsc-references/assignmentToParenthesizedIdentifiers.1.normal.js, crates/swc/tests/tsc-references/assignmentToParenthesizedIdentifiers.2.minified.js, crates/swc/tests/tsc-references/assignments.1.normal.js, crates/swc/tests/tsc-references/assignments.2.minified.js, crates/swc/tests/tsc-references/invalidUndefinedAssignments.1.normal.js, crates/swc/tests/tsc-references/invalidUndefinedAssignments.2.minified.js, crates/swc/tests/tsc-references/validNullAssignments.1.normal.js, crates/swc/tests/tsc-references/validNullAssignments.2.minified.js, crates/swc_ecma_lints/src/rules/const_assign.rs
- Closes https://github.com/swc-project/swc/issues/6471.
=> fix(es/lints): Revert check for reassignment to classes

crates/swc/tests/tsc-references/objectSpreadSetonlyAccessor.2.minified.js, crates/swc_atoms/words.txt, crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/tests/fixture/issues/6422/1/config.json, crates/swc_ecma_minifier/tests/fixture/issues/6422/1/input.js, crates/swc_ecma_minifier/tests/fixture/issues/6422/1/output.js, crates/swc_ecma_minifier/tests/fixture/issues/6422/2/config.json, crates/swc_ecma_minifier/tests/fixture/issues/6422/2/input.js, crates/swc_ecma_minifier/tests/fixture/issues/6422/2/output.js, crates/swc_ecma_minifier/tests/fixture/issues/6422/3/config.json, crates/swc_ecma_minifier/tests/fixture/issues/6422/3/input.js, crates/swc_ecma_minifier/tests/fixture/issues/6422/3/output.js, crates/swc_ecma_utils/src/lib.rs
=> fix(es/minifier): should not drop statements which has side-effects

crates/swc/src/builder.rs, crates/swc/src/lib.rs, crates/swc/tests/fixture/issues-6xxx/6373/input/.swcrc, crates/swc/tests/fixture/issues-6xxx/6373/input/input.js, crates/swc/tests/fixture/issues-6xxx/6373/output/input.js, crates/swc/tests/tsc-references/privateNameInInExpressionUnused.1.normal.js, crates/swc/tests/tsc-references/privateNameInInExpressionUnused.2.minified.js, crates/swc_ecma_parser/src/lib.rs, crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_parser/tests/test262-error-references/fail/c3731145e0e65d1d.js.stderr, crates/swc_ecma_transforms_compat/tests/es2015_new_target.rs, crates/swc_ecma_transforms_compat/tests/es2022_private_in_object.rs, crates/swc_ecma_transforms_typescript/tests/strip_correctness.rs
private in object has already landed in ES2022 and there're many browsers supporting it, so related config can be removed. This won't be a break change for JS side as currently `serde` only checks extra fields in top level.
closes #6373
=> fix(es): Remove `privateInObject` related setting

crates/swc/tests/fixture/issues-6xxx/6438/input/.swcrc, crates/swc/tests/fixture/issues-6xxx/6438/input/index.js, crates/swc/tests/fixture/issues-6xxx/6438/output/index.js, crates/swc_ecma_codegen/src/lib.rs
=> fix(es/codegen): Preserve parentheses for new expr in optional chaining

.github/workflows/CI.yml
Curious if we're interested in having reduced scope to trigger pr workflow? currently it is wide, runs all CI workflow for the commit / pr both when new commit's being updated in pull request. `synchronize` supposed to do the work for the pr, while we keep main branch push behavior as is.
ref: https://github.com/vercel/next.js/blob/canary/.github/workflows/build_test_deploy.yml#L3-L5
=> ci(actions): scope pr trigger type

.github/workflows/bench.yml
Minor optimization for ci workflow: people can run ci on fork for various reasons (I do it for testing before PR) but running benchmark doesn't make sense lot as it is uncontrolled machine doesn't give reliable number anyway. 
PR changes flow to shortcurcuit those to not waste ci turnaround time for the fork.
=> ci(actions): skip benchmark on fork

.github/workflows/publish-node.yml, scripts/cli_upload_gh_release.sh
This PR tries to upload CLI binaries to gh release.
I hoped to verify this before creating PR, but in the fork however I try I couldn't pass napi to create github release successfuly. :/
=> build(publish): upload cli binaries to gh release

crates/swc/tests/tsc-references/classStaticBlock15(target=es2022).2.minified.js, crates/swc/tests/tsc-references/classStaticBlock23.2.minified.js, crates/swc/tests/tsc-references/classStaticBlock5(target=es2022).2.minified.js, crates/swc/tests/tsc-references/classStaticBlockUseBeforeDef1.2.minified.js, crates/swc/tests/tsc-references/classStaticBlockUseBeforeDef2.2.minified.js, crates/swc/tests/tsc-references/privateNameComputedPropertyName4(target=es2022).2.minified.js, crates/swc/tests/tsc-references/superInStaticMembers1(target=es2022).2.minified.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers1(target=es2022).2.minified.js, crates/swc/tests/tsc-references/thisAndSuperInStaticMembers2(target=es2022).2.minified.js, crates/swc/tests/tsc-references/typeOfThisInStaticMembers10(target=es2022).2.minified.js, crates/swc/tests/tsc-references/typeOfThisInStaticMembers11(target=es2022).2.minified.js, crates/swc/tests/tsc-references/typeOfThisInStaticMembers12(target=es2022).2.minified.js, crates/swc/tests/tsc-references/typeOfThisInStaticMembers13(target=es2022).2.minified.js, crates/swc/tests/tsc-references/typeOfThisInStaticMembers3(target=es2022).2.minified.js, crates/swc/tests/tsc-references/typeOfThisInStaticMembers4(target=es2022).2.minified.js, crates/swc/tests/tsc-references/typeOfThisInStaticMembers7(target=es2022).2.minified.js, crates/swc/tests/tsc-references/typeOfThisInStaticMembers8(target=es2022).2.minified.js, crates/swc/tests/tsc-references/typeOfThisInStaticMembers9(target=es2022).2.minified.js, crates/swc/tests/tsc-references/uniqueSymbols.2.minified.js, crates/swc/tests/tsc-references/uniqueSymbolsDeclarations.2.minified.js, crates/swc/tests/tsc-references/uniqueSymbolsDeclarationsInJs.2.minified.js, crates/swc_ecma_minifier/src/compress/optimize/unused.rs, crates/swc_ecma_minifier/tests/fixture/issues/5588/config.json, crates/swc_ecma_minifier/tests/fixture/issues/5588/input.js, crates/swc_ecma_minifier/tests/fixture/issues/5588/output.js
=> fix(es/minifier): should preserve classes with side effects in static fields

crates/swc_ecma_transforms_base/src/resolver/mod.rs, crates/swc_ecma_transforms_base/tests/ts-resolver/stc/2/input.ts, crates/swc_ecma_transforms_base/tests/ts-resolver/stc/2/output.ts, crates/swc_ecma_transforms_base/tests/ts-resolver/stc/3/input.ts, crates/swc_ecma_transforms_base/tests/ts-resolver/stc/3/output.ts, crates/swc_ecma_visit/src/lib.rs
=> fix(es/visit): Visit TypeScript satisfies expressions

scripts/cli_artifacts.sh, scripts/cli_upload_gh_release.sh
Seems like previous CI adjustment was not working correctly, trying to fix forward.
=> ci(publish): trying to fix upload cli binaries

crates/swc/benches/minify.rs, crates/swc/scripts/instrument.sh, crates/swc_common/src/lib.rs, crates/swc_common/src/source_map.rs
This PR makes the source map generator cache the previous position instead of searching it from 0 every time.
- Closes https://github.com/swc-project/swc/issues/6411.
=> perf(common): Fix perf bug of sourcemap for inputs with multi-byte chars

crates/swc_html_codegen/tests/fixture/cdata/input.html, crates/swc_html_codegen/tests/fixture/cdata/output.html, crates/swc_html_codegen/tests/fixture/cdata/output.min.html, crates/swc_html_parser/src/lexer/mod.rs, crates/swc_html_parser/src/parser/mod.rs, crates/swc_html_parser/tests/fixture/text/cdata-svg/dom.rust-debug, crates/swc_html_parser/tests/fixture/text/cdata-svg/input.html, crates/swc_html_parser/tests/fixture/text/cdata-svg/output.json, crates/swc_html_parser/tests/fixture/text/cdata-svg/span.rust-debug, crates/swc_html_parser/tests/recovery/comment/cdata-1/output.stderr, crates/swc_html_parser/tests/recovery/text/cdata/dom.rust-debug, crates/swc_html_parser/tests/recovery/text/cdata/input.html, crates/swc_html_parser/tests/recovery/text/cdata/output.json, crates/swc_html_parser/tests/recovery/text/cdata/output.stderr, crates/swc_html_parser/tests/recovery/text/cdata/span.rust-debug
=> fix(html/parser): cdata parsing + tests

.github/workflows/publish-node.yml
https://github.com/meilisearch/meilisearch/issues/1410
- Closes https://github.com/swc-project/swc/issues/5967.
=> chore(bindings): Fix jemalloc on aarch64

Cargo.lock, crates/swc_core/Cargo.toml, crates/swc_core/src/lib.rs
1. Adding `swc_ecma_transform_proposal` reexport sub module
2. Adding `swc_ecam_transform_compat` reexport dependency, and submodule.
=> chore(swc_core): add more sub module into swc_core

crates/swc/tests/fixture/sourcemap/issue-6552/input-map/input/.swcrc, crates/swc/tests/fixture/sourcemap/issue-6552/input-map/input/index.js, crates/swc/tests/fixture/sourcemap/issue-6552/input-map/output/index.js, crates/swc/tests/fixture/sourcemap/issue-6552/input-map/output/index.map, crates/swc/tests/fixture/sourcemap/issue-6552/no-map/input/.swcrc, crates/swc/tests/fixture/sourcemap/issue-6552/no-map/input/index.js, crates/swc/tests/fixture/sourcemap/issue-6552/no-map/output/index.js, crates/swc/tests/fixture/sourcemap/issue-6552/no-map/output/index.map, crates/swc_common/src/source_map.rs, crates/swc_common/src/syntax_pos.rs, crates/swc_estree_compat/src/babelify/mod.rs
This fixes the BytePos -> CharPos calculation necessary for source maps. There were a few issues in the old code:
1. UTF-8 maps 1-3 bytes into 1 UTF-16 char, but 4 bytes into 2 UTF-16 chars
2. The starting offset was not recorded when we reach the end of the `multibyte_chars` iteration
3. The `mappings` can be unordered, meaning we need to restart UTF-16 offset calculation
Fixes #6552
=> Fix BytePos -> CharPos calculations

crates/swc_ecma_parser/src/lexer/state.rs, crates/swc_ecma_parser/tests/jsx/basic/issue-6522/input.js, crates/swc_ecma_parser/tests/jsx/basic/issue-6522/input.js.json
fix ASI with JSX
No
fixes https://github.com/swc-project/swc/issues/6522
=> fix(ecma/parser): parse JSX with ASI

crates/swc_css_parser/benches/lexer.rs, crates/swc_css_parser/benches/parser.rs, crates/swc_css_parser/scripts/instruemnt/bench-parser.sh, crates/swc_css_parser/src/parser/input.rs
- We use `(BytePos, BytePos)` instead of `Box<Span>`.
- We use `Cow` for `Input`.
---
=> perf(css/parser): Reduce clones and allocations

crates/swc_css_parser/src/parser/macros.rs
Avoid skipping whitespaces in `[`/`(`/`{` because:
- it is invalid, whitespaces can allowed and can be disallowed based on context, we can't apply this logic for any CSS context
- we already skip whitespaces where it is necessary (no failed tests)
- avoid extra actions
No
No
=> fix(css/parser): avoid skipping extra whitespaces

crates/swc_css_ast/src/lib.rs, crates/swc_css_codegen/src/lib.rs, crates/swc_css_minifier/src/compressor/color.rs, crates/swc_css_minifier/src/compressor/declaration.rs, crates/swc_css_minifier/src/compressor/easing_function.rs, crates/swc_css_minifier/src/compressor/keyframes.rs, crates/swc_css_minifier/src/compressor/math/mod.rs, crates/swc_css_minifier/src/compressor/mod.rs, crates/swc_css_minifier/src/compressor/rules.rs, crates/swc_css_minifier/src/compressor/selector.rs, crates/swc_css_minifier/src/compressor/transform_function.rs, crates/swc_css_minifier/src/compressor/url.rs, crates/swc_css_minifier/src/lib.rs, crates/swc_css_parser/src/lexer/mod.rs, crates/swc_css_parser/src/parser/at_rules/mod.rs, crates/swc_css_parser/src/parser/macros.rs, crates/swc_css_parser/src/parser/selectors/mod.rs, crates/swc_css_parser/src/parser/syntax/mod.rs, crates/swc_css_parser/src/parser/values_and_units/mod.rs, crates/swc_css_prefixer/src/prefixer.rs, crates/swc_css_utils/src/lib.rs
We don't need to allocate to compare.
=> perf(css/parser): Don't allocate for comparisons

.github/workflows/bench.yml
It's broken due to 6-hour time limit of GitHub actions. To fix it, this PR changes the machine type to `ubuntu-large`.
=> chore(ci): Fix benchmark action

crates/swc_css_codegen/src/lib.rs, crates/swc_css_utils/src/lib.rs
=> perf(css/codegen): Reduce allocations

node-swc/src/types.ts
Some fixes of typescript types for `@swc/core` package
=> fix(node-swc): sync available settings for optimizer.globals

crates/swc_ecma_transforms_compat/src/es2015/block_scoping/mod.rs, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-6573/1/input.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-6573/1/output.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-6573/2/input.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-6573/2/output.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-6573/3/input.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-6573/3/output.js
=> fix(es/transform_compat): should prepend generated `_loop` function to correct scope

crates/swc_ecma_parser/src/lib.rs, crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_parser/src/parser/object.rs, crates/swc_ecma_parser/src/parser/stmt.rs, crates/swc_ecma_parser/tests/typescript/issue-6601/index.tsx, crates/swc_ecma_parser/tests/typescript/issue-6601/index.tsx.json
https://github.com/swc-project/swc/issues/6601
No
Fixed https://github.com/swc-project/swc/issues/6601
=> fix(ecma/parser): parse types in `CallExpression` inside templates

crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/tests/fixture/issue-6589/js/input.js, crates/swc_ecma_codegen/tests/fixture/issue-6589/js/output.js, crates/swc_ecma_codegen/tests/fixture/issue-6589/js/output.min.js, crates/swc_ecma_codegen/tests/fixture/issue-6589/ts/input.ts, crates/swc_ecma_codegen/tests/fixture/issue-6589/ts/output.ts
https://github.com/swc-project/swc/issues/6589
No
Fixed https://github.com/swc-project/swc/issues/6589
=> fix(ecma/codegen): don't print trailing coma for rest argument

node-swc/src/types.ts
https://github.com/swc-project/swc/blob/a5efa8af503c3e570b36248b7a05bfa393c82f0b/crates/swc_ecma_minifier/src/option/terser.rs#L243-L244
SWC has `const_to_let`, but it is missing in the type.
=> fix(node-swc): Add missing `const_to_let` to the type

crates/swc_ecma_codegen/src/typescript.rs, crates/swc_ecma_codegen/tests/fixture/issues/6616/input.ts, crates/swc_ecma_codegen/tests/fixture/issues/6616/output.ts
In some situations the code generated for mapped types would include a `/` instead of a `?`.
This is a small bug fix and shouldn't be breaking change.
fixes #6616
=> fix(es/codegen): fix issue with typescript's mapped types output

crates/swc_css_prefixer/data/prefixes_and_browsers.json, crates/swc_css_prefixer/src/prefixer.rs, crates/swc_css_prefixer/tests/fixture/calc/input.css, crates/swc_css_prefixer/tests/fixture/calc/output.css, crates/swc_css_prefixer/tests/fixture/calc/output.defaults-not-ie-11.css
Port - https://preset-env.cssdb.org/features/#nested-calc
Also bug fix - always use `(` and `)` for prefixed
No
No
=> feat(css/prefixer): nested calc

crates/swc_atoms/words.txt, crates/swc_css_prefixer/data/prefixes_and_browsers.json, crates/swc_css_prefixer/src/prefixer.rs, crates/swc_css_prefixer/tests/fixture/font-face-format/input.css, crates/swc_css_prefixer/tests/fixture/font-face-format/output.css, crates/swc_css_prefixer/tests/fixture/font-face-format/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/image-set/input.css, crates/swc_css_prefixer/tests/fixture/image-set/output.css, crates/swc_css_prefixer/tests/fixture/image-set/output.defaults-not-ie-11.css
Port https://preset-env.cssdb.org/features/#font-format-keywords
No
No
=> feat(css/prefixer): font-face format

crates/swc_css_parser/tests/fixture/at-rule/media/input.css, crates/swc_css_parser/tests/fixture/at-rule/media/output.json, crates/swc_css_parser/tests/fixture/at-rule/media/span.swc-stderr
I have an internal report (on twitter) that we've already had issues with this, just check we don't have an issue anymore
No
No
=> test(css/parser): check we don't have a regression

crates/swc_css_codegen/src/lib.rs, crates/swc_css_minifier/src/compressor/declaration.rs, crates/swc_css_modules/src/lib.rs, crates/swc_css_parser/src/parser/syntax/mod.rs, crates/swc_css_parser/tests/fixture/at-rule/import/output.json, crates/swc_css_parser/tests/fixture/important/basic/output.json, crates/swc_css_parser/tests/fixture/vendor/rome/at-page/output.json, crates/swc_css_parser/tests/fixture/vendor/rome/at-page/page-properties-case-insensitive/output.json, crates/swc_css_prefixer/src/prefixer.rs, crates/swc_css_prefixer/tests/fixture/case-insensivity/input.css, crates/swc_css_prefixer/tests/fixture/case-insensivity/output.css, crates/swc_css_prefixer/tests/fixture/case-insensivity/output.defaults-not-ie-11.css
Normalize declartion and important, also found a bug in `swc_css_prefixer` (because we don't check case) and fixed
No
No
=> feat(css/parser): normalize declaration and important

crates/swc_css_minifier/src/compressor/keyframes.rs, crates/swc_css_parser/src/parser/at_rules/mod.rs, crates/swc_css_parser/tests/fixture/at-rule/keyframe/output.json
Normalize `from`/`to` for keyframes selector
No
No
=> feat(css/parser): normalize keyframe selector

crates/swc/src/config/mod.rs
- Closes https://github.com/swc-project/swc/issues/6677.
=> fix(es): Preserve license comments by default

crates/swc/src/config/mod.rs
Fixes an issue where import statements to symbolic links (symlinks) are canonicalized in generated code and use the absolute form of the path with all intermediate components normalized and symbolic links resolved.
Import resolution was introduced in https://github.com/swc-project/swc/pull/1834.
However, resolving symbolic links in generated code is unnecessary. A JavaScript runtime (Node.js, Deno) will resolve import statements to symbolic links at runtime. 
The suggested solution introduces a new `match` guard to determine whether the path is relative and uses the current working directory as a base path. For example, the current working directory is already used as a base path for module resolution
https://github.com/swc-project/swc/blob/072bd130239579566d319a47156c570277cebb1b/crates/s …
=> fix(swc): Remove import statement canonicalization

bindings/swc_cli/src/commands/plugin.rs
New plugins created with `swc plugin new` can't be compiled because the feature `plugin_transform` used by the plugin was recently removed (in fa8f7b00fc458c4ee2a74b431fb9004f67e54dde). This leads to errors like the following:
```
error: failed to select a version for `swc_core`.
... required by package `swc_plugin v0.1.0 (<redacted path>)`
versions that meet the requirements `0.50.*` are: 0.50.3, 0.50.2, 0.50.1, 0.50.0
the package `swc_plugin` depends on `swc_core`, with features: `plugin_transform` but `swc_core` does not have these features.
failed to select a version for `swc_core` which could resolve this conflict
```
This PR updates the template used for new plugins to depend on a proper feature name. I'm assuming it's supposed to be `ecma_plugin_transform` by …
=> Fix feature used for plugin starter.

crates/swc_ecma_minifier/tests/terser/compress/dead_code/dead_code_2_should_warn/output.js, crates/swc_ecma_minifier/tests/terser/compress/dead_code/dead_code_2_should_warn_strict/output.js, crates/swc_ecma_transforms_optimization/src/simplify/branch/tests.rs, crates/swc_ecma_utils/src/lib.rs
=> fix(es/transforms_optimization): should capture hoisted variables correctly

crates/swc_ecma_preset_env/src/corejs2/entry.rs, crates/swc_ecma_preset_env/src/corejs3/entry.rs, crates/swc_ecma_preset_env/src/lib.rs
use VisitMut for polyfill pass
=> refactor(ecma_preset_env): visit_mut for polyfills

crates/swc/tests/fixture/issues-6xxx/6729/input/.swcrc, crates/swc/tests/fixture/issues-6xxx/6729/input/index.js, crates/swc/tests/fixture/issues-6xxx/6729/output/index.js, crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/tests/exec.rs
We skip non-computed property names while checking if we can inline an expression.
- Closes https://github.com/swc-project/swc/issues/6729.
=> fix(es/minifier): Fix usage counter to fix infinite loop

crates/swc_ecma_transforms_react/src/refresh/mod.rs, crates/swc_ecma_transforms_react/src/refresh/tests.rs
=> fix(es/transform_react): should force refresh if code contains `@refresh reset`

crates/swc/tests/source_map.rs, crates/swc_common/src/syntax_pos.rs, crates/swc_common/src/syntax_pos/analyze_source_file.rs, crates/swc_ecma_codegen/src/text_writer/basic_impl.rs
There were several issues with the way we updated the current `LineCol` position during the printing of the generated file:
- We used `chars` and `char_indices` (UTF-32) instead of `encode_utf16` (UTF-16) chars.
- JS uses UCS-2 (basically UTF-16) for its strings, and sourcemaps default to that implicitly.
- `\r` was incorrectly handled
- it didn't add a `line_start`, only `\n` did
- `\r\n` was incorrectly handled
- It was trying to let `\n` path handle the `line_start`, but it called `chars.next()` which ate the `\n` char.
I also took the opportunity to avoid the `Vec` allocations and reduced some code duplication.
See the [before](https://evanw.github.io/source-map-visualization/#ODEzAC8qKgogKiBmb28KICogQHBhcmFtIGRhdGEgZm9vCiAqIEByZXR1cm5zIGZvbwogKi8gZXhwb3J0IGNvbnN0IGZpe …
=> fix(swc_ecma_codegen): fix LineCol calculation of printed files

bindings/swc_cli/src/commands/plugin.rs
Replace `-` with `_` in generated package.json `main` field to match what cargo names the output `.wasm` file. Allows swc-core to load the plugin at runtime.
- Closes https://github.com/swc-project/swc/issues/6814.
=> fix(es/plugin): Fix starter template main field (#6814)

crates/swc_ecma_codegen/src/jsx.rs, crates/swc_ecma_codegen/tests/fixture/next-36251/output.tsx, crates/swc_ecma_transforms_base/tests/resolver/issues/2854/1/output.js, crates/swc_ecma_transforms_base/tests/resolver/vercel/next/server/render/1/output.js, crates/swc_ecma_transforms_typescript/tests/fixture/next/server/render/1/output.js
For now, when emit a JSXOpeningElement directly, it will contain a space whether or not attrs is empty.
```jsx
// input
<div></div>
// output
<div ></div>
```
This PR fix this issue by skip space!() and emit attrs when attrs is empty.
=> fix(es/codegen): Skip emit space if jsx attrs is empty
