.github/workflows/docs.yml, crates/swc_core/Cargo.toml, crates/swc_core/src/lib.rs
=> doc(swc_core): Fix rustdoc, really

Cargo.lock, crates/dbg-swc/Cargo.toml, crates/swc/Cargo.toml, crates/swc_bundler/Cargo.toml, crates/swc_common/Cargo.toml, crates/swc_core/Cargo.toml, crates/swc_css_visit/Cargo.toml, crates/swc_ecma_lints/Cargo.toml, crates/swc_ecma_minifier/Cargo.toml, crates/swc_ecma_transforms/Cargo.toml, crates/swc_ecma_transforms_base/Cargo.toml, crates/swc_ecma_transforms_classes/Cargo.toml, crates/swc_ecma_transforms_compat/Cargo.toml, crates/swc_ecma_transforms_module/Cargo.toml, crates/swc_ecma_transforms_optimization/Cargo.toml, crates/swc_ecma_transforms_proposal/Cargo.toml, crates/swc_ecma_transforms_react/Cargo.toml, crates/swc_ecma_transforms_testing/Cargo.toml, crates/swc_ecma_transforms_typescript/Cargo.toml, crates/swc_ecma_visit/Cargo.toml, crates/swc_eq_ignore_macros/Cargo.toml, crates/swc_html_minifier/Cargo.toml, crates/swc_html_visit/Cargo.toml, crates/swc_plugin_proxy/Cargo.toml, crates/swc_plugin_runner/Cargo.toml, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/Cargo.lock, crates/swc_visit/Cargo.toml, crates/swc_visit_macros/Cargo.toml, crates/swc_xml_visit/Cargo.toml
Another attempt to fix code differences issue. This time compilation passes, but some esoteric runtime error thrown while using latest git as dep didn't cause problems. It was not easy to find out root cause, instead I tried to bisect changes between published pkg vs git tree then bumps up pkg have any source differences. 
I'm not sure if this'll fix the problem though - we'll need updated @swc/core and all the rust pkgs to retry those tests.
=> fix(swc): bump up pkgs

Cargo.lock, crates/swc_core/Cargo.toml
=> fix(swc/core): apply plugin features

.github/workflows/publish-node.yml
=> chore(ci): Fix publish action

packages/swc-helpers/src/_class_static_private_field_spec_get.mjs
=> fix(swc-helpers): Correct import path

Cargo.lock, crates/swc/Cargo.toml, crates/swc_core/Cargo.toml, crates/swc_plugin_macro/Cargo.toml
=> build(cargo): bump up version

crates/swc_atoms/src/lib.rs
=> fix(atoms): Workaround a bug of `rkyv`

.github/workflows/cargo.yml, .github/workflows/integration.yml
=> test(es/plugin): Expand test matrix

Cargo.lock, crates/binding_core_node/Cargo.toml, crates/binding_core_node/src/bundle.rs, crates/binding_core_node/src/minify.rs, crates/binding_core_node/src/parse.rs, crates/binding_core_node/src/print.rs, crates/binding_core_node/src/transform.rs, crates/binding_core_node/src/util.rs, crates/swc_core/Cargo.toml, crates/swc_core/src/lib.rs, crates/swc_node_bundler/Cargo.toml, crates/swc_nodejs_common/src/lib.rs, crates/swc_plugin_proxy/src/comments/plugin_comments_proxy.rs, crates/swc_plugin_proxy/src/metadata/transform_plugin_metadata.rs, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/Cargo.lock, node-swc/e2e/fixtures/plugin_transform_schema_vtest/Cargo.lock
PR moves out rest of the dependencies from bindings_node, allows to built it against swc_core. This'll allow to try attempt our next attempt for the plugin regressions.
=> feat(swc/core): expose nodejs, update bindings_node

crates/swc/tests/exec/git-keep/js/exec.js, crates/swc/tests/exec/git-keep/ts/exec.ts, crates/swc/tests/exec/issues-5xxx/5383/exec.js, crates/swc_ecma_transforms_base/src/helpers/_async_iterator.js, crates/swc_ecma_transforms_compat/tests/async-to-generator/issue-5383/1/exec.js, packages/swc-helpers/src/_async_iterator.mjs
=> fix(es/helpers): Fix `for await`

crates/swc_core/Cargo.toml, crates/swc_plugin_macro/Cargo.toml
=> fix(swc/core): bump up plugin_macro

Cargo.lock, crates/swc/Cargo.toml, crates/swc_core/Cargo.toml, crates/swc_plugin_proxy/Cargo.toml, crates/swc_plugin_proxy/src/source_map/plugin_source_map_proxy.rs, crates/swc_plugin_runner/Cargo.toml
This seems to be caused while resolving merge conflict, ends up compilation fails on the plugin side.
=> fix(swc/plugin_proxy): correct compilation attr

Cargo.lock, crates/swc_core/Cargo.toml, crates/swc_core/build.rs, crates/swc_core/src/lib.rs, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/Cargo.lock
It is my mistake to understand way `vergen` works - in result, it makes not possible to publish plugin.
For now simply revert it and attempt to find new way instead.
=> Revert 5494 feat swc core metadata git

Cargo.lock, crates/swc_atoms/Cargo.toml, crates/swc_common/Cargo.toml, crates/swc_core/Cargo.toml, crates/swc_css_ast/Cargo.toml, crates/swc_ecma_ast/Cargo.toml, crates/swc_html_ast/Cargo.toml, crates/swc_plugin_proxy/Cargo.toml
Requires https://github.com/swc-project/swc/pull/5506 - once it's in PR should be rebased.
=> build(swc/core): bump up rkyv

Cargo.lock, crates/swc_core/Cargo.toml, crates/swc_plugin/Cargo.toml, crates/swc_plugin/src/allocation.rs, crates/swc_plugin_macro/Cargo.toml, crates/swc_plugin_macro/src/lib.rs, crates/swc_plugin_proxy/Cargo.toml, crates/swc_plugin_runner/Cargo.toml, crates/swc_plugin_runner/src/cache.rs, crates/swc_plugin_runner/src/host_environment.rs, crates/swc_plugin_runner/src/imported_fn/comments.rs, crates/swc_plugin_runner/src/imported_fn/handler.rs, crates/swc_plugin_runner/src/imported_fn/hygiene.rs, crates/swc_plugin_runner/src/imported_fn/metadata_context.rs, crates/swc_plugin_runner/src/imported_fn/mod.rs, crates/swc_plugin_runner/src/imported_fn/set_transform_result.rs, crates/swc_plugin_runner/src/imported_fn/source_map.rs, crates/swc_plugin_runner/src/load_plugin.rs, crates/swc_plugin_runner/src/memory_interop.rs, crates/swc_plugin_runner/src/transform_executor.rs, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/Cargo.lock
require https://github.com/swc-project/swc/pull/5507 to rebase.
- Closes https://github.com/swc-project/swc/issues/5480
=> feat(swc/plugin): wasmer@3 

bindings/binding_core_node/Cargo.lock, bindings/binding_core_node/Cargo.toml, bindings/binding_core_wasm/Cargo.lock, bindings/binding_core_wasm/Cargo.toml, bindings/swc_cli/Cargo.lock, bindings/swc_cli/Cargo.toml
=> feat(swc): bump up swc_core

Cargo.lock, crates/swc/Cargo.toml, crates/swc_atoms/Cargo.toml, crates/swc_common/Cargo.toml, crates/swc_core/Cargo.toml, crates/swc_css_ast/Cargo.toml, crates/swc_ecma_ast/Cargo.toml, crates/swc_html_ast/Cargo.toml, crates/swc_plugin_proxy/Cargo.toml, crates/swc_plugin_runner/Cargo.toml, crates/swc_plugin_runner/src/imported_fn/source_map.rs, crates/swc_plugin_runner/src/load_plugin.rs
There was a missing memory export while migrating into wasmer@3. Unfortunately, this means we'll need another `@swc/core` with swc_core release.
=> fix(swc/plugin_runner): provide guest memory alloc for the sourcemap

Cargo.lock, crates/swc_atoms/Cargo.toml, crates/swc_common/Cargo.toml, crates/swc_core/Cargo.toml, crates/swc_css_ast/Cargo.toml, crates/swc_ecma_ast/Cargo.toml, crates/swc_html_ast/Cargo.toml, crates/swc_plugin_proxy/Cargo.toml, crates/swc_plugin_runner/Cargo.toml, crates/swc_plugin_runner/src/cache.rs, crates/swc_plugin_runner/src/host_environment.rs, crates/swc_plugin_runner/src/imported_fn/comments.rs, crates/swc_plugin_runner/src/imported_fn/handler.rs, crates/swc_plugin_runner/src/imported_fn/hygiene.rs, crates/swc_plugin_runner/src/imported_fn/metadata_context.rs, crates/swc_plugin_runner/src/imported_fn/mod.rs, crates/swc_plugin_runner/src/imported_fn/set_transform_result.rs, crates/swc_plugin_runner/src/imported_fn/source_map.rs, crates/swc_plugin_runner/src/load_plugin.rs, crates/swc_plugin_runner/src/memory_interop.rs, crates/swc_plugin_runner/src/transform_executor.rs, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/Cargo.lock
https://github.com/swc-project/swc/issues/5480
=> fix(swc/plugin_runner): revert wasmer@3

bindings/Cargo.lock, bindings/binding_core_node/Cargo.toml, bindings/binding_core_wasm/Cargo.toml, bindings/swc_cli/Cargo.toml
=> feat(swc): bump up swc

crates/swc_css_prefixer/data/prefixes_and_browsers.json, crates/swc_css_prefixer/src/prefixer.rs, crates/swc_css_prefixer/tests/fixture/basic/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/cursor/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/display/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/filter/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/flex/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/image-rendering/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/isolate-override/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/keyframes/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/prefixed/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/recovery/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/supports/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/transform/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/transition/output.css, crates/swc_css_prefixer/tests/fixture/transition/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/width-size/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/width/output.defaults-not-ie-11.css
Now all properties and values generated based on env
No
No
=> feat(css/prefixer): more env properties and values

crates/swc/tests/fixture/issues-5xxx/5530/input/.swcrc, crates/swc/tests/fixture/issues-5xxx/5530/input/index.js, crates/swc/tests/fixture/issues-5xxx/5530/output/index.js, crates/swc_ecma_transforms_base/src/fixer.rs
And this PR removed some useless paren in await expr.
- fix #5530
=> fix(es/fixer): Wrap with paren for yield expr

crates/swc/src/plugin.rs, crates/swc_common/src/plugin/serialized.rs, crates/swc_plugin_runner/src/transform_executor.rs
Minor improvements to the host side spans.
=> feat(swc/plugin): add more traces

crates/swc_css_prefixer/src/prefixer.rs, crates/swc_css_prefixer/tests/fixture/autofill/output.css, crates/swc_css_prefixer/tests/fixture/autofill/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/duplicate-at-rule-3/output.css, crates/swc_css_prefixer/tests/fixture/resolution/input.css, crates/swc_css_prefixer/tests/fixture/resolution/output.css, crates/swc_css_prefixer/tests/fixture/resolution/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/selection/output.css
Less duplication + more test + fix bug with `@import`
No
No
=> fix(css/prefixer): less duplication

crates/swc_ecma_quote/src/clone.rs
=> fix(es/quote): Allow cloning

crates/swc/tests/fixture/issues-5xxx/5557/input/.swcrc, crates/swc/tests/fixture/issues-5xxx/5557/input/index.js, crates/swc/tests/fixture/issues-5xxx/5557/output/index.js, crates/swc_ecma_parser/src/lexer/state.rs, crates/swc_ecma_parser/src/parser/stmt.rs
=> fix(es/parser): Allow expr to follow `ClassExpr`

packages/swc-helpers/src/_class_static_private_field_destructure.mjs
Found by https://github.com/swc-project/swc/pull/5578
=> fix(es/helpers): Fix an import

bindings/Cargo.lock, bindings/binding_core_node/Cargo.toml, bindings/binding_core_wasm/Cargo.toml, bindings/swc_cli/Cargo.toml
This'll need https://github.com/swc-project/swc/pull/5593 (and rebump).
=> feat(swc/bindings): bump up swc_core

Cargo.lock, crates/swc_core/Cargo.toml, crates/swc_core/src/lib.rs
Expands few more features for `swc_core` to migrate next-swc.
=> feat(swc/core): expand features

Cargo.lock, crates/swc_core/Cargo.toml
Updated version to include new features.
=> build(cargo): update swc_core version

Cargo.lock, crates/swc_core/Cargo.toml, crates/swc_core/src/lib.rs
=> fix(swc/core): properly exports swc_cached

Cargo.lock, crates/swc_core/Cargo.toml, crates/swc_core/src/lib.rs, crates/swc_plugin_macro/Cargo.toml
This PR exposes a few css features next-swc (and its custom transforms) relying on.
=> feat(swc/core): add css features

bindings/swc_cli/src/commands/plugin.rs
Let plugin scaffold apply optimizations as much as it can.
=> feat(swc/cli): enable lto by default for the plugins

packages/swc-helpers/src/_class_static_private_field_update.mjs
=> fix(es/helpers): Fix `_classStaticPrivateFieldUpdate`

bindings/Cargo.lock, bindings/binding_core_node/Cargo.toml, bindings/binding_core_wasm/Cargo.toml, bindings/swc_cli/Cargo.toml, package.json
=> chore: Publish `v1.2.243`

crates/swc_ecma_transforms_compat/tests/async-to-generator/issue-4486/1/exec.js
- Closes https://github.com/swc-project/swc/issues/4486
=> test(es/compat): Add a test for a fixed issue

.github/workflows/cargo.yml, crates/swc_bundler/tests/deno.rs, crates/swc_ecma_minifier/Cargo.toml, crates/swc_ecma_minifier/benches/full.rs, crates/swc_ecma_minifier/src/lib.rs, crates/swc_ecma_minifier/tests/compress.rs, crates/swc_ecma_minifier/tests/exec.rs, crates/swc_ecma_minifier/tests/terser_exec.rs, crates/swc_ecma_transforms_base/src/perf.rs, crates/swc_ecma_transforms_base/src/rename/ops.rs, crates/swc_ecma_transforms_compat/src/es2015/duplicate_keys.rs, crates/swc_ecma_transforms_compat/src/es2015/function_name.rs, crates/swc_ecma_transforms_compat/src/es2015/instanceof.rs, crates/swc_ecma_transforms_compat/src/es2015/shorthand_property.rs, crates/swc_ecma_transforms_compat/src/es2015/sticky_regex.rs, crates/swc_ecma_transforms_compat/src/es2015/template_literal.rs, crates/swc_ecma_transforms_compat/src/es2015/typeof_symbol.rs, crates/swc_ecma_transforms_compat/src/es2018/object_rest_spread.rs, crates/swc_ecma_transforms_compat/src/es2021/logical_assignments.rs, crates/swc_ecma_transforms_compat/src/reserved_words.rs, crates/swc_ecma_transforms_macros/src/parallel.rs, crates/swc_ecma_transforms_optimization/Cargo.toml, crates/swc_ecma_transforms_react/src/jsx_self/mod.rs, crates/swc_ecma_transforms_react/src/jsx_src/mod.rs, scripts/ci/test-concurrent.sh
It's required for the minifier parallelization.
Without this, https://github.com/swc-project/swc/pull/5699 makes minifier too slow
=> perf(es/minifier): Enable parallel processing

Cargo.toml, bindings/Cargo.toml
=> feat(bindings): Reduce size

bindings/Cargo.lock, bindings/binding_core_node/Cargo.toml, bindings/binding_core_wasm/Cargo.toml, bindings/swc_cli/Cargo.toml, package.json
=> chore: Publish `v1.2.246`

crates/swc_ecma_parser/src/lexer/state.rs, crates/swc_ecma_parser/src/lexer/tests.rs, crates/swc_ecma_parser/src/parser/stmt.rs
=> fix(es/lexer): drop `ClassExpr` context in object prop

Cargo.lock, crates/swc_core/Cargo.toml, crates/swc_core/src/lib.rs
Remove references to kitchensink `transforms` from `swc_core`.
=> refactor(swc/core): directly export transforms_base

bindings/Cargo.lock, bindings/binding_core_node/Cargo.toml, bindings/binding_core_node/src/bundle.rs, bindings/binding_core_node/src/print.rs, bindings/binding_core_node/src/transform.rs, bindings/binding_core_wasm/Cargo.toml, bindings/swc_cli/Cargo.toml, package.json
=> chore: Publish `v1.2.247`

Cargo.toml, crates/swc_ecma_minifier/examples/minify-all.rs
This is to compare performance of real-world cases
=> chore(es/minifier): Fix example

Cargo.lock, crates/swc_core/Cargo.toml, crates/swc_ecma_transforms_optimization/Cargo.toml, crates/swc_ecma_utils/Cargo.toml
=> fix(swc/core): bump up dependecies

Cargo.lock, crates/binding_macros/Cargo.toml, crates/swc/Cargo.toml, crates/swc_bundler/Cargo.toml, crates/swc_core/Cargo.toml, crates/swc_ecma_minifier/Cargo.toml, crates/swc_ecma_preset_env/Cargo.toml, crates/swc_ecma_transforms/Cargo.toml, crates/swc_ecmascript/Cargo.toml, crates/swc_estree_compat/Cargo.toml, crates/swc_node_bundler/Cargo.toml
https://github.com/swc-project/swc/pull/5746 was not a complete fix unfortunately. Attempt to fix relevant packages.
=> fix(swc/transform_optimization): bump up deps

bindings/Cargo.lock, bindings/binding_core_node/Cargo.toml, bindings/binding_core_wasm/Cargo.toml, bindings/swc_cli/Cargo.toml, package.json, scripts/bot/src/cargo/bump.ts
=> chore: Publish `v1.2.248`

bindings/swc_cli/src/commands/plugin.rs
I fixed just a typo.
**BREAKING CHANGE:** No
**Related issue (if exists):** No
=> Fix typo in plugin template

crates/swc_ecma_minifier/src/compress/optimize/util.rs
We don't have to recurse fully. We can simply check `e` and children nodes
=> perf(es/minifier): Make `MultiReplacer` single-pass

crates/swc_ecma_minifier/examples/minifier.rs, crates/swc_ecma_minifier/scripts/size.sh
Name mangler should consider block scoping
```
Compiling swc_ecma_minifier v0.152.10 (/Users/kdy1/projects/s/minifier/crates/swc_ecma_minifier)
Finished release [optimized] target(s) in 3.83s
Running `/Users/kdy1/projects/s/minifier/target/release/examples/minifier ./benches/full/antd.js`
File: ./benches/full/antd.js
459295
Finished release [optimized] target(s) in 0.26s
Running `/Users/kdy1/projects/s/minifier/target/release/examples/minifier ./benches/full/d3.js`
File: ./benches/full/d3.js
87905
Finished release [optimized] target(s) in 0.26s
Running `/Users/kdy1/projects/s/minifier/target/release/examples/minifier ./benches/full/echarts.js`
File: ./benches/full/echarts.js
323197
Finished release [optimized] target(s) in 0.26s
Running …
```
=> chore(es/minifier): Fix size calculator script

.github/workflows/cargo.yml, scripts/github/create-matrix.sh, scripts/github/tests.yml
Let's use powerful instance for `swc` crate testing...
=> chore(ci): Cleanup CI config

crates/swc_plugin_proxy/src/lib.rs, crates/swc_plugin_runner/benches/invoke.rs, crates/swc_plugin_runner/src/lib.rs, crates/swc_plugin_runner/tests/integration.rs
=> refactor(es/plugin): Fix lints

.github/workflows/stale.yml, Cargo.lock, crates/swc_css_minifier/Cargo.toml, crates/swc_css_minifier/benches/full.rs, crates/swc_css_minifier/scripts/instrument/bench-full.sh, package.json, yarn.lock
I created a simple benchmark for the css minifier. It's full benchmark, which also profiles parser and codegen
=> perf(css/minifier): Setup benchmark

crates/swc/tests/exec/next/40399/1/exec.js, crates/swc/tests/exec/next/40399/2/exec.js, crates/swc/tests/exec/next/40399/3/exec.js, crates/swc/tests/fixture/next.js/40399/1/input/index.js, crates/swc/tests/fixture/next.js/40399/1/output/index.js, crates/swc/tests/fixture/next.js/40399/2/input/index.js, crates/swc/tests/fixture/next.js/40399/2/output/index.js, crates/swc/tests/fixture/next.js/40399/3/input/index.js, crates/swc/tests/fixture/next.js/40399/3/output/index.js, crates/swc/tests/tsc-references/awaitCallExpression6_es5.1.normal.js, crates/swc/tests/tsc-references/awaitCallExpression7_es5.1.normal.js, crates/swc/tests/tsc-references/awaitClassExpression_es5.1.normal.js, crates/swc_ecma_transforms_compat/src/es2015/generator.rs
- merge temp_vars into hoisted_vars
- fix context of function call and new call
- vercel/next.js/issues/40399
=> fix(es/compat): ts generator

crates/swc_css_minifier/benches/full.rs, crates/swc_css_parser/src/parser/at_rule.rs, crates/swc_css_parser/src/parser/base.rs, crates/swc_css_parser/src/parser/input.rs, crates/swc_css_parser/src/parser/macros.rs, crates/swc_css_parser/src/parser/selector/mod.rs, crates/swc_css_parser/src/parser/value/mod.rs
=> perf(css/parser): Remove needless branching

crates/swc_css_parser/scripts/instruemnt/bench-parser.sh, crates/swc_css_parser/src/lexer/mod.rs, crates/swc_css_parser/src/parser/input.rs
Lexer can handle it more efficiently.
=> perf(css/parser): Skip whiltespace from lexer

bindings/Cargo.lock, bindings/binding_core_node/Cargo.toml, bindings/binding_core_wasm/Cargo.toml, bindings/swc_cli/Cargo.toml, package.json
=> chore: Publish `v1.3.0`

crates/swc_core/Cargo.toml
Exports swc_common's sourcemap optional dep.
=> feat(swc/core): export common/sourcemap

crates/swc_core/Cargo.toml, crates/swc_core/src/lib.rs
This PR exports general testing utilites from swc_core.
=> feat(swc/core): export testing utilities

crates/swc_core/src/lib.rs
Minor fix to correctly reexport testing utilities.
=> fix(swc/core): fix export for testing

.github/workflows/cargo.yml, Cargo.lock, crates/ast_node/src/lib.rs, crates/swc_core/Cargo.toml, crates/swc_css_ast/Cargo.toml, crates/swc_ecma_ast/Cargo.toml, crates/swc_ecma_ast/build.rs, crates/swc_ecma_ast/src/class.rs, crates/swc_ecma_ast/src/decl.rs, crates/swc_ecma_ast/src/expr.rs, crates/swc_ecma_ast/src/ident.rs, crates/swc_ecma_ast/src/lit.rs, crates/swc_ecma_ast/src/operators.rs, crates/swc_ecma_ast/src/typescript.rs, crates/swc_html_ast/Cargo.toml, crates/swc_plugin_proxy/src/comments/host_comments_storage.rs, crates/swc_plugin_proxy/src/comments/mod.rs, crates/swc_plugin_proxy/src/comments/plugin_comments_proxy.rs, crates/swc_plugin_proxy/src/metadata/mod.rs, crates/swc_plugin_proxy/src/metadata/transform_plugin_metadata.rs, crates/swc_plugin_proxy/src/source_map/mod.rs
This PR updates ast* related package's rkyv bytecheck flags.
=> refactor(swc/ecma_ast): apply rkyv-bytecheck flag

.github/workflows/cargo.yml, Cargo.lock, crates/ast_node/src/lib.rs, crates/swc_core/Cargo.toml, crates/swc_css_ast/Cargo.toml, crates/swc_ecma_ast/Cargo.toml, crates/swc_ecma_ast/build.rs, crates/swc_ecma_ast/src/class.rs, crates/swc_ecma_ast/src/decl.rs, crates/swc_ecma_ast/src/expr.rs, crates/swc_ecma_ast/src/ident.rs, crates/swc_ecma_ast/src/lit.rs, crates/swc_ecma_ast/src/operators.rs, crates/swc_ecma_ast/src/typescript.rs, crates/swc_html_ast/Cargo.toml, crates/swc_plugin_proxy/src/comments/host_comments_storage.rs, crates/swc_plugin_proxy/src/comments/mod.rs, crates/swc_plugin_proxy/src/comments/plugin_comments_proxy.rs, crates/swc_plugin_proxy/src/metadata/mod.rs, crates/swc_plugin_proxy/src/metadata/transform_plugin_metadata.rs, crates/swc_plugin_proxy/src/source_map/mod.rs
This reverts commit 37f42df877b63479c3c6ed0f2d7fb24791da6589.
=> fix(es/ast): Revert #5798 (#5798)

.github/workflows/cargo.yml, README.md
MSRV is the current stable rust toolchain
=> chore: Update MSRV

crates/swc_ecma_minifier/src/compress/pure/strings.rs, crates/swc_ecma_minifier/tests/exec.rs, crates/swc_ecma_utils/src/lib.rs
- Closes https://github.com/swc-project/swc/issues/5799
=> fix(es/minifier): Fix unicode handling

bindings/Cargo.lock, crates/swc_core/Cargo.toml, crates/swc_plugin_proxy/src/comments/plugin_comments_proxy.rs
Enable internal flag for the plugin transform with bytecheck.
=> feat(swc/core): enable bytecheck for plugin

crates/swc_html_parser/src/parser/mod.rs, crates/swc_html_parser/tests/fixture/element/template-1/dom.rust-debug, crates/swc_html_parser/tests/fixture/element/template-1/input.html, crates/swc_html_parser/tests/fixture/element/template-1/output.json, crates/swc_html_parser/tests/fixture/element/template-1/span.rust-debug, crates/swc_html_parser/tests/fixture/element/template-2/dom.rust-debug, crates/swc_html_parser/tests/fixture/element/template-2/input.html, crates/swc_html_parser/tests/fixture/element/template-2/output.json, crates/swc_html_parser/tests/fixture/element/template-2/span.rust-debug, crates/swc_html_parser/tests/recovery/element/template-5/dom.rust-debug, crates/swc_html_parser/tests/recovery/element/template-5/input.html, crates/swc_html_parser/tests/recovery/element/template-5/output.json, crates/swc_html_parser/tests/recovery/element/template-5/output.stderr, crates/swc_html_parser/tests/recovery/element/template-5/span.rust-debug
I found a bug in HTML spec, so I started to fix it in spec and our parser + tests for `html5tests-lib` for other parser
Original issue - https://github.com/whatwg/html/issues/7922
So we are showring potential fix in spec/parser here (and no problems with other tests). Let's merge when HTML spec marked it as bug and fix it in spec.
No
Ref: https://github.com/whatwg/html/issues/7922
Ref: https://github.com/html5lib/html5lib-tests/pull/150
=> fix(html/parser): potential bug in spec

crates/swc/Cargo.toml, crates/swc/src/config/mod.rs, crates/swc/src/plugin.rs
Fixes oversight to enabling plugin when plugin-bytecheck is enabled.
=> feat(swc): enable plugin for bytecheck flags

bindings/swc_cli/src/commands/plugin.rs
ref: https://github.com/swc-project/swc/pull/5824
that pr loses one comma.
=> fix(cli): missing comma

Cargo.toml, crates/swc/tests/exec.rs, crates/swc_ecma_minifier/tests/compress.rs, crates/swc_ecma_minifier/tests/exec.rs, crates/swc_ecma_testing/src/lib.rs, crates/swc_ecma_transforms_testing/src/lib.rs
This PR adds a way to provide arguments to `exec_node_js`.
=> test(es): Accept arguments

crates/swc/tests/fixture/issues-5xxx/5914/1/.swcrc, crates/swc/tests/fixture/issues-5xxx/5914/1/exec.js, crates/swc_ecma_minifier/src/lib.rs, crates/swc_ecma_minifier/tests/exec.rs
- https://github.com/swc-project/swc/issues/5914.
=> test(es/minifier): Add a test for a wrong issue

crates/swc_ecma_minifier/tests/fixture/issues/quagga2/1.4.2/1/output.mangleOnly.js, crates/swc_ecma_minifier/tests/fixture/next/31077/static/chunks/1606726a.10299989c08cb523/output.mangleOnly.js, crates/swc_ecma_minifier/tests/fixture/next/33265/static/chunks/d6e1aeb5-38a8d7ae57119c23/output.mangleOnly.js, crates/swc_ecma_minifier/tests/fixture/next/33265/static/chunks/pages/index-cb36c1bf7f830e3c/output.mangleOnly.js, crates/swc_ecma_minifier/tests/fixture/next/wrap-contracts/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/collapse_rhs_lhs_2/output.js, crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/collapse_rhs_lhs_2/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/issue_2313_2/output.js, crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/issue_2313_2/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/drop_unused/issue_1709/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/drop_unused/issue_1715_4/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/reduce_vars/duplicate_lambda_defun_name_1/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/reduce_vars/duplicate_lambda_defun_name_2/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/reduce_vars/inverted_var/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/typeof/duplicate_lambda_arg_name/output.js, crates/swc_ecma_minifier/tests/terser/compress/typeof/duplicate_lambda_arg_name/output.mangleOnly.js, crates/swc_ecma_transforms_base/src/resolver/mod.rs, crates/swc_ecma_transforms_base/tests/resolver/class/nested/var/output.js, crates/swc_ecma_transforms_base/tests/resolver/export/default/fn_decl/scope/output.js, crates/swc_ecma_transforms_base/tests/resolver/fn_expr/scope/output.js, crates/swc_ecma_transforms_base/tests/resolver/issues/271/output.js, crates/swc_ecma_transforms_base/tests/resolver/issues/292/1/output.js, crates/swc_ecma_transforms_base/tests/resolver/issues/292/2/output.js, crates/swc_ecma_transforms_base/tests/resolver/issues/438/output.js, crates/swc_ecma_transforms_base/tests/resolver/minifier/15/output.js, crates/swc_ecma_transforms_base/tests/resolver/minifier/16/output.js
=> fix(es/base): Use seperate mark for FnExpr Ident

crates/swc/tests/tsc-references/ES5For-of1.2.minified.js, crates/swc/tests/tsc-references/ES5For-of22.2.minified.js, crates/swc/tests/tsc-references/ES5For-of23.2.minified.js, crates/swc/tests/tsc-references/ES5For-of33.2.minified.js, crates/swc/tests/tsc-references/classStaticBlock15(target=es2015).2.minified.js, crates/swc/tests/tsc-references/classStaticBlock15(target=es2022).2.minified.js, crates/swc/tests/tsc-references/destructuringObjectBindingPatternAndAssignment6(target=es5).2.minified.js, crates/swc/tests/tsc-references/destructuringObjectBindingPatternAndAssignment7(target=es5).2.minified.js, crates/swc/tests/tsc-references/destructuringObjectBindingPatternAndAssignment8(target=es5).2.minified.js, crates/swc/tests/tsc-references/importsNotUsedAsValues_error.2.minified.js, crates/swc/tests/tsc-references/privateNameSetterExprReturnValue.2.minified.js, crates/swc/tests/tsc-references/requireTwoPropertyAccesses.2.minified.js, crates/swc/tests/vercel/full/utf8-1/output/index.js, crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/src/compress/util/mod.rs, crates/swc_ecma_minifier/tests/TODO.txt, crates/swc_ecma_minifier/tests/fixture/issues/5280/output.js, crates/swc_ecma_minifier/tests/fixture/issues/5680/config.json, crates/swc_ecma_minifier/tests/fixture/issues/5910/1/output.js, crates/swc_ecma_minifier/tests/fixture/next/wrap-contracts/output.js, crates/swc_ecma_minifier/tests/passing.txt, crates/swc_ecma_minifier/tests/projects/output/mootools-1.4.5.js, crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/collapse_vars_eval_and_with/output.js, crates/swc_ecma_minifier/tests/terser/compress/functions/duplicate_argnames/output.js, crates/swc_ecma_minifier/tests/terser/compress/issue_1639/issue_1639_3/output.js, crates/swc_ecma_minifier/tests/terser/compress/loops/dead_code_condition/output.js, crates/swc_ecma_minifier/tests/terser/compress/reduce_vars/var_assign_5/output.js, crates/swc_ecma_minifier/tests/terser/compress/sequences/lift_sequences_2/output.js, crates/swc_ecma_minifier/tests/terser/compress/sequences/lift_sequences_5/output.js, crates/swc_ecma_minifier/tests/terser/compress/sequences/lift_sequences_6/output.js
We can skip **member access** to `console` as it does not have any side effect.
Ref: https://developer.mozilla.org/en-US/docs/Web/API/console
=> feat(es/minifier): Ignore more expressions in sequential inliner

crates/swc/tests/exec/issues-5xxx/5950/1/.swcrc, crates/swc/tests/exec/issues-5xxx/5950/1/exec.js, crates/swc_ecma_minifier/src/analyzer/mod.rs
- Closes https://github.com/swc-project/swc/issues/5950.
=> fix(es/minifier): Fix analysis of nested function-like properties

crates/swc_ecma_minifier/tests/fixture/issues/5955/input.js, crates/swc_ecma_minifier/tests/fixture/issues/5955/output.js, crates/swc_ecma_minifier/tests/fixture/issues/5955/output.mangleOnly.js, crates/swc_ecma_transforms_optimization/src/simplify/dce/mod.rs, crates/swc_ecma_utils/src/lib.rs
=> fix(es/optimization): Preserve export

crates/swc_ecma_minifier/src/analyzer/mod.rs, crates/swc_ecma_minifier/src/analyzer/storage/mod.rs, crates/swc_ecma_minifier/src/analyzer/storage/normal.rs, crates/swc_ecma_minifier/src/compress/optimize/iife.rs, crates/swc_ecma_minifier/src/compress/optimize/inline.rs, crates/swc_ecma_minifier/src/compress/optimize/unused.rs, crates/swc_ecma_minifier/tests/benches-full/echarts.js, crates/swc_ecma_minifier/tests/benches-full/lodash.js, crates/swc_ecma_minifier/tests/benches-full/three.js, crates/swc_ecma_minifier/tests/benches-full/victory.js, crates/swc_ecma_minifier/tests/fixture/issues/5955/output.js, crates/swc_ecma_minifier/tests/fixture/issues/firebase-core/1/output.js, crates/swc_ecma_minifier/tests/fixture/issues/quagga2/1.4.2/1/output.js, crates/swc_ecma_minifier/tests/fixture/next/feedback-2/codemirror/output.js, crates/swc_ecma_minifier/tests/fixture/next/react-pdf-renderer/output.js, crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/collapse_vars_self_reference/output.js, crates/swc_ecma_transforms_base/tests/resolver/minifier/18/input.js, crates/swc_ecma_transforms_base/tests/resolver/minifier/18/output.js
=> mod(es/minifier): cache recursive use

crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/src/option.rs
Fix typo in the option name
Yes
No
=> fix(html/minifier): typo

Cargo.toml, crates/swc_core/Cargo.toml, crates/swc_ecma_ast/Cargo.toml, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/Cargo.lock, crates/swc_plugin_runner/tests/fixture/swc_noop_plugin/Cargo.lock
This PR attempts to apply workspaces dep inheritance over internal packages. If this publishes as expected, we can reduce lot of duplications across pkgs.
=> build(cargo): use workspace deps for internal pkg

node-swc/src/types.ts
Add type definition for module config
fix type definition for mangle
fix: #5917
fix: #5717
=> fix: update type definitions

crates/swc/tests/exec/issues-5xxx/5994/exec.js, crates/swc/tests/exec/issues-5xxx/5994/exec.mjs, crates/swc_ecma_transforms_compat/src/es2015/generator.rs
- Closes https://github.com/swc-project/swc/issues/5994.
=> fix(es/compat): Fix handling of op-assignment in `generator`

crates/swc_css_modules/src/lib.rs, crates/swc_css_modules/tests/fixture/modules/tests-cases/leak-scope/source.compiled.css, crates/swc_css_modules/tests/fixture/modules/tests-cases/local/source.compiled.css, crates/swc_css_modules/tests/fixture/modules/tests-cases/mode-switching/source.compiled.css, crates/swc_css_modules/tests/fixture/modules/tests-cases/mode-switching/source.transform.json
This PR adds support for `:local` and `:global` directives.
=> feat(css/modules): Support `:local` and `:global`

crates/swc_css_modules/src/lib.rs, crates/swc_css_modules/tests/fixture.rs, crates/swc_css_modules/tests/fixture/modules/tests-cases/leak-scope/source.compiled.css
=> feat(css/modules): Support `:global` in `@keyframes`

.github/workflows/codeball.yml, crates/swc_ecma_codegen/src/comments.rs
This PR configures codeball to automate code reviews partially.
=> chore(ci): Configure codeball

Cargo.lock, crates/swc_core/Cargo.toml, crates/swc_core/src/lib.rs
=> feat(swc_core): Reexport `swc_css_compat`

crates/string_enum/src/lib.rs, crates/string_enum/tests/simple.rs, crates/swc_ecma_preset_env/data/@babel/compat-data/data/plugin-bugfixes.json, crates/swc_ecma_preset_env/data/@babel/compat-data/data/plugins.json, crates/swc_ecma_preset_env/data/core-js-compat/data.json, crates/swc_ecma_preset_env/data/core-js-compat/entries.json, crates/swc_ecma_preset_env/data/core-js-compat/modules-by-versions.json, crates/swc_ecma_preset_env/src/transform_data.rs, package.json
=> fix(es/preset-env): Update data

crates/swc_css_prefixer/tests/fixture/gradient/input.css, crates/swc_css_prefixer/tests/fixture/gradient/output.css, crates/swc_css_prefixer/tests/fixture/gradient/output.defaults-not-ie-11.css
Port tests from https://github.com/postcss/autoprefixer/commit/2d286dd8b7dda067c4d5f3445f6bd1f17094202f
Currently we don't support very old `linear-gradient` (we have TODO for it, but it is really old syntax, so it is not high priority right now)
No
No
=> test(css/prefixer): verify

crates/swc_ecma_utils/src/parallel.rs
=> feat(es/utils): Add indexed API to the parallel helper

crates/swc_ecma_transforms_optimization/src/simplify/expr/mod.rs
=> fix(es/minifier): Don't create a numeric literal with `NaN` value

crates/swc/tests/tsc-references/abstractProperty(target=es2015).1.normal.js, crates/swc/tests/tsc-references/abstractProperty(target=es2022).1.normal.js, crates/swc_ecma_transforms_typescript/src/strip.rs, crates/swc_ecma_transforms_typescript/tests/strip.rs
=> fix(es/typescript): Don't generate class field for abstract props

crates/swc_plugin_runner/Cargo.toml, crates/swc_plugin_runner/src/cache.rs
=> build(es/plugin): Fix Wasm build

Cargo.lock, crates/swc_node_base/Cargo.toml
This PR bumps up mimalloc-rust to align transitive dependencies across packages.
=> build(node_base): bump up mimalloc

crates/swc_html_ast/src/base.rs, crates/swc_html_ast/src/token.rs, crates/swc_html_parser/src/lexer/mod.rs, crates/swc_html_parser/src/parser/mod.rs, crates/swc_html_parser/src/parser/node.rs, crates/swc_html_parser/tests/html5lib_tests.rs, crates/swc_html_visit/src/lib.rs
Before using `swc_html_minify` to bench:
```
html/minify/document/css_spec                                                                           
time:   [48.143 ms 48.257 ms 48.390 ms]
change: [-3.1896% -0.9565% +0.6793%] (p = 0.46 > 0.05)
1 (10.00%) high severe
html/minify/document/github                                                                           
time:   [19.532 ms 19.569 ms 19.618 ms]
change: [-3.1896% -0.9565% +0.6793%] (p = 0.46 > 0.05)
No change in performance detected.
1 (10.00%) high severe
html/minify/document/stackoverflow                                                                           
time:   [16.958 ms 17.008 …
```
=> perf(html/parser): atom + perf

crates/swc_html_parser/src/lexer/mod.rs, crates/swc_html_parser/src/parser/active_formatting_element_stack.rs
Missing this in the previously PR
Avoid cloning when we are working with active formatting elements
No
No
=> perf(html/parser): small improvement

Cargo.lock, crates/swc_node_base/Cargo.toml
=> chore(swc_node_base): update jemallocator

crates/swc/tests/exec/issues-6xxx/6127/1/input/.swcrc, crates/swc/tests/exec/issues-6xxx/6127/1/input/exec.js, crates/swc_ecma_minifier/tests/exec.rs, crates/swc_html_parser/tests/html5lib_tests.rs
- Closes https://github.com/swc-project/swc/issues/6217.
=> test(es/minifier): Add a test for a fixed issue

node-swc/__tests__/transform/preset-env_test.mjs
- Closes https://github.com/swc-project/swc/issues/5052
=> test(es/preset-env): Ensure custom transforms are working

crates/swc_css_parser/src/lexer/mod.rs, crates/swc_css_parser/src/parser/input.rs, crates/swc_css_parser/src/parser/mod.rs, crates/swc_css_parser/src/parser/util.rs, crates/swc_css_parser/src/parser/values_and_units/mod.rs, crates/swc_css_parser/tests/fixture/only/1/input.css, crates/swc_css_parser/tests/fixture/only/1/output.json, crates/swc_css_parser/tests/fixture/only/1/span.rust-debug, crates/swc_css_parser/tests/recovery/at-rule/document/output.swc-stderr
cc @alexander-akait I did this because this is very important
=> fix(css/parser): Add more error recovery

Cargo.lock, crates/swc_node_base/Cargo.toml
=> build(bindings): Revert jemallloc bump

crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/tests/TODO.txt, crates/swc_ecma_minifier/tests/passing.txt, crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/may_throw_2/output.js, crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/reduce_vars_assign/output.js, crates/swc_ecma_minifier/tests/terser/compress/drop_unused/assign_binding/output.js, crates/swc_ecma_minifier/tests/terser/compress/issue_281/drop_fargs/output.js, crates/swc_ecma_minifier/tests/terser/compress/issue_281/keep_fargs/output.js, crates/swc_ecma_minifier/tests/terser/compress/sequences/func_def_1/output.js, crates/swc_ecma_minifier/tests/terser/compress/sequences/func_def_3/output.js, crates/swc_ecma_minifier/tests/terser/compress/sequences/func_def_4/output.js
The real purpose of this PR is organizing terser test list.
=> feat(es/minifier): Respect options

bindings/Cargo.lock, bindings/binding_core_node/Cargo.toml, bindings/binding_core_wasm/Cargo.toml, bindings/swc_cli/Cargo.toml, package.json
=> chore: Publish `v1.3.11`

crates/swc/tests/exec/issues-6xxx/6332/exec.js
- Closes https://github.com/swc-project/swc/issues/6332
=> test(es/resolver): Add a test about hoisting of functions in a switch

crates/swc/tests/tsc-references/classStaticBlock5(target=es2015).1.normal.js, crates/swc/tests/tsc-references/classStaticBlock5(target=es2015).2.minified.js, crates/swc/tests/tsc-references/classStaticBlock5(target=es5).1.normal.js, crates/swc/tests/tsc-references/classStaticBlock5(target=es5).2.minified.js, crates/swc/tests/tsc-references/superInStaticMembers1(target=es2015).1.normal.js, crates/swc/tests/tsc-references/superInStaticMembers1(target=es2015).2.minified.js, crates/swc/tests/tsc-references/superInStaticMembers1(target=es2021).1.normal.js, crates/swc/tests/tsc-references/superInStaticMembers1(target=es2021).2.minified.js, crates/swc/tests/tsc-references/superInStaticMembers1(target=es5).1.normal.js, crates/swc/tests/tsc-references/superInStaticMembers1(target=es5).2.minified.js, crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs, crates/swc_ecma_transforms_compat/tests/es2022_class_properties.rs
=> fix(es/compat): super in private static prop

crates/swc/tests/errors/lints/const-assign/3/input.js, crates/swc/tests/errors/lints/const-assign/3/output.swc-stderr, crates/swc/tests/tsc-references/assignmentToParenthesizedIdentifiers.1.normal.js, crates/swc/tests/tsc-references/assignmentToParenthesizedIdentifiers.2.minified.js, crates/swc/tests/tsc-references/assignments.1.normal.js, crates/swc/tests/tsc-references/assignments.2.minified.js, crates/swc/tests/tsc-references/invalidUndefinedAssignments.1.normal.js, crates/swc/tests/tsc-references/invalidUndefinedAssignments.2.minified.js, crates/swc/tests/tsc-references/validNullAssignments.1.normal.js, crates/swc/tests/tsc-references/validNullAssignments.2.minified.js, crates/swc_ecma_lints/src/rules/const_assign.rs
=> fix(es/lints): Disallow assign to class

crates/swc_ecma_transforms_compat/src/es2020/nullish_coalescing/mod.rs, crates/swc_ecma_transforms_compat/src/es2020/nullish_coalescing/tests.rs
=> fix(es/compat): Nullish coalescing in case condition with empty body

packages/swc-helpers/src/_decorate.mjs
fix the import `_typeof` in `_decorate.mjs`.
=> fix(swc-helpers): import _typeof in _decorate

crates/swc_css_parser/src/parser/values_and_units/mod.rs
After refactor we don't need it anymore
No
No
=> refactor(css/parser): avoid unnecessary checks

Cargo.lock, crates/swc_core/Cargo.toml, crates/swc_core/src/lib.rs
Exposes css_modules via swc_core.
=> feat(swc/core): expose css_modules

CONTRIBUTING.md
`swc_plugin_runner` cannot be compiled with `memory_cache` feature.
Also, there are some feature issues about `memory_cache` with `rkyv-impl`.
So let new comers use the `filesystem_cache` not affected by above things.
**BREAKING CHANGE: X** 
- https://github.com/swc-project/swc/issues/6232
=> doc(contributing): Change cache feature for running all tests

crates/swc_css_parser/src/parser/at_rules/mod.rs, crates/swc_css_parser/src/parser/syntax/mod.rs, crates/swc_css_parser/src/parser/util.rs, crates/swc_css_parser/src/parser/values_and_units/mod.rs, crates/swc_css_parser/tests/recovery/at-rule/layer/empty/output.swc-stderr
refactor code +  fix bugs with block scope
No
No
=> fix(css/parser): bug with scope in block

crates/swc_plugin_proxy/src/comments/plugin_comments_proxy.rs, crates/swc_plugin_proxy/src/metadata/transform_plugin_metadata.rs
Followup changes for https://github.com/swc-project/swc/pull/6426 attempts to fix https://github.com/swc-project/swc/discussions/3540#discussioncomment-4143924.
=> fix(swc/plugin_proxy): adjust import with compile time flags

.github/workflows/CI.yml, Cargo.lock, bindings/binding_core_wasm/Cargo.toml, bindings/binding_core_wasm/src/lib.rs, crates/binding_macros/Cargo.toml, crates/binding_macros/src/wasm.rs, crates/swc_core/.gitignore, crates/swc_core/Cargo.toml, crates/swc_core/tests/fixture/stub_napi/Cargo.toml, crates/swc_core/tests/fixture/stub_napi/build.rs, crates/swc_core/tests/fixture/stub_napi/src/lib.rs, crates/swc_core/tests/fixture/stub_wasm/Cargo.toml, crates/swc_core/tests/fixture/stub_wasm/src/lib.rs, crates/swc_core/tests/integration.rs
Second attempts to https://github.com/swc-project/swc/pull/6436, with various fixes to ensure things are not breaking.
PR also adds naive testing to swc_core to test with latest workspace root to build. This allows to catch problems upfront before publish swc_core (not @swc/core). It actually caught various failures while I'm working on this PR.
Also, PR updates `bindings_macro` to reflect latest changes.
=> refactor(bindings/wasm): deprecate jsvalue::*_serde

crates/swc_ecma_transforms_base/src/helpers/mod.rs
Probably not a noticeable improvement.
=> perf(es/transform_base): return early if any helper is used

crates/swc_ecma_parser/src/parser/typescript.rs, crates/swc_ecma_parser/tests/typescript/issue-6430/index.ts, crates/swc_ecma_parser/tests/typescript/issue-6430/index.ts.json
Fix parsing
No
fixes https://github.com/swc-project/swc/issues/6430
=> fix(ecma/parser): `typeof` in `TSCallSignatureDeclaration`

crates/swc_common/src/source_map.rs
Just a few cleanups after https://github.com/swc-project/swc/pull/6561
=> Small cleanup to the source_map module

crates/swc_ecma_minifier/src/lib.rs, crates/swc_ecma_minifier/src/metadata/mod.rs
1. remove unnecessary code, this function is invoked but did nothing if it return true,
also https://github.com/swc-project/swc/blob/9a20ddff71d31049a6b03d324ba3f20b04979645/crates/swc_ecma_minifier/src/metadata/mod.rs#L350-L444, Although this visitor visit `&mut ` Ast node, but we could see that it does't modified ast node, over all, remove 
those code is safe.
2. This pr would improve a little performance.
=> chore: 🤖 remove unnecessary code

crates/swc_css_ast/src/base.rs, crates/swc_css_ast/src/selector.rs, crates/swc_css_ast/src/token.rs, crates/swc_css_minifier/src/compressor/rules.rs, crates/swc_css_parser/scripts/instruemnt/bench-lexer.sh, crates/swc_css_parser/scripts/instruemnt/bench-parser.sh
- Remove redundant clone of selectors.
---
=> perf(css/minifier): Remove redundant clone

crates/swc_css_ast/src/base.rs, crates/swc_css_minifier/src/compressor/rules.rs
=> perf(css/minifier): Remove more redundant clones

crates/swc_css_parser/benches/lexer.rs
=> chore: fix typo in benches

crates/swc_css_parser/src/lexer/mod.rs, crates/swc_css_parser/src/macros.rs, crates/swc_css_parser/tests/fixture/value/ident/input.css, crates/swc_css_parser/tests/fixture/value/ident/output.json, crates/swc_css_parser/tests/fixture/value/ident/span.swc-stderr, crates/swc_css_parser/tests/fixture/value/url/input.css, crates/swc_css_parser/tests/fixture/value/url/output.json, crates/swc_css_parser/tests/fixture/value/url/span.swc-stderr, crates/swc_css_parser/tests/line-comment/css-in-js/11/input.css, crates/swc_css_parser/tests/line-comment/css-in-js/11/output.json, crates/swc_css_parser/tests/line-comment/css-in-js/11/span.swc-stderr
Refactor and small perf improvement due to avoid unnecessary calls + tests for edge cases
No
No
=> perf(css/parser): refactor and small perf improvement

crates/swc_html_codegen/src/lib.rs, crates/swc_html_parser/benches/lexer.rs, crates/swc_html_parser/benches/parser.rs, crates/swc_html_parser/src/lexer/mod.rs, crates/swc_html_parser/tests/recovery/doctype/newline/dom.rust-debug, crates/swc_html_parser/tests/recovery/doctype/newline/input.html, crates/swc_html_parser/tests/recovery/doctype/newline/output.json, crates/swc_html_parser/tests/recovery/doctype/newline/output.stderr, crates/swc_html_parser/tests/recovery/doctype/newline/span.rust-debug
- Also small bug fix for `swc_html_codegen`
perf:
```
html/parser_document/css_2021_spec                                                                            
time:   [23.669 ms 23.763 ms 23.871 ms]
change: [-4.2093% -3.4579% -2.7503%] (p = 0.00 < 0.05)
Found 6 outliers among 100 measurements (6.00%)
3 (3.00%) high mild
3 (3.00%) high severe
Benchmarking html/parser_document/github_com_17_05_2022: Collecting 100 samples in estimated 5.1213 s (600 iterati                                                                                                                  html/parser_document/github_com_17_05_2022                        
time:   [8.2812 ms 8.3389 ms 8.4115 ms]
change: [-11.642% -10.727% -9.6697%] (p = 0.00 < 0.05)
Performance has …
```
=> perf(html/parser): improve

crates/swc_css_parser/src/parser/syntax/mod.rs
=> refactor(css/parser): small refactoring to align with spec

crates/swc_ecma_transforms_typescript/src/strip.rs, crates/swc_ecma_transforms_typescript/tests/fixture/issue-6598/input.ts
=> fix(es/transform_typescript): import inline type declaration is striped incorrectly

crates/dbg-swc/src/minify/reduce.rs, crates/dbg-swc/src/util/mod.rs
=> feat(dbg-swc): Kill `creduce` on drop

crates/swc_atoms/words.txt, crates/swc_css_prefixer/data/prefixes_and_browsers.json, crates/swc_css_prefixer/src/prefixer.rs, crates/swc_css_prefixer/tests/fixture/display/input.css, crates/swc_css_prefixer/tests/fixture/display/output.css, crates/swc_css_prefixer/tests/fixture/display/output.defaults-not-ie-11.css
Port - https://preset-env.cssdb.org/features/#display-two-values
No
No
=> feat(css/prefixer): port display

crates/swc_css_compat/src/compiler/color_hex_alpha.rs, crates/swc_css_compat/src/compiler/mod.rs, crates/swc_css_compat/src/feature.rs, crates/swc_css_compat/tests/color-hex-alpha/input.css, crates/swc_css_compat/tests/color-hex-alpha/input.expect.css, crates/swc_css_compat/tests/fixture.rs
Port https://preset-env.cssdb.org/features/#hexadecimal-alpha-notation
No
No
=> feat(css/compat): color hex alpha

Cargo.lock, bindings/Cargo.lock, package.json, yarn.lock
Refs: https://github.com/oracle/graal/issues/5581
=> fix(bindings): crash in GraalVM

scripts/cli_artifacts.sh
Minor fix and hope to resolve upload issues for all.
=> ci(actions): fix upload cli binaries

crates/swc_css_prefixer/data/prefixes_and_browsers.json, crates/swc_css_prefixer/src/prefixer.rs, crates/swc_css_prefixer/tests/fixture/multicolumn/output.css, crates/swc_css_prefixer/tests/fixture/page-break/input.css, crates/swc_css_prefixer/tests/fixture/page-break/output.css, crates/swc_css_prefixer/tests/fixture/page-break/output.defaults-not-ie-11.css
Port - https://github.com/shrpne/postcss-page-break/
Also:
- fix bug with duplicate properties (still need to check logic for duplicate values)
- refactor code
No
No
=> feat(css/prefixer): page break

crates/swc/examples/minify.rs, crates/swc/examples/transform.rs, crates/swc/examples/transform_error.rs
fix example of swc
I think it was broken by https://github.com/swc-project/swc/pull/5975
=> fix(swc): example

crates/swc/tests/fixture/jest/issue-6540/input/.swcrc, crates/swc/tests/fixture/jest/issue-6540/input/index.ts, crates/swc/tests/fixture/jest/issue-6540/output/index.ts, crates/swc_ecma_ext_transforms/src/jest.rs
- Closes https://github.com/swc-project/swc/issues/6540.
=> feat(es/jest): Support chaining of jest function calls

crates/swc_ecma_minifier/src/eval.rs, crates/swc_ecma_minifier/tests/eval.rs
=> fix(es/minifier): handle boolean in Evaluator

crates/swc_ecma_transforms_base/src/helpers/_class_private_field_loose_base.js, packages/swc-helpers/src/_class_private_field_loose_base.mjs
=> fix(es/helper): `classPrivateFieldBase` should return receiver

crates/swc_ecma_transforms_compat/tests/es2015_parameters.rs, crates/swc_ecma_transforms_compat/tests/parameters/issue-6790/1/input.js, crates/swc_ecma_transforms_compat/tests/parameters/issue-6790/1/output.js
- Closes https://github.com/swc-project/swc/issues/6790.
=> test(es/compat): Add a test to verify parameters passs

crates/swc/src/config/mod.rs, crates/swc_ecma_minifier/src/pass/mangle_names/mod.rs, crates/swc_ecma_minifier/tests/TODO.txt, crates/swc_ecma_minifier/tests/mangle.rs, crates/swc_ecma_minifier/tests/passing.txt, crates/swc_ecma_minifier/tests/postponed.txt, crates/swc_ecma_minifier/tests/terser/compress/harmony/class_name_can_be_preserved/output.js, crates/swc_ecma_minifier/tests/terser/compress/keep_names/keep_classnames/output.js, crates/swc_ecma_minifier/tests/terser/compress/try_catch/broken_safari_catch_scope/output.js, crates/swc_ecma_minifier/tests/terser/compress/try_catch/broken_safari_catch_scope_caveat/output.js, crates/swc_ecma_transforms_base/src/hygiene/mod.rs, crates/swc_ecma_transforms_base/src/hygiene/tests.rs, crates/swc_ecma_transforms_base/src/rename/analyzer/mod.rs, crates/swc_ecma_transforms_base/src/rename/mod.rs, crates/swc_ecma_transforms_base/src/resolver/tests.rs
=> feat(es/renamer): Support `safari10` from the name mangler

crates/swc_ecma_minifier/tests/pass-1/regexp/1/input.js, crates/swc_ecma_minifier/tests/pass-1/regexp/1/output.js
- https://github.com/vercel/next.js/discussions/30237#discussioncomment-4674405
=> test(es/minifier): Add a test for an invalid issue

crates/swc_ecma_minifier/src/compress/pure/mod.rs, crates/swc_ecma_minifier/tests/pass-1/issue-6788/1/input.js, crates/swc_ecma_minifier/tests/pass-1/issue-6788/1/output.js
- Closes https://github.com/swc-project/swc/issues/6788.
=> feat(es/minifier): Remove noop spreads

crates/swc_atoms/words.txt, crates/swc_css_ast/src/at_rule.rs, crates/swc_css_codegen/src/lib.rs, crates/swc_css_codegen/tests/fixture.rs, crates/swc_css_codegen/tests/fixture/at-rules/media/4/output.css, crates/swc_css_codegen/tests/fixture/at-rules/page/1/output.css, crates/swc_css_compat/src/compiler/custom_media.rs, crates/swc_css_modules/tests/fixture/import/import.compiled.css, crates/swc_css_parser/src/parser/at_rules/mod.rs, crates/swc_css_parser/tests/fixture/at-rule/color-profile/input.css, crates/swc_css_parser/tests/fixture/at-rule/color-profile/output.json, crates/swc_css_parser/tests/fixture/at-rule/color-profile/span.swc-stderr, crates/swc_css_parser/tests/fixture/at-rule/container/input.css, crates/swc_css_parser/tests/fixture/at-rule/container/output.json, crates/swc_css_parser/tests/fixture/at-rule/container/span.swc-stderr, crates/swc_css_parser/tests/fixture/at-rule/custom-media/output.json, crates/swc_css_parser/tests/fixture/at-rule/custom-media/span.swc-stderr, crates/swc_css_parser/tests/fixture/at-rule/import/output.json, crates/swc_css_parser/tests/fixture/at-rule/media/input.css, crates/swc_css_parser/tests/fixture/at-rule/media/output.json, crates/swc_css_parser/tests/fixture/at-rule/media/span.swc-stderr, crates/swc_css_parser/tests/fixture/at-rule/page/input.css, crates/swc_css_parser/tests/fixture/at-rule/page/output.json, crates/swc_css_parser/tests/fixture/at-rule/page/span.swc-stderr, crates/swc_css_parser/tests/fixture/at-rule/supports/output.json, crates/swc_css_parser/tests/recovery/at-rule/page/no-space/span.swc-stderr, crates/swc_css_prefixer/src/prefixer.rs, crates/swc_css_visit/src/lib.rs
Here:
- normalize ident to lowercase where it is allowed by spec
- improve AST for custom media by spec (comment in code)
- more tests
Yes
No
=> feat(css/parser): normalize at-rules

crates/swc_ecma_preset_env/src/corejs3/data.rs
=> refact(es/preset-env): use const fn instead of macro

crates/swc_ecma_minifier/src/compress/pure/arrows.rs, crates/swc_ecma_minifier/tests/fixture/issues/6730/output.js, crates/swc_ecma_minifier/tests/pass-1/issue-6123/1/config.json, crates/swc_ecma_minifier/tests/pass-1/issue-6123/1/input.js, crates/swc_ecma_minifier/tests/pass-1/issue-6123/1/output.js
- Closes https://github.com/swc-project/swc/issues/6123.
=> feat(es/minifier): Improve compatibility of `arrows` with `terser`

crates/swc_ecma_minifier/src/program_data.rs, crates/swc_ecma_minifier/tests/fixture/issues/6864/input.js, crates/swc_ecma_minifier/tests/fixture/issues/6864/output.js
- Closes https://github.com/swc-project/swc/issues/6864.
=> fix(es/minifier): Track reassign in parent scope

crates/swc_visit_macros/src/lib.rs
=> fix(es/visit_macros): change `NewExprField::Args` => `NewExprField::Args(usize)`

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Actually this is a comment template but GitHub does not support it.
=> chore: Make issue templates mention `no +1`

node-swc/src/types.ts
**Description:** Fix #6904
**BREAKING CHANGE:** No
**Related issue (if exists):** Fix #6904
=> fix(node-swc/types): add missing "esnext" target for JscTarget

crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/tests/exec.rs, crates/swc_ecma_transforms_optimization/src/simplify/expr/mod.rs
- Closes https://github.com/swc-project/swc/issues/6896.
=> fix(es/minifier): Respect span hygiene from expr simplifier

crates/swc_ecma_transforms_react/src/jsx/mod.rs, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-6931/input.js, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-6931/output.mjs, crates/swc_ecma_transforms_react/tests/jsx/fixture/vercel/1/output.mjs
- Closes https://github.com/swc-project/swc/issues/6931.
=> fix(es/react): Fix handling of whitespaces

crates/swc_bundler/src/bundler/export.rs
Fixes #6946
No breaking change expected
**Related issue (if exists):** #6946
=> fix(bundler): Don't panic while finding exports

crates/swc_ecma_parser/src/parser/expr.rs
Closed https://github.com/swc-project/swc/issues/6966
=> chore: reduce preAllocation to save memory usage

crates/swc/tests/exec.rs, crates/swc/tests/fixture/issues-3xxx/3686/1/output/index.ts, crates/swc/tests/fixture/issues-6xxx/6951/1/input/.swcrc, crates/swc/tests/fixture/issues-6xxx/6951/1/input/index.ts, crates/swc/tests/fixture/issues-6xxx/6951/1/output/index.ts, crates/swc/tests/fixture/issues-6xxx/6951/2/input/.swcrc, crates/swc/tests/fixture/issues-6xxx/6951/2/input/index.ts, crates/swc/tests/fixture/issues-6xxx/6951/2/output/index.ts, crates/swc/tests/fixture/issues-6xxx/6951/3/input/.swcrc, crates/swc/tests/fixture/issues-6xxx/6951/3/input/index.ts, crates/swc/tests/fixture/issues-6xxx/6951/3/output/index.ts, crates/swc/tests/fixture/issues-6xxx/6951/4/input/.swcrc, crates/swc/tests/fixture/issues-6xxx/6951/4/input/index.ts, crates/swc/tests/fixture/issues-6xxx/6951/4/output/index.ts, crates/swc_ecma_transforms/tests/fixture/legacy-metadata/issues/3979/output.ts, crates/swc_ecma_transforms/tests/fixture/legacy-only/issues/1913/1/output.ts, crates/swc_ecma_transforms/tests/fixture/legacy-only/issues/1913/2/output.ts, crates/swc_ecma_transforms/tests/fixture/legacy-only/issues/591/1/output.ts, crates/swc_ecma_transforms/tests/fixture/legacy-only/issues/591/2/output.ts, crates/swc_ecma_transforms/tests/fixture/legacy-only/issues/879/1/output.ts, crates/swc_ecma_transforms_optimization/tests/simplify_dce.rs, crates/swc_ecma_transforms_proposal/src/decorators/legacy/mod.rs, crates/swc_ecma_transforms_proposal/src/decorators/mod.rs, crates/swc_ecma_transforms_typescript/src/strip.rs
=> fix(es/decorator): Preserve class prop order

crates/swc/tests/fixture/issues-6xxx/6217/1/output/input.js, crates/swc/tests/fixture/issues-6xxx/6217/2/output/input.js, crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/tests/benches-full/jquery.js, crates/swc_ecma_minifier/tests/benches-full/terser.js, crates/swc_ecma_minifier/tests/benches-full/victory.js, crates/swc_ecma_minifier/tests/fixture/issues/6422/1/output.js, crates/swc_ecma_minifier/tests/fixture/issues/7004/input.js, crates/swc_ecma_minifier/tests/fixture/issues/7004/output.js, crates/swc_ecma_minifier/tests/fixture/next/react-pdf-renderer/output.js, crates/swc_ecma_minifier/tests/fixture/next/syncfusion/933-e9f9a6bf671b96fc/output.js
=> fix(es/minifier): Seq Inline wrongly callee with side effect

crates/swc_ecma_minifier/src/compress/pure/misc.rs, crates/swc_ecma_minifier/tests/fixture/issues/4234/output.js, crates/swc_ecma_minifier/tests/terser/compress/issue_269/regexp/output.js
=> fix(es/minifier): Bailout Regex optimization when facing invalid flags

bindings/Cargo.lock, bindings/binding_core_node/Cargo.toml, bindings/binding_core_wasm/Cargo.toml, bindings/swc_cli/Cargo.toml, crates/swc_ecma_minifier/src/compress/pure/evaluate.rs, crates/swc_ecma_parser/src/error.rs, crates/swc_ecma_parser/src/lexer/mod.rs, crates/swc_ecma_parser/src/lexer/number.rs, crates/swc_ecma_parser/src/lexer/util.rs
=> perf(es/parser): Use `SmartString` as the buffer

crates/swc_ecma_parser/src/parser/class_and_fn.rs, crates/swc_ecma_parser/tests/typescript/issue-7042/case1/input.ts, crates/swc_ecma_parser/tests/typescript/issue-7042/case1/input.ts.json, crates/swc_ecma_parser/tests/typescript/issue-7042/case2/input.ts, crates/swc_ecma_parser/tests/typescript/issue-7042/case2/input.ts.json, crates/swc_ecma_transforms_typescript/tests/fixture/issue-7042/case1/input.ts, crates/swc_ecma_transforms_typescript/tests/fixture/issue-7042/case1/output.js, crates/swc_ecma_transforms_typescript/tests/fixture/issue-7042/case2/input.ts, crates/swc_ecma_transforms_typescript/tests/fixture/issue-7042/case2/output.js
fix issue-7042
- Closes https://github.com/swc-project/swc/issues/7042.
=> fix: support accessor method and property

crates/swc_common/src/input.rs, crates/swc_ecma_parser/src/lexer/jsx.rs, crates/swc_ecma_parser/src/lexer/mod.rs, crates/swc_ecma_parser/src/lexer/state.rs, crates/swc_ecma_parser/src/lexer/util.rs
=> perf(es/lexer): Make lexer faster

crates/swc_ecma_transforms_base/src/fixer.rs, crates/swc_ecma_transforms_base/src/lib.rs, crates/swc_ecma_transforms_compat/src/es2022/class_properties/private_field.rs, crates/swc_ecma_transforms_compat/src/lib.rs
cc @dsherret for visibility.
- Closes https://github.com/swc-project/swc/issues/7039.
=> fix(es): Support stable rustc again

bindings/Cargo.lock, bindings/binding_core_node/Cargo.toml, bindings/binding_core_wasm/Cargo.toml, bindings/swc_cli/Cargo.toml
=> fix(bindings/cli): Update `swc_ecma_ast`

crates/swc/tests/fixture/issues-7xxx/7064/case1/input/.swcrc, crates/swc/tests/fixture/issues-7xxx/7064/case1/input/index.js, crates/swc/tests/fixture/issues-7xxx/7064/case1/output/index.js, crates/swc_ecma_transforms_compat/src/es2021/logical_assignments.rs
=> fix(es/compat): Insert the variable declaration nearest to the available statements

crates/swc_ecma_ast/src/source_map.rs, crates/swc_ecma_codegen/src/lib.rs
=> refactor(es/codegen): Extract code from generic functions to reduce compile time

crates/swc/tests/fixture/issues-7xxx/7174/input/.swcrc, crates/swc/tests/fixture/issues-7xxx/7174/input/index.js, crates/swc/tests/fixture/issues-7xxx/7174/output/index.js, crates/swc/tests/tsc-references/intraExpressionInferences.1.normal.js, crates/swc_ecma_transforms_compat/src/es2015/block_scoping/operator.rs
=> fix(es/compat): Handle shorthand object prop when rename

crates/swc_core/Cargo.toml
Corrects what appears to be a type in `swc_core`'s reexport of `ecma_loader_parking_lot`.
=> fix(core) ecma_loader_parking_lot reexport name

bindings/Cargo.lock, bindings/binding_core_wasm/Cargo.toml, package.json, yarn.lock
- Closes https://github.com/swc-project/swc/issues/7203.
=> chore: Publish `v1.3.46` with fixed `peerDependency`

package.json, yarn.lock
Mark the `@swc/helpers` dependency of `@swc/core` as optional.
Closes https://github.com/swc-project/swc/issues/7212
=> Make helpers an optional peer dependency of core

crates/swc_ecma_transforms_testing/src/lib.rs
cc @magic-akari for visibility.
=> fix(es/testing): Ensure that we call `fold_program`

crates/swc_plugin_runner/src/imported_fn/comments.rs, crates/swc_plugin_runner/src/imported_fn/metadata_context.rs, crates/swc_plugin_runner/src/memory_interop.rs, crates/swc_plugin_runner/src/transform_executor.rs
=> refactor(plugin/runner): Fix clippy warnings

crates/swc/tests/fixture/issues-7xxx/7241/input/.swcrc, crates/swc/tests/fixture/issues-7xxx/7241/input/index.js, crates/swc/tests/fixture/issues-7xxx/7241/output/index.js, crates/swc_ecma_minifier/src/metadata/mod.rs, crates/swc_ecma_minifier/tests/fixture/issues/7241/input.js, crates/swc_ecma_minifier/tests/fixture/issues/7241/output.js
- Closes https://github.com/swc-project/swc/issues/7241.
=> feat(es/minifier): Support `PURE` comment of seq exprs

crates/swc_atoms/Cargo.toml, crates/swc_common/Cargo.toml, crates/swc_common/src/plugin/serialized.rs, crates/swc_css_ast/Cargo.toml, crates/swc_ecma_ast/Cargo.toml, crates/swc_html_ast/Cargo.toml, crates/swc_plugin_proxy/Cargo.toml, crates/swc_plugin_proxy/src/memory_interop/mod.rs, crates/swc_plugin_proxy/src/memory_interop/read_returned_result_from_host.rs, crates/swc_plugin_proxy/src/source_map/plugin_source_map_proxy.rs, crates/swc_plugin_runner/src/imported_fn/source_map.rs, crates/swc_plugin_runner/src/memory_interop.rs, crates/swc_plugin_runner/tests/fixture/swc_internal_plugin/src/lib.rs
This PR enables validation features from rkyv, replaces unsafe/unchecked serialization into validated one.
=> feat(rkyv): enable validation

bindings/Cargo.lock, bindings/binding_core_node/Cargo.toml, bindings/binding_core_wasm/Cargo.toml, bindings/swc_cli/Cargo.toml, package.json
=> chore: Publish `v1.3.50` with `swc_core` `v0.75.15`

packages/swc-helpers/scripts/build.js
This pattern works in cjs-module-lexer as well. And it's valid synatx in es5 strict mode.
- fix #7264
=> fix(es/helpers): Do not duplicate property names

Cargo.lock, crates/preset_env_base/Cargo.toml, crates/swc_ecma_preset_env/Cargo.toml
x-ref: https://vercel.slack.com/archives/C02HY34AKME/p1681811874650839
=> perf(preset-env): Update static map

crates/swc/tests/fixture/issues-7xxx/7287/1/input/.swcrc, crates/swc/tests/fixture/issues-7xxx/7287/1/input/index.js, crates/swc/tests/fixture/issues-7xxx/7287/1/output/index.js, crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/tests/fixture/issues/7287/1/input.js, crates/swc_ecma_minifier/tests/fixture/issues/7287/1/output.js
- Closes https://github.com/swc-project/swc/issues/7287.
=> fix(es/minifier): Fix a inliner bug related to `Script`

crates/swc/tests/exec/issues-7xxx/7248/1/exec.js, crates/swc/tests/tsc-references/parameterInitializersForwardReferencing.1.normal.js, crates/swc_ecma_transforms_base/src/resolver/mod.rs, crates/swc_ecma_transforms_base/tests/resolver/issue-7248/input.js, crates/swc_ecma_transforms_base/tests/resolver/issue-7248/output.js, crates/swc_ecma_transforms_base/tests/ts-resolver/issue-5622/2/output.ts
=> fix(es/hygiene): Hoist parameter in arrow and constructor

crates/swc_ecma_transforms_compat/tests/es2020_nullish_coalescing.rs
=> test(es/compat): Add a test for a wrong issue

Cargo.lock, bindings/swc_cli/src/commands/compile.rs, crates/swc/src/lib.rs
- Reverts #7229.
- Closes #7301.
=> fix(es): Fix a crash related to source map

packages/swc-helpers/.dprint.json, packages/swc-helpers/.gitignore, packages/swc-helpers/package.json, packages/swc-helpers/scripts/build.js
- https://github.com/vercel/next.js/issues/48593
=> fix(swc-helpers): Add `src/*.mjs` entry back

crates/swc_plugin_runner/src/cache.rs
This reverts commit 245163a77827767ab0b4df59d00597c4af62d745.
=> fix(plugin/runner): Revert #7341

crates/swc_ecma_transforms_compat/src/es2015/parameters.rs, crates/swc_ecma_transforms_compat/tests/parameters/vercel-1/input.js, crates/swc_ecma_transforms_compat/tests/parameters/vercel-1/output.js
x-ref: https://vercel.slack.com/archives/C02HY34AKME/p1682667306929829
=> fix(es/compat): Fix `is_setter` in `parameters` pass

crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/src/text_writer/basic_impl.rs, crates/swc_ecma_transforms_compat/src/es2015/generator.rs
x-ref: https://vercel.slack.com/archives/C03EWR7LGEN/p1683787972706329?thread_ts=1683738076.476839&cid=C03EWR7LGEN
=> chore(es): Enable tracing spans for release builds

crates/swc_common/src/syntax_pos.rs
Simple update to missing flags.
=> refactor(swc_common): bytecheck arcstring

crates/swc_ecma_minifier/src/compress/optimize/inline.rs, crates/swc_ecma_minifier/src/program_data.rs, crates/swc_ecma_minifier/tests/benches-full/vue.js, crates/swc_ecma_minifier/tests/fixture/issues/7412/input.js, crates/swc_ecma_minifier/tests/fixture/issues/7412/output.js, crates/swc_ecma_minifier/tests/fixture/issues/firebase-firestore/1/output.js, crates/swc_ecma_minifier/tests/fixture/next/react-pdf-renderer/output.js
=> fix(es/minifier): Prevent inlining vars assigned outside current function scope

crates/swc_plugin_runner/src/plugin_module_bytes.rs
Seems Turbopack's Vc requires some attributes to wrap into, attempt to support it.
=> refactor(plugin/runner): Add attributes to the module bytes

crates/swc_ecma_parser/src/parser/class_and_fn.rs, crates/swc_ecma_parser/tests/js/jssue-7428/1/input.js, crates/swc_ecma_parser/tests/js/jssue-7428/1/input.js.json, crates/swc_ecma_parser/tests/typescript/jssue-7428/1/input.ts, crates/swc_ecma_parser/tests/typescript/jssue-7428/1/input.ts.json, crates/swc_ecma_parser/tests/typescript/jssue-7428/2/input.tsx, crates/swc_ecma_parser/tests/typescript/jssue-7428/2/input.tsx.json
=> fix(es/parser): Reset class context

crates/swc/tests/fixture/issues-2xxx/2531/2/output/index.js, crates/swc/tests/tsc-references/objectRestForOf.1.normal.js, crates/swc/tests/tsc-references/objectRestForOf.2.minified.js, crates/swc_ecma_transforms_compat/src/es2018/object_rest_spread.rs, crates/swc_ecma_transforms_compat/tests/es2018_object_rest_spread.rs
=> fix(es/compat): Fix variable scoping of object rest pass.

crates/swc_ecma_parser/src/parser/jsx.rs, crates/swc_ecma_parser/tests/typescript/issue-7224/1/input.tsx, crates/swc_ecma_parser/tests/typescript/issue-7224/1/input.tsx.json
=> fix(es/parser): Fix parsing of tsx with type ann in cond expr

crates/swc_ecma_utils/Cargo.toml, crates/swc_visit/src/lib.rs, crates/swc_visit_macros/src/lib.rs
x-ref: https://vercel.slack.com/archives/C03EWR7LGEN/p1684898884673379
- https://github.com/web-infra-dev/rspack/issues/3058.
=> refactor(visit): Reduce expanded LOCs

crates/swc_ecma_codegen/src/typescript.rs, crates/swc_ecma_codegen/tests/fixture/typescript/ts_import_equals/input.js, crates/swc_ecma_codegen/tests/fixture/typescript/ts_import_equals/output.js, crates/swc_ecma_codegen/tests/fixture/typescript/ts_import_equals/output.min.js, crates/swc_ecma_transforms_base/tests/ts-resolver/internalModules/codeGeneration/importStatements/output.ts
Emits a semi-colon for TsImportEqualsDecls.
=> fix(es/codegen): emit semi for `TsImportEqualsDecl`

.github/workflows/publish-node.yml
- Close https://github.com/swc-project/swc/issues/7725
=> ci: fix permissions

crates/swc_ecma_parser/src/error.rs, crates/swc_ecma_parser/src/parser/mod.rs, crates/swc_ecma_parser/src/parser/stmt.rs, crates/swc_ecma_parser/tests/test262-error-references/fail/1aefe47e20eb91fa.module.js.swc-stderr, crates/swc_ecma_parser/tests/typescript-errors/custom/top-level-await-jsc-target/input.ts.swc-stderr
Description:
Original: #7766 
I accidentally force pushed after bump comment, so create this new pr
BREAKING CHANGE:
Related issue (if exists):
=> refactor(es/parser): Do not validate top-level await with target 

crates/swc/tests/fixture/issues-7xxx/7678/input/.swcrc, crates/swc/tests/fixture/issues-7xxx/7678/input/1.js, crates/swc/tests/fixture/issues-7xxx/7678/output/1.js, crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_minifier/tests/fixture/issues/7678/input.js, crates/swc_ecma_minifier/tests/fixture/issues/7678/output.js
=> fix(es/codegen): Don't strip necessary escape characters

crates/swc/tests/fixture/issues-7xxx/7789/input/1.js, crates/swc/tests/fixture/issues-7xxx/7789/output/1.js, crates/swc/tests/fixture/issues-7xxx/7898/input/1.js, crates/swc/tests/fixture/issues-7xxx/7898/output/1.js, crates/swc_ecma_transforms_compat/src/es2020/optional_chaining.rs, crates/swc_ecma_transforms_compat/tests/optional-chaining-loose/issue-7559/output.js, crates/swc_ecma_transforms_compat/tests/optional-chaining/issue-7561/input.js, crates/swc_ecma_transforms_compat/tests/optional-chaining/issue-7561/output.js
- Reverts #7610.
- Closes #7798.
- Closes #7789.
- Opens #7561.
=> fix(es/compat): Revert #7610 

crates/swc_ecma_parser/src/lexer/mod.rs
=> refactor(es/parser): Remove needless `unsafe`

crates/swc/src/config/mod.rs, crates/swc/src/lib.rs, crates/swc/tests/fixture/issues-7xxx/7863/1/input/.swcrc, crates/swc/tests/fixture/issues-7xxx/7863/1/input/1.js, crates/swc/tests/fixture/issues-7xxx/7863/1/output/1.js, crates/swc_ecma_loader/src/resolvers/node.rs, crates/swc_ecma_loader/src/resolvers/tsc.rs, node-swc/__tests__/transform/issue_4730_test.mjs
=> fix(es/module): Don't resolve as `node_modules` from `TscResolver`

.github/ISSUE_TEMPLATE/bug_report.yml, packages/swc-info/.gitignore, packages/swc-info/.npmignore, packages/swc-info/README.md, packages/swc-info/bin/swc-info.js, packages/swc-info/lib/index.ts, packages/swc-info/package.json, packages/swc-info/tsconfig.json, packages/types/package.json, packages/yarn.lock
=> feat(swc-info): Add a CLI to help issue reporting

crates/swc_ecma_dep_graph/src/lib.rs
It was not analyzing children of a dynamic imports.
=> fix(es/dep-graph): Analyze import type children

crates/swc_ecma_minifier/src/compress/optimize/dead_code.rs, crates/swc_ecma_minifier/src/program_data.rs, crates/swc_ecma_minifier/tests/fixture/issues/7847/input.js, crates/swc_ecma_minifier/tests/fixture/issues/7847/output.js
=> fix(es/minifier): Report `is_fn_local` even if var is hoisted

Cargo.lock, crates/swc_ecma_codegen/Cargo.toml
=> chore(deps): Update `memchr`

bindings/Cargo.lock, bindings/binding_core_node/Cargo.toml, bindings/binding_core_wasm/Cargo.toml, bindings/swc_cli/Cargo.toml, package.json
=> chore: Publish `v1.3.84` with `swc_core` `v0.83.5`

crates/swc/tests/fixture/issues-7xxx/7956/input/1/.swcrc, crates/swc/tests/fixture/issues-7xxx/7956/input/1/index.js, crates/swc/tests/fixture/issues-7xxx/7956/output/1/index.js, crates/swc_ecma_transforms_compat/src/es2021/logical_assignments.rs
=> fix(es/compat): Handle `PrivateName` in `logical_assignments`

.cargo/config.toml
Should resolve https://github.com/swc-project/swc/issues/1351#issuecomment-1283551742
CI passed: https://github.com/swc-project/swc/actions/runs/6217017170
=> build(bindings/node): Link msvc runtime statically

crates/swc_ecma_lints/src/lib.rs, crates/swc_ecma_lints/src/rules/no_alert.rs, crates/swc_ecma_lints/src/rules/radix.rs
=> refactor(es/lint): Remove usage of `box_patterns`

packages/types/index.ts, packages/types/package.json
=> fix(bindings/type): Update types of `jsc.experimental`

crates/swc/src/config/mod.rs, crates/swc/tests/fixture/issues-7xxx/7908/input/3/.swcrc, crates/swc/tests/fixture/issues-7xxx/7908/input/3/1.js, crates/swc/tests/fixture/issues-7xxx/7908/output/3/1.js
=> feat(es/config): Accept `jsc.experimental.keepImportAssertions`

crates/swc/src/config/mod.rs
=> fix(es): Enable resolver if `jsc.baseUrl` is specified

crates/swc_ecma_transforms_typescript/src/strip_import_export.rs, crates/swc_ecma_transforms_typescript/tests/fixture/issue-8007/1/input.ts, crates/swc_ecma_transforms_typescript/tests/fixture/issue-8007/1/output.js, crates/swc_ecma_transforms_typescript/tests/fixture/issue-8007/2/input.ts, crates/swc_ecma_transforms_typescript/tests/fixture/issue-8007/2/output.js
=> fix(es/typescript): Handle `DeclareCollect` correctly

.github/invalid-link.md, .github/workflows/nissuer.yml
Add https://github.com/marketplace/actions/nissuer to the repository.
=> chore: Configure `nissuer`

.github/workflows/nissuer.yml
See https://github.com/swc-project/swc/issues/8059#issuecomment-1744960852
=> chore: Update nissuer.yml

crates/swc_ecma_transforms_base/src/helpers/_interop_require_wildcard.js, packages/helpers/esm/_interop_require_wildcard.js
- https://github.com/babel/babel/issues/15995
=> fix(es/helpers): Override mistake in `_interop_require_wildcard`

Cargo.lock, xtask/Cargo.toml, xtask/src/git/mod.rs, xtask/src/git/reduce/core_ver.rs, xtask/src/git/reduce/mod.rs, xtask/src/git/reduce/swc_core.rs, xtask/src/main.rs, xtask/src/util/mod.rs
This command should be useful for reducing regressions to commits.
=> chore(xtask): Add `git reduce core-ver`

.github/workflows/CI.yml, xtask/src/bench.rs
- Add `--features` to `xtask bench`
=> chore(xtask): Add `--features` to `xtask bench`

crates/swc/tests/fixture/issues-8xxx/8096/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8096/input/1.js, crates/swc/tests/fixture/issues-8xxx/8096/output/1.js, crates/swc_ecma_parser/src/parser/expr/ops.rs, crates/swc_ecma_parser/src/parser/stmt.rs
=> fix(es/parser): Fix parsing of `await using`

node-swc/src/Visitor.ts, node-swc/src/index.ts
=> chore(bindings): Add `@deprecated` to JS plugins

crates/swc_ecma_parser/tests/tsc/thisTypeInAccessors.json, crates/swc_ecma_parser/tests/tsc/thisTypeInAccessorsNegative.json, crates/swc_ecma_transforms_module/src/lib.rs, crates/swc_ecma_transforms_module/src/path.rs
=> chore(es/module): Remove `serde(deny_unknown_fields)`

crates/swc/tests/fixture/issues-8xxx/8193/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8193/input/1.js, crates/swc/tests/fixture/issues-8xxx/8193/output/1.js, crates/swc_ecma_preset_env/data/@babel/compat-data/data/plugin-bugfixes.json, crates/swc_ecma_preset_env/data/@babel/compat-data/data/plugins.json, crates/swc_ecma_preset_env/data/core-js-compat/data.json, crates/swc_ecma_preset_env/data/core-js-compat/entries.json, crates/swc_ecma_preset_env/data/core-js-compat/modules-by-versions.json, crates/swc_ecma_transforms_compat/tests/__swc_snapshots__/tests/es2015_destructuring.rs/destructuring_for_in.js, crates/swc_ecma_transforms_compat/tests/__swc_snapshots__/tests/es2015_destructuring.rs/destructuring_for_in_loose.js, crates/swc_ecma_transforms_compat/tests/__swc_snapshots__/tests/es2015_destructuring.rs/destructuring_for_of.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-8148/1/output.js, package.json, yarn.lock
=> feat(es/preset-env): Update compat data

crates/swc/tests/fixture/issues-8xxx/8204/input/index.ts, crates/swc/tests/fixture/issues-8xxx/8204/output/index.ts, crates/swc/tests/tsc-references/enums.1.normal.js, crates/swc/tests/tsc-references/enums.2.minified.js, crates/swc/tests/tsc-references/exportsAndImports1-amd.1.normal.js, crates/swc/tests/tsc-references/exportsAndImports1-amd.2.minified.js, crates/swc/tests/tsc-references/exportsAndImports1-es6.1.normal.js, crates/swc/tests/tsc-references/exportsAndImports1-es6.2.minified.js, crates/swc/tests/tsc-references/exportsAndImports1.1.normal.js, crates/swc/tests/tsc-references/exportsAndImports1.2.minified.js, crates/swc_ecma_transforms_typescript/src/transform.rs
=> fix(es/typescript): Preserve const enum for named export

crates/swc/tests/fixture/issues-8xxx/8210/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8210/input/1.js, crates/swc/tests/fixture/issues-8xxx/8210/output/1.js, crates/swc_ecma_transforms_react/src/jsx_src/mod.rs
=> fix(es/react): Visit children nodes in `jsx-src` pass

crates/swc_ecma_codegen/src/lib.rs
Improves on #8252 `fn replace_close_inline_script` by removing unsafe and improving performance by ~35%
=> perf(es/minifier): Improve format.inline_script

crates/swc_ecma_codegen/src/typescript.rs, crates/swc_ecma_codegen/tests/fixture/typescript/ts_type_query/input.js, crates/swc_ecma_codegen/tests/fixture/typescript/ts_type_query/output.js, crates/swc_ecma_codegen/tests/fixture/typescript/ts_type_query/output.min.js
**Description:** Fixes the emit for TsImportType and TsTypeQuery
I'm back to working on my declaration file bundler with swc. A decent prototype is almost done.
=> fix(es/codegen): Fix codegen of type args of an import type and a type query

crates/swc_ecma_minifier/src/compress/optimize/iife.rs, crates/swc_ecma_minifier/src/compress/optimize/inline.rs, crates/swc_ecma_minifier/src/compress/optimize/util.rs, crates/swc_ecma_minifier/tests/benches-full/echarts.js, crates/swc_ecma_minifier/tests/fixture/issues/emotion/react/1/output.js, crates/swc_ecma_minifier/tests/fixture/issues/firebase-firestore/1/output.js, crates/swc_ecma_minifier/tests/fixture/next/outstatic/1/output.js, crates/swc_ecma_minifier/tests/fixture/next/react-pdf-renderer/output.js, crates/swc_ecma_minifier/tests/projects/output/react-dom-17.0.2.js
=> fix(es/minifier): Apply new `SyntaxContext` to inlined `Arrow` correctly

bindings/Cargo.lock, bindings/binding_core_wasm/Cargo.toml, bindings/binding_minifier_wasm/Cargo.toml, bindings/swc_cli/Cargo.toml, package.json, packages/minifier/package.json, packages/minifier/scripts/npm/darwin-arm64/package.json, packages/minifier/scripts/npm/darwin-x64/package.json, packages/minifier/scripts/npm/linux-arm64-gnu/package.json, packages/minifier/scripts/npm/linux-arm64-musl/package.json, packages/minifier/scripts/npm/linux-x64-gnu/package.json, packages/minifier/scripts/npm/linux-x64-musl/package.json, packages/minifier/scripts/npm/win32-arm64-msvc/package.json, packages/minifier/scripts/npm/win32-ia32-msvc/package.json, packages/minifier/scripts/npm/win32-x64-msvc/package.json, scripts/npm/darwin-arm64/package.json, scripts/npm/darwin-x64/package.json, scripts/npm/linux-arm64-gnu/package.json, scripts/npm/linux-arm64-musl/package.json, scripts/npm/linux-x64-gnu/package.json, scripts/npm/linux-x64-musl/package.json, scripts/npm/win32-arm64-msvc/package.json, scripts/npm/win32-ia32-msvc/package.json, scripts/npm/win32-x64-msvc/package.json
=> chore: Publish `v1.3.100` with `swc_core` `v0.86.84`

Cargo.lock, crates/swc/Cargo.toml, crates/swc/src/lib.rs, crates/swc_bundler/Cargo.toml, crates/swc_compiler_base/Cargo.toml, crates/swc_compiler_base/src/lib.rs, crates/swc_ecma_codegen/Cargo.toml, crates/swc_ecma_codegen/tests/sourcemap.rs, crates/swc_ecma_transforms_react/Cargo.toml, crates/swc_ecma_transforms_react/src/refresh/hook.rs, crates/swc_ecma_transforms_testing/Cargo.toml, crates/swc_ecma_transforms_testing/src/lib.rs
Updates `base64` dependency to `v0.21`, removing dependency on `base64` `v0.13` and reducing dependency duplication.
**BREAKING CHANGE:** None
=> chore(deps): Update `base64` to `v0.21`

crates/swc_css_modules/src/imports.rs, crates/swc_css_modules/src/lib.rs
=> refactor(css/modules): Support stable rust

crates/swc_html_minifier/src/lib.rs
=> refactor(html/minifier): Support stable rust

crates/swc_css_codegen/src/lib.rs
=> refactor(css/codegen): Support stable rust

crates/swc_css_minifier/src/compressor/alpha_value.rs, crates/swc_css_minifier/src/compressor/angle.rs, crates/swc_css_minifier/src/compressor/calc_sum.rs, crates/swc_css_minifier/src/compressor/color.rs, crates/swc_css_minifier/src/compressor/container.rs, crates/swc_css_minifier/src/compressor/declaration.rs, crates/swc_css_minifier/src/compressor/easing_function.rs, crates/swc_css_minifier/src/compressor/length.rs, crates/swc_css_minifier/src/compressor/media.rs, crates/swc_css_minifier/src/compressor/mod.rs, crates/swc_css_minifier/src/compressor/rules.rs, crates/swc_css_minifier/src/compressor/transform_function.rs, crates/swc_css_minifier/src/lib.rs
=> refactor(css/minifier): Support stable rust

crates/swc_css_compat/src/compiler/color_hex_alpha.rs, crates/swc_css_compat/src/compiler/color_hwb.rs, crates/swc_css_compat/src/compiler/color_space_separated_parameters.rs, crates/swc_css_compat/src/compiler/custom_media.rs, crates/swc_css_compat/src/compiler/legacy_rgb_and_hsl.rs, crates/swc_css_compat/src/compiler/media_query_ranges.rs, crates/swc_css_compat/src/lib.rs
=> refactor(css/compat): Support stable rust

crates/swc_css_prefixer/src/lib.rs, crates/swc_css_prefixer/src/prefixer.rs
=> refactor(css/prefixer): Support stable rust

crates/swc/tests/fixture/issues-8xxx/8397/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8397/input/index.js, crates/swc/tests/fixture/issues-8xxx/8397/output/index.js, crates/swc_ecma_compat_es2015/src/generator.rs
=> fix(es/compat): Preserve spread in generator

crates/swc/tests/fixture/issues-8xxx/8419/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8419/input/index.js, crates/swc/tests/fixture/issues-8xxx/8419/output/index.js, crates/swc/tests/vercel/loader-only/next-33291/1-automatic/output/index.js, crates/swc/tests/vercel/loader-only/next-33291/2-classic/output/index.js, crates/swc_ecma_compat_common/src/macros.rs
=> fix(es/compat): Preserve comment for arrow body

crates/swc/tests/fixture/issues-8xxx/8185/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8185/input/helper.js, crates/swc/tests/fixture/issues-8xxx/8185/input/input.js, crates/swc/tests/fixture/issues-8xxx/8185/output/helper.js, crates/swc/tests/fixture/issues-8xxx/8185/output/input.js, crates/swc_ecma_minifier/tests/fixture/issues/6628/output.js, crates/swc_ecma_minifier/tests/fixture/next/43052/output.js, crates/swc_ecma_minifier/tests/fixture/next/outstatic/1/output.js, crates/swc_ecma_minifier/tests/full/issues/7094/1/output.js, crates/swc_ecma_minifier/tests/full/issues/7094/2/output.js, crates/swc_ecma_minifier/tests/terser/compress/issue_976/eval_collapse_vars/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/issue_976/eval_mangle/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/issue_976/eval_unused/output.mangleOnly.js, crates/swc_ecma_transforms_base/src/rename/collector.rs
- Closes #8451.
- Closes #8185.
=> fix(es/renamer): Correctly check top level

crates/swc_ecma_compat_es2015/src/destructuring.rs, crates/swc_ecma_transforms_compat/tests/destructuring/pr-8470/input.js, crates/swc_ecma_transforms_compat/tests/destructuring/pr-8470/output.js
=> fix(es/compat): Set inserted var inside export class in destructing

packages/types/index.ts
Add type hint `"2021-12" | "2023-03` for `jsc.transform.decoratorVersion`.
#8467
=> fix(binding/types): Add type for `decoratorVersion`

crates/swc_ecma_minifier/tests/compress.rs, crates/swc_ecma_minifier/tests/terser/compress/blocks/issue_1672_for/output.js, crates/swc_ecma_minifier/tests/terser/compress/blocks/issue_1672_if/output.js, crates/swc_ecma_minifier/tests/terser/compress/dead_code/dead_code_const_declaration/output.js, crates/swc_ecma_minifier/tests/terser/compress/harmony/shorthand_keywords/output.js, crates/swc_ecma_minifier/tests/terser_exec.rs
=> test(es/minifier): Enable non esm mode for tests

crates/swc_ecma_minifier/tests/mangle.rs, crates/swc_ecma_minifier/tests/terser/compress/arrow/async_identifiers/input.js, crates/swc_ecma_minifier/tests/terser/compress/arrow/async_identifiers/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/async/async_identifiers/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/async/async_shorthand_property/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/blocks/issue_1672_for/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/blocks/issue_1672_if/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/dead_code/dead_code_constant_boolean_should_warn_more/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/functions/hoist_funs/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/harmony/shorthand_keywords/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/yield/yield_as_identifier_in_function_in_generator/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser_exec.rs
=> test(es/minifier): Enable script mode for `terser_exec` and `mangle`

crates/swc_ecma_codegen/src/decl.rs, crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/tests/fixture/typescript/class/input.js, crates/swc_ecma_codegen/tests/fixture/typescript/class/output.js, crates/swc_ecma_codegen/tests/fixture/typescript/class/output.min.js, crates/swc_ecma_codegen/tests/fixture/typescript/class_method/input.js, crates/swc_ecma_codegen/tests/fixture/typescript/class_method/output.js, crates/swc_ecma_codegen/tests/fixture/typescript/class_method/output.min.js, crates/swc_ecma_codegen/tests/fixture/typescript/class_prop/input.js, crates/swc_ecma_codegen/tests/fixture/typescript/class_prop/output.js, crates/swc_ecma_codegen/tests/fixture/typescript/class_prop/output.min.js, crates/swc_ecma_transforms_base/tests/ts-resolver/stc/1/output.ts, crates/swc_ecma_transforms_typescript/src/strip_type.rs
**Description:** Emits the abstract keyword on classes and their methods and properties.
=> fix(es/codegen): Emit abstract keyword

ARCHITECTURE.md
`string_cache` has already been replace by #8126 
=> doc: Replace `string_cache` with `hstr` in `ARCHITECTURE.md`

packages/types/index.ts
Add `bugfixes` field to EnvConfig
=> fix(binding/types): Add `bugfixes` field to EnvConfig

crates/swc/Cargo.toml, crates/swc_cli_impl/Cargo.toml, crates/swc_compiler_base/Cargo.toml, crates/swc_ecma_codegen/Cargo.toml, crates/swc_ecma_transforms/Cargo.toml, crates/swc_ecma_transforms_testing/Cargo.toml
=> chore(common): Update `sourcemap`

crates/swc_ecma_transforms_testing/src/lib.rs
=> test(es/testing): Ensure that `test_inline!` is working properly

bindings/binding_core_wasm/src/types.rs, bindings/binding_minifier_wasm/src/types.rs, packages/types/index.ts
=> fix(binding/types): Update typings for `options.envs` to match implementation

crates/swc_common/src/plugin/mod.rs
=> fix(es/plugin): Fix schema version issue

Cargo.lock, bindings/Cargo.lock, bindings/Cargo.toml, bindings/binding_core_node/Cargo.toml, bindings/binding_core_node/src/transform.rs, crates/binding_macros/Cargo.toml, crates/swc_plugin_runner/Cargo.toml, crates/swc_plugin_runner/src/wasix_runtime.rs, crates/swc_plugin_runner/tests/css_rkyv.rs, crates/swc_plugin_runner/tests/ecma_integration.rs, crates/swc_plugin_runner/tests/ecma_rkyv.rs, crates/swc_plugin_runner/tests/issues.rs, deny.toml, node-swc/e2e/plugins/plugins.compat.test.js
This is required to update rustc.
=> build(plugin): Update `wasmer` to `v4.2.5`

crates/swc/tests/fixture/issues-8xxx/8640/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8640/input/index.tsx, crates/swc/tests/fixture/issues-8xxx/8640/output/index.tsx, crates/swc_ecma_utils/src/lib.rs
=> fix(es/typescript): Handle exported JSX members

crates/swc_ecma_minifier/src/compress/optimize/props.rs, crates/swc_ecma_minifier/tests/fixture/issues/8643/input.js, crates/swc_ecma_minifier/tests/fixture/issues/8643/output.js, crates/swc_ecma_minifier/tests/terser/compress/hoist_props/contains_this_2/output.js, crates/swc_ecma_minifier/tests/terser/compress/hoist_props/new_this/output.js
=> fix(es/minifier): Abort property hoister on `this` usage

crates/swc/tests/fixture/issues-8xxx/8701/1/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8701/1/input/src/app.controller.spec.ts, crates/swc/tests/fixture/issues-8xxx/8701/1/input/src/app.controller.ts, crates/swc/tests/fixture/issues-8xxx/8701/1/input/src/app.module.ts, crates/swc/tests/fixture/issues-8xxx/8701/1/input/src/app.service.ts, crates/swc/tests/fixture/issues-8xxx/8701/1/input/src/main.ts, crates/swc/tests/fixture/issues-8xxx/8701/1/output/src/app.controller.spec.ts, crates/swc/tests/fixture/issues-8xxx/8701/1/output/src/app.controller.ts, crates/swc/tests/fixture/issues-8xxx/8701/1/output/src/app.module.ts, crates/swc/tests/fixture/issues-8xxx/8701/1/output/src/app.service.ts, crates/swc/tests/fixture/issues-8xxx/8701/1/output/src/main.ts, crates/swc/tests/projects.rs, crates/swc/tests/projects/issue-8701/src/app.controller.spec.ts, crates/swc/tests/projects/issue-8701/src/app.controller.ts, crates/swc/tests/projects/issue-8701/src/app.module.ts, crates/swc/tests/projects/issue-8701/src/app.service.ts, crates/swc/tests/projects/issue-8701/src/main.ts, crates/swc_ecma_transforms_module/src/path.rs, crates/swc_ecma_transforms_module/tests/path_node.rs, crates/swc_ecma_transforms_module/tests/paths/pack-1682/1/output/index.ts, node-swc/__tests__/transform/issue_7806_test.mjs, node-swc/__tests__/transform/issue_8701_test.mjs, node-swc/tests/issue-8701/src/app.controller.spec.ts, node-swc/tests/issue-8701/src/app.controller.ts, node-swc/tests/issue-8701/src/app.module.ts, node-swc/tests/issue-8701/src/app.service.ts, node-swc/tests/issue-8701/src/main.ts
=> fix(es/module): Fix relativeness check for `jsc.paths`

crates/swc_ecma_loader/src/resolvers/node.rs, crates/swc_ecma_loader/src/resolvers/tsc.rs, crates/swc_ecma_transforms_module/src/path.rs
- x-ref (vercel slack): https://vercel.slack.com/archives/C03S8ED1DKM/p1710371667695459?thread_ts=1710362018.271789&cid=C03S8ED1DKM
=> fix(es/module): Fix regression of resolving relative modules

crates/swc/tests/fixture/issues-7xxx/7829/1/input/.swcrc, crates/swc/tests/fixture/issues-7xxx/7829/1/output/1.js, crates/swc/tests/fixture/issues-7xxx/7829/2/input/.swcrc, crates/swc/tests/fixture/issues-7xxx/7898/1/output/index.ts, crates/swc/tests/fixture/issues-8xxx/8782/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8782/input/libs/common/main.js, crates/swc/tests/fixture/issues-8xxx/8782/input/libs/math/index.js, crates/swc/tests/fixture/issues-8xxx/8782/input/libs/math/src/foo.js, crates/swc/tests/fixture/issues-8xxx/8782/input/projects/api/main.ts, crates/swc/tests/fixture/issues-8xxx/8782/input/projects/api/models.js, crates/swc/tests/fixture/issues-8xxx/8782/output/libs/common/main.js, crates/swc/tests/fixture/issues-8xxx/8782/output/libs/math/index.js, crates/swc/tests/fixture/issues-8xxx/8782/output/libs/math/src/foo.js, crates/swc/tests/fixture/issues-8xxx/8782/output/projects/api/main.ts, crates/swc/tests/fixture/issues-8xxx/8782/output/projects/api/models.js, crates/swc_ecma_loader/src/resolvers/tsc.rs, crates/swc_ecma_loader/tests/tsc_resolver.rs, crates/swc_ecma_transforms_module/tests/path_node.rs, crates/swc_ecma_transforms_module/tests/paths/issue-7417/output/index.ts, node-swc/__tests__/transform/issue_4730_test.mjs
=> fix(es/module): Fix `jsc.paths` with `resolveFully`

crates/swc_ecma_parser/src/error.rs
Tweak the msg, the option `jsc.parser.usingDecl` has been replaced by `jsc.parser.explicitResourceManagement`
=> fix(es/parser): Tweak msg of `SyntaxError::UsingDeclNotEnabled`

crates/swc_plugin_runner/src/transform_executor.rs
=> feat(plugin/runner): Improve error message for Wasm plugin crashes

Cargo.lock, crates/swc_atoms/Cargo.toml
- https://github.com/dudykr/ddbase/pull/27
- https://github.com/dudykr/ddbase/pull/29
=> perf(atoms): Update `hstr`

crates/swc_common/src/source_map.rs
=> fix(common): Fix source index for `inputSourceMap`

.github/workflows/CI.yml
it can help to find some `ub` in swc
=> chore(ci): Add miri tests

crates/swc_common/src/plugin/mod.rs
=> doc(swc_core): Resolve build issue with `--all-features` flag

crates/swc/tests/tsc-references/switchStatements.2.minified.js, crates/swc_ecma_minifier/tests/fixture/issues/8813/input.js, crates/swc_ecma_minifier/tests/fixture/issues/8813/output.js, crates/swc_ecma_minifier/tests/terser/compress/functions/issue_2620_4/output.js, crates/swc_ecma_transforms_optimization/src/simplify/branch/mod.rs, crates/swc_ecma_transforms_optimization/src/simplify/branch/tests.rs
=> fix(es/minifier): Handle switch cases

crates/swc_ecma_transforms_base/src/helpers/mod.rs
=> fix(es/helpers): Fix resolving of `usingCtx` helper

crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/tests/fixture/issues/8841/input.js, crates/swc_ecma_minifier/tests/fixture/issues/8841/output.js
=> fix(es/minifier): Abort seq inline on recursive usage

crates/swc/tests/fixture/issues-8xxx/8920/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8920/input/1.js, crates/swc/tests/fixture/issues-8xxx/8920/output/1.js, crates/swc_ecma_transforms_base/src/fixer.rs
=> fix(es/fixer): Wrap class expressions in callee

crates/swc_ecma_minifier/src/compress/optimize/dead_code.rs, crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/tests/exec.rs, crates/swc_ecma_minifier/tests/fixture/issues/8924/output.js
=> fix(es/minifier): Abort seq inliner on `**`

crates/swc_ecma_transforms_typescript/examples/ts_to_js.rs
=> doc(es/typescript): Fix example

crates/swc_ecma_minifier/src/compress/util/mod.rs, crates/swc_ecma_minifier/tests/fixture/issues/9007/input.js, crates/swc_ecma_minifier/tests/fixture/issues/9007/output.js
=> fix(es/minifier): Fix comparison of `-0.0`

crates/swc_compiler_base/src/lib.rs
=> fix(es): Make `output` field optional

crates/swc_ecma_codegen/src/typescript.rs, crates/swc_ecma_codegen/tests/fixture/typescript/mapped_type/input.ts, crates/swc_ecma_codegen/tests/fixture/typescript/mapped_type/output.ts, crates/swc_ecma_transforms_base/tests/ts-resolver/ts_mapped_type_as_clauses_01/output.ts
Fixes the emit of mapped types.
=> fix(es/codegen): Emit named type in mapped types

.github/workflows/CI.yml
=> chore: Reduce cache of CI

crates/swc_ecma_parser/src/lexer/mod.rs
We don't need to allocate at all in the fast path.
=> perf(es/lexer): Add a fast-path to template literal lexer

Cargo.lock, Cargo.toml, crates/swc_typescript/Cargo.toml, crates/swc_typescript/src/lib.rs
This crate will be used for TypeScript Isolated Declaration support
=> chore: Add a crate `swc_typescript`

Cargo.lock, crates/swc_core/Cargo.toml, crates/swc_core/src/lib.rs
=> feat(swc_core): Reexport `swc_typescript`

.github/workflows/CI.yml, crates/swc_ecma_parser/src/parser/util.rs
We can skip some checks for error recovery.
=> perf(es/parser): Remove unnecessary check

crates/swc/tests/fixture/issues-9xxx/9110/input/.swcrc, crates/swc/tests/fixture/issues-9xxx/9110/input/1.js, crates/swc/tests/fixture/issues-9xxx/9110/output/1.js, crates/swc_ecma_compat_es2020/src/nullish_coalescing.rs
=> fix(es/compat): Do not reuse span

.github/workflows/CI.yml, .github/workflows/publish-core.yml
=> fix(ci): Restore disabled CI checks

.github/workflows/CI.yml
=> chore(ci): Use `taiki-e/install-action` if possible

crates/swc_plugin_proxy/src/comments/plugin_comments_proxy.rs
- Closes https://github.com/swc-project/swc/issues/9169
=> fix(es/testing): Fix `PluginCommentProxy`

crates/swc_ecma_transforms_module/src/lib.rs
- Closes https://github.com/swc-project/swc/issues/9182
=> fix(es/modules): Fix lint issue

crates/swc_ecma_quote_macros/src/ast/class.rs, crates/swc_ecma_quote_macros/src/ast/decl.rs, crates/swc_ecma_quote_macros/src/ast/expr.rs, crates/swc_ecma_quote_macros/src/ast/mod.rs, crates/swc_ecma_quote_macros/src/ast/module_decl.rs, crates/swc_ecma_quote_macros/src/ast/prop.rs, crates/swc_ecma_quote_macros/src/ast/stmt.rs
=> fix(es/quote): Fix macro

bindings/binding_typescript_wasm/scripts/patch.mjs
> [!NOTE]  
> We should remove this if https://github.com/rustwasm/wasm-bindgen/pull/4015 get mereged.
=> fix(es/typescript): Workaround `wasm-bindgen`

.github/workflows/publish.yml, Cargo.lock
- Closes https://github.com/swc-project/swc/issues/9304
=> chore(ci): Bump crates before publishing

.changeset/cold-chefs-cheat.md, crates/swc/tests/fixture/issues-9xxx/9287/input/.swcrc, crates/swc/tests/fixture/issues-9xxx/9287/input/index.js, crates/swc/tests/fixture/issues-9xxx/9287/output/index.js, crates/swc_ecma_ast/src/lib.rs
=> fix(es/ast): Accept any case of EsVersion during deserialization

bindings/binding_typescript_wasm/README.md
- https://github.com/nodejs/amaro/issues/10
=> doc(bindings/wasm): Document supported TypeScript version

.changeset/lovely-ducks-visit.md, crates/swc_ecma_utils/src/lib.rs
- Closes https://github.com/swc-project/swc/issues/9335
=> fix(es/decorators): Fix TypeScript syntax assertion

CONTRIBUTING.md
=> doc(contributing): Add warning for `test --all`

.changeset/wicked-pandas-lick.md, crates/swc_ecma_minifier/src/compress/optimize/unused.rs, crates/swc_ecma_minifier/tests/fixture/issues/8643/output.js, crates/swc_ecma_minifier/tests/fixture/issues/9148/input.js, crates/swc_ecma_minifier/tests/fixture/issues/9148/output.js, crates/swc_ecma_minifier/tests/terser/compress/hoist_props/contains_this_1/output.js
- Closes https://github.com/swc-project/swc/issues/9148
=> fix(es/minifier): Fix detection of `this`

bindings/binding_typescript_wasm/README.md
=> chore: Typo in typescript_wasm README

.changeset/flat-geese-care.md, crates/swc/tests/fixture/issues-9xxx/9350/input/.swcrc, crates/swc/tests/fixture/issues-9xxx/9350/input/index.ts, crates/swc/tests/fixture/issues-9xxx/9350/input/test.ts, crates/swc/tests/fixture/issues-9xxx/9350/output/index.ts, crates/swc/tests/fixture/issues-9xxx/9350/output/test.ts, crates/swc_ecma_transforms_proposal/src/decorators/legacy/mod.rs
=> fix(es/decorators): Use correct class name reference

.changeset/four-onions-wash.md, crates/swc_ecma_transforms/tests/fixture/legacy-metadata/issues/9435/input.ts, crates/swc_ecma_transforms/tests/fixture/legacy-metadata/issues/9435/output.ts, crates/swc_ecma_transforms_proposal/src/decorators/legacy/metadata.rs
- Closes https://github.com/swc-project/swc/issues/9435
=> fix(es/decorators): Fix metadata for accessors

bindings/binding_minifier_wasm/src/types.rs
- Closes https://github.com/swc-project/swc/issues/9442
=> fix(bindings/wasm): Fix typing

.changeset/smooth-pets-beam.md, crates/swc_ecma_minifier/src/compress/optimize/unused.rs, crates/swc_ecma_minifier/tests/fixture/issues/9459/input.js, crates/swc_ecma_minifier/tests/fixture/issues/9459/output.js
- Closes https://github.com/swc-project/swc/issues/9459
- Closes https://github.com/swc-project/swc/issues/9460
- Closes https://github.com/swc-project/swc/pull/9465
=> feat(es/minifier): Drop more patterns with `PURE` marker

.changeset/silver-taxis-do.md, crates/swc_ecma_transforms_typescript/src/strip_import_export.rs, crates/swc_ecma_transforms_typescript/tests/fixture/issue-9486/input.ts, crates/swc_ecma_transforms_typescript/tests/fixture/issue-9486/output.js
=> fix(es/typescript): Correctly handle deep import chains

.changeset/rare-queens-change.md, crates/swc_ecma_transforms_typescript/src/transform.rs, crates/swc_ecma_transforms_typescript/src/utils.rs, crates/swc_ecma_utils/src/lib.rs
=> refactor(es/utils): Unify `prepend_stmts`

.changeset/sour-pumpkins-rescue.md, crates/swc_ecma_minifier/tests/exec.rs, crates/swc_ecma_usage_analyzer/src/analyzer/mod.rs
- Closes https://github.com/swc-project/swc/issues/9499
=> fix(es/minifier): Track if a var is used with `in`

.changeset/fresh-zoos-act.md, crates/swc/tests/fixture/issues-9xxx/9531/input/.swcrc, crates/swc/tests/fixture/issues-9xxx/9531/input/index.ts, crates/swc/tests/fixture/issues-9xxx/9531/output/index.ts, crates/swc/tests/tsc-references/constEnum4.1.normal.js, crates/swc/tests/tsc-references/constEnum4.2.minified.js, crates/swc_ecma_transforms_typescript/src/transform.rs, crates/swc_ecma_transforms_typescript/src/utils.rs, crates/swc_ecma_transforms_typescript/tests/strip_correctness.rs
- Closes https://github.com/swc-project/swc/issues/9531
=> fix(es/typescript): Handle enum in single statement

.changeset/serious-ducks-suffer.md, crates/swc/src/builder.rs, crates/swc/src/config/mod.rs, crates/swc/src/lib.rs, crates/swc/tests/ts-isolated-declaration/rewrite-import-specifier/input/.swcrc, crates/swc/tests/ts-isolated-declaration/rewrite-import-specifier/input/index.ts, crates/swc/tests/ts-isolated-declaration/rewrite-import-specifier/input/src/example.ts, crates/swc/tests/ts-isolated-declaration/rewrite-import-specifier/output/index.d.ts, crates/swc/tests/ts-isolated-declaration/rewrite-import-specifier/output/index.ts, crates/swc/tests/ts-isolated-declaration/rewrite-import-specifier/output/src/example.d.ts, crates/swc/tests/ts-isolated-declaration/rewrite-import-specifier/output/src/example.ts, crates/swc_ecma_transforms/tests/decorators.rs, crates/swc_ecma_transforms/tests/es2015_function_name.rs, crates/swc_ecma_transforms_module/src/amd.rs, crates/swc_ecma_transforms_module/src/common_js.rs, crates/swc_ecma_transforms_module/src/path.rs, crates/swc_ecma_transforms_module/src/rewriter.rs, crates/swc_ecma_transforms_module/src/system_js.rs, crates/swc_ecma_transforms_module/src/umd.rs, crates/swc_ecma_transforms_module/tests/amd.rs, crates/swc_ecma_transforms_module/tests/common_js.rs, crates/swc_ecma_transforms_module/tests/path_node.rs, crates/swc_ecma_transforms_module/tests/system_js.rs, crates/swc_ecma_transforms_module/tests/umd.rs, crates/swc_ecma_transforms_optimization/tests/simplify.rs
Use `Arc<dyn ImportResolver>` to reduce cost
- Closes https://github.com/swc-project/swc/issues/9548
=> fix(es/module): Rewrite import specifier in type declaration

.changeset/wicked-windows-occur.md, crates/swc_ecma_lints/src/rules/duplicate_exports.rs, crates/swc_ecma_lints/tests/pass/issue-9632/1/input.ts
=> fix(es/lints): Correct the false positive error of TS2309

.changeset/good-lions-design.md, crates/swc_ecma_minifier/src/compress/optimize/if_return.rs, crates/swc_ecma_minifier/tests/fixture/issues/9628/input.js, crates/swc_ecma_minifier/tests/fixture/issues/9628/output.js
=> fix(es/minifier): Only merge last if return

crates/swc/src/config/mod.rs, packages/types/index.ts
- Closes https://github.com/swc-project/swc/issues/9132
=> feat(es): Introduce `runPluginFirst` for Wasm plugins

.changeset/fixesrenamer_check_preserved_in_normal_renaming_mode.md, .changeset/sixty-ladybugs-help.md, crates/swc/tests/projects.rs, crates/swc/tests/projects/issue-9663/.swcrc, crates/swc/tests/projects/issue-9663/input.js, crates/swc_ecma_transforms_base/src/rename/analyzer/scope.rs, crates/swc_ecma_transforms_base/src/rename/mod.rs
**Description:** check `preserved` in normal renaming mode
fix #9663
=> fix(es/renamer): Check `preserved` in normal renaming mode

.changeset/fair-maps-move.md, crates/swc_typescript/src/fast_dts/mod.rs, crates/swc_typescript/tests/fast_dts_deno.rs
closes https://github.com/swc-project/swc/issues/9656
=> fix(typescript): Check whether the method is abstract when checking `is_overload`

.changeset/fifty-ears-press.md, crates/swc/tests/fixture/issues-9xxx/9688/input/.swcrc, crates/swc/tests/fixture/issues-9xxx/9688/input/index.js, crates/swc/tests/fixture/issues-9xxx/9688/output/index.js, crates/swc_ecma_parser/src/parser/stmt.rs
=> fix(es/parser): Parse `await using()` call

.changeset/three-clocks-punch.md, crates/swc_ecma_ast/src/lib.rs, packages/types/index.ts, packages/types/package.json, tools/generate-code/src/main.rs
=> feat(es): Add `es2023` and `es2024` to `EsVersion`

crates/swc_ecma_transforms_base/src/rename/ops.rs
=> perf(es/renamer): Modify parallel renaming threshold

docs/adr/00001-support-transformation-plugin-native.md
fix typo
**BREAKING CHANGE:** None
=> chore: Typo

.changeset/foo.md, crates/swc_ecma_codegen/src/util.rs
- Closes https://github.com/swc-project/swc/issues/9719
=> fix(es/codegen): Fix `ends_with_alpha_num`

.changeset/many-cats-clap.md, Cargo.lock, Cargo.toml, crates/swc_plugin_runner/Cargo.toml
=> feat(plugin): Update `wasmer` to `v5`

packages/core/binding.js
The bunding.js code is not formatted correctly, resulting in a lack of smooth and natural reading
=> chore(bindings/node): Format `binding.js`

.changeset/dirty-ways-remain.md, crates/swc_ecma_minifier/src/compress/pure/drop_console.rs, crates/swc_ecma_minifier/tests/fixture/issues/9757/config.json, crates/swc_ecma_minifier/tests/fixture/issues/9757/input.js, crates/swc_ecma_minifier/tests/fixture/issues/9757/output.js
- Closes https://github.com/swc-project/swc/issues/9757
=> fix(es/minifier): Drop `console` in optional chainings

.changeset/curvy-icons-drum.md, crates/swc_estree_compat/src/lib.rs, crates/swc_estree_compat/src/swcify/expr.rs, crates/swc_estree_compat/src/swcify/typescript.rs
- Closes https://github.com/swc-project/swc/issues/9770
=> refactor(estree/compat): Do not use nightly features

packages/types/index.ts
=> doc(types): fix broken links

.changeset/blue-rules-eat.md, crates/swc_typescript/examples/isolated_declarations.rs, crates/swc_typescript/src/fast_dts/class.rs, crates/swc_typescript/tests/fixture/issues/9817.snap, crates/swc_typescript/tests/fixture/issues/9817.tsx, crates/swc_typescript/tests/typescript.rs
fixes https://github.com/swc-project/swc/issues/9817
=> fix(typescript): Fix wrong check for super class

.github/swc-ecosystem-ci/tests/vite-plugin-swc-transform.ts
Adding [vite-plugin-swc-transform](https://github.com/ziir/vite-plugin-swc-transform) to the ecosystem CI.
=> chore(ci): Add `vite-plugin-swc-transform` to ecosystem-ci

.changeset/great-owls-think.md, crates/swc/src/config/mod.rs, crates/swc_ecma_lints/benches/all.rs, crates/swc_ecma_lints/src/rules/const_assign.rs, crates/swc_ecma_lints/src/rules/duplicate_bindings.rs, crates/swc_ecma_lints/src/rules/duplicate_exports.rs, crates/swc_ecma_lints/src/rules/mod.rs, crates/swc_ecma_lints/src/rules/no_dupe_args.rs
The ES lints are causing some performance problems for turbopack.
- Follow-up of https://github.com/swc-project/swc/pull/9833
=> perf(es/lints): Make ES lints faster

.changeset/cool-beans-check.md, .changeset/red-coats-melt.md, Cargo.lock, crates/swc_ecma_minifier/Cargo.toml, crates/swc_ecma_minifier/src/compress/pure/ctx.rs, crates/swc_ecma_minifier/src/compress/pure/mod.rs, crates/swc_ecma_transforms_base/Cargo.toml, crates/swc_ecma_transforms_base/src/perf.rs, crates/swc_ecma_transforms_optimization/src/inline_globals.rs, crates/swc_ecma_transforms_optimization/src/simplify/branch/mod.rs, crates/swc_ecma_transforms_optimization/src/simplify/dce/mod.rs, crates/swc_ecma_transforms_optimization/src/simplify/expr/mod.rs
```
es/minifier/libs/es/minifier/libs/rspack
time:   [916.51 ms 918.15 ms 920.06 ms]
change: [-2.9454% -2.6510% -2.3679%] (p = 0.00 < 0.05)
```
=> perf(es/minifier): Replace `rayon` with `chili`

.github/workflows/CI.yml, Cargo.lock, crates/swc_ecma_utils/src/parallel.rs, crates/swc_parallel/Cargo.toml, crates/swc_parallel/src/items.rs, crates/swc_parallel/src/lib.rs, crates/swc_parallel/tests/simulate.rs
- Diff range: https://github.com/swc-project/swc/compare/v1.10.4...v1.10.6
- https://github.com/swc-project/swc/issues/9855
=> test(parallel): Add test to debug segfault on windows x64

.changeset/new-pants-agree.md, .github/workflows/CI.yml, Cargo.lock, Cargo.toml, crates/swc_plugin_runner/Cargo.toml
=> build: Update `wasmer` to `v5.0.5-rc1`

.github/workflows/bench.yml, scripts/bench/build-all-crates.sh, scripts/cargo/list-features.sh
This PR enables cargo feature `concurrent` for codspeed benchmark done by CI machine for crates that have a such feature.
=> perf: Enable `concurrent` in codspeed bench

crates/swc_ecma_minifier/examples/minify-all.rs
I'll create a public repository that contains the inputs for the minifier using public next.js apps and some libraries
=> refactor(es/minifier): Add a way to profile minifier for real-world inputs

crates/swc_ecma_minifier/examples/minify-all.rs
=> refactor(es/minifier): Use `chili` for `minify-all` example

crates/swc_ecma_minifier/examples/minify-all.rs, crates/swc_ecma_minifier/src/util/base54.rs
I modified it to minify 10 times so I can profile it.
=> refactor(es/minifier): Make `minify-all` profilable

crates/swc_ecma_minifier/examples/minify-all.rs
I need this information to know if an optimization worths the cost
=> feat(es/minifier): Print total size from `minify-all` example

.changeset/tall-apples-cross.md, crates/swc_ecma_minifier/src/compress/pure/mod.rs, crates/swc_ecma_minifier/src/compress/pure/numbers.rs, crates/swc_ecma_minifier/tests/benches-full/d3.js, crates/swc_ecma_minifier/tests/benches-full/jquery.js, crates/swc_ecma_minifier/tests/benches-full/victory.js, crates/swc_ecma_minifier/tests/fixture/next/react-pdf-renderer/output.js, crates/swc_ecma_minifier/tests/fixture/next/styled-components/1/output.js, crates/swc_ecma_minifier/tests/projects/output/angular-1.2.5.js
=> feat(es/minifier): Turn `1 * v` into `+v`

.changeset/curly-geese-learn.md, crates/swc_ecma_usage_analyzer/src/alias/ctx.rs, crates/swc_ecma_usage_analyzer/src/alias/mod.rs
We don't need to split those two visitors.
=> perf(es/minifier): Merge binding analyzer into infection analyzer

.changeset/popular-spiders-bake.md, bindings/binding_typescript_wasm/__tests__/__snapshots__/transform.js.snap, bindings/binding_typescript_wasm/__tests__/transform.js, crates/swc_fast_ts_strip/src/lib.rs, crates/swc_fast_ts_strip/tests/errors/issue-9977.swc-stderr, crates/swc_fast_ts_strip/tests/errors/issue-9977.ts, crates/swc_fast_ts_strip/tests/errors/modules.swc-stderr, crates/swc_fast_ts_strip/tests/errors/modules.ts, crates/swc_fast_ts_strip/tests/errors/namespaces.swc-stderr, crates/swc_fast_ts_strip/tests/errors/namespaces.ts, crates/swc_fast_ts_strip/tests/fixture/issue-9977.js, crates/swc_fast_ts_strip/tests/fixture/issue-9977.swc-stderr, crates/swc_fast_ts_strip/tests/fixture/issue-9977.transform.js, crates/swc_fast_ts_strip/tests/fixture/issue-9977.ts
=> feat(ts/fast-strip): Support type-only/uninstantiated namespaces

.changeset/strange-eggs-jump.md, crates/swc_typescript/src/fast_dts/class.rs, crates/swc_typescript/src/fast_dts/visitors/type_usage.rs, crates/swc_typescript/tests/fixture/issues/10034.snap, crates/swc_typescript/tests/fixture/issues/10034.ts, crates/swc_typescript/tests/fixture/private-accessibility.snap, crates/swc_typescript/tests/fixture/private-accessibility.ts
Fixes https://github.com/swc-project/swc/issues/10034
=> fix(typescript): Remove the usages of private members

crates/hstr/src/dynamic.rs, crates/hstr/src/lib.rs, crates/hstr/src/tests.rs
=> test(hstr): Add tests

crates/swc_ecma_minifier/examples/minify-all.rs, crates/swc_ecma_minifier/scripts/next/add-test.sh
=> chore(es/minifier): Make `minify-all` example ignore parsing errors

crates/swc_common/src/eq.rs, crates/swc_common/src/pos.rs, crates/swc_common/src/util/take.rs
It was not shown because the feature was not enabled by default.
=> fix(swc_common): Fix build with `swc_allocator/nightly`

.changeset/rich-beers-pay.md, Cargo.lock, crates/swc_malloc/Cargo.toml, crates/swc_malloc/src/lib.rs
Github Actions run: https://github.com/swc-project/swc/actions/runs/13560294213/job/37902319812
=> fix: Use `jemalloc` on platforms that `mimalloc` fails to build

crates/swc_ecma_fast_parser/src/lexer/identifier.rs
This PR adds a fast lookup table for keyword lexing.
=> perf(es/fast-lexer): Optimize lexing of keywords

.changeset/twelve-seals-join.md, crates/swc/tests/fixture/amaro-194/input/.swcrc, crates/swc/tests/fixture/amaro-194/input/index.ts, crates/swc/tests/fixture/amaro-194/output/index.ts, crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_parser/tests/typescript/amaro-194/input.ts, crates/swc_ecma_parser/tests/typescript/amaro-194/input.ts.json
- https://github.com/nodejs/amaro/issues/194
=> fix(es/parser): Rescan `<<` in new expression

bindings/Cargo.lock, bindings/binding_typescript_wasm/Cargo.toml, bindings/binding_typescript_wasm/__tests__/__snapshots__/transform.js.snap, bindings/binding_typescript_wasm/src/lib.rs
Throw an object from `@swc/wasm-typescript`.
- Closes https://github.com/swc-project/swc/issues/10150
=> feat(ts/fast-strip): Throw an object instead of string

Cargo.lock, crates/swc_ecma_fast_parser/Cargo.toml, crates/swc_ecma_fast_parser/src/lexer/cursor.rs, crates/swc_ecma_fast_parser/src/lexer/mod.rs
=> perf(es/fast-lexer): Use `memchr` for `skip_line_comments`

crates/swc_ecma_fast_parser/src/lexer/cursor.rs, crates/swc_ecma_fast_parser/src/lexer/identifier.rs, crates/swc_ecma_fast_parser/src/lexer/jsx.rs, crates/swc_ecma_fast_parser/src/lexer/number.rs, crates/swc_ecma_fast_parser/src/lexer/operators.rs, crates/swc_ecma_fast_parser/src/lexer/regex.rs, crates/swc_ecma_fast_parser/src/lexer/string.rs, crates/swc_ecma_fast_parser/src/lexer/template.rs
=> perf(es/fast-lexer): Remove bound checks

.changeset/brave-pugs-agree.md, crates/swc_ecma_minifier/src/compress/optimize/inline.rs, crates/swc_ecma_minifier/tests/fixture/issues/10178/input.js, crates/swc_ecma_minifier/tests/fixture/issues/10178/output.js, crates/swc_ecma_usage_analyzer/src/analyzer/mod.rs
=> fix(es/minifier): Check array inline for indexed with dynamic key

bindings/binding_typescript_wasm/__tests__/__snapshots__/transform.js.snap, bindings/binding_typescript_wasm/src/lib.rs
- Closes https://github.com/swc-project/swc/issues/10180
=> feat(ts/fast-strip): Throw js object instead of map

.AI.md, .cursorrules, crates/swc_ecma_fast_parser/.AI.md, crates/swc_ecma_minifier/.AI.md
Applies https://kdy1.dev/2025-3-12-prompt-context
=> chore: Improve AI prompt

crates/swc_ecma_minifier/src/compress/mod.rs, crates/swc_ecma_minifier/src/compress/optimize/mod.rs
We don't provide high `passes` these days
=> refactor(es/minifier): Remove code for infinite loop

crates/swc_ecma_minifier/examples/minify-all.rs
=> doc(es/minifier): Make `minifier` example utilize comments

.changeset/selfish-badgers-repair.md, crates/swc_ecma_minifier/benches/full.rs, crates/swc_ecma_minifier/tests/exec.rs, crates/swc_ecma_transforms_optimization/src/simplify/dce/mod.rs
I pinned the commit using the hash to make updating the inputs explicit.
=> test(es/minifier): Add a benchmark for real-world inputs

bindings/binding_core_wasm/src/types.rs
Fixes #10223
Broken in this commit: https://github.com/nicksrandall/swc/commit/e71b000392a01ecb5a35ec8f0faac9cd79ff2cd1
=> fix(es/types): Fix broken types

Cargo.lock, crates/swc_ecma_fast_parser/Cargo.toml, crates/swc_ecma_fast_parser/src/lexer/cursor.rs, crates/swc_ecma_fast_parser/src/lexer/identifier.rs, crates/swc_ecma_fast_parser/src/lexer/mod.rs, crates/swc_ecma_fast_parser/src/lexer/regex.rs, crates/swc_ecma_fast_parser/src/lexer/tests.rs
- Added support for Unicode characters in identifiers, allowing for a broader range of valid identifiers.
- Introduced methods to handle Unicode escape sequences and UTF-8 characters in identifiers.
- Updated the lexer to utilize these new methods, improving the parsing of identifiers that include non-ASCII characters.
- Added tests to verify the correct handling of identifiers with Unicode characters and escape sequences.
=> feat(fast_parser): enhance identifier handling with Unicode support

crates/swc_ecma_minifier/src/util/base54.rs
The bug was not detected because `chili` is far better for reusing current thread.
=> fix(es/minifier): Fix access to `GLOBALS` in char freq compute

.changeset/kind-kangaroos-return.md, crates/swc_common/src/syntax_pos.rs, crates/swc_ecma_ast/src/ident.rs
Add some documentations to some methods.
- Closes https://github.com/swc-project/swc/issues/10244
=> doc(es): Improve documentation

bindings/binding_typescript_wasm/__tests__/__snapshots__/transform.js.snap, bindings/binding_typescript_wasm/src/lib.rs
Note: This PR does not include a fix for the parser diagnostics.
- Closes https://github.com/swc-project/swc/issues/10188
=> feat(ts/fast-strip): Add start/end span information

.changeset/light-rabbits-repair.md, Cargo.lock, crates/swc_core/Cargo.toml
It would make selecting feature of `swc_parallel` easier.
=> feat(swc_core): Expose features of `swc_parallel`

.changeset/heavy-pears-divide.md, crates/swc/examples/hygiene_visualizer.rs, crates/swc_ecma_transforms_base/src/resolver/mod.rs, crates/swc_ecma_transforms_base/tests/resolver/issue-10331/input.js, crates/swc_ecma_transforms_base/tests/resolver/issue-10331/output.js
=> fix(es/resolver): Handle using declarations

crates/swc_ecma_parser/src/parser/stmt.rs
=> chore(es/parser): Remove useless check

.changeset/fair-ghosts-glow.md, crates/swc_typescript/src/fast_dts/types.rs, crates/swc_typescript/tests/fixture/symbol-properties.snap
=> fix(typescript/dts): Emit `readonly` for Object getter prop

crates/swc_ecma_utils/src/lib.rs
=> fix(es/utils): Fix `extract_var_ids`

.github/workflows/CI.yml, bindings/Cargo.lock, bindings/Cargo.toml
- https://github.com/nodejs/amaro/pull/241
=> chore(bindings): Use published versions of crates

.changeset/nice-grapes-mix.md, Cargo.lock, crates/swc_ecma_react_compiler/Cargo.toml, crates/swc_ecma_react_compiler/src/fast_check.rs
=> fix(react-compiler): Fix fast check

.changeset/silly-humans-design.md, crates/swc_common/src/input.rs
Let's examine whether there are any potential improvements.
=> perf(swc_common): Remove `char_indices` calls

.changeset/breezy-cherries-hear.md, crates/swc_ecma_minifier/src/js.rs
Fix `wrap_iife` typo (`warp_iife`) https://terser.org/docs/options/#format-options
N/A
=> fix(es/minifier): Fix typo in an option name

.changeset/clever-donkeys-protect.md, crates/swc_common/src/source_map.rs
Cursor removed my changes on the tab in the previous PR.
=> fix(swc_common): Fix skip condition for sourcemap, really

.changeset/dull-needles-behave.md, crates/swc_common/src/source_map.rs
=> fix(swc_common): Add `Files#is_in_file`

.changeset/soft-pots-roll.md, crates/swc_ecma_transforms_optimization/src/simplify/dce/mod.rs
=> fix(es/minifier): Fix top level detection of DCE

.changeset/seven-years-battle.md, crates/swc_ecma_parser/src/lexer/state.rs, crates/swc_ecma_parser/src/parser/input.rs, crates/swc_ecma_parser/src/parser/jsx/mod.rs, crates/swc_ecma_parser/tests/jsx/basic/issue-10635/input.js, crates/swc_ecma_parser/tests/jsx/basic/issue-10635/input.js.json, crates/swc_ecma_parser/tests/jsx/errors/issue-10635/index.js, crates/swc_ecma_parser/tests/jsx/errors/issue-10635/index.js.swc-stderr
=> fix(es/parser): Don't be greedy in the end of jsx open el

.changeset/clever-cows-camp.md, Cargo.lock, bindings/binding_typescript_wasm/Cargo.toml, bindings/binding_typescript_wasm/scripts/build.sh, bindings/binding_typescript_wasm/scripts/test.sh, crates/swc_fast_ts_strip/Cargo.toml, crates/swc_fast_ts_strip/src/lib.rs, crates/swc_fast_ts_strip/tests/fixture.rs
=> feat(ts/fast-strip): Support JSX under a feature flag

.changeset/proud-candles-hunt.md, crates/swc_ecma_minifier/src/compress/optimize/unused.rs, crates/swc_ecma_minifier/tests/exec.rs
- Closes https://github.com/swc-project/swc/issues/10435
=> fix(es/minifier): Fix condition for preserving properties

.changeset/sweet-glasses-sell.md, crates/swc_ecma_lexer/src/common/syntax.rs, crates/swc_ecma_parser/src/parser/stmt.rs, packages/types/index.ts
- Closes https://github.com/swc-project/swc/issues/10704
- Closes https://github.com/swc-project/swc/issues/10705
=> feat(es/parser): Enable import attributes unconditionally

.changeset/warm-lamps-prove.md, crates/swc_ecma_minifier/tests/fixture/issues/10720/input.js, crates/swc_ecma_minifier/tests/fixture/issues/10720/output.js, crates/swc_ecma_minifier/tests/fixture/next/wrap-contracts/output.js, crates/swc_ecma_minifier/tests/libs-size.snapshot.md, crates/swc_ecma_utils/src/lib.rs
`terminates()` of `swc_ecma_utils` was wrong.
- Closes https://github.com/swc-project/swc/issues/10720
=> fix(es/minifier): Fix termination detection 

.changeset/quick-snakes-warn.md, crates/swc/tests/fixture/issues-10xxx/10890/input/.swcrc, crates/swc/tests/fixture/issues-10xxx/10890/input/index.ts, crates/swc/tests/fixture/issues-10xxx/10890/output/index.ts, crates/swc_ecma_transforms_proposal/src/decorators/mod.rs
=> fix(es/decorators): Handle empty class members

Cargo.lock, crates/swc_ecma_compat_es2022/Cargo.toml, crates/swc_ecma_compiler/Cargo.toml, crates/swc_ecma_compiler/src/features.rs, crates/swc_ecma_compiler/src/lib.rs
I'll merge es2022 into compiler with a follow-up PR
=> feat(es/compiler): Improve structure

crates/swc_ecma_minifier/tests/fixture/issues/10918/config.json, crates/swc_ecma_minifier/tests/fixture/issues/10918/output.js
I notice that the test case in my previous PR #10923 (for issue #10918) is the same as PR #10898 (for issue #10885).
Issue #10918 was not caught because the `break` was removed by other minify options.
This PR is to update the minifier fixture/issue/10918 test case.
**Related issue (if exists):** #10918
=> test(es/minifier): update fixture/issue/10918 test case

crates/swc_ecma_minifier/src/compress/hoist_decls.rs, crates/swc_ecma_minifier/src/compress/optimize/arguments.rs, crates/swc_ecma_minifier/src/compress/optimize/if_return.rs, crates/swc_ecma_minifier/src/compress/optimize/iife.rs, crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/src/compress/optimize/unused.rs, crates/swc_ecma_minifier/src/compress/optimize/util.rs, crates/swc_ecma_minifier/src/compress/pure/dead_code.rs, crates/swc_ecma_minifier/src/compress/pure/mod.rs, crates/swc_ecma_minifier/src/compress/pure/switches.rs, crates/swc_ecma_minifier/src/compress/pure/vars.rs, crates/swc_ecma_minifier/src/compress/util/mod.rs, crates/swc_ecma_minifier/src/compress/util/tests.rs, crates/swc_ecma_minifier/src/debug.rs, crates/swc_ecma_minifier/src/metadata/mod.rs, crates/swc_ecma_minifier/src/pass/global_defs.rs, crates/swc_ecma_minifier/src/pass/mangle_names/mangler.rs, crates/swc_ecma_minifier/src/pass/mangle_names/preserver.rs, crates/swc_ecma_minifier/src/pass/mangle_props.rs, crates/swc_ecma_minifier/src/pass/merge_exports.rs, crates/swc_ecma_minifier/src/pass/postcompress.rs, crates/swc_ecma_minifier/src/util/mod.rs
- https://github.com/swc-project/swc/issues/10944
=> fix(es/minifier): Disallow types

crates/swc_ecma_minifier/src/compress/optimize/inline.rs, crates/swc_ecma_minifier/src/compress/optimize/unused.rs
=> fix(es/minifier): Fix debug feature

bindings/binding_core_wasm/src/types.rs, bindings/binding_minifier_wasm/src/types.rs, crates/swc_ecma_ast/src/jsx.rs, crates/swc_ecma_ast/src/lib.rs, crates/swc_ecma_codegen/src/jsx.rs, crates/swc_ecma_lexer/src/common/parser/jsx.rs, crates/swc_ecma_parser/src/parser/jsx/mod.rs, crates/swc_ecma_parser/tests/typescript/issue-10993/input.ts.json, crates/swc_ecma_quote_macros/src/ast/expr.rs, crates/swc_ecma_transforms_react/src/jsx/mod.rs, crates/swc_estree_compat/src/babelify/jsx.rs, crates/swc_estree_compat/src/swcify/expr.rs, crates/swc_plugin_backend_wasmer/src/lib.rs, packages/core/src/Visitor.ts, packages/types/index.ts
Cherry pick e39a909f960f3962c1293ecb52b2911b430ecf4d from https://github.com/swc-project/swc/pull/10739 because we are going to make a Wasm-breaking change anyway
=> refactor(es/ast): Cherry-pick #10763

crates/swc_plugin_backend_wasmtime/src/lib.rs
This writes the cache atomically and uses read instead of mmap to load cache, avoid wasmtime crashes caused by load from an incomplete cache.
- https://github.com/web-infra-dev/rspack/issues/11529
=> fix(plugin/runner): fix wasmtime backend cache corruption

.changeset/metal-cars-poke.md, crates/swc/tests/tsc-references/optionalChainingInParameterInitializer(target=es2015).2.minified.js, crates/swc/tests/tsc-references/optionalChainingInParameterInitializer.2(target=es2015).2.minified.js, crates/swc_ecma_minifier/src/compress/optimize/iife.rs, crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/tests/fixture/issues/11082/input.js, crates/swc_ecma_minifier/tests/fixture/issues/11082/output.js
=> fix(es/minifier): Check in param before add ident

.changeset/gorgeous-masks-enjoy.md, crates/swc_ecma_lexer/src/common/parser/typescript.rs, crates/swc_ecma_parser/tests/typescript/issue-11124/input.ts, crates/swc_ecma_parser/tests/typescript/issue-11124/input.ts.json, crates/swc_ts_fast_strip/tests/fixture/issue-11124.js, crates/swc_ts_fast_strip/tests/fixture/issue-11124.transform.js, crates/swc_ts_fast_strip/tests/fixture/issue-11124.ts
=> fix(es/parser): Parse `(void)` correctly as arrow function return type

.changeset/sour-mugs-learn.md, crates/swc_ecma_transforms_react/src/jsx/mod.rs, crates/swc_ecma_transforms_typescript/src/transform.rs, crates/swc_ts_fast_strip/src/lib.rs
- Will fix .. https://github.com/denoland/deno/issues/30858
=> fix(es/transforms): Check errors::HANDLER.is_set() before failing
