swc-project/swc

crates/swc_ecma_transforms_typescript/src/strip.rs
It looks like `Strip.uninitialized_vars` is not used. Remove it?
=> refactor(es/typescript): Remove unused code

crates/swc_ecma_minifier/src/metadata/mod.rs, crates/swc_ecma_minifier/src/metadata/tests.rs
We might need to pass a giant pure function list to the SWC minifier as esbuild did [here](https://github.com/evanw/esbuild/blob/5fe21253ee75fb4c5ea395a0877b2a5ab51c3575/internal/config/globals.go).
The current implementation could slow the minifier.
=> perf(es/minifier): check whether a function is pure with O(1) cost

node-swc/src/binding.js
(Previously, this was enclosed in a try-catch and did not manifest itself as a clear error, but was problematic in the situation described in the issue below.)
<br>
If `process.platform === 'darwin' && (process.arch !== 'x64' && process.arch !== 'arm64')`,
then Error "Unsupported architecture on macOS: (process.arch)" will be thrown.
Previously, **however**, the Error "Failed to load native binding" would have been thrown because `@swc/core-darwin-arm64` does not exist. In this point of view, Probably I can argue that this changes make error easy-to-understand.
<br>
- ref #6901
=> fix(swc/core): Stop doing require unnecessary packages (`@swc/core-darwin-universal`).

bindings/swc_cli/src/commands/plugin.rs
SWC plugin interface is not allowed when binary in .zip archive. (pnp environment)
Therefore, in order to easily support the yarn pnp environment, it is set to be installed as unplug by default.
- https://github.com/blitz-js/next-superjson-plugin/pull/61
=> chore(cli): Enable `preferUnplugged` by default for the plugins

crates/swc_ecma_transforms_typescript/src/strip.rs, crates/swc_ecma_transforms_typescript/tests/fixture/next-45561/1/input.tsx, crates/swc_ecma_transforms_typescript/tests/fixture/next-45561/1/output.js, crates/swc_ecma_transforms_typescript/tests/fixture/next-45561/2/input.tsx, crates/swc_ecma_transforms_typescript/tests/fixture/next-45561/2/output.js, crates/swc_ecma_transforms_typescript/tests/fixture/next-45561/input.tsx
- https://github.com/vercel/next.js/issues/45561.
=> fix(es/typescript): Ignore jsx element names

crates/swc_ecma_minifier/src/compress/optimize/conditionals.rs, crates/swc_ecma_minifier/tests/exec.rs
- Closes https://github.com/swc-project/swc/issues/6903.
=> fix(es/minifier): Don't break ternary with assignment in test

crates/swc/tests/fixture/issues-5xxx/5165/1/input/.swcrc, crates/swc/tests/fixture/issues-5xxx/5165/1/input/src/import.ts, crates/swc/tests/fixture/issues-5xxx/5165/1/input/src/main.ts, crates/swc/tests/fixture/issues-5xxx/5165/1/output/src/import.ts, crates/swc/tests/fixture/issues-5xxx/5165/1/output/src/main.ts
- Closes https://github.com/swc-project/swc/issues/5165.
=> test(es/module): Add a test for `jsc.paths` on windows

crates/swc/tests/tsc-references/objectLiteralShorthandPropertiesES6.2.minified.js, crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/tests/TODO.txt, crates/swc_ecma_minifier/tests/exec.rs, crates/swc_ecma_minifier/tests/passing.txt
- Closes https://github.com/swc-project/swc/issues/6914.
=> fix(es/minifier): Don't skip shorthand properties from sequential inliner

Cargo.lock, crates/swc_core/Cargo.toml, crates/swc_css/Cargo.toml, crates/swc_css_codegen/Cargo.toml, crates/swc_css_compat/Cargo.toml, crates/swc_css_lints/Cargo.toml, crates/swc_css_minifier/Cargo.toml, crates/swc_css_modules/Cargo.toml, crates/swc_css_parser/Cargo.toml, crates/swc_css_prefixer/Cargo.toml, crates/swc_html_minifier/Cargo.toml, crates/swc_plugin_runner/Cargo.toml
Coming from internal report from @jridgewell 
```
swc_css_parser [v0.143.2](https://github.com/swc-project/swc/blob/29fee382249c9b91155d0d3c39d0df82bbd531c1/crates/swc_css_parser/Cargo.toml#L10) has a [js_word!(“first”)](https://github.com/swc-project/swc/blob/29fee382249c9b91155d0d3c39d0df82bbd531c1/crates/swc_css_parser/src/parser/at_rules/mod.rs#L2037)
The swc_css_parser v0.143.2 has a [hard dep](https://github.com/swc-project/swc/blob/29fee382249c9b91155d0d3c39d0df82bbd531c1/crates/swc_css_parser/Cargo.toml#L22) on swc_atoms v0.4.32
swc_atom [0.4.32](https://github.com/swc-project/swc/blob/1161360d5475e82e81aa1179557933d2748ae806/crates/swc_atoms/Cargo.toml#L10) does not include first in its [word list](https://github.com/swc-project/swc/blob/1161360d5475e82e81aa117955 …
```
=> build(cargo): bump up swc_css_*

crates/swc_ecma_transforms_typescript/src/strip.rs, crates/swc_ecma_transforms_typescript/tests/fixture/issue-6923/input.tsx, crates/swc_ecma_transforms_typescript/tests/fixture/issue-6923/output.js
- Closes https://github.com/swc-project/swc/issues/6923.
=> fix(es/typescript): Fix handling of non-uppercase JSX elements

bindings/swc_cli/src/commands/compile.rs
`@swc/cli` uses a different format for `--config`, so use a different name.
Experimental `--config` option has been renamed to `--config-json`.
**Related issue (if exists):** https://github.com/swc-project/swc/issues/4017#issuecomment-1425273484
=> fix(bindings/cli): Rename --config to --config-json

crates/swc/src/config/mod.rs, crates/swc/tests/fixture/issues-6xxx/6782/1/input/.swcrc, crates/swc/tests/fixture/issues-6xxx/6782/1/input/config/index.ts, crates/swc/tests/fixture/issues-6xxx/6782/1/input/src/index.ts, crates/swc/tests/fixture/issues-6xxx/6782/1/output/config/index.ts, crates/swc/tests/fixture/issues-6xxx/6782/1/output/src/index.ts, crates/swc_ecma_transforms_module/src/path.rs
- Reverts https://github.com/swc-project/swc/pull/6716.
- Closes https://github.com/swc-project/swc/issues/6782.
=> fix(es/module): Fix `jsc.paths` on Windows

Cargo.lock, bindings/binding_core_node/Cargo.toml, crates/swc_nodejs_common/Cargo.toml, crates/swc_nodejs_common/src/lib.rs
- Ref: https://github.com/vercel/turbo/pull/3772
=> chore(swc_nodejs_common): remove swc_node_base from swc_nodejs_common

crates/swc_ecma_transforms_react/src/jsx/mod.rs, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-6939/input.js, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-6939/options.json, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-6939/output.mjs, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-6939/output.stderr
- Closes https://github.com/swc-project/swc/issues/6939.
=> fix(es/react): Don't panic on `key` without a value

node-swc/src/index.ts
- Closes https://github.com/swc-project/swc/issues/6958.
=> fix(bindings/node): Treat `.cts` and `.mts` as input by default

crates/swc_atoms/words.txt, crates/swc_css_modules/src/lib.rs, crates/swc_css_modules/tests/fixture/modules/animation/source.compiled.css, crates/swc_css_modules/tests/fixture/modules/animation/source.css, crates/swc_css_modules/tests/fixture/modules/animation/source.transform.json
In the current implementation of `swc_css_modules`, any first identifier in `animation` properties are transformed as the local identifier.
Current behaviour:
```css
/* this */
.a {
animation: 3s ease animationName;
}
/* will be transformed like this: */
.__local__a {
animation: 3s __local__ease animationName;
}
```
Expected behaviour:
```css
/* this */
.a {
animation: 3s ease animationName;
}
/* should be transformed like this: */
.__local__a {
animation: 3s ease __local__animationName;
}
```
This pull request will fix this.
FYI: https://developer.mozilla.org/en-US/docs/Web/CSS/animation
=> fix: properly handle CSS animation on CSS Modules

crates/swc/tests/serde.rs, crates/swc_ecma_codegen/tests/sourcemap.rs, crates/swc_ecma_codegen/tests/test262.rs, crates/swc_ecma_dep_graph/src/lib.rs, crates/swc_ecma_parser/src/lexer/jsx.rs, crates/swc_ecma_parser/src/lexer/mod.rs, crates/swc_ecma_parser/src/lexer/number.rs, crates/swc_ecma_parser/src/lexer/state.rs, crates/swc_ecma_parser/src/lexer/util.rs, crates/swc_ecma_parser/src/lib.rs, crates/swc_ecma_parser/src/parser/mod.rs, crates/swc_ecma_parser/tests/errors.rs, crates/swc_ecma_parser/tests/js.rs, crates/swc_ecma_parser/tests/jsx.rs, crates/swc_ecma_parser/tests/span.rs, crates/swc_ecma_parser/tests/test262.rs, crates/swc_ecma_parser/tests/typescript.rs, crates/swc_ecma_quote_macros/src/ret_type.rs, crates/swc_ecma_transforms_base/src/tests.rs, crates/swc_ecma_transforms_base/tests/fixer_test262.rs, crates/swc_ecma_transforms_testing/src/lib.rs, crates/swc_ecma_transforms_typescript/tests/strip_correctness.rs
Currently, it uses `StringInput` as the input type, but I'll refactor it to use `String` or `Vec<u8>` directly to optimize it further.
- https://github.com/swc-project/swc/discussions/6991
=> refactor(es/parser): Make lexer not generic over `Input`

node-swc/src/Visitor.ts
`Visitor#visitBindingIdentifier()` currently doesn't go through type annotations, which makes customized visitor easy to overlook.
Changing the function type shouldn't break existing code because BindingIdentifier can be coerced to Identifier implicitly. Adding some specific typescript tests can better justify that, any suggestions about adding those?
n/a
=> fix: visitBindingIdentifier should go through type annotations

crates/swc_ecma_transforms_typescript/src/strip.rs, crates/swc_ecma_transforms_typescript/tests/fixture/issue-6953/1/input.ts, crates/swc_ecma_transforms_typescript/tests/fixture/issue-6953/1/output.js
- Closes https://github.com/swc-project/swc/issues/6953.
=> fix(es/typescript): Treat export default declarations as declarations

crates/swc_ecma_transforms_optimization/src/const_modules.rs, crates/swc_ecma_transforms_optimization/tests/const_modules.rs
=> fix(es/transforms): handle member obj in missing else branch

crates/swc_common/src/source_map.rs, crates/swc_common/src/syntax_pos.rs
Actually allocation is not required in this case.
=> feat(common): Add an API to create a `SourceFile` without allocation

Cargo.lock, crates/swc_atoms/Cargo.toml, crates/swc_common/Cargo.toml
Bump the "string-cache" crate to 0.8.5, which includes [this PR](https://github.com/servo/string-cache/commit/b473a4ad3be989166031f56976f7ce54ae79ac05).
Internally, it now locks on each individual bucket within the DYNAMIC_SET struct, rather than locking on the whole data structure.
Parallel performance should improve.
=> (perf) bump "string-cache" crate for per-bucket mutex

Cargo.lock, crates/swc_ecma_parser/Cargo.toml, crates/swc_ecma_parser/src/lexer/number.rs
=> perf(es/parser): Use Cow for `_` in numeric literals

Cargo.lock, crates/swc_ecma_quote/Cargo.toml, crates/swc_ecma_quote_macros/src/ctxt.rs
Fix errors from `cargo test -p swc_ecma_quote --doc` (part of `cargo test`).
I suspect this was broken by
- #5713
- #6797
although I wonder why this hasn’t been noticed—am I the first to try running `cargo test`?
=> Fix doctests for swc_ecma_quote

crates/swc_common/src/input.rs, crates/swc_ecma_parser/src/lexer/util.rs
=> perf(es/lexer): Use string searcher for lexing line comments

crates/swc/src/config/mod.rs, crates/swc/tests/fixture/issues-1xxx/1278/output/index.ts, crates/swc/tests/fixture/issues-2xxx/2011/no-minify/output/index.js, crates/swc/tests/fixture/issues-2xxx/2011/reduced/output/index.js, crates/swc/tests/fixture/issues-2xxx/2216/output/index.ts
=> fix(es/config): respect the value of assumptions

bindings/swc_cli/src/commands/compile.rs
Prevents the stdin handle from waiting in an infinite loop for the read stream to finish, when running in a process with a detached console on Windows. 
This is a [known issue](https://doc.rust-lang.org/std/io/fn.stdin.html#note-windows-portability-considerations) on Windows. To prevent this from happening, this change simply flips the order how inputs are parsed. Now, the files option is used first before using the stdin input as a fallback.
As a workaround in Bazel rules_swc, we forward the output of the null device to force the read stream to immediately finish on Windows. However, this workaround appears to cause a difference in argv quoting.
https://github.com/aspect-build/rules_swc/blob/e149dd5fc9e512d5b87b3d52a5aa8422c1a1a309/swc/private/swc.bzl#L194
Related 
- …
=> fix(cli): Windows stdin handle waits in an infinite loop

crates/testing_macros/src/fixture.rs
Clippy is complaining about the `test_path__to__fixture` name casing generated by `testing::fixture`.
=> Ignore non_snake_case generated test names

Cargo.lock, crates/swc_ecma_transforms_base/Cargo.toml, crates/swc_ecma_transforms_base/src/fixer.rs
Or when encountering nested paren expr with comments, comments would be lost. Found this problem when testing #7096 
=> mod(es/base): Move comments following the order of insertion in `fixer`

node-swc/src/spack.ts
`spack` config file provided from CLI may not be properly imported with `require()`. Without a leading '/', './', or '../' to indicate a file, the module must either be a core module or be loaded from a node_modules folder, but spack.config.js is a local file.
N/A
ISSUE #3345
=> fix(bindings/node): Fix loading of `spack.config.js`

crates/swc_ecma_ast/src/lit.rs, crates/swc_ecma_minifier/tests/fixture/issues/7111/input.js, crates/swc_ecma_minifier/tests/fixture/issues/7111/output.js, crates/swc_ecma_minifier/tests/fixture/next/wrap-contracts/output.js
- Closes https://github.com/swc-project/swc/issues/7111.
=> fix(es/ast): Fix `EqIgnoreSpan` impl of `Number`

crates/swc_ecma_visit/src/lib.rs, crates/swc_ecma_visit/tests/main.rs
Visitor used in AndThen or Repeat cannot invoke `fold_program`
=> fix(es/visit): Fix handling of `Program` of `AndThen`

crates/swc/tests/tsc-references/jsxJsxsCjsTransformKeyPropCustomImportPragma.1.normal.js, crates/swc/tests/tsc-references/jsxJsxsCjsTransformKeyPropCustomImportPragma.2.minified.js, crates/swc_ecma_transforms_react/src/jsx/mod.rs, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-6987/input.js, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-6987/options.json, crates/swc_ecma_transforms_react/tests/jsx/fixture/issue-6987/output.mjs
=> fix(react): honour `import_source` in new jsx

crates/ast_node/src/spanned.rs, crates/swc_ecma_ast/build.rs, crates/swc_ecma_ast/src/lib.rs, crates/swc_plugin_proxy/build.rs, crates/swc_plugin_proxy/src/lib.rs
=> refactor(es): Remove needless build scripts to reduce compile time

crates/swc_ecma_transforms_module/src/common_js.rs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-7180/input.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-7180/module.json, crates/swc_ecma_transforms_module/tests/fixture/common/issue-7180/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/issue-7180/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/issue-7180/output.umd.js
`cjs-module-lexer` detection is fragile. Redundant parentheses can cause detection failure.
Therefore, I replaced the sequence expression with a binary expression.
before:
```JavaScript 
0 && (__export(require("foo")), __export(require("bar")));
```
after this pull request
```JavaScript 
0 && __export(require("foo")) &&  __export(require("bar"));
```
- fix #7180
=> fix(es/modules): Hint nodejs for multiple `export *`

crates/swc_plugin_runner/src/cache.rs
This PR is minor improvement, non breaking changes to cache path for the plugin. In short, it tries to combine rustc version if available to expand. `option_env!` supposed to embed build time rustc version. It'd be ideal if we could match between plugin's as well, but I doubt if we could before actually load plugin.
=> feat(plugin_runner): improve cache path

crates/swc_ecma_parser/src/parser/stmt.rs, crates/swc_ecma_parser/tests/errors/jsx_in_js/input.js, crates/swc_ecma_parser/tests/errors/jsx_in_js/input.js.swc-stderr
This fixes an infinite loop in the parser when it encountered an invalid token. This was easiest to reproduce by trying to parse JSX as JS.
I'm new to the swc codebase and I couldn't find places which a have a similar logic. So I opted to break out of the loop instead of modifying the `bump!` macro. Let me know if that is not the proper way to do it. 
no
Fixes #7189
=> fix(es/parser): fix infinite loop on jsx in js

crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_parser/src/parser/typescript.rs, crates/swc_ecma_parser/tests/typescript-errors/variance-annotations/1/input.ts.swc-stderr, crates/swc_ecma_parser/tests/typescript/arrow-function/const-type-param/input.ts, crates/swc_ecma_parser/tests/typescript/arrow-function/const-type-param/input.ts.json, crates/swc_ecma_parser/tests/typescript/variance-annotations/1/input.ts.json, crates/swc_ecma_parser/tests/typescript/variance-annotations/with_jsx/input.tsx.json
Ensures code like the following gets parsed as a `const` type parameter:
```ts
export const fn = <const Data extends ReadonlyArray<unknown>>(payload: Data) => payload;
```
Also if a type parameter is `in` / `out` / `const` incorrectly, the AST should still reflect that while emitting a diagnostic.
=> fix(parser): parse `const` type parameters in arrow function expressions

crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/src/tests.rs
- https://github.com/swc-project/swc/issues/7240.
=> fix(es/codegen): Respect `ascii_only` for identifiers

crates/swc_ecma_transforms_compat/src/es3/reserved_word.rs
There is a similar case with exported `class`.
But I do not believe that `class` will be preserved in es3 phase.
- fix #7237
=> fix(es/compat): Handle export function in `reserved_word`

crates/swc/tests/tsc-references/privateNameStaticsAndStaticMethods.1.normal.js, crates/swc/tests/tsc-references/privateNamesAndMethods.1.normal.js, crates/swc/tests/tsc-references/privateNamesAndStaticMethods.1.normal.js, crates/swc_ecma_minifier/tests/mangle/issue-7261/input.js, crates/swc_ecma_minifier/tests/mangle/issue-7261/output.js, crates/swc_ecma_minifier/tests/terser/compress/properties/mangle_private_properties/output.js, crates/swc_ecma_minifier/tests/terser/compress/properties/mangle_private_properties/output.mangleOnly.js, crates/swc_ecma_transforms_base/src/rename/analyzer/mod.rs, crates/swc_ecma_transforms_base/src/rename/mod.rs
The probleam arises in L235 of swc_ecma_transforms_base/src/rename/mod.rs
```rs
unit!(visit_mut_fn_decl, FnDecl, true);
```
which calls `get_map` and evals to
```rs
node.visit_children_with(&mut v);
```
with `FnDecl` and `Analyzer` in L132. However in `Analyzer`, a visit to raw function was not overloaded, so function arguments and function body are considered different scope.
closes #7261
=> fix(es/renamer): Ensure that param and function body are in same scope

Cargo.lock, crates/swc_ecma_transforms_react/Cargo.toml, crates/swc_ecma_transforms_react/src/jsx/mod.rs, crates/swc_ecma_transforms_react/src/refresh/hook.rs
It's causing a performance problem in concurrent scenarios.
x-ref: https://linear.app/vercel/issue/WEB-921
x-ref: https://vercel.slack.com/archives/C02HY34AKME/p1681757237489689
=> perf(es/react): Don't use regex

crates/testing/src/output.rs
This makes sure that even if there's a windows path with `/` it still gets picked up
Example: `"C:/User/test/Code/project/src/f.js"` -> `"$DIR/src/f.js"`
=> fix path normalization on windows for testing diffs

node-swc/src/Visitor.ts, node-swc/src/types.ts
**Description:** This pull request support the new feature of typescript `satisfies`, it's been supported by swc, but not supported by the bindings and visitor yet. 
=> fix(bindings): Types and Visitor for TsSatisfiesExpression

crates/swc_ecma_codegen/src/typescript.rs, crates/swc_ecma_codegen/tests/fixture/typescript/module/input.js, crates/swc_ecma_codegen/tests/fixture/typescript/module/output.js, crates/swc_ecma_codegen/tests/fixture/typescript/module/output.min.js
This improves/fixes the emit of TsModuleDecl when it hasn't been transformed to JavaScript. I'm working on a tool that emits typescript code as-is in some scenarios.
=> fix(es/codegen): Fix codegen of `TsModuleDecl`

bindings/binding_core_wasm/src/types.rs, crates/swc_ecma_transforms_module/src/common_js.rs, crates/swc_ecma_transforms_module/src/util.rs, crates/swc_ecma_transforms_module/tests/fixture/common/export-interop-annotation/input.js, crates/swc_ecma_transforms_module/tests/fixture/common/export-interop-annotation/module.json, crates/swc_ecma_transforms_module/tests/fixture/common/export-interop-annotation/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/export-interop-annotation/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/export-interop-annotation/output.umd.js, node-swc/src/types.ts
=> feat(es/module): Add `export_interop_annotation` flag

crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/src/typescript.rs
The ECMA code generation implementation was not emitting type arguments for call expressions. This PR fixes that.
=> fix(es/codegen): Emit type arguments for call expressions

crates/swc_plugin_runner/src/cache.rs
Previously disabled cache (storing compiled module in memory) still doesn't work, so falling back to storing raw bytes and create new module each time. This is the same behavior to the wasm build's approach.
Also minor improved caching root to include more information. Previous rustc didn't seem to work unfortunately, so removed but instead using plugin_runner's version.
=> feat(plugin/runner): Improve caching

crates/swc_plugin_runner/src/cache.rs
I don't see how original change could affect ci in a negative way (theoretically, compile a module from IO / or in memory shouldn't be that different even in the worst case) but anyway, let's split changes to confirm. 
PR takes part of previous pr for fine grained cache path. _if this causes same regression_, that means accessing env is somehow excessively slow (which also shouldn't, but we'll see).
=> refactor(plugin_runner): refine cache location

crates/swc_plugin_runner/src/cache.rs
Finally we can enable this again. Locally tested against one of my plugin (swc-coverage-instrument) and it seems working, and shows noticeable performance boost when processing multiple files with same plugin in a single process.
=> feat(plugin/runner): Enable in-memory precompiled module cache

crates/swc_core/Cargo.toml
PR moves out mode-specific features (`plugin-mode`) so `common-plugin-transform` can be used in either plugin host or plugin transforms.
=> refactor(swc_core): Make `common_plugin_transform` agnostic to mode

crates/swc_core/src/lib.rs, crates/swc_core/src/plugin.rs
Following up https://github.com/swc-project/swc/pull/7422, `swc_core::plugin` itself is not exposed to `__plugin_transform_host` so still not able to access inner plugin proxy.
=> fix(core): correctly expose plugin with host

crates/swc_ecma_parser/src/parser/typescript.rs, crates/swc_ecma_parser/tests/typescript/issue-7186/1/input.ts, crates/swc_ecma_parser/tests/typescript/issue-7186/1/input.ts.json, crates/swc_ecma_parser/tests/typescript/issue-7186/2/input.tsx, crates/swc_ecma_parser/tests/typescript/issue-7186/2/input.tsx.json
=> fix(es/parser): Allow using `package` as a parameter name in TS interface

crates/swc/src/lib.rs, crates/swc/tests/source_map.rs, crates/swc/tests/srcmap/case-none-file/input.js
User's npm package is missing a .map file. If there is a compilation error, the user will not be able to compile the project.
babel :
https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/normalize-file.js#L63
no
=> fix: ignore input sourcemap error

crates/swc_ecma_transforms_module/src/system_js.rs, crates/swc_ecma_transforms_module/tests/system_js.rs
Fix  transpile the continuous assignment code like `d.a = d.b = d.c = d.d = ... = void 0;` to SystemJS may cause Infinite loop.
- Closes #7143.
=> fix(es/module): Fix handling of continuous assignments in `systemjs`

crates/swc/src/config/mod.rs
=> feat(es): Alias `format` as `output` for `minify()`

crates/swc/src/config/mod.rs, crates/swc_plugin_runner/src/cache.rs
**Description**
I tried using swc-loader in webpack, and found out that if I have multiple entries, and using WASM plugins, it increased build time significantly. That's because Webpack run swc-loader multiple times, and since swc-loader is async, and then invoke process_js multiple times at nearly the same time, while the first WASM module is being compiled but not finished, the second time process_js get invoked, it sees that the WASM is not compiled, so it begins compiling too.
Currently SWC does not read file system cache at all, and write new cache to FS every time.
As I'm very likely not understand the design of swc WASM cache that much, and cache is hard, so this fix needs carefully review from you team.
After the modification, my little app's build time has been from 12s to 7s …
=> fix(plugin/runner): Use fs cache properly

Cargo.lock, crates/swc_ecma_parser/Cargo.toml, crates/swc_ecma_parser/src/lexer/mod.rs, crates/swc_ecma_parser/src/lexer/number.rs
This PR replaces the current usage of lexical within the swc_ecma_parser crate with equivalent parsing of large numbers using BigInt.
**Description:** As discussed in https://github.com/swc-project/swc/issues/7752, lexical contains a number of soundness issues but doesn't appear to be actively supported. Given the relatively low integration surface it seems reasonable to replace the usage of lexical with another package to avoid this issue.
- Closes #7752
=> refactor(es/parser): Do not use `lexical`

crates/swc_ecma_parser/src/lexer/mod.rs
bump() has a safety invariant that there must be input in the buffer to read (See https://github.com/swc-project/swc/issues/7709).
This function as currently written calls `bump()` after calling `read_token_interpreter()`, which *may* have exhausted the buffer already in the specific case that it is handling a shebang. (The input string `#!/bin/js` with no newline is sufficient to cause UB here)
Fortunately, shebangs never reach this function, due to `read_shebang`! Hurray!
It's cleaner to not attempt to handle shebangs here when this code path will never be reached, and use a debug assertion to ensure that we're not dealing with shebangs.
=> refactor(es/parser): Don't attempt to handle shebangs in `read_token_number_sign`

crates/swc_common/src/lib.rs, crates/swc_ecma_ast/src/lib.rs
For crates using both `rkyv` and `swc`, where ast nodes from `swc_ecma_ast` are included in data that's serialized with `rkyv`, it's difficult to access the archived data from the archived ast nodes since the types are private.
More context in the issue.
- Closes #7810.
=> feat(es/ast): Expose `Archived` types

bindings/binding_core_wasm/Cargo.toml, crates/swc/Cargo.toml, crates/swc_common/Cargo.toml, crates/swc_common/src/collections.rs, crates/swc_common/src/lib.rs, crates/swc_core/Cargo.toml, crates/swc_core/tests/fixture/stub_wasm/Cargo.toml
This adds the ability to not include `ahash` with swc_common, which caused some issues for me compiling dprint-plugin-typescript to Wasm because of:
```
Compiling ahash v0.8.3
Compiling getrandom v0.2.10
error: the wasm*-unknown-unknown targets are not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support
--> C:\Users\david\.cargo\registry\src\index.crates.io-6f17d22bba15001f\getrandom-0.2.10\src\lib.rs:285:9
|
285 | /         compile_error!("the wasm*-unknown-unknown targets are not supported by \
286 | |                         default, you may need to enable the \"js\" feature. \
287 | |                         For more information see: \
288 | | …
```
=> refactor(common): Make `ahash` optional

crates/swc/tests/fixture/issues-7xxx/7240/output/index.js, crates/swc/tests/fixture/issues-7xxx/7805/input/.swcrc, crates/swc/tests/fixture/issues-7xxx/7805/input/1.js, crates/swc/tests/fixture/issues-7xxx/7805/output/1.js, crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/src/tests.rs
=> fix(es/codegen): Add quotes to property names when `ascii_only` is `true`

crates/swc/src/config/mod.rs, crates/swc/src/lib.rs, node-swc/__tests__/transform/experimental.mjs, package.json, packages/types/index.ts, packages/types/package.json, yarn.lock
I'm experimenting with a new API. If this option is enabled, all builtin transforms are disabled and only Wasm plugins are applied.
=> feat(es): Add an option to disable builtin transforms

crates/swc/src/config/mod.rs, crates/swc_ecma_parser/src/lib.rs, crates/swc_ecma_parser/src/parser/stmt.rs
=> fix(es/compat): Apply transforms for explicit resource management

crates/swc/tests/fixture/minify/comments/false-02/input/.swcrc, crates/swc/tests/fixture/minify/comments/false-02/input/index.js, crates/swc/tests/fixture/minify/comments/false-02/output/index.js, crates/swc_ecma_codegen/src/lib.rs
Looks like the bug I ran into had nothing to do with the changes in #7856, since it's reproducible without it. Looks like it might have only surfaced now because https://github.com/swc-project/swc/pull/7853 changed the default value of `jsc.minify.format.comments`? Added a minimal test case here with the expected result.
Here's the actual output:
```js
export var padding = '';
export function exec2({ commands }) {
return __awaiter(this, void 0, void 0, function*() {
for(let i2 = 0; i2 < commands.length; i2++){
let command = commands[i2];
yield // some-comment
function({ command }) {
command();
}({
command,
handleError
});
}
});
}
```
The comment ends up getting added after the yield, which makes the output invalid.
Going to see if I can figure out a fix tomorrow, but let …
=> fix(es/codegen): Fix placing of comments of yield arguments

crates/swc_ecma_transforms_macros/src/parallel.rs, crates/swc_ecma_transforms_optimization/src/inline_globals.rs, crates/swc_ecma_transforms_optimization/src/json_parse.rs
=> perf(es/transforms): Remove wrong parallelism

crates/swc_ecma_minifier/src/compress/optimize/inline.rs, crates/swc_ecma_minifier/src/compress/optimize/props.rs, crates/swc_ecma_minifier/src/compress/optimize/unused.rs, crates/swc_ecma_minifier/src/program_data.rs, crates/swc_ecma_usage_analyzer/src/analyzer/mod.rs, crates/swc_ecma_usage_analyzer/src/analyzer/storage.rs
`mutated` can be seen as a combination of `reassigned` and `has_property_mutation`, and `mutation_by_call_count` is simply useless.
=> refactor(es/minifier): Remove `mutated` and `mutation_by_call_count`

bindings/Cargo.lock, bindings/binding_core_node/Cargo.toml, bindings/binding_core_wasm/Cargo.toml, bindings/swc_cli/Cargo.toml, crates/swc/src/config/mod.rs, crates/swc/tests/fixture/issues-7xxx/7806/input/.swcrc, crates/swc/tests/fixture/issues-7xxx/7806/input/src/index.ts, crates/swc/tests/fixture/issues-7xxx/7806/input/src/utils/hello-world.utils.ts, crates/swc/tests/fixture/issues-7xxx/7806/output/src/index.ts, crates/swc/tests/fixture/issues-7xxx/7806/output/src/utils/hello-world.utils.ts, node-swc/__tests__/transform/issue_7806_test.mjs, node-swc/tests/swc-path-bug-1/.swcrc, node-swc/tests/swc-path-bug-1/src/index.ts, node-swc/tests/swc-path-bug-1/src/utils/hello-world.utils.ts, yarn.lock
=> fix(es/module): Don't create absolute paths for `jsc.paths` on Windows

crates/swc_ecma_minifier/tests/fixture/issues/7683/1/output.js, crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/issue_2506/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/functions/issue_2616/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/functions/issue_2620_3/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/functions/issue_2620_4/output.mangleOnly.js, crates/swc_ecma_minifier/tests/terser/compress/issue_597/NaN_and_Infinity_should_not_be_replaced_when_they_are_redefined/output.js, crates/swc_ecma_minifier/tests/terser/compress/issue_597/NaN_and_Infinity_should_not_be_replaced_when_they_are_redefined/output.mangleOnly.js, crates/swc_ecma_transforms_base/src/resolver/mod.rs, crates/swc_ecma_transforms_base/tests/resolver/issues/7685/input.js, crates/swc_ecma_transforms_base/tests/resolver/issues/7685/output.js, crates/swc_node_bundler/tests/pass/resolve-name-fix/output/entry.js
=> fix(es/resolver): Correctly resolve global value

crates/swc/tests/fixture/deno/paths/issue-2126/output/src/index.ts, crates/swc/tests/fixture/deno/paths/issue-2724/output/src/index.ts, crates/swc/tests/fixture/deno/paths/issue-2753/1/output/src/index.ts, crates/swc/tests/fixture/deno/paths/issue-2844/output/src/index.ts, crates/swc/tests/fixture/issues-6xxx/6782/1/output/src/index.ts, crates/swc/tests/fixture/issues-7xxx/7417/output/src/lib/foo.ts, crates/swc/tests/fixture/issues-7xxx/7829/1/output/1.js, crates/swc_ecma_transforms_module/src/path.rs, crates/swc_ecma_transforms_module/tests/fixture-manual/issue-4730/output/index.js, crates/swc_ecma_transforms_module/tests/paths/issue-7417/output/index.ts, node-swc/__tests__/transform/issue_4730_test.mjs
=> fix(es/module): Make `jsc.paths` fully resolve TypeScript files

crates/swc/tests/fixture/deno/paths/issue-2126/output/src/index.ts, crates/swc/tests/fixture/deno/paths/issue-2724/output/src/index.ts, crates/swc/tests/fixture/deno/paths/issue-2753/1/output/src/index.ts, crates/swc/tests/fixture/deno/paths/issue-2844/output/src/index.ts, crates/swc/tests/fixture/issues-6xxx/6782/1/output/src/index.ts, crates/swc/tests/fixture/issues-7xxx/7417/output/src/lib/foo.ts, crates/swc/tests/fixture/issues-7xxx/7829/1/output/1.js, crates/swc_ecma_transforms_module/src/path.rs, crates/swc_ecma_transforms_module/tests/fixture-manual/issue-4730/output/index.js, crates/swc_ecma_transforms_module/tests/paths/issue-7417/output/index.ts, node-swc/__tests__/transform/issue_4730_test.mjs
I'm reverting #7901 because it caused a regression in next.js CI. https://github.com/vercel/next.js/pull/54653
- Reverts #7901.
=> fix(es/module): Revert #7901

crates/swc_ecma_transforms_compat/src/es2015/generator.rs, crates/swc_ecma_transforms_compat/tests/es2015_generator.rs
=> fix(es/compat): Visit assign expr in generator

crates/swc/src/config/mod.rs, crates/swc/src/lib.rs, crates/swc/tests/fixture/issues-7xxx/7908/output/1/1.js, crates/swc_ecma_codegen/src/lib.rs
- Add `format.emitAssertForImportAttributes` to `minify()`
- Use `jsc.experimental. emitAssertForImportAttributes`.
- Closes #7926
- Closes #7928
=> fix(es/codegen): Use `emitAssertForImportAttributes`

crates/swc_ecma_transforms_optimization/src/const_modules.rs, crates/swc_ecma_transforms_optimization/tests/const-modules/issue-7747/globals.json, crates/swc_ecma_transforms_optimization/tests/const-modules/issue-7747/input.js, crates/swc_ecma_transforms_optimization/tests/const-modules/issue-7747/output.js, crates/swc_ecma_transforms_optimization/tests/const_modules.rs
=> fix(es/minifier): Handle `ModuleDecl` when transform const modules

crates/swc/tests/fixture/issues-7xxx/7977/input/.swcrc, crates/swc/tests/fixture/issues-7xxx/7977/input/index.ts, crates/swc/tests/fixture/issues-7xxx/7977/output/index.ts, crates/swc_ecma_transforms_compat/src/es2020/nullish_coalescing.rs
=> fix(es/compat): Handle nullish in fn expr scope

crates/swc/tests/fixture/issues-8xxx/8004/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8004/input/1.js, crates/swc/tests/fixture/issues-8xxx/8004/output/1.js, crates/swc_ecma_codegen/src/lib.rs
=> fix(es/codegen): Fix codegen of optional chaining expr with a comment

crates/swc_ecma_transforms_typescript/src/transform.rs, crates/swc_ecma_transforms_typescript/src/ts_enum.rs, crates/swc_ecma_transforms_typescript/src/typescript.rs
This is just a typo fix. No functional changes are expected. 
However, correcting the wrong parameter name will avoid confusing our Rust-side users.
- Closes: #8016
=> fix(es/typescript): Rename wrong `unresolved_mark`

crates/swc_ecma_transforms_proposal/src/decorator_2022_03.rs, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-getters-and-setters--to-es2015/private/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-getters-and-setters--to-es2015/static-private/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-getters-and-setters/private/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-getters-and-setters/static-private/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-methods--to-es2015/private/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-methods--to-es2015/static-private/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-methods/private/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-methods/static-private/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-misc/all-decorators/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-misc/setting-private-method-via-array-pattern/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-misc/setting-private-method-via-for-of/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-misc/setting-private-method-via-object-pattern/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-misc/setting-private-method-via-rest/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-misc/setting-private-method-via-update/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-misc/setting-private-method/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-misc/super-in-private-method/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-ordering/accessor-simple/1/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-ordering/accessor-static-method-initializers/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-ordering/initializers/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-setters--to-es2015/private/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-setters--to-es2015/static-private/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-setters/private/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-setters/static-private/output.js
This aligns with other implementations such as TypeScript's and correctly implements the currently proposed behavior.
- Closes #8015.
=> fix(es/compat): Use return statements for method and setter decorator

crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/tests/fixture/issues/7984/input.js, crates/swc_ecma_minifier/tests/fixture/issues/7984/output.js
=> fix(es/minifier): Check if object shorthand is skippable for seq inliner

crates/swc/tests/fixture/issues-8xxx/8020/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8020/input/1.js, crates/swc/tests/fixture/issues-8xxx/8020/output/1.js, crates/swc_ecma_transforms_proposal/src/explicit_resource_management.rs, crates/swc_ecma_transforms_proposal/tests/explicit-resource-management/transform-await/mixed/output.mjs, crates/swc_ecma_transforms_proposal/tests/explicit-resource-management/transform-await/only-using-await/output.mjs, crates/swc_ecma_transforms_proposal/tests/explicit-resource-management/transform-sync/bare-block/output.js, crates/swc_ecma_transforms_proposal/tests/explicit-resource-management/transform-sync/function-body/output.js, crates/swc_ecma_transforms_proposal/tests/explicit-resource-management/transform-sync/if-body/output.js, crates/swc_ecma_transforms_proposal/tests/explicit-resource-management/transform-sync/multiple-nested/output.js, crates/swc_ecma_transforms_proposal/tests/explicit-resource-management/transform-sync/multiple-same-level/output.js, crates/swc_ecma_transforms_proposal/tests/explicit-resource-management/transform-sync/static-block/output.js, crates/swc_ecma_transforms_proposal/tests/explicit-resource-management/transform-top-level/hoisting/output.mjs
=> fix(es/compat): Fix scoping of `explicit-resource-management`

crates/swc/tests/fixture/issues-7xxx/7989/input/.swcrc, crates/swc/tests/fixture/issues-7xxx/7989/input/1.js, crates/swc/tests/fixture/issues-7xxx/7989/output/1.js, crates/swc_ecma_transforms_compat/src/es2015/block_scoping/mod.rs, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-7989/input.js, crates/swc_ecma_transforms_compat/tests/block-scoping/issue-7989/output.js
=> fix(es/compat): Use `async` and `await` correctly in `block-scoping` pass

crates/swc_ecma_transforms_compat/src/es2015/shorthand_property.rs, crates/swc_ecma_transforms_compat/tests/es2015_shorthand_propertie.rs, crates/swc_ecma_transforms_compat/tests/shorthand_properties/.method-type-annotations/input.js, crates/swc_ecma_transforms_compat/tests/shorthand_properties/.method-type-annotations/output.js, crates/swc_ecma_transforms_compat/tests/shorthand_properties/method-plain/input.js, crates/swc_ecma_transforms_compat/tests/shorthand_properties/method-plain/output.js, crates/swc_ecma_transforms_compat/tests/shorthand_properties/proto/input.js, crates/swc_ecma_transforms_compat/tests/shorthand_properties/proto/output.js, crates/swc_ecma_transforms_compat/tests/shorthand_properties/shorthand-comments/input.js, crates/swc_ecma_transforms_compat/tests/shorthand_properties/shorthand-comments/output.js, crates/swc_ecma_transforms_compat/tests/shorthand_properties/shorthand-mixed/input.js, crates/swc_ecma_transforms_compat/tests/shorthand_properties/shorthand-mixed/output.js, crates/swc_ecma_transforms_compat/tests/shorthand_properties/shorthand-multiple/input.js, crates/swc_ecma_transforms_compat/tests/shorthand_properties/shorthand-multiple/output.js, crates/swc_ecma_transforms_compat/tests/shorthand_properties/shorthand-single/input.js, crates/swc_ecma_transforms_compat/tests/shorthand_properties/shorthand-single/output.js
- https://github.com/babel/babel/pull/12664
=> fix(es/compat): Handle `__proto__` edge case in `shorthand` pass

crates/swc_ecma_transforms_proposal/src/decorator_2022_03.rs, crates/swc_ecma_transforms_proposal/tests/decorators/issue-8098/1/input.js, crates/swc_ecma_transforms_proposal/tests/decorators/issue-8098/1/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/issue-8098/options.json
=> fix(es/compat): Handle export default decorator only if not empty

crates/swc_ecma_preset_env/src/lib.rs
=> refactor(es/preset-env): Rename parameter to avoid confusion

crates/swc_ecma_transforms_typescript/tests/fixture/issue-8124/input.ts, crates/swc_ecma_transforms_typescript/tests/fixture/issue-8124/output.js, crates/swc_ecma_utils/src/lib.rs
=> fix(es/utils): Skip var declarator name in `RefRewriter`

crates/swc_ecma_transforms_base/src/helpers/_apply_decs_2203_r.js, crates/swc_ecma_transforms_proposal/src/decorator_2022_03.rs, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-classes--to-es2015/expressions-static-blocks/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-classes--to-es2015/expressions/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-classes--to-es2015/inheritance/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-classes--to-es2015/initializers/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-classes/expressions-static-blocks/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-classes/expressions/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-classes/inheritance/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-classes/initializers/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-metadata/class/exec.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-metadata/element/exec.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-metadata/no-decorators/exec.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-metadata/options.json, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-metadata/subclass-no-super-decorators/exec.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-metadata/subclass-super-decorators/exec.js, crates/swc_ecma_transforms_proposal/tests/decorators/2022-03-misc/super-in-nested-constructor-expression/output.js, packages/helpers/esm/_apply_decs_2203_r.js
This PR implements the [decorator metadata](https://github.com/tc39/proposal-decorator-metadata) proposal, that is now at Stage 3.
As the decorator metadata proposal is a small extension of the decorator proposal and is not possible to compile the metadata without transpiling decorators, I opted to implement it into the existing decorator transformer (and helper)
- Closes #7957
=> feat(es/compat): Implement decorator metadata proposal

crates/swc_css_ast/src/token.rs
when hash a stylesheet ast, it will trigger stack overflow.
the root cause is that ,  `Token`'s `hash` function recursively call itself.
No
https://github.com/swc-project/swc/discussions/8142
=> fix(css/ast): Make `.hash()` of `Token` not recursive

crates/swc_ecma_transforms_typescript/src/transform.rs, crates/swc_ecma_transforms_typescript/tests/strip.rs
**Description:** Bug I introduced in https://github.com/swc-project/swc/pull/8115/files (it was not implemented correctly)
=> fix(es/typescript): Support `ts_enum_is_mutable` with const enums

crates/swc_ecma_minifier/src/compress/optimize/inline.rs, crates/swc_ecma_minifier/tests/fixture/issues/8161/input.js, crates/swc_ecma_minifier/tests/fixture/issues/8161/output.js
=> fix(es/minifier): Always consider `reassigned` when inlining

crates/swc/tests/fixture/issues-8xxx/8199/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8199/input/1.js, crates/swc/tests/fixture/issues-8xxx/8199/output/1.js, crates/swc_ecma_compat_es2015/src/parameters.rs
=> fix(es/compat): Use dummy span for blocks in `parameters`

crates/swc_ecma_compat_es2015/src/classes/mod.rs, crates/swc_ecma_transforms_react/src/jsx/mod.rs, crates/swc_ecma_transforms_react/src/pure_annotations/mod.rs
- https://github.com/vercel/next.js/pull/57904 (CI failed)
=> fix(es/transforms): Do not add `PURE` comment to `BytePos(0)`

crates/swc/tests/fixture/issues-7xxx/7561/es2019/output/1.js, crates/swc/tests/fixture/issues-7xxx/7561/es2021/output/1.js, crates/swc/tests/fixture/issues-8xxx/8073/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8073/input/1.js, crates/swc/tests/fixture/issues-8xxx/8073/output/1.js, crates/swc/tests/fixture/issues-8xxx/8199/output/1.js, crates/swc/tests/fixture/issues-8xxx/8210/output/1.js, crates/swc_ecma_parser/src/parser/typescript.rs, crates/swc_ecma_parser/tests/tsc/asiPreventsParsingAsTypeAlias01.json, crates/swc_ecma_parser/tests/tsc/asiPreventsParsingAsTypeAlias02.json, crates/swc_ecma_parser/tests/typescript/issue-8073/input.ts, crates/swc_ecma_parser/tests/typescript/issue-8073/input.ts.json
=> fix(es/parser): Consider ASI while parsing TypeScript type aliases

Cargo.lock, crates/swc_bundler/src/bundler/load.rs, crates/swc_common/Cargo.toml, crates/swc_common/src/eq.rs
I believe we can remove this now because of hstr?
(I don't need this. I just noticed it was not used in the swc repo anymore. Maybe it's used elsewhere though?)
**BREAKING CHANGE:** Removes `EqIgnoreSpan` and `TypeEq` implementations for `string_cache::Atom`
=> refactor(common): Remove string_cache dependency

Cargo.lock, crates/swc_ecma_ext_transforms/Cargo.toml, crates/swc_ecma_transforms_base/Cargo.toml
**Description:** Sorry, should have included this in my last PR, but I just noticed this one.
This removes the duplicate phf dependency to align with the version in hstr.
=> build(es): Remove duplicate `phf` dependency

crates/swc_ecma_minifier/src/compress/optimize/iife.rs, crates/swc_ecma_minifier/src/compress/optimize/inline.rs, crates/swc_ecma_minifier/tests/full/issues/8288/input.js, crates/swc_ecma_minifier/tests/full/issues/8288/output.js
=> fix(es/minifier): Apply new `SyntaxContext` to inlined `Arrow`

crates/swc_ecma_minifier/src/compress/pure/dead_code.rs, crates/swc_ecma_minifier/src/util/mod.rs, crates/swc_ecma_minifier/tests/fixture/issues/8337/config.json, crates/swc_ecma_minifier/tests/fixture/issues/8337/input.js, crates/swc_ecma_minifier/tests/fixture/issues/8337/output.js
- Closes #8337.
- Closes #8324.
- Reverts #8328.
=> fix(es/minifier): Give up terminate merge if in `try` with `finally`

crates/swc_ecma_transforms_react/src/jsx/mod.rs, crates/swc_ecma_transforms_react/tests/jsx/fixture/react-automatic/should-detect-static-jsx/input.js, crates/swc_ecma_transforms_react/tests/jsx/fixture/react-automatic/should-detect-static-jsx/output.mjs, crates/swc_ecma_transforms_react/tests/jsx/fixture/react-automatic/should-disallow-spread-children/output.mjs
Example:
```js
<h1>{...a}</h1>
```
Before:
```js
_jsx("h1", {
children: [
...a
]
})
```
After:
```js
_jsxs("h1", {
children: [
...a
]
})
```
Following the implementation in [Typescript](https://github.com/microsoft/TypeScript/blob/d4fbc9b57d9aa7d02faac9b1e9bb7b37c687f6e9/src/compiler/transformers/jsx.ts#L340), jsx with a single spread child should also be considered as static jsx.
Live examples:
[Typescript](https://www.typescriptlang.org/play?target=99&jsx=4#code/MYewdgzgLgBAhjAvDAPACwIwD4DeA6AgbQwCYBmAXQF8UB6TLAKCA)
[Esbuild](https://esbuild.github.io/try/#dAAwLjE5LjcAewogIGxvYWRlcjogJ2pzeCcsCiAganN4OiAnYXV0b21hdGljJywKfQA8ZGl2PnsuLi5bXX08L2Rpdj4)
[SWC](https://play.swc.rs/?version=1.3.100-nightly-20231124.1&code=H4sIAAAAAAAAA0vOzysuUUhUsFWwSckss6vW09OLjq210QdxAHOBudocAA …
=> fix(es/react): jsx with single spread child is static

crates/swc_ecma_parser/src/lib.rs, crates/swc_ecma_parser/src/parser/mod.rs
`swc_ecma_parser` crate has a `typescript` feature which enables TS parsing, the `Syntax::Typescript` variant is behind the `typescript` feature, compiling without this feature fails as `Syntax::Typescript` is referenced at many places without `#[cfg(feature = "typescript")]`
None
=> fix(es/parser): Fix conditional compilation

crates/swc/tests/fixture/issues-8xxx/8345/input/1.js, crates/swc/tests/fixture/issues-8xxx/8345/output/1.js, crates/swc_ecma_codegen/src/lib.rs
=> fix(es/codegen): Fix panic due to `\\ud`

crates/swc_atoms/src/lib.rs
**Related issue:** 
- Closes #8362
=> chore(atoms): Evaluate `.into()` in `AtomStoreCell` eagerly

crates/swc/tests/fixture/issues-8xxx/8367/input/index.ts, crates/swc/tests/fixture/issues-8xxx/8367/output/index.ts, crates/swc/tests/tsc-references/classAbstractMergedDeclaration.1.normal.js, crates/swc/tests/tsc-references/classAbstractMergedDeclaration.2.minified.js, crates/swc/tests/tsc-references/declaredClassMergedwithSelf.1.normal.js, crates/swc/tests/tsc-references/declaredClassMergedwithSelf.2.minified.js, crates/swc_ecma_lints/src/rules/duplicate_bindings.rs
=> fix(es/lint): Ignore ambient context binding 

crates/swc_css_parser/src/lib.rs, crates/swc_css_parser/src/parser/selectors/mod.rs, crates/swc_css_parser/src/parser/syntax/mod.rs, crates/swc_css_parser/src/parser/util.rs, crates/swc_css_parser/src/parser/values_and_units/mod.rs
=> refactor(css/parser): Support stable rust

Cargo.lock, crates/swc_ecma_testing/Cargo.toml, crates/swc_ecma_testing/src/lib.rs, crates/swc_ecma_transforms_testing/Cargo.toml, crates/swc_ecma_transforms_testing/src/lib.rs
**Descrption:**
`sha-1` crate has been deprecated and the algorithm itself is not considered secure or collision-proof. Moving to `sha2` solves this.
- Closes #8382
=> Use sha2 in place of sha-1

crates/swc_css_lints/src/lib.rs, crates/swc_css_lints/src/rules/font_family_no_duplicate_names.rs, crates/swc_css_lints/src/rules/no_invalid_position_at_import_rule.rs, crates/swc_css_lints/src/rules/unit_no_unknown.rs
=> refactor(css/lints): Support stable rust

crates/swc_common/src/source_map.rs
The previous code was very strange, and it could easily cause OOM.
=> perf(common): Fix OOM of `inputSourceMap`

crates/ast_node/src/ast_node_macro.rs, crates/ast_node/src/enum_deserialize.rs, crates/ast_node/src/lib.rs, crates/ast_node/src/spanned.rs, crates/string_enum/src/lib.rs, crates/swc_config_macro/src/merge.rs, crates/swc_css_codegen_macros/src/lib.rs, crates/swc_ecma_codegen_macros/src/fold.rs, crates/swc_ecma_codegen_macros/src/lib.rs, crates/swc_ecma_quote_macros/src/ast/enums.rs, crates/swc_ecma_quote_macros/src/ast/id.rs, crates/swc_ecma_quote_macros/src/ast/lit.rs, crates/swc_ecma_quote_macros/src/ast/mod.rs, crates/swc_ecma_quote_macros/src/ctxt.rs, crates/swc_ecma_transforms_macros/src/fast.rs, crates/swc_ecma_transforms_macros/src/parallel.rs, crates/swc_html_codegen_macros/src/lib.rs, crates/swc_visit_macros/src/lib.rs, crates/swc_xml_codegen_macros/src/lib.rs
`pmutil` borned to die. Now almost all useful features are merged into `syn` and `quote`, so it's now just a compile-time bloat. (Although I didn't send PRs to them, sorry)
=> build(macros): Drop `pmutil` to improve compile time

crates/swc_ecma_transforms_base/src/resolver/mod.rs, crates/swc_ecma_transforms_base/tests/ts-resolver/issue-7967/1/input.ts, crates/swc_ecma_transforms_base/tests/ts-resolver/issue-7967/1/output.ts, crates/swc_ecma_transforms_base/tests/ts-resolver/issue-7967/2/input.ts, crates/swc_ecma_transforms_base/tests/ts-resolver/issue-7967/2/output.ts
Related issue:
- Closes: https://github.com/swc-project/swc/issues/7967
=> fix(es/resolver): Handle `TsInterfaceDecl` and `UsingDecl` correctly

crates/swc_ecma_ast/src/expr.rs
=> feat(es/ast): Add `as_import_with` to `ObjectLit` to provide easier API

crates/swc_bundler/src/bundler/chunk/merge.rs, crates/swc_ecma_ast/src/ident.rs, crates/swc_ecma_compat_es2015/src/classes/mod.rs, crates/swc_ecma_compat_es2015/src/computed_props.rs, crates/swc_ecma_compat_es2015/src/destructuring.rs, crates/swc_ecma_compat_es2015/src/for_of.rs, crates/swc_ecma_compat_es2015/src/generator.rs, crates/swc_ecma_compat_es2015/src/new_target.rs, crates/swc_ecma_compat_es2015/src/parameters.rs, crates/swc_ecma_compat_es2017/src/async_to_generator.rs, crates/swc_ecma_compat_es2018/src/object_rest.rs, crates/swc_ecma_compat_es2022/src/class_properties/member_init.rs, crates/swc_ecma_compat_es2022/src/class_properties/private_field.rs, crates/swc_ecma_transforms_classes/src/super_field.rs, crates/swc_ecma_transforms_compat/src/class_fields_use_set.rs, crates/swc_ecma_transforms_module/src/amd.rs, crates/swc_ecma_transforms_module/src/common_js.rs, crates/swc_ecma_transforms_module/src/system_js.rs, crates/swc_ecma_transforms_module/src/umd.rs, crates/swc_ecma_transforms_module/src/util.rs, crates/swc_ecma_transforms_typescript/src/transform.rs, crates/swc_ecma_transforms_typescript/src/ts_enum.rs, crates/swc_ecma_utils/src/constructor.rs, crates/swc_ecma_utils/src/factory.rs, crates/swc_ecma_utils/src/function/fn_env_hoister.rs, crates/swc_ecma_utils/src/function/function_wrapper.rs, crates/swc_ecma_utils/src/lib.rs, crates/swc_ecma_utils/src/macros.rs, crates/swc_ecma_utils/src/node_ignore_span.rs
This PR is extracted from #8333 because it's too large. 
**Breaking Changes**:
- `ExprFactory::make_member()` now returns `MemberExpr` instead of `Box<Expr>`.
- `member_expr!()` now returns `MemberExpr` instead of `Box<Expr>`.
=> refactor(es/utils): Use exact type for factory methods

crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/tests/fixture/typescript/class_prop/input.js, crates/swc_ecma_codegen/tests/fixture/typescript/class_prop/output.js, crates/swc_ecma_codegen/tests/fixture/typescript/class_prop/output.min.js, crates/swc_ecma_transforms/tests/fixture/legacy-metadata/issues/1160/1/output.ts, crates/swc_ecma_transforms/tests/fixture/legacy-metadata/issues/1421/1/output.ts, crates/swc_ecma_transforms/tests/fixture/legacy-only/issues/862/1/output.ts, crates/swc_ecma_transforms/tests/fixture/legacy-only/issues/862/2/output.ts, crates/swc_ecma_transforms_typescript/src/strip_type.rs
**Description:** This fixes the codegen of private properties with `is_optional` or`definite` and class properties with `definite`.
=> fix(es/codegen): Fix codegen of ts specific syntax in class props

crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/tests/fixture/typescript/exports/input.js, crates/swc_ecma_codegen/tests/fixture/typescript/exports/output.js, crates/swc_ecma_codegen/tests/fixture/typescript/exports/output.min.js, crates/swc_ecma_codegen/tests/fixture/typescript/imports/input.js, crates/swc_ecma_codegen/tests/fixture/typescript/imports/output.js, crates/swc_ecma_codegen/tests/fixture/typescript/imports/output.min.js, crates/swc_ecma_codegen/tests/fixture/typescript/ts_import_equals/input.js, crates/swc_ecma_codegen/tests/fixture/typescript/ts_import_equals/output.js, crates/swc_ecma_codegen/tests/fixture/typescript/ts_import_equals/output.min.js
This fixes the emit for `export type { } from "..."` and `export { type A } from "..."`.
=> fix(es/codegen): Correct emit for type-only export declarations

crates/swc_ecma_usage_analyzer/src/util.rs
I was trying to remove references to Weak Ref from minified code and despite the expression not being used, it was still included.
E.g.
```
var x = WeakRef;
```
with
```
{
"minify": true,
"jsc": {
"minify": {
"compress": {
"pure_getters": true,
"unused": true
},
"mangle": true
}
}
}
```
outputs
```
WeakRef;
```
but when I use something on this list e.g. parseFloat, it gets cleaned up and outputs empty string.
btw - I tried different options for pure_getters that I assumed would allow me to say WeakRef as a getter was pure, but it had no effect.
WeakRef getter is as safe to remove as the other items on this list and has no effect in accessing it.
=> fix(es/minifier): Add WeakRef as a safe global reference

crates/swc_ecma_ast/src/list.rs, crates/swc_ecma_codegen/tests/fixture/typescript/class_implements/input.js, crates/swc_ecma_codegen/tests/fixture/typescript/class_implements/output.js, crates/swc_ecma_codegen/tests/fixture/typescript/class_implements/output.min.js
Emitting `implements` was missing commas.
=> fix(es/codegen): Emit implements clause with commas

crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/tests/fixture/typescript/class_prop/input.js, crates/swc_ecma_codegen/tests/fixture/typescript/class_prop/output.js, crates/swc_ecma_codegen/tests/fixture/typescript/class_prop/output.min.js
**Description:** Emits optional `?` for a computed property.
=> fix(es/codegen): Emit `?` for an optional computed property

crates/swc/tests/fixture/issues-8xxx/8505/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8505/input/index.ts, crates/swc/tests/fixture/issues-8xxx/8505/output/index.ts, crates/swc_ecma_transforms_module/src/system_js.rs
=> fix(es/systemjs): Handle top level this

Cargo.lock, crates/swc_cli_impl/src/commands/plugin.rs, crates/swc_ecma_transforms_testing/Cargo.toml, crates/swc_ecma_transforms_testing/src/lib.rs
I made a bad decision while migrating tests in the core repository to snapshot testing. So, I'm adding the `test!` macro back with a slight renaming.
- Closes #8504
=> fix(es): Fix plugin template & restore `test!` as `test_inline!`

crates/swc_core/src/plugin.rs, crates/swc_plugin_macro/src/lib.rs
- `swc_common::errors::handler::HANDLER` should be used, and `swc_core::plugin::errors::HANDLER` is now a simple alias.
- Closes #8502
=> fix(plugin): Set `swc_common::errors::HANDLER` while invoking plugins

crates/swc_ecma_transforms_typescript/src/typescript.rs, crates/swc_ecma_transforms_typescript/tests/__swc_snapshots__/tests/strip.rs/ts_jsx_bad_pragma.js, crates/swc_ecma_transforms_typescript/tests/strip.rs
Currently a jsx pragma with an invalid js identifier (eg, with dashes: `@jsx bad-pragma` causes a panic.
This PR prevents a panic and will ignore an invalid pragma in a comment.
(There may be an argument for showing an error or warning instead, but given a jsx pragma is still valid ES I'm not sure whether that makes sense?)
[Original (Deno) issue here](https://github.com/denoland/deno/issues/21927)
=> fix(es/typescript): Fix panic on invalid jsx pragma

Cargo.lock, crates/preset_env_base/Cargo.toml, crates/swc_atoms/Cargo.toml, crates/swc_css_prefixer/tests/fixture/autofill/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/file-selector-button/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/grouping-rule/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/nested/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/placeholder/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/resolution/output.defaults-not-ie-11.css, crates/swc_css_prefixer/tests/fixture/text-emphasis/output.defaults-not-ie-11.css, crates/swc_ecma_preset_env/tests/fixtures/corejs2/usage-for-of-destructure-with/output.mjs, crates/swc_ecma_preset_env/tests/fixtures/corejs2/usage-for-of-destructure-without/output.mjs, crates/swc_ecma_preset_env/tests/fixtures/corejs2/usage-instance-methods-native-support/output.mjs, crates/swc_ecma_preset_env/tests/fixtures/corejs2/usage-native-support/output.mjs, crates/swc_ecma_preset_env/tests/fixtures/corejs3/usage-for-of-destructure-with/output.mjs, crates/swc_ecma_preset_env/tests/fixtures/corejs3/usage-for-of-destructure-without/output.mjs, crates/swc_ecma_preset_env/tests/fixtures/corejs3/usage-instance-methods-native-support/output.mjs, crates/swc_ecma_preset_env/tests/fixtures/corejs3/usage-native-support/output.mjs, crates/swc_ecma_preset_env/tests/fixtures/corejs3/usage-static-methods-native-support/output.mjs, crates/swc_ecma_preset_env/tests/fixtures/corejs3/usage-static-methods/output.mjs
=> chore(preset-env): Update `browserslist-rs`

crates/swc_ecma_quote_macros/src/ast/enums.rs, crates/swc_ecma_quote_macros/src/ast/expr.rs, crates/swc_ecma_quote_macros/src/ast/module_decl.rs
When using quote! to generate import decl, compile error: missing field `phase` in initializer of 'swc_core::ecma::ast::Import'
=> fix(es/quote): Add support for import phase to quote macro

crates/swc/tests/fixture/issues-8xxx/8551/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8551/input/index.ts, crates/swc/tests/fixture/issues-8xxx/8551/output/index.ts, crates/swc_ecma_transforms_proposal/src/decorator_2022_03.rs
=> fix(es/decorator): Preserve state while traversing the `module_items` scope

crates/swc_ecma_transforms_testing/src/lib.rs
I made a mistake while working on `test_inline!`
- #8568
=> fix(es/testing): Make `test_inline!` not read output as a file

crates/swc_ecma_transforms_base/src/helpers/_using.js, crates/swc_ecma_transforms_proposal/tests/explicit-resource-management/exec-async/using-function.js, crates/swc_ecma_transforms_proposal/tests/explicit-resource-management/exec-sync/using-function.js, packages/counter/package.json, packages/helpers/esm/_using.js, packages/helpers/package.json, packages/swc-info/package.json, packages/types/package.json
- Closes #8570
- https://github.com/babel/babel/pull/16150
=> fix(es/proposals): Support using `using` keyword with functions

crates/swc/tests/fixture/issues-8xxx/8594/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8594/input/index.tsx, crates/swc/tests/fixture/issues-8xxx/8594/output/index.tsx, crates/swc_ecma_transforms_module/src/module_ref_rewriter.rs, crates/swc_ecma_transforms_typescript/src/transform.rs, crates/swc_ecma_utils/src/lib.rs
=> fix(es/typescript): Handle exported JSX binding name in TypeScript namespace

crates/swc_ecma_quote/src/lib.rs, crates/swc_ecma_quote_macros/src/ctxt.rs, crates/swc_ecma_quote_macros/src/ret_type.rs
This is required to fix https://github.com/vercel/turbo/pull/7272
- https://github.com/vercel/turbo/pull/7272
=> fix(es/quote): Allow variables typed `AssignTarget`

crates/swc_ecma_transforms_proposal/src/decorator_2022_03.rs, crates/swc_ecma_transforms_proposal/tests/decorators.rs, crates/swc_ecma_transforms_proposal/tests/decorators/issue-8631/1/input.ts, crates/swc_ecma_transforms_proposal/tests/decorators/issue-8631/1/output.js, crates/swc_ecma_transforms_proposal/tests/decorators/issue-8631/1/output.ts, crates/swc_ecma_transforms_proposal/tests/decorators/issue-8631/options.json
Doesn't insert a duplicate ctor when the ctor uses overloads in TS.
**Related issue:** 
- Closes #8630.
=> fix(es/decorators): Do not insert duplicate constructors

bindings/binding_core_node/Cargo.toml, crates/swc/src/config/mod.rs, crates/swc_ecma_transforms_base/src/rename/analyzer/scope.rs, crates/swc_ecma_transforms_module/src/path.rs, package.json, yarn.lock
`PathBuf` and `rayon` is usable in `wasm32-wasi-preview1-threads` target, so we can enable it.
=> refactor(es): Prepare `wasm32-wasi-preview1-threads` target support

crates/swc_ecma_minifier/tests/fixture/issues/8706/config.json, crates/swc_ecma_minifier/tests/fixture/issues/8706/input.js, crates/swc_ecma_minifier/tests/fixture/issues/8706/output.js, crates/swc_ecma_utils/src/lib.rs
=> fix(es/minifier): Fix evaluation of array literals with `void 0`

crates/swc/tests/fixture/deno/paths/issue-2753/2-cjs/input/src/command/restore.ts, crates/swc/tests/fixture/deno/paths/issue-2753/2-cjs/output/src/command/restore.ts, crates/swc/tests/fixture/deno/paths/issue-2753/2-esm/input/src/command/restore.ts, crates/swc/tests/fixture/deno/paths/issue-2753/2-esm/output/src/command/restore.ts, crates/swc_cli_impl/tests/issues.rs, crates/swc_ecma_transforms_module/src/path.rs
=> fix(es/module): Fix interop of `jsc.paths` with symlinks

crates/swc_ecma_ext_transforms/Cargo.toml
**Description:** Add the `repository` field to `swc_ecma_ext_transforms`, making it easier for users or automated tools to find the git repository a crate is published from.
=> chore(es/transforms): Add `repository` field to `swc_ecma_ext_transforms`

Cargo.lock, crates/swc_ecma_ast/Cargo.toml, crates/swc_ecma_ast/src/ident.rs
=> perf(es/parser): Use faster unicode crate

crates/swc_ecma_transforms_proposal/src/decorator_2022_03.rs, crates/swc_ecma_utils/src/lib.rs
**Description:** Fixes an incorrect capacity (found while investigating a segfault).
More details: https://github.com/denoland/deno/pull/23187#issuecomment-2036266885
=> fix(es/transforms): Fix capacity overflow with decorators

crates/swc_visit/src/util/move_map.rs
**Description:** Simplifies the `move_map` implementation.
**Related issue (if exists):** None.
=> refactor(visit): Simplify `Vec::move_map`

crates/swc_ecma_codegen/src/comments.rs, crates/swc_ecma_codegen/src/text_writer.rs, crates/swc_ecma_parser/src/lexer/jsx.rs, crates/swc_ecma_parser/src/lexer/number.rs, crates/swc_ecma_parser/src/lib.rs, crates/swc_ecma_parser/src/parser/class_and_fn.rs, crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_parser/src/parser/expr/ops.rs, crates/swc_ecma_parser/src/parser/jsx.rs, crates/swc_ecma_transforms_optimization/src/simplify/expr/mod.rs
**Description:** Makes the code compile with miri.
For some reason, Miri seems more strict.
=> refactor(es): Make the code compile with `miri`

packages/helpers/esm/_identity.js
when i use @swc/core to build my code and set tsconfig with `"importHelpers": true`
it has error `Missing "./_/_identity" specifier in "@swc/helpers" package`.
I found that the reason for the error is that this file is missing.
=> fix(es/helpers): Add missing helpers

crates/swc_ecma_minifier/src/compress/pure/evaluate.rs, crates/swc_ecma_minifier/tests/exec.rs
=> fix(es/minifier): Remove `raw` of strings after modification

crates/swc/src/lib.rs, crates/swc/tests/fixture/issues-8xxx/8869/input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8869/input/1.js, crates/swc/tests/fixture/issues-8xxx/8869/output/1.js, crates/swc/tests/fixture/sourcemap/issue-6552/input-map/output/index.map
=> fix(es): Ignore `sourceMappingURL` in string literals

crates/swc_ecma_minifier/src/compress/optimize/iife.rs, crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/tests/fixture/issues/8622/input.js, crates/swc_ecma_minifier/tests/fixture/issues/8622/mangle.json, crates/swc_ecma_minifier/tests/fixture/issues/8622/output.js
`inline` and `seq inline` should apply this change too.
- Closes #8622
=> fix(es/minifier): Don't invoke IIFE containing reserved words

crates/swc_ecma_minifier/src/compress/pure/evaluate.rs, crates/swc_ecma_minifier/tests/exec.rs
=> fix(es/minifier): Fix evaluation of `String.charCodeAt`

crates/swc_ecma_ast/src/ident.rs, crates/swc_ecma_compat_es2022/src/class_properties/mod.rs, crates/swc_ecma_compat_es2022/src/class_properties/private_field.rs, crates/swc_ecma_transforms_compat/tests/__swc_snapshots__/tests/es2022_class_properties.rs/loose_keyword_method.js, crates/swc_ecma_transforms_compat/tests/class-properties/issue-8948/input.js, crates/swc_ecma_transforms_compat/tests/class-properties/issue-8948/output.js, crates/swc_ecma_transforms_compat/tests/es2022_class_properties.rs
Following development should follow babel/babel#16261 to avoid separate `WeakMap` for each individual private method
- Closes #8948.
=> fix(es/compat): Avoid reserved name for private method

crates/swc/src/lib.rs
Some libraries generate source maps but do not upload them to npm, which causes SWC to fail.
- https://github.com/swc-project/swc/issues/8789#issuecomment-2105055772
=> fix(es): Allow input source map file to be omitted

crates/swc/tests/fixture/jest/mock-globals/input/.swcrc, crates/swc/tests/fixture/jest/mock-globals/input/1.js, crates/swc/tests/fixture/jest/mock-globals/output/1.js, crates/swc_ecma_ast/src/module_decl.rs, crates/swc_ecma_ext_transforms/src/jest.rs
- We have two `jest` pass. One in `@swc/core` (via _hidden.jest flag), and one in the plugin. This PR fixes only the core one.
However, the linked issue is wrong because the code tries to break the rule of ESM specification. So although this PR closes the issue, the final form is not the issue author wanted.
- Closes https://github.com/swc-project/plugins/issues/310
=> fix(es/jest): Handle `@jest/globals`

crates/swc_ecma_ast/src/expr.rs, crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/tests/test262.rs, crates/swc_ecma_parser/src/lexer/jsx.rs, crates/swc_ecma_parser/src/lexer/mod.rs, crates/swc_ecma_parser/src/lexer/number.rs
We can skip this logic completely, as it's `raw`.
~I'm under the impression that I'm super stupid~
=> perf(es/parser): Do not track `raw` by hand

crates/swc/tests/errors/lints/no-dupe-args/hash-mode/input.js, crates/swc/tests/errors/lints/no-dupe-args/hash-mode/output.swc-stderr, crates/swc_ecma_lints/src/rules/no_dupe_args.rs, crates/swc_ecma_utils/src/lib.rs
I introduced a zero-allocation variant for `swc_ecma_utils::DestructuringFinder` that does not allocate anything.
=> perf(es/lints): Avoid needless allocations in `no-dupe-args`

crates/swc_ecma_parser/src/lexer/mod.rs, crates/swc_ecma_parser/src/lexer/util.rs
=> refactor(es/parser): Remove unused `raw: Raw` params

crates/swc_ecma_parser/src/lexer/number.rs
We don't need to allocate one byte at a time while lexing numbers.
=> perf(es/parser): Reduce allocations for `raw` while lexing numbers

crates/swc_common/src/input.rs, crates/swc_ecma_parser/src/lexer/mod.rs
=> refactor(common): Simplify `StringInput` implementation

.github/workflows/bench.yml, crates/swc_ecma_parser/src/lexer/mod.rs
In the fast path, we don't even use the buffer.
```
Benchmarking es/lexer/cal-com
Benchmarking es/lexer/cal-com: Warming up for 3.0000 s
Benchmarking es/lexer/cal-com: Collecting 100 samples in estimated 5.5395 s (900 iterations)
Benchmarking es/lexer/cal-com: Analyzing
es/lexer/cal-com        time:   [6.1799 ms 6.2010 ms 6.2250 ms]
change: [-4.4027% -3.9504% -3.5372%] (p = 0.00 < 0.05)
Found 17 outliers among 100 measurements (17.00%)
4 (4.00%) high mild
13 (13.00%) high severe
```
=> perf(es/lexer): Reduce allocation while lexing identifiers

crates/swc_ecma_parser/src/lexer/mod.rs, crates/swc_ecma_parser/src/lexer/state.rs, crates/swc_ecma_parser/src/parser/typescript.rs
- `TokenContexts` now uses smallvec, as the element type is very small (1 byte) now.
- Some codes are moved to allow CPU to cache code correctly.
=> perf(es/lexer): Apply various optimizations

crates/swc/src/lib.rs, crates/swc_cli_impl/examples/cli.rs, crates/swc_cli_impl/src/commands/compile.rs, packages/types/index.ts, packages/types/package.json
I verified that `swc_cli` (Rust) works with 
```json
{
"jsc": {
"parser": {
"syntax": "typescript"
},
"experimental": {
"emitIsolatedDts": true
}
}
}
```
=> feat(cli): Support generating `.d.ts` files

Cargo.lock, crates/swc_ecma_parser/Cargo.toml, crates/swc_ecma_parser/src/lexer/jsx.rs, crates/swc_ecma_parser/src/lexer/mod.rs, crates/swc_ecma_parser/src/lexer/state.rs, crates/swc_ecma_parser/src/lexer/util.rs
This PR also makes the lexer more CPU-cache friendly.
=> perf(es/lexer): Use `memchr::memmem` for lexing block comments

crates/swc_ecma_parser/src/lexer/util.rs, crates/swc_ecma_parser/src/lexer/whitespace.rs, crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_parser/src/parser/expr/ops.rs, crates/swc_ecma_parser/src/parser/ident.rs, crates/swc_ecma_parser/src/parser/jsx.rs, crates/swc_ecma_parser/src/parser/macros.rs, crates/swc_ecma_parser/src/parser/mod.rs, crates/swc_ecma_parser/src/parser/object.rs, crates/swc_ecma_parser/src/parser/pat.rs, crates/swc_ecma_parser/src/parser/stmt.rs, crates/swc_ecma_parser/src/parser/stmt/module_item.rs, crates/swc_ecma_parser/src/parser/typescript.rs, crates/swc_ecma_parser/tests/jsx/errors/adjacent-tags/input.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/6a96389a0cce57e9.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/94535dc25ef762ee.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/e7087ec92f0f3c44.js.swc-stderr, xtask/src/bench.rs, xtask/src/util/mod.rs
I could optimize macros used enormous amount of times.
=> perf(es/parser): Optimize macros

crates/swc_ecma_parser/src/lexer/mod.rs
`c.is_ascii_uppercase()` was expensive than expected.
=> perf(es/parser): Add a check before performing numeric operations

.github/workflows/publish-core.yml
I'm going to create a TypeScript-strip-only Wasm publish pipeline so it can be used by node.js.
- https://github.com/marco-ippolito/node/pull/2
=> chore: Improve Wasm publish pipeline

.github/workflows/publish-core.yml, bindings/Cargo.lock, bindings/Cargo.toml, bindings/binding_core_node/build.rs, bindings/binding_minifier_node/src/minify.rs, bindings/binding_minifier_wasm/scripts/build.sh, bindings/binding_minifier_wasm/scripts/build_nodejs_release.sh, bindings/binding_minifier_wasm/scripts/build_web_release.sh, bindings/binding_minifier_wasm/scripts/test.sh, bindings/binding_typescript_wasm/Cargo.toml, bindings/binding_typescript_wasm/package.json, bindings/binding_typescript_wasm/src/lib.rs, scripts/publish.sh, yarn.lock
This PR adds a Wasm binding which is only capable of stripping TypeScript types.
- https://github.com/marco-ippolito/node/pull/2
=> feat(binding): Create Wasm package for stripping only TypeScript

bindings/binding_typescript_wasm/src/lib.rs, crates/swc_ecma_transforms_typescript/src/lib.rs, crates/swc_ecma_transforms_typescript/src/strip_type.rs
The Node.js team wants a Wasm package that only implements type annotation proposals. So we need to refactor our TypeScript transform to allow it.
- https://github.com/nodejs/loaders/issues/208#issuecomment-2205063110
=> refactor(es/typescript): Extract type annotation proposal out

crates/swc_ecma_loader/src/resolvers/node.rs
=> fix(es/loader): Exclude `.json` from default extension list

bindings/binding_typescript_wasm/Cargo.toml, bindings/binding_typescript_wasm/__tests__/__snapshots__/transform.js.snap, bindings/binding_typescript_wasm/__tests__/transform.js, bindings/binding_typescript_wasm/package.json, bindings/binding_typescript_wasm/src/lib.rs, yarn.lock
This PR adds `strip-only`/`transform` mode to `@swc/wasm-typescript`.
- Both mode errors on decorator usages.
- In `strip-only` mode, `enum` and TypeScript parameter properties are treated as an invalid syntax.
- In `transform` mode, those are transpiled.
=> feat(bindings/ts): Add transform/strip-only mode

.github/workflows/publish-core.yml, bindings/binding_core_wasm/scripts/build.sh, bindings/binding_core_wasm/scripts/test.sh, bindings/binding_typescript_wasm/Cargo.toml, bindings/binding_typescript_wasm/scripts/build.sh, bindings/binding_typescript_wasm/scripts/patch.mjs
Requested by https://github.com/marco-ippolito/node/pull/2/files#r1665267733
=> refactor(bindings/ts): Inline Wasm file into `wasm.js`

crates/swc_fast_ts_strip/src/lib.rs, crates/swc_fast_ts_strip/tests/fixture/this-param.js, crates/swc_fast_ts_strip/tests/fixture/this-param.ts, crates/swc_fast_ts_strip/tests/fixture/type-import.js, crates/swc_fast_ts_strip/tests/fixture/type-import.ts
=> feat(es/typescript): Improve fast TS stripper

crates/swc_ecma_parser/src/parser/input.rs, crates/swc_fast_ts_strip/src/lib.rs, crates/swc_fast_ts_strip/tests/fixture/tricky.js, crates/swc_fast_ts_strip/tests/fixture/tricky.ts
We can leverage lexer information to handle tricky cases.
=> fix(es/typescript): Fix tricky cases in TS fast strip

Cargo.lock, Cargo.toml
This bumps unicode support to unicode v15.1.0
The crate version is unpinned by removing the katana middle dot problem occured in unicode v15.1.0
See https://github.com/oxc-project/unicode-id-start/pull/3
relates https://github.com/swc-project/swc/issues/8940
=> chore(es): Bump `unicode-id-start` to `v1.2.0`

crates/swc/tests/fixture/issues-3xxx/3417/1/output/index.ts, crates/swc_ecma_compat_es2015/src/block_scoping/mod.rs, crates/swc_ecma_transforms_compat/tests/for-of/issue-8010/1/exec.js
The original code separately records the usage of variables and checks if there is a closure. Changed to only record variables used in a closure.
I run `UPDATE=1 cargo test -p swc -p swc_ecma_transforms_compat --features concurrent`. I'm not sure if that's enough.
- Closes https://github.com/swc-project/swc/issues/8010
=> fix(es/compat): Consider only the variables used in the closure

Cargo.lock, Cargo.toml, crates/swc_allocator/Cargo.toml, crates/swc_allocator/src/lib.rs
=> feat(allocator): Initialize package

crates/swc_ecma_transforms_optimization/src/simplify/expr/tests.rs, crates/swc_ecma_utils/src/lib.rs
This PR allows `ArrayLit`s to be converted to numbers in the `cast_to_number` function. This allows expressions using arrays to be converted to numbers. See some example expressions below that were previously not able to be computed, but are now able to due to this change.
```js
+[] // 0
+[[]] // 0
+[1] // 1
+[undefined] // 0
+[null] // 0
+[[1]] // 1
+[,] // 0
+[,,] // NaN
```
Regarding the implementation, arrays are converted to strings, and the string is then parsed as a number. So arrays like `[]` and `[undefined]` return `""` which then return `0` when parsed as a string. This is also why arrays with more than one element can't be parsed because e.g. `[1, 2]` returns `"1,2"`. This procedure follows the ECMAScript specification. …
=> feat(es/utils): Support for arrays using `cast_to_number`

bindings/Cargo.toml, bindings/binding_typescript_wasm/scripts/build.sh
Reverts swc-project/swc#9191
I'm reverting because it applies even to `@swc/core`. cc @magic-akari 
Instead, I used an environment variable.
=> perf(bindings): Invert Wasm size shrink

crates/swc_ecma_minifier/src/compress/pure/arrows.rs, crates/swc_ecma_minifier/tests/fixture/issues/9186/1/input.js, crates/swc_ecma_minifier/tests/fixture/issues/9186/1/output.js, crates/swc_ecma_minifier/tests/fixture/issues/9186/2/config.json, crates/swc_ecma_minifier/tests/fixture/issues/9186/2/input.js, crates/swc_ecma_minifier/tests/fixture/issues/9186/2/output.js
Closes https://github.com/swc-project/swc/issues/9186
=> fix(es/minifier): Check `this` in function params

Cargo.lock, crates/swc_allocator/Cargo.toml, crates/swc_allocator/benches/bench.rs, crates/swc_allocator/src/alloc.rs, crates/swc_allocator/src/boxed/mod.rs, crates/swc_allocator/src/lib.rs, crates/swc_allocator/src/vec/mod.rs, crates/swc_allocator/tests/apis.rs
This is a part of https://github.com/swc-project/swc/pull/9230. I profiled the performance, and `thread_local` took too long to get the address of the thread-local variable. So, I inlined the reference into the allocator.
```
common/allocator/alloc/std/1000000
time:   [4.9478 ms 4.9653 ms 4.9922 ms]
Found 17 outliers among 100 measurements (17.00%)
4 (4.00%) high mild
13 (13.00%) high severe
common/allocator/alloc/no-scope/1000000
time:   [5.4821 ms 5.4938 ms 5.5068 ms]
Found 17 outliers among 100 measurements (17.00%)
2 (2.00%) high mild
15 (15.00%) high severe
common/allocator/alloc/scoped/1000000
time:   [3.1401 ms 3.1456 ms 3.1518 ms]
Found 12 outliers among 100 measurements (12.00%)
3 (3.00%) high mild
9 (9.00%) high severe …
```
=> refactor(allocator): Use `&` instead of a thread-local

Cargo.lock, crates/swc_ecma_transforms_typescript/src/config.rs, crates/swc_fast_ts_strip/Cargo.toml, crates/swc_fast_ts_strip/benches/assets.rs, crates/swc_fast_ts_strip/src/lib.rs, crates/swc_fast_ts_strip/tests/fixture.rs
=> feat(es/typescript): Add `transform` mode back to fast TS strip

Cargo.lock, README.md, clippy.toml, crates/swc_allocator/Cargo.toml, crates/swc_allocator/src/alloc.rs
The performance is much better without it.
=> perf(allocator): Drop `scoped_tls`

.vscode/settings.json, crates/swc_allocator/src/alloc.rs, crates/swc_allocator/src/boxed/mod.rs, crates/swc_allocator/src/lib.rs, crates/swc_allocator/src/vec/mod.rs
In the default mode, `Box<T>` and `Vec<T>` should work just like them from std.
- This PR is part of https://github.com/swc-project/swc/pull/9230
=> feat(allocator): Implement `default` mode

crates/swc_allocator/Cargo.toml, crates/swc_fast_ts_strip/src/lib.rs, crates/swc_fast_ts_strip/tests/fixture.rs, crates/swc_fast_ts_strip/tests/fixture/mixed/output.transform.js, crates/swc_fast_ts_strip/tests/fixture/nonnull-assertion/output.transform.js, crates/swc_fast_ts_strip/tests/fixture/output.transform.js, crates/swc_fast_ts_strip/tests/fixture/satisfies/output.transform.js, crates/swc_fast_ts_strip/tests/fixture/type-alias/output.transform.js, crates/swc_fast_ts_strip/tests/fixture/type-ann/var-decl/output.transform.js, crates/swc_fast_ts_strip/tests/fixture/type-assertions/output.transform.js
=> fix(es/typescript): Fix `transform` mode

crates/swc_allocator/src/alloc.rs, crates/swc_allocator/src/lib.rs, crates/swc_allocator/tests/escape.rs
=> fix(allocator): Remove wrong assertions and add tests

crates/swc_allocator/benches/bench.rs, crates/swc_allocator/src/alloc.rs, crates/swc_allocator/src/vec/mod.rs, crates/swc_allocator/tests/apis.rs, crates/swc_allocator/tests/escape.rs
- https://github.com/swc-project/swc/issues/9253
=> refactor(allocator): Use RAII guard instead of `scope`

crates/swc_ecma_minifier/src/compress/pure/strings.rs, crates/swc_ecma_minifier/tests/exec.rs
convert `raw` value  to `cooked` for creating new Tpl element.
<del>
while optimizing nested tpl, after concatenating some cooked strs to assemble a new tpl element,
the `raw` of the tpl should be escaped cooked string value.
</del>
None
https://github.com/swc-project/swc/issues/9184
=> fix(es/minifier): Collect raw str values for new Tpl element

.github/workflows/publish-npm-package.yml, bindings/binding_typescript_wasm/scripts/esm.mjs, bindings/binding_typescript_wasm/scripts/esm.sh, bindings/binding_typescript_wasm/scripts/patch.mjs, bindings/binding_typescript_wasm/src/wasm-node.js
=> feat(es/typescript): Add esm build for fast ts strip

packages/types/index.ts
Add missing mangle options to be consistent with the SWC documentation:
https://swc.rs/docs/configuration/minification#jscminifymangle
=> fix(bindings/types): Add missing mangle options

.github/workflows/CI.yml, Cargo.lock, bindings/Cargo.toml, bindings/binding_typescript_wasm/Cargo.toml, bindings/binding_typescript_wasm/src/lib.rs, crates/swc_fast_ts_strip/Cargo.toml, crates/swc_fast_ts_strip/src/lib.rs
=> fix(es/typescript): Fix typings

.changeset/chilly-jobs-worry.md, crates/swc_html_visit/src/generated.rs, crates/swc_xml_visit/src/generated.rs, tools/generate-code/src/generators/visitor.rs
=> perf(visit): Add `#[inline]`

.changeset/unlucky-planets-laugh.md, .github/workflows/CI.yml, crates/swc_ecma_utils/src/macros.rs
- Closes https://github.com/swc-project/swc/issues/9299
=> fix(es/utils): Use `$crate` for `quote_ident!()`

.changeset/cold-pillows-walk.md, crates/swc_bundler/src/bundler/chunk/merge.rs, crates/swc_bundler/src/bundler/finalize.rs, crates/swc_bundler/src/bundler/load.rs, crates/swc_ecma_transforms_base/src/helpers/mod.rs, crates/swc_ecma_transforms_base/src/perf.rs
- Closes https://github.com/swc-project/swc/issues/9222
=> perf(es/helpers): Use `bool` instead of `AtomicBool`

.changeset/rare-brooms-serve.md, crates/swc_core/src/lib.rs
While upgrading to 0.99.4, we encounter a compile error with the `ecma_preset_env` feature on `swc_core`. Seems that the preset_env_base package is not a dependency of [swc_core](https://github.com/swc-project/swc/blob/95af17ff917a6ec3d1420f6bc089585f89a8cd31/crates/swc_core/Cargo.toml#L336-L387)
[Repro](https://github.com/LingyuCoder/swc-ecma-preset-env-error)
=> fix(swc_core): Remove unused `preset_env`

.changeset/eighty-comics-act.md, crates/swc_ecma_minifier/src/compress/optimize/inline.rs, crates/swc_ecma_minifier/tests/fixture/issues/9263/input.js, crates/swc_ecma_minifier/tests/fixture/issues/9263/output.js, crates/swc_ecma_usage_analyzer/src/analyzer/mod.rs
- Closes https://github.com/swc-project/swc/issues/9263
=> fix(es/minifier): Fix analysis of for-in/of

.changeset/tall-cooks-speak.md, crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/tests/fixture/typescript/class_method/input.js, crates/swc_ecma_codegen/tests/fixture/typescript/class_method/output.js, crates/swc_ecma_codegen/tests/fixture/typescript/class_method/output.min.js, crates/swc_ecma_transforms_typescript/src/strip_type.rs
I'm in the process of upgrading swc and stumbled on this one.
**Description:** Regression in emitting class methods that are optional.
=> fix(es/codegen): Emit question token for class methods

.changeset/polite-tools-lie.md, crates/swc_fast_ts_strip/src/lib.rs, crates/swc_fast_ts_strip/tests/fixture/issue-9355.js, crates/swc_fast_ts_strip/tests/fixture/issue-9355.transform.js, crates/swc_fast_ts_strip/tests/fixture/issue-9355.ts
=> fix(es/typescript): Fix ASI in expression for fast strip

.changeset/large-glasses-move.md, crates/swc_common/src/input.rs, crates/swc_ecma_parser/src/lexer/util.rs
- https://github.com/wooorm/mdxjs-rs/pull/49
=> fix(es/parser): Fix span for unterminated block comments

.changeset/thin-cobras-taste.md, crates/swc_ecma_parser/src/lexer/util.rs, crates/swc_ecma_parser/tests/test262-error-references/fail/025560435ed0b9a6.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/100c329e6dd70e5a.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/1c6ba8177a9624f0.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/65a7e95d594ad7ad.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/766e0153d3f7ec95.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/86308fd40fa95e9d.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/8d64a30d9de151b6.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/ac1ee2739ad30d66.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/d056300d8658429f.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/e2cdddda85e8ffe1.js.swc-stderr
- https://github.com/wooorm/markdown-rs/pull/120
=> fix(es/parser): Make `UnterminatedBlockComment` stick to the EOF

.changeset/wicked-lizards-smoke.md, crates/swc/tests/tsc-references/amdImportNotAsPrimaryExpression.1.normal.js, crates/swc/tests/tsc-references/amdImportNotAsPrimaryExpression.2.minified.js, crates/swc/tests/tsc-references/commonJSImportNotAsPrimaryExpression.1.normal.js, crates/swc/tests/tsc-references/commonJSImportNotAsPrimaryExpression.2.minified.js, crates/swc/tests/tsc-references/importStatementsInterfaces.1.normal.js, crates/swc/tests/tsc-references/importStatementsInterfaces.2.minified.js, crates/swc_ecma_transforms_typescript/src/strip_import_export.rs, crates/swc_ecma_transforms_typescript/tests/__swc_snapshots__/tests/strip.rs/deno_12395_import_equals_2.js, crates/swc_ecma_transforms_typescript/tests/fixture/issue-9368/input.ts, crates/swc_ecma_transforms_typescript/tests/fixture/issue-9368/output.js
=> fix(es/typescript): Analyze import chain

bindings/binding_typescript_wasm/README.md
`tyescript` ->  `typescript` !
Found in <https://github.com/nodejs/amaro/tree/main/lib/swc>, <https://www.npmjs.com/package/@swc/wasm-typescript>, ...
None
None
=> chore: Fix Typo

.changeset/modern-bears-flash.md, crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/tests/fixture/typescript/class_abstract/input.ts, crates/swc_ecma_codegen/tests/fixture/typescript/class_abstract/output.ts
=> fix(es/codegen): Print the missing `abstract` in class expression

.changeset/three-ways-smell.md, crates/swc_common/Cargo.toml
[EqIgnoreSpan](https://github.com/swc-project/swc/blob/ec03d1ec54fc7f3acfddbb5061c2f0c75a574e91/crates/swc_common/src/eq.rs#L4) uses the nightly_only macro, which was introduced in version 0.1.7 of swc_allocator. When building with the older version of the allocator, the following error results:
error[E0432]: unresolved import `swc_allocator::nightly_only`
--> /home/user/.cargo/registry/.../swc_common-0.36.3/src/eq.rs:4:5
|
4 | use swc_allocator::nightly_only;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `nightly_only` in the root
=> fix(common): Require newer version of allocator

.changeset/slow-forks-brake.md, crates/swc_common/src/errors/emitter.rs
Moving the import under the tty-emitter feature fixes the following:
warning: unused import: `IsTerminal`
--> /home/user/swc/crates/swc_common/src/errors/emitter.rs:15:28
|
15 |     io::{self, prelude::*, IsTerminal},
|                            ^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
=> fix(common): Remove unused import

crates/swc_ecma_minifier/tests/exec.rs, crates/swc_ecma_minifier/tests/fixture/issues/9356/input.js, crates/swc_ecma_transforms_optimization/src/simplify/branch/mod.rs, crates/swc_ecma_transforms_optimization/src/simplify/branch/tests.rs
- Closes https://github.com/swc-project/swc/issues/9356
=> fix(es/minifier): Preserve function length

.changeset/wet-pets-check.md, crates/swc/tests/fixture/issues-9xxx/9394/input/.swcrc, crates/swc/tests/fixture/issues-9xxx/9394/input/index.tsx, crates/swc/tests/fixture/issues-9xxx/9394/output/index.tsx, crates/swc_ecma_utils/src/constructor.rs
=> fix(es/typescript): Enable Injector to process JSX

.changeset/soft-plants-prove.md, crates/swc_fast_ts_strip/src/lib.rs, crates/swc_fast_ts_strip/tests/tsc/defaultExportWithOverloads01.strip.broken, crates/swc_fast_ts_strip/tests/tsc/defaultExportWithOverloads01.strip.js
=> fix(es/typescript): Strip exported default overload function declaration

LICENSE, bindings/binding_core_node/LICENSE, bindings/binding_core_wasm/LICENSE, bindings/binding_minifier_node/LICENSE, bindings/binding_minifier_wasm/LICENSE, bindings/binding_typescript_wasm/LICENSE, packages/helpers/LICENSE, packages/types/LICENSE
This change adds mention of SWC in the license otherwise it would be anonymous (and odd 😄 )
=> chore: Mention swc in the license

.changeset/ninety-tips-heal.md, crates/swc_html/Cargo.toml, crates/swc_html_minifier/Cargo.toml, crates/swc_html_minifier/src/lib.rs, crates/swc_html_minifier/src/option.rs
Support use a custom css minifier when minimizing html, add `feature = "custom-css-minifier"` to enable this and remove the dependencies of `swc_css_*`.
And `feature = "default-css-minifier"` keep the original behavior, using `swc_css` when minimizing html, and this is the default feature.
(Rspack is now using LightningCSS to minimize CSS files, but the CSS insides html is still using `swc_css` (which called by `swc_html_minifier`) to do the minify, so we want to also use LightningCSS to minify the CSS insides html to keep the consistent with CSS files)
=> feat(html/minifier): Support using custom css minifier

bindings/binding_typescript_wasm/scripts/patch.mjs
- https://github.com/rustwasm/wasm-bindgen/pull/4015
=> chore(es/typescript): Remove the workaround for wasm-bindgen

.changeset/grumpy-cars-move.md, crates/swc/tests/fixture/issues-4xxx/4208/1/output/index.ts, crates/swc/tests/fixture/issues-4xxx/4224/1/output/index.js, crates/swc/tests/fixture/issues-4xxx/4224/2/output/index.js, crates/swc_ecma_compat_es2015/src/arrow.rs, crates/swc_ecma_compat_es2017/src/async_to_generator.rs, crates/swc_ecma_transforms_compat/tests/__swc_snapshots__/tests/es2017_async_to_generator.rs/issue_8452.js, crates/swc_ecma_transforms_compat/tests/__swc_snapshots__/tests/es2017_async_to_generator.rs/issue_9432.js, crates/swc_ecma_transforms_compat/tests/es2017_async_to_generator.rs
- Closes https://github.com/swc-project/swc/issues/8452
- Closes https://github.com/swc-project/swc/issues/9432
=> fix(es/compat): Init this in sub class constructor for async

.changeset/cyan-rules-wink.md, crates/swc/tests/tsc-references/for-of51.1.normal.js, crates/swc/tests/tsc-references/for-of51.2.minified.js, crates/swc_ecma_parser/src/parser/class_and_fn.rs, crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_parser/src/parser/object.rs, crates/swc_ecma_parser/src/parser/pat.rs, crates/swc_ecma_parser/src/parser/stmt.rs, crates/swc_ecma_parser/src/parser/stmt/module_item.rs, crates/swc_ecma_parser/src/parser/typescript.rs, crates/swc_ecma_parser/tests/errors/issue-8269/input.js, crates/swc_ecma_parser/tests/errors/issue-8269/input.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/0abefbc80bf651fa.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/39551fb86dcd3b29.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/49624f905645b7d0.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/ac4ee5fb095faad0.js.swc-stderr, crates/swc_ecma_parser/tests/test262-error-references/fail/b02b296bd115b9b9.js.swc-stderr, crates/swc_ecma_parser/tests/typescript-errors/issue-1391/case2/input.ts.swc-stderr, crates/swc_ecma_parser/tests/typescript-errors/let/index.ts.swc-stderr, crates/swc_ecma_parser/tests/typescript.rs
- Closes https://github.com/swc-project/swc/issues/8269
=> feat(es/parser): Disallow `let let`

.changeset/bright-olives-sell.md, crates/swc_ecma_codegen/Cargo.toml
`swc_ecma_codegen` uses `swc_allocator::collections` modules:
https://github.com/swc-project/swc/blob/f500dd4530a1e214d787151689ef9ddb64fb7510/crates/swc_ecma_codegen/src/text_writer/basic_impl.rs#L3
https://github.com/swc-project/swc/blob/f500dd4530a1e214d787151689ef9ddb64fb7510/crates/swc_ecma_codegen/tests/sourcemap.rs#L5
`collections` module was added to `swc_allocator` in 0.1.8. However, `swc_ecma_codegen` still says that the minimum required version of `swc_allocator` is 0.1.7:
https://github.com/swc-project/swc/blob/f500dd4530a1e214d787151689ef9ddb64fb7510/crates/swc_ecma_codegen/Cargo.toml#L27
This can cause a compile error when someone has a lockfile that pins `swc_allocator` 0.1.7, which is supposed to work with `swc_ecma_codegen` according to the manifest, but …
=> chore(es/codegen): Bump minimum required swc_allocator version to 0.1.8

.changeset/nasty-ligers-reflect.md, crates/swc/tests/fixture/issues-9xxx/9429/input/.swcrc, crates/swc/tests/fixture/issues-9xxx/9429/input/index.ts, crates/swc/tests/fixture/issues-9xxx/9429/input/test.ts, crates/swc/tests/fixture/issues-9xxx/9429/output/index.ts, crates/swc/tests/fixture/issues-9xxx/9429/output/test.ts, crates/swc_ecma_transforms_proposal/src/decorators/legacy/mod.rs
**Related issue :**
- Closes: #9429
=> fix(es/decorator): Add support for private access expressions in legacy decorators

.changeset/warm-lies-work.md, crates/swc/tests/fixture/issues-5xxx/5068/1/output/index.js, crates/swc_ecma_minifier/tests/mangle/issue-9542/input.js, crates/swc_ecma_minifier/tests/mangle/issue-9542/output.js, crates/swc_ecma_transforms_base/src/rename/mod.rs
=> fix(es/minifier): Avoid decl name when mangle with eval

packages/core/__tests__/issue-9520.mjs
=> test(es): Add tests for arm64 windows

.changeset/weak-papayas-deliver.md, crates/swc_cli_impl/src/commands/compile.rs, crates/swc_cli_impl/tests/issues.rs
`get_files_list` does not check if a path with the `extensions` is really a file.
- Closes https://github.com/swc-project/swc/issues/9559
=> fix(cli): Exclude non-files from get_files_list

.changeset/four-tips-impress.md, crates/ast_node/src/lib.rs, crates/swc_atoms/Cargo.toml, crates/swc_common/Cargo.toml, crates/swc_common/src/plugin/serialized.rs, crates/swc_css_ast/Cargo.toml, crates/swc_css_ast/src/at_rule.rs, crates/swc_css_ast/src/selector.rs, crates/swc_css_ast/src/token.rs, crates/swc_css_ast/src/value.rs, crates/swc_ecma_ast/Cargo.toml, crates/swc_ecma_ast/src/expr.rs, crates/swc_ecma_ast/src/ident.rs, crates/swc_html_ast/Cargo.toml, crates/swc_html_ast/src/base.rs, crates/swc_html_ast/src/token.rs, crates/swc_plugin_proxy/Cargo.toml, crates/swc_plugin_proxy/src/memory_interop/read_returned_result_from_host.rs
1. Disable rkyv strict feature, it is useless in swc.
2. Archived_root will panic if the wasm plugin ast binary not match core ast, so use safe api to avoid panic when mismatch. Implementation reference: https://github.com/rkyv/rkyv/blob/v0.7.43/examples/json/src/main.rs#L57-L76
No
=> fix(plugin): Don't panic when ast byte not match

.github/workflows/publish.yml, Cargo.lock, tools/swc-releaser/Cargo.toml, tools/swc-releaser/src/main.rs
We now have bump command inline.
=> chore: Drop dependency on `cargo-mono`

.changeset/tough-cooks-stare.md, crates/swc_common/tests/attr_interop.rs, crates/swc_ecma_ast/src/expr.rs, crates/swc_ecma_ast/src/ident.rs, crates/swc_html_ast/src/base.rs, crates/swc_html_ast/src/token.rs
1. all struct that support rkyv add `archive(check_bytes)`
2. all recursive struct that support rkyv add check_bytes bound
this PR will fix the error reported in https://github.com/swc-project/swc/pull/9562
No
=> fix(ast): Add `archive(check_bytes)` to all relevant AST types

.changeset/gentle-cycles-repair.md, Cargo.lock, crates/swc/tests/fixture/sourcemap/issue-9567/input/.swcrc, crates/swc/tests/fixture/sourcemap/issue-9567/input/index.js, crates/swc/tests/fixture/sourcemap/issue-9567/output/index.js, crates/swc/tests/fixture/sourcemap/issue-9567/output/index.map, crates/swc_ecma_codegen/Cargo.toml, crates/swc_ecma_codegen/src/lib.rs
1. split quasi by '\n' 
2. add the mapping between original string and generated string one by one.
closes https://github.com/swc-project/swc/issues/9567
=> fix(es/codegen): Fix wrong sourcemap when there are new lines in tpl

.changeset/shy-eagles-shake.md, crates/swc/tests/fixture/issues-9xxx/9579/input/.swcrc, crates/swc/tests/fixture/issues-9xxx/9579/input/index.js, crates/swc/tests/fixture/issues-9xxx/9579/output/index.js, crates/swc_ecma_compat_es2015/src/block_scoping/mod.rs
- Closes: #9579 
- https://github.com/swc-project/swc/issues/9161#issuecomment-2211641985
=> fix(es/compat): Skip `getter` and `setter` as FlowHelper `function` do

.changeset/neat-ties-smoke.md, crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_codegen/src/tests.rs
=> fix(es/codegen): Emit space after div if rhs has leading comment

.changeset/lazy-ladybugs-jump.md, crates/swc_ecma_utils/src/lib.rs
Adds support for `-` in `cast_to_number`. Before it only worked if `arg` is `Infinity`. Now it uses a recursive call on `arg` so it works for expressions like `-5`, `-[]` etc.
This change is important because negative number literals (e.g. `-5`) are a `UnaryExpr` with `op`=`-` & `arg`=`5`, unless you apply `expr_simplifier` pass or something else that uses it.
=> feat(es/minifier): Support unary negate in `cast_to_number`

.github/workflows/CI.yml
Running miri for `swc_ecma_codegen` and `swc_ecma_minifier` is too slow.
Miri on `swc_ecma_codegen` consumes up to 4 hours, and miri on `swc_ecma_minifier` consumes up to 6 hours, which exceeded github's 6 hour limit and makes ci bound to error.
Since they do not introduce too much unsafe code, I think we'd better remove the miri tests for them or run partial tests in a reasonable time.
=> chore(ci): Remove miri ci for `swc_ecma_codegen` and `swc_ecma_minifier`

CONTRIBUTING.md
Requested from https://github.com/swc-project/swc/pull/9666#issuecomment-2428091630
=> doc(contributing): Document changeset

packages/core/src/Visitor.ts, packages/types/index.ts
As per PR #8955
> TsPropertySignature can not have params, type params, or an initializer.
This PR clean up these fields from ts definition and visitor
=> fix(bindings/node): Add `VisitTsPropertySignature`

.changeset/fifty-goats-beg.md, crates/swc_ecma_parser/src/lexer/state.rs, crates/swc_ecma_parser/src/parser/input.rs, crates/swc_ecma_parser/src/parser/mod.rs, crates/swc_ecma_parser/src/parser/tests.rs
In Deno I'm now parsing stuff as a program more often because I sometimes now need to discover if something is a script or es module by looking at the contents. A problem is that the module errors are discarded when parsing as a script, but I still might need them later if I discover the program the program should be treated as an ES module.
Adds a new method to the `Tokens` trait.
=> feat(es/parser): Ability to get script's potential module errors

.changeset/silent-cows-brake.md, crates/swc/src/config/mod.rs, crates/swc_common/src/plugin/metadata.rs
Cache `current_dir()` system calls. Those are needless because we already cache `current_dir` in some places so it will break if the user changes cwd anyway.
- https://github.com/swc-project/swc/issues/9601
=> perf(es): Cache `current_dir()` system calls

.changeset/quick-actors-do.md, crates/swc/tests/exec/issues-9xxx/9110/.swcrc, crates/swc/tests/exec/issues-9xxx/9110/1/exec.js, crates/swc_ecma_compat_es2015/src/generator.rs
closes https://github.com/swc-project/swc/issues/9110
=> fix(es/generator): Fix code generation for `break` in nested while

.changeset/poor-tools-arrive.md, crates/swc/src/config/mod.rs, crates/swc/tests/error_msg.rs, crates/swc/tests/tsc.rs
This is a footgun for users of `swc` crate. So I changed the default value of `jsc.experimental.disableAllLints` to `true`.
=> perf(es/lints): Disable lints by default

.changeset/fluffy-eyes-hope.md, crates/swc/tests/fixture/issues-9xxx/9685/input/index.tsx, crates/swc/tests/fixture/issues-9xxx/9685/output/index.tsx, crates/swc_ecma_transforms_base/src/resolver/mod.rs, crates/swc_ecma_transforms_base/tests/fixture.rs, crates/swc_ecma_transforms_base/tests/resolver/issues/2854/1/output.js, crates/swc_ecma_transforms_base/tests/ts-resolver/issue-9685/1/input.tsx, crates/swc_ecma_transforms_base/tests/ts-resolver/issue-9685/1/output.tsx
=> fix(es/resolver): Skip resolving lowercase `JSXIdentifiers`

.changeset/shiny-bears-thank.md, crates/swc/Cargo.toml, crates/swc/src/plugin.rs
This can cause a problem for Wasm plugin runtimes.
=> feat(es/plugin): Introduce `manual-tokio-runtmie` to `swc` crate

.changeset/swift-hairs-bow.md, crates/swc_fast_ts_strip/src/lib.rs, crates/swc_fast_ts_strip/tests/fixture/issue-9698.js, crates/swc_fast_ts_strip/tests/fixture/issue-9698.transform.js, crates/swc_fast_ts_strip/tests/fixture/issue-9698.ts
=> fix(es/typescript): Handle multiline type parameters in async arrow functions

.changeset/neat-cheetahs-suffer.md, crates/swc_fast_ts_strip/src/lib.rs, crates/swc_fast_ts_strip/tests/fixture/issue-9681.js, crates/swc_fast_ts_strip/tests/fixture/issue-9681.transform.js, crates/swc_fast_ts_strip/tests/fixture/issue-9681.ts
=> fix(es/typescript): Handle ASI hazards in fast type strip

.changeset/witty-bears-attend.md, crates/swc/src/lib.rs, crates/swc_typescript/src/fast_dts/mod.rs, crates/swc_typescript/tests/fast_dts_deno.rs
In https://github.com/denoland/deno_graph/commits/main/src/fast_check/transform_dts.rs:
From https://github.com/denoland/deno_graph/commit/7f38d56de34f9a4ef7542db69db4a34157893dc3 to https://github.com/denoland/deno_graph/commit/258186c4296a933a068f3df53aff1118928e4ccc
PR list:
I will port the tests if I have spare time.
=> feat(typescript): Port deno `isolatedDeclarations` updates

.changeset/lemon-zebras-sort.md, crates/swc/src/config/mod.rs, crates/swc/src/lib.rs, crates/swc/tests/fixture/issues-7xxx/7602/input/.swcrc, crates/swc/tests/fixture/issues-7xxx/7602/input/index.js, crates/swc/tests/fixture/issues-7xxx/7602/output/index.js, crates/swc/tests/ts-isolated-declaration/oxc/output/function-overloads.d.ts, crates/swc_ecma_codegen/src/lib.rs, packages/types/index.ts, packages/types/package.json
- Closes https://github.com/swc-project/swc/issues/7602
=> feat(es/codegen): Implement proper `inline_script` support

.changeset/calm-crabs-lie.md, crates/swc_common/src/cache.rs, crates/swc_common/src/lib.rs, crates/swc_common/src/source_map.rs, crates/swc_common/src/syntax_pos.rs, crates/swc_error_reporters/src/lib.rs, crates/swc_estree_compat/src/swcify/ctx.rs
This reverts commit 772f023fd2f8bbcb336b0561a81621f0f1163622.
- Reverts https://github.com/swc-project/swc/pull/9717
=> perf(es/plugin): Make `analyze_source_file` lazy, again

.changeset/sixty-walls-hang.md, crates/swc_cli_impl/src/commands/plugin.rs
As per https://doc.rust-lang.org/cargo/reference/config.html we should be generating a `.cargo/config.toml` instead of `.cargo/config` when creating a new plugin
Motivation - console warnings 😆 
Technically this means users **must** have a toolchain > 1.38 (released september, 2019 - so five years ago). 
Given that:
- the [public documentation for swc plugins](https://swc.rs/docs/plugin/ecmascript/getting-started#install-rust) link directly to the latest version of the rust toolchain (currently 1.81)
- 1.38 was > **five years ago** 
- This only impacts **new** usages of `swc plugin new ..`
- README.md specifies that the `swc-project/swc` MSRV is 1.73 anyways - whilst that doesn't **specifically** refer to **generated** code, it shows the intent of the …
=> fix(es/plugin): Migrate `swc plugin new` to use `.cargo/config.toml`

packages/types/assumptions.ts, packages/types/index.ts, packages/types/package.json
- Closes https://github.com/swc-project/swc/issues/9743
=> doc(types): Document `Assumptions` API

.changeset/little-scissors-join.md, crates/swc_ecma_codegen/src/jsx.rs, crates/swc_ecma_codegen/tests/fixture.rs, crates/swc_ecma_codegen/tests/fixture/issue-9758/input.jsx, crates/swc_ecma_codegen/tests/fixture/issue-9758/output.jsx, crates/swc_ecma_codegen/tests/fixture/issue-9758/output.min.jsx
=> fix(es/codegen): Use raw value for emitting JSX text

.changeset/modern-carpets-attend.md, crates/swc/tests/fixture/issues-9xxx/9673/input/.swcrc, crates/swc/tests/fixture/issues-9xxx/9673/input/1.js, crates/swc/tests/fixture/issues-9xxx/9673/output/1.js, crates/swc_ecma_transforms_base/src/helpers/mod.rs
- Closes https://github.com/swc-project/swc/issues/9673
=> fix(es/compat): Fix marker for inlined helpers

.changeset/new-apricots-exercise.md, crates/swc/src/plugin.rs
Currently when wasm plugin is not compatible with swc version it will panic which cause it hard to report useful error info from caller except use catch_unwind.
change the behavior to not panic and let the user to decide error handling 
No
=> fix: don't panic when wasm bytecheck faild

bindings/binding_typescript_wasm/__tests__/__snapshots__/transform.js.snap, bindings/binding_typescript_wasm/__tests__/transform.js, bindings/binding_typescript_wasm/src/lib.rs
=> fix: Remove `Caused by: 'failed to parse'` from TS blank space

.changeset/gold-shoes-cross.md, crates/swc_ecma_minifier/src/compress/optimize/conditionals.rs, crates/swc_ecma_minifier/tests/fixture/issues/framer-motion/1/input.js, crates/swc_ecma_minifier/tests/fixture/issues/framer-motion/1/output.js
Next.js 15 seems to minify parts of `framer-motion`'s code in an invalid way, changing the meaning. The original function modifies the single `definition` variable as it changes meaning (see `input.js`):
- if `definition` is a function, it calls it and saves the return value as `definition`
- if `definition` is a string, it resolves animation variant based on value as name and saves the variant as `definition`
- if `definition` is again a function, it calls it again and saves the return value as `definition` again
However, `swc` seems to be not noticing that `definition` may be mutated between the calls and collapses all `if`s into one:
```
// `resolveVariantFromProps` in framer-motion
// https://github.com/motiondivision/motion/blob/ecd97f7dce8954be300aa73ab6a96208437941c …
```
=> fix(es/minifier): Fix minification of `framer-motion` by checking `cons.termniates()`

.changeset/loud-bottles-teach.md, crates/swc_atoms/src/fast.rs, crates/swc_atoms/src/lib.rs, crates/swc_ecma_ast/src/ident.rs, crates/swc_ecma_ast/src/lib.rs, crates/swc_ecma_transforms_optimization/src/simplify/dce/mod.rs, crates/swc_ecma_utils/src/ident.rs
**Description**:
`FastJsWord` and `FastId` implement `Copy` and do not need to be cloned or dropped, unlike `JsWord` or `Id`.
Of course, they are inherently unsafe. But I found that I could use it for the minifier.
- Extracted from #9813
=> perf(es/minifier): Introduce `FastJsWord` and `FastId` in `swc_atoms`

.github/workflows/CI.yml
It may work with custom runners, but I don't think we can afford it.
=> chore(ci): Disable `miri` for `swc` as it fails with OOM

Cargo.lock, crates/swc_ecma_lints/Cargo.toml, crates/swc_ecma_lints/benches/all.rs
The lints are causing perf issues for turbopack.
=> perf(es/lints): Configure a benchmark for ES lints

.changeset/red-coats-melt.md, Cargo.lock, crates/swc_ecma_lints/Cargo.toml, crates/swc_ecma_lints/src/rule.rs, crates/swc_ecma_lints/src/rules/const_assign.rs, crates/swc_ecma_lints/src/rules/no_dupe_args.rs, crates/swc_ecma_utils/Cargo.toml, crates/swc_ecma_utils/src/parallel.rs, crates/swc_parallel/src/lib.rs
This PR makes ES linter much more parallel using `chili`. 
- Follow-up of https://github.com/swc-project/swc/pull/9840
- Follow-up of https://github.com/swc-project/swc/pull/9838
=> perf(es/lints): Make lint rules parallel

.changeset/poor-needles-drop.md, crates/swc_parallel/src/lib.rs
=> doc(swc_parallel): Document safety

.changeset/forty-maps-smoke.md, crates/swc_ecma_minifier/src/compress/optimize/sequences.rs
In https://github.com/chenjiahan/rspack-swc-minify-test:
Rspack + SWC minify: 15.89 s
Rspack + esbuild minify: 1.74 s
This is caused by `merge_sequences_in_exprs` which tries to merge every pair of exprs with time complexity of O(n^2). In the given example, a vec of 5003 exprs (react component declarations and other declarations) are passed to this function. 
From the profiling result below we can see `visit_children_with` takes a lot of times, which is called by `IdentUsageFinder` and `idents_used_by` to check whether an ident is used in an ast node. However, in the O(n^2) loops, this part of the result is heavily recalculated.
Example:
```js
// input.js
export function source() {
let c = 0, a = 1;
c += a, a += 5;
let b = c;
console.log(a, b, c);
}
// esbuild/terser output
export …
```
=> perf(es/minifier): Speed up `merge_sequences_in_exprs` by caching computation

crates/swc/tests/tsc-references/accessorsOverrideProperty3.2.minified.js, crates/swc/tests/tsc-references/accessorsOverrideProperty4.2.minified.js, crates/swc/tests/tsc-references/asyncGeneratorParameterEvaluation(target=es2015).2.minified.js, crates/swc/tests/tsc-references/asyncGeneratorParameterEvaluation(target=es2017).2.minified.js, crates/swc/tests/tsc-references/asyncGeneratorParameterEvaluation(target=es2018).2.minified.js, crates/swc/tests/tsc-references/override19.2.minified.js, crates/swc/tests/tsc-references/overrideInterfaceProperty.2.minified.js, crates/swc/tests/tsc-references/thisPropertyOverridesAccessors.2.minified.js, crates/swc_bundler/tests/fixture/deno-9591/output/entry.inlined.ts, crates/swc_bundler/tests/fixture/deno-9591/output/entry.ts, crates/swc_ecma_minifier/tests/fixture/issues/9823/1-class/input.js, crates/swc_ecma_minifier/tests/fixture/issues/9823/1-class/output.js, crates/swc_ecma_minifier/tests/fixture/issues/9823/2-class-extends/input.js, crates/swc_ecma_minifier/tests/fixture/issues/9823/2-class-extends/output.js, crates/swc_ecma_minifier/tests/fixture/issues/9823/3/input.js, crates/swc_ecma_minifier/tests/fixture/issues/9823/3/output.js, crates/swc_ecma_transforms_optimization/src/simplify/dce/mod.rs
- We should check for the super class while dropping class declarations. 
- Add early-check for `null && foo` and `true || foo`.
- Closes https://github.com/swc-project/swc/issues/9823
=> fix(es/minifier): Improve DCE

.github/workflows/publish.yml
We should not create a git tag if we want to publish only nightly.
=> fix(ci/publish): Do not tag stable if `onlyNightly` is on

.changeset/tricky-glasses-call.md, crates/swc_ecma_transforms_base/src/rename/analyzer/scope.rs
`Vec::contains` was causing a time complexity issue for large input files.
=> perf(es/renamer): Use `IndexSet` for rename queue

.changeset/twelve-colts-call.md, crates/swc_typescript/src/fast_dts/class.rs, crates/swc_typescript/src/fast_dts/decl.rs, crates/swc_typescript/src/fast_dts/types.rs, crates/swc_typescript/src/fast_dts/util/ast_ext.rs, crates/swc_typescript/tests/fixture/signature-computed-property-name.snap, crates/swc_typescript/tests/fixture/signature-computed-property-name.ts
I find this missing part when I check https://github.com/swc-project/swc/issues/9859
swc: https://play.swc.rs/?version=1.10.6&code=H4sIAAAAAAAAA0utKMgvKlHIzCtJLUpLTE5VcFSo5lIAgmiltPx8JYXEYoXikqLMvPRYK4W80tyk1CJrqHRSYhGytEYiTIGmFVTMmquWiysVYkFJZUGqgpOCLVVNt%2BYCAA%2Bn8R2%2FAAAA&config=H4sIAAAAAAAAA1WMOQ6AMAwEe14RueYF1DQUPCIKLoI4LNtIQYi%2FY64Iut0Z7W6Fc9BLgMptFq2QZ0HO3Yisk%2FpkBHQllMCRFMrXqpxKecGL7LcATIQcR7Tp8Dk7zRi1kXnwil2t8hsXzwHIvHDA1lP2%2BwE5e0RDqwAAAA%3D%3D
ts playground: https://www.typescriptlang.org/play/?isolatedDeclarations=true&isolatedModules=true#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgQTgG8AoOcuAbQCJ0IJq5MBnOZmKZAcwF0AuOEgCuAWwBGaANxkKNMZiiMWbDtx4AKTAOHi0ASgHtOSLtIC+JEqEiw4MAJ5g8AITgBeYjPI06DJqyM1bVEJKGkKKmp5RX8VY15NYN0oAzjuc2kgA
=> feat(typescript): Check computed property names of ts signatures

.changeset/stale-apricots-dream.md, crates/swc_ecma_minifier/src/lib.rs, crates/swc_ecma_minifier/src/pass/precompress.rs
We can drop constant branches from precompress pass to make the pass after it faster.
=> perf(es/minifier): Make the first run of DCE more efficient

crates/swc_ecma_utils/src/parallel.rs
I was not sure if two create in parallel are faster thana  single create in the original thread at the moment of writing the function, but when I tried single create was faster.
=> perf(es/utils): Optimize `maybe_par_idx_raw`

.changeset/swift-experts-dance.md, crates/swc_ecma_ast/src/ident.rs, crates/swc_ecma_ast/src/lib.rs, crates/swc_ecma_utils/src/ident.rs
`UnsafeAtom` is the correct name of the type.
=> refactor(atoms): Rename `FastAtom` to `UnsafeAtom`

.changeset/curly-poems-dance.md, crates/swc_fast_ts_strip/src/lib.rs, crates/swc_fast_ts_strip/tests/fixture/issue-9878.js, crates/swc_fast_ts_strip/tests/fixture/issue-9878.transform.js, crates/swc_fast_ts_strip/tests/fixture/issue-9878.ts
=> fix(es/ts_strip): Handle ASI hazard in return statement

.changeset/tricky-llamas-collect.md, Cargo.lock, crates/swc_ecma_transforms_testing/Cargo.toml, crates/swc_ecma_transforms_testing/src/lib.rs
This is a regression from https://github.com/swc-project/swc/pull/9150
=> fix(es/testing): Fix sourcemap generation

.changeset/calm-pumpkins-explain.md, crates/swc_typescript/src/fast_dts/class.rs, crates/swc_typescript/src/fast_dts/enum.rs, crates/swc_typescript/src/fast_dts/types.rs, crates/swc_typescript/src/fast_dts/util/ast_ext.rs, crates/swc_typescript/src/fast_dts/visitors/type_usage.rs, crates/swc_typescript/tests/fixture/signature-computed-property-name.snap, crates/swc_typescript/tests/fixture/signature-computed-property-name.ts, crates/swc_typescript/tests/fixture/type-usage.snap, crates/swc_typescript/tests/fixture/type-usage.ts
fixes https://github.com/swc-project/swc/issues/9875
=> fix(typescript): Collect usages in extend clauses of classes and interfaces

.changeset/late-maps-jump.md, crates/swc_ecma_minifier/src/compress/optimize/inline.rs, crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/src/program_data.rs
As the `ProgramData.vars` is re-allocated lots of time, we can reduce `memmove` operations by boxing the `VarUsageInfo`. This is because the hash map would need to allocate, e.g., `1024 * size_of<Box<T>>` instead of `1024 * size_of<VarUsageInfo>`  while incrementing the size of the hash map from 512 to 1024.
```
Benchmarking es/minifier/libs/es/minifier/libs/antd
Benchmarking es/minifier/libs/es/minifier/libs/antd: Warming up for 3.0000 s
Benchmarking es/minifier/libs/es/minifier/libs/antd: Collecting 10 samples in estimated 9.7340 s (20 iterations)
Benchmarking es/minifier/libs/es/minifier/libs/antd: Analyzing
es/minifier/libs/es/minifier/libs/antd
time:   [489.01 ms 490.05 ms 490.97 ms]
change: [-1.5287% -1.2158% -0.9269%] (p = 0.00 < 0.05)
Change within noise …
```
=> perf(es/minifier): Box `VarUsageInfo` of `ProgramData`

.changeset/friendly-crews-breathe.md, crates/swc_ecma_utils/src/parallel.rs
Document that `after_*` is not used for `visit_*_par`
=> doc(es/parallel): Improve document of `Parallel`

.changeset/tall-flowers-remember.md, crates/swc_ecma_minifier/src/util/base54.rs
=> perf(es/minifier): Make character frequency analysis parallel

crates/swc_ecma_minifier/examples/minify-all.rs
I got
```
1970 files
Total size after minification: 46586141
Max duration (per file): 1.861938125s
Total run: Took 2.089914291s
```
This means that one single file is time-consuming and we should optimize for the large files to reduce the total time.
=> chore(es/minifier): Print slow files from `minify-all` example

.changeset/calm-frogs-search.md, crates/swc_ecma_lints/src/rules/const_assign.rs, crates/swc_ecma_lints/src/rules/no_dupe_args.rs, crates/swc_ecma_minifier/src/compress/optimize/util.rs, crates/swc_ecma_minifier/src/compress/pure/mod.rs, crates/swc_ecma_minifier/src/util/base54.rs, crates/swc_ecma_transforms_base/src/rename/ops.rs, crates/swc_ecma_transforms_optimization/src/inline_globals.rs, crates/swc_ecma_transforms_optimization/src/simplify/branch/mod.rs, crates/swc_ecma_transforms_optimization/src/simplify/dce/mod.rs, crates/swc_ecma_transforms_optimization/src/simplify/expr/mod.rs
These methods were missing and it makes the minification of some files needlessly slow.
=> perf(es/minifier): Parallelize handling of class members

.changeset/old-foxes-train.md, crates/swc_ecma_minifier/src/compress/optimize/inline.rs
In `store_var_for_inlining`, we had called `inline_with_multi_replacer` needlessly. This PR fixes it.
=> perf(es/minifier): Do heavy operation only if required

.changeset/six-rats-fetch.md, crates/swc_ecma_usage_analyzer/src/analyzer/mod.rs
This is a simple fix to ensure that we hash the `Id` only once.
=> perf(es/minifier): Cache `var_or_default` calls

.changeset/selfish-coats-shave.md, crates/swc_ecma_usage_analyzer/src/analyzer/mod.rs
Previous PR may decrease the performance if the result of `collect_infects_to` is empty.
- Inverts https://github.com/swc-project/swc/pull/9909
=> perf(es/minifier): Invert cache to be really a cache

.changeset/quick-needles-sing.md, crates/swc_ecma_minifier/src/compress/optimize/inline.rs, crates/swc_ecma_minifier/tests/benches-full/echarts.js, crates/swc_ecma_minifier/tests/benches-full/vue.js, crates/swc_ecma_minifier/tests/fixture/issues/emotion/react/1/output.js, crates/swc_ecma_minifier/tests/fixture/next/36127/2/2/output.js, crates/swc_ecma_minifier/tests/projects/output/react-dom-17.0.2.js
We don't actually store those variables for inlining in the previous code. This PR fixes it by locating the `self.vars.inline_with_multi_replacer(init);` calls very above the storing code.
=> perf(es/minifier): Skip complex inline operations if possible

.changeset/cuddly-rocks-cross.md, crates/swc_ecma_parser/src/parser/stmt.rs, crates/swc_ecma_parser/tests/typescript-errors/issue-1170-1/input.ts.swc-stderr, crates/swc_ecma_parser/tests/typescript-errors/issue-1391/case1/input.ts.swc-stderr, crates/swc_fast_ts_strip/tests/errors/invalid-syntax-1.swc-stderr, crates/swc_fast_ts_strip/tests/errors/invalid-syntax-1.ts
- Closes https://github.com/swc-project/swc/issues/9883
=> fix(es/parser): Remove wrong check about `const` without init

.changeset/shy-apes-listen.md, crates/swc_core/Cargo.toml
- Fix typo in the `ecma_ast_serde` feature
- Add a `ecma_visit_serde` feature
=> fix(swc_core): Fix typo in swc_core feature

Cargo.lock, bindings/Cargo.lock, bindings/Cargo.toml, bindings/binding_typescript_wasm/Cargo.toml, bindings/binding_typescript_wasm/src/lib.rs
- https://github.com/swc-project/swc/issues/9851
=> feat(fast-ts): Support Uint8Array Input

packages/helpers/package.json, packages/helpers/scripts/build.js
1. Expose `module-sync` entry points for Node.js require(esm) compatibility. [^1]
2. Expose `webpack` entry points to piroitize esm entry for webpack-based bundlers, eliminating duplicate dependencies and code bloat. [^2]
[^1]: https://nodejs.org/docs/latest-v22.x/api/modules.html#loading-ecmascript-modules-using-require:~:text=If%20%60%2D%2Dexperimental%2Drequire%2Dmodule%60%20is%20enabled%0A%20%20a.-,let%20CONDITIONS%20%3D%20%5B%22node%22%2C%20%22require%22%2C%20%22module%2Dsync%22%5D,-b.%20Else%2C%20let%20CONDITIONS%20%3D%20%5B%22node%22%2C%20%22require%22%5D%0A5
[^2]: https://webpack.js.org/guides/package-exports/#conditions-preprocessor-and-runtimes
=> feat(es/helpers): Update package exports for module-sync and webpack compatibility

.changeset/young-boats-remain.md, crates/swc_ecma_minifier/src/compress/optimize/unused.rs
- Closes https://github.com/swc-project/swc/issues/9999
=> perf(es/minifier): Do not clone from `take_ident_of_pat_if_unused`

.changeset/proud-pens-exercise.md, crates/swc_ecma_minifier/src/program_data.rs
- Closes https://github.com/swc-project/swc/issues/9998
=> perf(es/minifier): Allocate in once from `mark_property_mutation`

.changeset/proud-adults-roll.md, crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/src/program_data.rs, crates/swc_ecma_usage_analyzer/src/alias/mod.rs, crates/swc_ecma_usage_analyzer/src/analyzer/mod.rs, crates/swc_ecma_usage_analyzer/src/analyzer/storage.rs
In most real-world inputs, many infected identifiers typically mean we can't optimize it anyway. Because of the variable usage analysis result of the infected variable, we can't do any optimization to the original variable in most cases. So this PR stops the infection analyzer at a specific threshold.
- Closes https://github.com/swc-project/swc/issues/10000
=> perf(es/minifier): Limit infection analysis by the entry size

crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/src/program_data.rs, crates/swc_ecma_usage_analyzer/src/analyzer/mod.rs, crates/swc_ecma_usage_analyzer/src/analyzer/storage.rs
Invert #10006 because the analyzer should not give up analyzing the aliases because it uses the aliasing information to modify `VarUsageInfo` of aliases.
=> fix(es/minifier): Revert #10006

.changeset/strange-crabs-argue.md, Cargo.lock, Cargo.toml, crates/swc_atoms/Cargo.toml, crates/swc_atoms/src/lib.rs, crates/swc_common/Cargo.toml, crates/swc_common/src/syntax_pos.rs, crates/swc_common/src/syntax_pos/hygiene.rs, crates/swc_core/Cargo.toml, crates/swc_ecma_ast/Cargo.toml, crates/swc_ecma_ast/src/class.rs, crates/swc_ecma_ast/src/decl.rs, crates/swc_ecma_ast/src/expr.rs, crates/swc_ecma_ast/src/function.rs, crates/swc_ecma_ast/src/ident.rs, crates/swc_ecma_ast/src/jsx.rs, crates/swc_ecma_ast/src/lib.rs, crates/swc_ecma_ast/src/lit.rs, crates/swc_ecma_ast/src/module.rs, crates/swc_ecma_ast/src/module_decl.rs, crates/swc_ecma_ast/src/operators.rs, crates/swc_ecma_ast/src/pat.rs, crates/swc_ecma_ast/src/prop.rs, crates/swc_ecma_ast/src/stmt.rs, crates/swc_ecma_ast/src/typescript.rs
This PR adds `ShrinkToFit` implementations to all ECMAScript AST nodes.
- Closes https://github.com/swc-project/swc/issues/9997
- Depends on https://github.com/dudykr/ddbase/pull/55
- Depends on https://github.com/dudykr/ddbase/pull/56
- Depends on https://github.com/dudykr/ddbase/pull/57
=> feat(es/ast): Add `ShrinkToFit` implementation

.changeset/eight-steaks-yawn.md, crates/hstr/src/dynamic.rs, crates/hstr/src/lib.rs
This would improve performance and reduce allocation.
- Closes https://github.com/swc-project/swc/issues/10030
=> perf(hstr): Use thin arc for hash and length

crates/hstr/src/dynamic.rs
Almost all long strings are likely to differ, so there's no worth interning them. Those are mostly template literals in the case of SWC, but I didn't see any instance of very long text being identical to other instances.
- Closes https://github.com/swc-project/swc/issues/10031
=> perf(hstr): Skip interning if the text is long enough

.changeset/nasty-days-help.md, crates/swc_typescript/src/fast_dts/inferrer.rs, crates/swc_typescript/src/fast_dts/types.rs, crates/swc_typescript/tests/deno_test.rs, crates/swc_typescript/tests/oxc_fixture/as-const.snap
I remember doing that by design, but I forget why. Now let's align it with tsc
=> fix(typescript): Improve type inferring for undefined and null

bindings/binding_typescript_wasm/__tests__/__snapshots__/transform.js.snap, bindings/binding_typescript_wasm/__tests__/transform.js, crates/swc_fast_ts_strip/tests/errors/ts-module.swc-stderr, crates/swc_fast_ts_strip/tests/errors/ts-module.ts
- https://github.com/nodejs/amaro/pull/174
=> test(ts/fast-strip): Add tests for `declare module` error cases

.changeset/chatty-horses-invent.md, crates/hstr/src/dynamic.rs, crates/hstr/src/global_store.rs
- Closes https://github.com/swc-project/swc/issues/10032
=> fix(hstr): Prevent memory leak for global stores

.changeset/shiny-fireants-smile.md, Cargo.lock, crates/swc_allocator/Cargo.toml, crates/swc_allocator/tests/alloction.rs, scripts/bench/list-crates-with-bench.sh
It disturbs moving some types to arena allocator
=> chore(swc_allocator): Remove `nightly` from default feature

packages/types/index.ts, packages/types/package.json
Add TypeScript definition for `transform.verbatimModuleSyntax`.
**Related issue (if exists):** #10078
=> fix(@swc/types): add `transform.verbatimModuleSyntax`

crates/swc/tests/tsc-references/compoundExponentiationAssignmentLHSIsReference.2.minified.js, crates/swc/tests/tsc-references/invalidVoidAssignments.2.minified.js, crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/tests/benches-full/echarts.js, crates/swc_ecma_minifier/tests/benches-full/three.js, crates/swc_ecma_minifier/tests/fixture/next/33265/static/chunks/d6e1aeb5-38a8d7ae57119c23/output.js, crates/swc_ecma_minifier/tests/fixture/next/33265/static/chunks/pages/index-cb36c1bf7f830e3c/output.js, crates/swc_ecma_minifier/tests/fixture/next/react-ace/chunks/8a28b14e.d8fbda268ed281a1/output.js, crates/swc_ecma_minifier/tests/fixture/next/syncfusion/933-e9f9a6bf671b96fc/output.js, crates/swc_ecma_minifier/tests/fixture/next/wrap-contracts/output.js
=> feat(es/minifier): Seq inline into var without init

crates/swc_ecma_lints/src/rule.rs
`Handler` already holds mutex internally, so we don't have to do locking from linter.
=> perf(es/lints): Remove needless locks

.changeset/curly-shirts-remember.md, crates/swc_malloc/Cargo.toml, crates/swc_malloc/src/lib.rs
- `cargo tree --target armv7-unknown-linux-gnueabihf -p swc_malloc -e features`:
```
swc_malloc v1.2.0 (/Users/kdy1/projects/s/minifier/crates/swc_malloc)
├── tikv-jemallocator feature "default"
│   ├── tikv-jemallocator v0.5.4
│   │   ├── libc v0.2.162
│   │   └── tikv-jemalloc-sys v0.5.4+5.3.0-patched
│   │       └── libc v0.2.162
│   │       [build-dependencies]
│   │       └── cc feature "default"
│   │           └── cc v1.2.13
│   │               └── shlex feature "default"
│   │                   ├── shlex v1.3.0
│   │                   └── shlex feature "std"
│   │                       └── shlex v1.3.0
│   └── tikv-jemallocator feature "background_threads_runtime_support"
│       ├── tikv-jemallocator v0.5.4 (*)
│       └── tikv-jemalloc-sys feature …
```
=> fix(swc_malloc): Fix build issue due to malloc, really

.changeset/fifty-grapes-remain.md, crates/swc_ecma_transforms_base/src/resolver/mod.rs
Just use iter_mut().for_each directly.
=> perf(es/resolver): Remove needless allocations

.changeset/brave-fishes-mate.md, bindings/binding_typescript_wasm/__tests__/__snapshots__/transform.js.snap, bindings/binding_typescript_wasm/__tests__/transform.js, crates/swc_fast_ts_strip/src/lib.rs, crates/swc_fast_ts_strip/tests/errors/ts-module.swc-stderr
This PR adds an early return to code paths to make them throw an object on error.
- Closes https://github.com/swc-project/swc/issues/10087
=> fix(ts/fast-strip): Throw object consistently

.changeset/cuddly-spiders-begin.md, crates/swc_ecma_minifier/src/program_data.rs, crates/swc_ecma_minifier/tests/benches-full/jquery.js, crates/swc_ecma_minifier/tests/benches-full/lodash.js, crates/swc_ecma_minifier/tests/exec.rs, crates/swc_ecma_minifier/tests/fixture/next/react-pdf-renderer/output.js
```js
function a() {
if (a.isInit) return;
a.isInit = true;
console.log('run')
}
function b() {
a();
console.log('after');
}
b();
b();
```
was minified as 
```js
function b() {
(function a() {
if (a.isInit) return;
a.isInit = true, console.log('run');
})(), console.log('after');
}
b(), b();
```
Which is wrong because the referential identity of `a` is important.
- Closes https://github.com/swc-project/swc/issues/10095
=> fix(es/minifier): Skip inlining if the referential identity of a function matters

.changeset/wild-roses-taste.md, Cargo.lock, bindings/binding_typescript_wasm/__tests__/__snapshots__/transform.js.snap, bindings/binding_typescript_wasm/__tests__/transform.js, bindings/binding_typescript_wasm/src/lib.rs, crates/swc_error_reporters/Cargo.toml, crates/swc_error_reporters/src/handler.rs, crates/swc_error_reporters/src/json_emitter.rs, crates/swc_error_reporters/src/lib.rs, crates/swc_fast_ts_strip/src/lib.rs, crates/swc_fast_ts_strip/tests/errors/enums.swc-stderr, crates/swc_fast_ts_strip/tests/errors/export-equals.swc-stderr, crates/swc_fast_ts_strip/tests/errors/import-equals.swc-stderr, crates/swc_fast_ts_strip/tests/errors/invalid-syntax-1.swc-stderr, crates/swc_fast_ts_strip/tests/errors/issue-9977.swc-stderr, crates/swc_fast_ts_strip/tests/errors/modules.swc-stderr, crates/swc_fast_ts_strip/tests/errors/namespaces.swc-stderr, crates/swc_fast_ts_strip/tests/errors/parameter-property.swc-stderr, crates/swc_fast_ts_strip/tests/errors/ts-module.swc-stderr, crates/swc_fast_ts_strip/tests/errors/ts-namespace.swc-stderr, crates/swc_fast_ts_strip/tests/errors/type-assertions.swc-stderr, crates/swc_fast_ts_strip/tests/fixture/class-properties.swc-stderr, crates/swc_fast_ts_strip/tests/fixture/unicode.swc-stderr
- Improves span for `swc_fast_ts_strip`.
- Add `try_with_json_handler` to `swc_error_reporters`.
- `@swc/wasm-typescript` now throws a string separated by `\n`.
- Closes https://github.com/swc-project/swc/issues/9884
=> feat(ts/fast-strip): Emit json errors

.github/workflows/bench.yml, scripts/bench/list-crates-with-bench.sh
- Closes https://github.com/swc-project/swc/issues/10148
=> chore(ci): Speed up benchmark action by sharding

crates/swc_ecma_fast_parser/src/lexer/number.rs, crates/swc_ecma_fast_parser/src/lexer/tests.rs
This is a PR to ensure correctness.
- This is a follow-up of https://github.com/swc-project/swc/pull/10145
=> fix(es/fast-lexer): Fix lexing of numeric literals

Cargo.lock, crates/swc_ecma_fast_parser/src/lexer/mod.rs
Previously the SIMD function processed one byte at a time.
=> perf(es/fast-lexer): Make whitespace skipper use SIMD properly

.github/swc-ecosystem-ci/tests/swc-plugins.ts
Add swc_plugins wasm plugin test to ecosystem ci to avoid the latest `@swc/core` load wams plugin failed.
Reference PR: https://github.com/swc-project/plugins/pull/424
- Closes https://github.com/swc-project/swc/issues/10127
=> ci: add swc_plugins test to ecosystem CI

.changeset/foo-bar.md, crates/swc/tests/fixture/issues-10xxx/10149/1/input/.swcrc, crates/swc/tests/fixture/issues-10xxx/10149/1/input/index.ts, crates/swc/tests/fixture/issues-10xxx/10149/1/output/index.ts, crates/swc/tests/fixture/issues-10xxx/10149/2/input/.swcrc, crates/swc/tests/fixture/issues-10xxx/10149/2/input/index.ts, crates/swc/tests/fixture/issues-10xxx/10149/2/output/index.ts, crates/swc/tests/fixture/issues-1xxx/1575/case1/output/index.js, crates/swc/tests/fixture/issues-1xxx/1575/case2/output/index.js, crates/swc_ecma_compat_es2017/src/async_to_generator.rs
=> fix(es/compat): Hoist `arguments` in object method while lowering async functions

crates/swc_ecma_fast_parser/src/lexer/string.rs
I'll merge this if there's no regression because this is an obvious optimization.
=> perf(es/fast-lexer): Use SIMD properly for string literals

crates/swc_ecma_fast_parser/src/token.rs
I'm not sure if this would be faster, but AI suggested to do it.
=> perf(es/fast-lexer): Add length-based fast path for keywords

crates/swc_ecma_fast_parser/src/lexer/cursor.rs
`pos` and `len` are frequently accessed
=> perf(es/fast-lexer): Optimize memory layout of cursor

Cargo.lock, crates/swc_ecma_fast_parser/Cargo.toml, crates/swc_ecma_fast_parser/src/lexer/cursor.rs, crates/swc_ecma_fast_parser/src/lexer/identifier.rs, crates/swc_ecma_fast_parser/src/token.rs
Replaces the perfect hash function (PHF) keyword lookup with a more performant static keyword lookup table. The new implementation:
- Removes dependency on `phf` crate
- Adds a custom static keyword lookup mechanism
- Introduces a more cache-friendly keyword search algorithm
- Adds support for the `module` keyword
=> perf(es/fast-lexer): replace PHF with static keyword lookup table

.changeset/unlucky-olives-whisper.md, crates/swc_typescript/src/fast_dts/visitors/type_usage.rs, crates/swc_typescript/tests/fixture/issues/10171.snap, crates/swc_typescript/tests/fixture/issues/10171.ts
Fixes https://github.com/swc-project/swc/issues/10171
=> fix(typescript): Skip the body of ArrowExpr in type usage analysis 

crates/swc_ecma_minifier/scripts/size.sh, crates/swc_ecma_minifier/src/compress/mod.rs
```
Finished `release` profile [optimized + debuginfo] target(s) in 48.34s
Running `/Users/kdy1/projects/s/minifier/target/release/examples/minifier ./benches/full/antd.js`
File: ./benches/full/antd.js
456855
Finished `release` profile [optimized + debuginfo] target(s) in 0.15s
Running `/Users/kdy1/projects/s/minifier/target/release/examples/minifier ./benches/full/d3.js`
File: ./benches/full/d3.js
86899
Finished `release` profile [optimized + debuginfo] target(s) in 0.14s
Running `/Users/kdy1/projects/s/minifier/target/release/examples/minifier ./benches/full/echarts.js`
File: ./benches/full/echarts.js
320588
Finished `release` profile [optimized + debuginfo] target(s) in 0.18s
Running `/Users/kdy1/projects/s/minifier/target/release/examples/minifier …
```
=> chore(es/minifier): Fix lints & `size.sh`

crates/swc_ecma_minifier/benches/full.rs
Those benchmarks are too slow.
=> test(es/minifier): Disable real-world benchmarks on CI

crates/swc_ecma_minifier/scripts/test.sh
We can run `size.rs` tests concurrently with compress tests, so do it. Without this patch, the script is too slow.
=> chore(es/minifier): Make `test.sh` faster

.changeset/new-dancers-remember.md, crates/swc_ecma_ast/src/expr.rs, crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_transforms_optimization/src/simplify/branch/mod.rs, crates/swc_ecma_transforms_optimization/src/simplify/expr/mod.rs
This is a breaking change, so I deprecated it instead of removing it.
=> fix(es/ast): Fix Typo in API

crates/swc_ecma_minifier/src/compress/pure/misc.rs, crates/swc_ecma_minifier/src/compress/pure/mod.rs
Previously, numbers could be dropped wrongly if they were not zero-valued. It's not realistic inreal-worldworld source code, but it is still a bug.
=> fix(es/minifier): Do not drop numbers incorrectly

.changeset/smart-flies-sort.md, crates/swc_ecma_minifier/src/compress/pure/vars.rs
`styled-jsx` passes typescript input to the `Evaluator`.
=> fix(es/minifier): Allow TypeScript nodes to fix `styled-jsx`

.changeset/loud-humans-arrive.md, crates/swc/tests/fixture/issues-8xxx/8251/output/2.js, crates/swc/tests/size.rs, crates/swc/tests/vercel/full/firebase/dist/1/output/index.js, crates/swc_ecma_minifier/src/js.rs, packages/core/__tests__/minify_test.mjs
AFAIK all bundlers used in production support extracting license comments. We can default to the smallest size, I think.
=> feat(es/minifier): Default to the smallest size

bindings/binding_core_wasm/src/types.rs, bindings/binding_minifier_wasm/src/types.rs, crates/swc/src/config/mod.rs
- Closes https://github.com/swc-project/swc/issues/10230
=> fix(es/minifier): Make `inline_globals` noop by default

.changeset/silver-fishes-fry.md, bindings/binding_typescript_wasm/__tests__/__snapshots__/transform.js.snap, crates/swc_ecma_parser/src/parser/expr/ops.rs
=> fix(es/parser): Fix span of wrong `await` tokens

bindings/binding_core_node/src/parse.rs, packages/core/__tests__/parse/api_test.js, packages/core/binding.d.ts
- Enhanced existing `parse` and `parseSync` functions to accept both string and Buffer inputs.
- Updated TypeScript definitions and JavaScript bindings to reflect the new input types.
- Improved tests to cover the new capabilities for parsing from both string and Buffer inputs.
Fixes: #9876
=> feat(bindings): Enhance existing parse function to accept both string and buffer types #9876

.changeset/weak-coins-cheat.md, crates/swc_ecma_parser/src/parser/macros.rs, crates/swc_ecma_parser/src/parser/stmt/module_item.rs, crates/swc_ecma_parser/tests/js.rs, crates/swc_ecma_parser/tests/js/issue-10372/config.json, crates/swc_ecma_parser/tests/js/issue-10372/input.js, crates/swc_ecma_parser/tests/js/issue-10372/input.js.json
- Closes https://github.com/swc-project/swc/issues/10372
=> fix(es/parser): Parse `export default from;` with `exportDefaultFrom: true` option

.changeset/five-jobs-teach.md, Cargo.lock, crates/swc_ecma_minifier/src/program_data.rs, crates/swc_ecma_usage_analyzer/Cargo.toml, crates/swc_ecma_usage_analyzer/src/analyzer/ctx.rs, crates/swc_ecma_usage_analyzer/src/analyzer/mod.rs
Related https://github.com/swc-project/swc/issues/10379
context 16 bytes -> 8 bytes
Let's wait for the benchmark results
=> perf(es/minifier): Use bigflags to reduce context size of analyzer

.changeset/selfish-pears-shake.md, crates/swc_ecma_parser/src/parser/class_and_fn.rs, crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_parser/src/parser/expr/ops.rs, crates/swc_ecma_parser/src/parser/mod.rs, crates/swc_ecma_parser/src/parser/stmt.rs
I'm not sure whether this is correct. I just think `found_module_item` is a property of the whole Program rather than one function scope. This may reduce the cost of creating `State`(72 bytes -> 64 bytes) in `parse_fn_body`.
=> perf(es/parser): move `found_module_item` to `Parser`

crates/swc_ecma_usage_analyzer/src/alias/ctx.rs, crates/swc_ecma_usage_analyzer/src/alias/mod.rs
Related https://github.com/swc-project/swc/issues/10379
Context size 3 bytes -> 1 byte
=> perf(es/minifier): Use bitflags to reduce context size of `InfectionCollector` 

Cargo.lock, crates/swc_ecma_minifier/Cargo.toml, crates/swc_ecma_minifier/src/compress/optimize/conditionals.rs, crates/swc_ecma_minifier/src/compress/optimize/dead_code.rs, crates/swc_ecma_minifier/src/compress/optimize/evaluate.rs, crates/swc_ecma_minifier/src/compress/optimize/if_return.rs, crates/swc_ecma_minifier/src/compress/optimize/iife.rs, crates/swc_ecma_minifier/src/compress/optimize/inline.rs, crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/src/compress/optimize/ops.rs, crates/swc_ecma_minifier/src/compress/optimize/props.rs, crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/src/compress/optimize/unused.rs
Related https://github.com/swc-project/swc/issues/10379
context 48 bytes -> 24 bytes
=> perf(es/minifier): Use bitflags to reduce compress context size

crates/swc_core/src/lib.rs, crates/swc_core/src/plugin.rs
This PR fixes an issue where downstream projects using swc_core as a dependency encounter build errors when generating documentation with --cfg docsrs. The problem occurs because certain conditional compilation flags include docsrs directly, causing rustdoc to include code that depends on modules not available in downstream projects.
The fix modifies conditional compilation flags in lib.rs and plugin.rs to require both docsrs and the relevant feature to be enabled, rather than including code with only docsrs set. This ensures that when a downstream project builds docs with --cfg docsrs, code is only included if the specific feature is also enabled
None. This change only affects documentation generation and has no impact on runtime behavior.
Closes …
=> fix(swc_core): Fix downstream doc builds

.changeset/flat-humans-sneeze.md, crates/swc_common/src/input.rs
https://github.com/rust-lang/rust/blob/1.86.0/compiler/rustc_lexer/src/cursor.rs#L56 mentions that using `next` is more optimized than `nth`, let's give this optimization a try.
=> pref(es/common): use next rather than nth

.changeset/smooth-parrots-happen.md, crates/swc_ecma_codegen/src/lib.rs, crates/swc_ecma_compat_es2015/src/classes/mod.rs, crates/swc_ecma_compat_es2015/src/destructuring.rs, crates/swc_ecma_compat_es2015/src/for_of.rs, crates/swc_ecma_compat_es2015/src/generator.rs, crates/swc_ecma_compat_es2015/src/spread.rs, crates/swc_ecma_compat_es2015/src/typeof_symbol.rs, crates/swc_ecma_compat_es2016/src/exponentiation.rs, crates/swc_ecma_compat_es2017/src/async_to_generator.rs, crates/swc_ecma_compat_es2018/src/object_rest.rs, crates/swc_ecma_compat_es2020/src/nullish_coalescing.rs, crates/swc_ecma_minifier/src/compress/optimize/iife.rs, crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/src/compress/optimize/sequences.rs, crates/swc_ecma_minifier/src/compress/optimize/unused.rs, crates/swc_ecma_minifier/src/compress/util/mod.rs, crates/swc_ecma_parser/src/parser/expr.rs, crates/swc_ecma_parser/src/parser/typescript.rs, crates/swc_ecma_transforms_optimization/src/simplify/dce/mod.rs, crates/swc_ecma_usage_analyzer/src/analyzer/mod.rs, crates/swc_trace_macro/src/lib.rs
ast related tracing contains too much trace data and seems not suitable for info level tracing, so change it to debug level which is same as rustc https://github.com/rust-lang/rust/blob/2ea33b591050c4ca1a3752830b29112638faecf6/compiler/rustc_ast_lowering/src/index.rs#L74
No
=> refactor: Use debug level tracing for ast related tracing

bindings/Cargo.toml
=> chore: Enable fat LTO by default

.changeset/ten-tables-design.md, crates/swc_ecma_react_compiler/src/fast_check.rs
JSX is also a target of the React Compiler
- https://github.com/vercel/next.js/pull/79479
=> fix(es/react-compiler): Fix usefulness detection

.changeset/silent-cameras-invent.md, crates/swc_typescript/src/fast_dts/class.rs, crates/swc_typescript/src/fast_dts/types.rs, crates/swc_typescript/src/fast_dts/util/ast_ext.rs, crates/swc_typescript/tests/fixture/symbol-getter-setter.snap, crates/swc_typescript/tests/fixture/symbol-getter-setter.ts
=> fix(ts/fast-dts): Correctly emit Symbol-keyed accessors in declarations

.changeset/big-knives-flow.md, crates/swc_common/src/source_map.rs
To make multi-file source map generation practically usable, we also need this change.
=> feat(swc_common): Add `map_raw_pos` to `Files`

.changeset/moody-cows-sleep.md, crates/swc_common/src/source_map.rs
We don't generate `BytePos(0)` so it was not a big deal for us, but now it matters because external crates are now allowed to generate `BytePos`
=> fix(swc_common): Fix skip condition for sourcemap

.changeset/sixty-pans-help.md, crates/swc_ecma_codegen/src/lib.rs
This was the only place where `Comments` were queried for dummy spans (`BytePos(0)`)
=> fix(es/codegen): Don't call `cmt.get_leading` for dummy span

bindings/binding_core_wasm/src/types.rs, bindings/binding_minifier_wasm/src/types.rs, packages/types/index.ts
Add TypeScript definition for `jsc.output.charset`
Ref:
- https://swc.rs/docs/configuration/compilation#jscoutputcharset
- https://github.com/swc-project/swc/pull/4708
- https://github.com/swc-project/swc/pull/7258
=> fix(@swc/types): add `jsc.output.charset`

.changeset/smart-wombats-share.md, crates/swc/tests/fixture/issues-9xxx/9821/case-default/input/.swcrc, crates/swc/tests/fixture/issues-9xxx/9821/case-default/input/index.ts, crates/swc/tests/fixture/issues-9xxx/9821/case-default/output/index.ts, crates/swc/tests/fixture/issues-9xxx/9821/case-verbatimModuleSyntax/input/.swcrc, crates/swc/tests/fixture/issues-9xxx/9821/case-verbatimModuleSyntax/input/index.ts, crates/swc/tests/fixture/issues-9xxx/9821/case-verbatimModuleSyntax/output/index.ts, crates/swc_ecma_transforms_typescript/src/strip_type.rs
=> fix(es/typescript): Handle `export declare var` in namespace

.changeset/weak-shirts-count.md, crates/swc_typescript/src/fast_dts/visitors/type_usage.rs, crates/swc_typescript/tests/fixture/issues/10576.snap, crates/swc_typescript/tests/fixture/issues/10576.ts
We should add egdes for all three possible namespaces because there's no mechanism to merge SymbolFlags with same Ids.
For example: 
```ts
const a = 1 // SymbolFlags::Value
type a = number // SymbolFlags::Type
class A {} // SymbolFlags::all()
export { a, A }
```
Ideally we should merge two `a`s with `SymbolFlags::all`. But it's not efficient to merge nodes in the real time. So when exporting symbols, we add edges for all possible cases.
fixes: https://github.com/swc-project/swc/issues/10576
=> fix(isolated_declarations): add edges `SymbolFlags::Value` and `SymbolFlags::Type` in exports

.changeset/soft-dolphins-divide.md, Cargo.lock, Cargo.toml
This deduplicates some wasmer dependencies.
This uses 0.600.0 instead of 0.600.1 because of a version range issue in `url` https://github.com/wasmerio/wasmer/issues/5597 (which would be a breaking change to support).
=> chore(plugin/runner): Update `virtual-fs` to dedupe dependencies

crates/swc_ecma_lexer/src/common/parser/expr.rs, crates/swc_ecma_lexer/src/common/parser/ident.rs, crates/swc_ecma_lexer/src/common/parser/jsx.rs, crates/swc_ecma_lexer/src/common/parser/macros.rs, crates/swc_ecma_lexer/src/common/parser/mod.rs, crates/swc_ecma_lexer/src/common/parser/module_item.rs, crates/swc_ecma_lexer/src/common/parser/stmt.rs, crates/swc_ecma_lexer/src/common/parser/typescript.rs
try removing `cur!($parser, false)` since in most cases it's unnecessary to generate the error structure at this point.
=> refactor(es/parser): Remove `cur!(false)` macro

crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/src/compress/pure/drop_console.rs, crates/swc_ecma_minifier/src/compress/pure/misc.rs, crates/swc_ecma_minifier/src/compress/pure/mod.rs, crates/swc_ecma_minifier/src/compress/pure/strings.rs, crates/swc_ecma_transforms_optimization/src/simplify/expr/mod.rs
From profiling, there are some time consuming function due to the deeply nested binary expr:
1. recursively visit expr
2. recursive function: `compress::pure::misc::remove_invalid`
3. recursive function: `compress::optimize::remove_invalid_bin`
4. recursive function: `swc_ecma_utils::is_str`
Sadly it's hard to eliminate all of them (especially reason 1). This pr only decreases the calling of function 2, 3, 4.
Before: 2.17s with samply https://share.firefox.dev/3TmuvkH
After: 0.77s with samply https://share.firefox.dev/3FYPMOk 
related: https://github.com/swc-project/swc/issues/10219
=> perf(es/minifier): avoid calling some costly function when optimizing deep nested binary expr

.changeset/yellow-pugs-relax.md, crates/swc/src/config/mod.rs
fn `build_resolver` should not return cache when pass different `file_extension` value
https://github.com/swc-project/swc/blob/20551778ff9ce4cbde59b36a1582993f656b2eef/crates/swc/src/config/mod.rs#L1859-L1861
=> fix(swc): Fix wrong caching of resolvers regarding file exts

.changeset/brave-drinks-remain.md, crates/swc_typescript/src/fast_dts/visitors/type_usage.rs, crates/swc_typescript/tests/fixture/issues/10620.snap, crates/swc_typescript/tests/fixture/issues/10620.ts
When the name of the decl is a binding ident, the usage of its type annotation should also depend on the usage of the ident name
fixes https://github.com/swc-project/swc/issues/10620
=> fix(isolated_declaration): the usage of its type annotation should also depend on the usage of the ident name

packages/core/src/index.ts
As pointed by @dmichon-msft with https://github.com/swc-project/swc/pull/10628/files#r2157725382
=> fix(es/minifier): Fix `Buffer` handling of `minify()` API

crates/swc_ecma_lexer/src/common/lexer/mod.rs
=> perf(es/lexer): Compare `\n` first

.changeset/tidy-tigers-lick.md, crates/hstr/src/dynamic.rs
The `copy_from_slice` method was not stabilized as `const` until 1.90. This replaces that method with a simple while loop which should be much more 'const compatible'
Tested with `rustup run 1.86 cargo test   -p hstr`  (note that also required removing the `-Zshare-generics=y` compiler flag).
Fixes #10662
=> Fix 10662: make the inline optimization compatible with earlier rust versions

.changeset/tidy-meals-share.md, crates/swc_typescript/src/fast_dts/class.rs, crates/swc_typescript/tests/fixture/class-private-constructor.snap, crates/swc_typescript/tests/fixture/class-private-constructor.ts
=> fix(ts/isolated-dts): Skip parameters without accessibility modifiers in private constructors

.changeset/stupid-llamas-remain.md, crates/swc_fast_ts_strip/src/lib.rs
Learnt from oxc's codegen. However, swc doesn't provide a universal codegen api, so the users should do this by themselves.
=> perf(ts/fast-strip): prealloc buf for codegen

.changeset/mean-pans-burn.md, crates/swc_ecma_parser/src/parser/jsx/mod.rs, crates/swc_ecma_parser/tests/jsx/errors/issue-10681/index.js, crates/swc_ecma_parser/tests/jsx/errors/issue-10681/index.js.swc-stderr
=> fix(es/parser): Throw error if JSX does not end with `>`

bindings/binding_core_wasm/src/types.rs, crates/swc/tests/fixture/issues-1xxx/1525/case1/input/.swcrc, crates/swc/tests/fixture/issues-1xxx/1687/.input/.swcrc, crates/swc/tests/fixture/issues-8xxx/8210/input/.swcrc, crates/swc/tests/tsc.rs, crates/swc_ecma_transforms_react/src/jsx/mod.rs, packages/types/index.ts
=> refactor(es/react): Add `preserve` supports and ts config style preset

.changeset/long-parrots-love.md, crates/swc/tests/fixture/issues-10xxx/10698/input/.swcrc, crates/swc/tests/fixture/issues-10xxx/10698/input/index.jsx, crates/swc/tests/fixture/issues-10xxx/10698/output/index.jsx, crates/swc_ecma_parser/src/parser/jsx/mod.rs, crates/swc_ecma_parser/tests/jsx/basic/issue-10698/input.js, crates/swc_ecma_parser/tests/jsx/basic/issue-10698/input.js.json
=> fix(es/parser): Support keywords as JSX member expression properties

.changeset/gentle-gorillas-rescue.md, crates/swc_ecma_parser/Cargo.toml, crates/swc_ecma_parser/src/lexer/mod.rs, crates/swc_ecma_parser/src/lib.rs
See https://github.com/swc-project/swc/discussions/10683
=> feat(es/parser): expose Token API with unstable feature flag

bindings/binding_core_wasm/src/types.rs, bindings/binding_minifier_wasm/src/types.rs, crates/swc_ecma_ast/src/jsx.rs, crates/swc_ecma_codegen/src/jsx.rs, crates/swc_ecma_lexer/src/common/parser/jsx.rs, crates/swc_ecma_parser/src/parser/jsx/mod.rs, crates/swc_ecma_quote_macros/src/ast/expr.rs, crates/swc_ecma_transforms_react/src/jsx/automatic.rs, crates/swc_ecma_transforms_react/src/jsx/classic.rs, crates/swc_estree_compat/src/babelify/jsx.rs, crates/swc_estree_compat/src/swcify/expr.rs, packages/core/src/Visitor.ts, packages/types/index.ts
=> refactor(es/ast): Replace `Literal` with `StringLiteral` in JSXAttrValue type

.changeset/blue-beers-raise.md, .changeset/quiet-dolphins-brush.md, crates/swc_core/Cargo.toml, crates/swc_estree_compat/Cargo.toml
setting default-features=false for swc usage to avoid introduce unnecessary lint and es3 code for consumers
yes for swc and swc_core crate api 
=> fix(es): Use `default-features = false` for `swc` crate usages

crates/swc_ecma_lexer/src/common/lexer/mod.rs, crates/swc_ecma_lexer/src/lexer/table.rs, crates/swc_ecma_parser/src/lexer/table.rs
When handling keywords, we can make sure that the first byte is a valid ASCII.
I will clean up the code if it's worth
=> perf(es/lexer): Remove unnecessary check when reading keywords

.changeset/sweet-lobsters-hammer.md, Cargo.lock, Cargo.toml, crates/swc_plugin_runner/Cargo.toml, crates/swc_plugin_runner/src/wasix_runtime.rs
In https://github.com/wasmerio/wasmer/issues/5612 we introduce sys-minimal feature to support only enable used wasmer-wasix feature to reduce binary size
This PR upgrade wasmer related crate to latest version and use sys-minimal feature instead of sys feature
it should pass all tests in swc_plugin repo, but not 100% sure will pass all existing wasm plugins
=> feat(plugin/runner): Use wasmer-wasix sys-minimal feature to reduce binary size

.changeset/gentle-hounds-buy.md, crates/swc/Cargo.toml, crates/swc_bundler/Cargo.toml, crates/swc_compiler_base/Cargo.toml, crates/swc_core/Cargo.toml, crates/swc_ecma_minifier/Cargo.toml, crates/swc_ecma_quote_macros/Cargo.toml, crates/swc_ecma_transforms_base/Cargo.toml, crates/swc_ecma_transforms_module/Cargo.toml, crates/swc_ecma_transforms_optimization/Cargo.toml, crates/swc_ecma_transforms_react/Cargo.toml, crates/swc_estree_compat/Cargo.toml, crates/swc_html_minifier/Cargo.toml, crates/swc_node_bundler/Cargo.toml, crates/swc_ts_fast_strip/Cargo.toml
This prevents the transitive dependency on stacker when using crates like swc_core and swc_ecma_transforms_base. All crates now explicitly opt-in to only the features they need (TypeScript in most cases).
- Closes #8422
=> fix(swc_core): Add `default-features = false` to drop `stacker`

.changeset/gentle-spies-complain.md, Cargo.lock, crates/swc_ecma_preset_env/Cargo.toml, crates/swc_ecma_preset_env/src/lib.rs, crates/swc_ecma_preset_env/src/transform_data.rs
=> refactor(es/preset-env): Apply swc_ecma_compiler in preset env

.changeset/honest-geese-rest.md, crates/swc_ecma_minifier/src/compress/optimize/dead_code.rs, crates/swc_ecma_minifier/tests/benches-full/echarts.js, crates/swc_ecma_minifier/tests/benches-full/terser.js, crates/swc_ecma_minifier/tests/benches-full/victory.js, crates/swc_ecma_minifier/tests/fixture/issues/10935/input.js, crates/swc_ecma_minifier/tests/fixture/issues/10935/output.js, crates/swc_ecma_minifier/tests/fixture/issues/2257/full/output.js, crates/swc_ecma_minifier/tests/fixture/issues/typescript/1/output.js, crates/swc_ecma_minifier/tests/fixture/next/react-pdf-renderer/output.js, crates/swc_ecma_minifier/tests/fixture/next/regression-1/framework-798bab57daac3897/output.js, crates/swc_ecma_minifier/tests/fixture/next/syncfusion/933-e9f9a6bf671b96fc/output.js, crates/swc_ecma_minifier/tests/libs-size.snapshot.md
=> fix(es/minifier): Check exported when optimize last expr

.changeset/breezy-experts-complain.md, crates/swc/tests/tsc-references/privateNamesConstructorChain-1.2.minified.js, crates/swc_ecma_minifier/tests/fixture/issues/cycle-1/input.js, crates/swc_ecma_minifier/tests/fixture/issues/cycle-1/output.js, crates/swc_ecma_minifier/tests/fixture/issues/cycle-2/input.js, crates/swc_ecma_minifier/tests/fixture/issues/cycle-2/output.js, crates/swc_ecma_transforms_optimization/src/simplify/dce/mod.rs
The super class expression of a class declaration should be analyzed from the outside context of the class declarartions.
=> fix(es/minifier): Fix cycle detection

.changeset/flat-turkeys-hammer.md, crates/swc/src/config/mod.rs
This PR #10449 changed `GlobalPassOption.build` to `pub(crate)`, but ReactLynx's WASM plugin depends on it (see https://github.com/lynx-family/lynx-stack/blob/main/packages/react/transform/src/lib.rs#L412). 
When upgrading `swc_core`, we encountered a crash due to this change. This PR aims to restore `GlobalPassOption.build` to `pub`.
=> fix: expose GlobalPassOption.build

.changeset/stupid-ligers-juggle.md, Cargo.lock, Cargo.toml, crates/swc_plugin_backend_tests/tests/css-plugins/swc_noop_plugin/Cargo.lock, crates/swc_plugin_backend_tests/tests/ecma_integration.rs, crates/swc_plugin_backend_tests/tests/fixture/issue_6404/Cargo.lock, crates/swc_plugin_backend_tests/tests/fixture/swc_internal_plugin/Cargo.lock, crates/swc_plugin_backend_tests/tests/fixture/swc_noop_plugin/Cargo.lock, crates/swc_plugin_backend_wasmtime/Cargo.toml, crates/swc_plugin_backend_wasmtime/src/lib.rs
Currently, `wasmtime-wasi` uses tokio `block_on` internally, which causes panic when used in the tokio runtime.
I originally thought this could be solved by use `block_in_place`, but the large scope of `block_in_place` caused a serious performance regression (even without use plugin). see https://github.com/web-infra-dev/rspack/pull/11303#issuecomment-3157488436
Switch to `wasi-common` is a better choice, which simplifies the wasi implment and makes it independent of tokio.
=> refactor(plugin/runner): Switch `wasmtime-wasi` to `wasi-common`

.changeset/ninety-cobras-stare.md, crates/swc_ecma_transforms_module/src/amd.rs, crates/swc_ecma_transforms_module/src/common_js.rs, crates/swc_ecma_transforms_module/tests/fixture/common/import-meta/input.js, crates/swc_ecma_transforms_module/tests/fixture/common/import-meta/output.amd.js, crates/swc_ecma_transforms_module/tests/fixture/common/import-meta/output.cjs, crates/swc_ecma_transforms_module/tests/fixture/common/import-meta/output.umd.js
`import.meta?.url` is not currently supported so it will not get transpiled. my thought is that it should get transpiled, so we are treating it the same as if the optional chain did not exist.
Example of this in `@cesium/engine` here: https://github.com/CesiumGS/cesium/blob/52f55d0e7063115b47b12fee20bfc1c291edcddb/packages/engine/Source/Core/buildModuleUrl.js#L44
closes #10988
=> fix(es/module): Support optional chaining in `import.meta`

crates/swc_ecma_lexer/src/common/input.rs, crates/swc_ecma_lexer/src/common/lexer/token.rs, crates/swc_ecma_lexer/src/common/parser/buffer.rs, crates/swc_ecma_lexer/src/common/parser/mod.rs, crates/swc_ecma_lexer/src/common/parser/typescript.rs, crates/swc_ecma_lexer/src/input.rs, crates/swc_ecma_lexer/src/lexer/state.rs, crates/swc_ecma_lexer/src/parser/mod.rs, crates/swc_ecma_parser/src/lexer/capturing.rs, crates/swc_ecma_parser/src/lexer/state.rs, crates/swc_ecma_parser/src/parser/input.rs, crates/swc_ecma_parser/src/parser/mod.rs
There could be no need to clone entire lexer and parser when calling `try_parse_xxx` in typescript. Here introduces checkpoints which only contains necessary data to recover from failed trials. This is also the prerequisite for https://github.com/swc-project/swc/pull/11000. And we can also remove the `Rc<RefCell<T>>` in the lexer later 
I'm not sure the data is completed for correctness. Let's see the test results.
=> perf(es/parser): introduce checkpoint to reduce clone

crates/swc_ecma_lexer/src/common/input.rs, crates/swc_ecma_lexer/src/common/lexer/mod.rs, crates/swc_ecma_lexer/src/common/parser/mod.rs, crates/swc_ecma_lexer/src/common/parser/pat.rs, crates/swc_ecma_lexer/src/input.rs, crates/swc_ecma_lexer/src/lexer/mod.rs, crates/swc_ecma_lexer/src/lexer/state.rs, crates/swc_ecma_parser/src/lexer/capturing.rs, crates/swc_ecma_parser/src/lexer/mod.rs, crates/swc_ecma_parser/src/lexer/state.rs
See https://github.com/swc-project/swc/pull/11001
I also remove `comments` since it's immutable. But we should be careful not to clone entire parser and lexer (we can ensure this by benchmark)
=> perf(es/parser): remove useless `Rc<RefCell<T>>`

.changeset/ninety-parrots-flow.md, crates/swc/src/config/mod.rs, crates/swc_ecma_transforms_optimization/src/inline_globals.rs, crates/swc_ecma_transforms_optimization/src/lib.rs, crates/swc_ecma_transforms_optimization/tests/__swc_snapshots__/src/inline_globals.rs/issue_10831_1.js, crates/swc_node_bundler/src/loaders/swc.rs
Revert https://github.com/swc-project/swc/pull/10449
`inline_globals` API changes
fixes https://github.com/swc-project/swc/issues/10831
=> fix(es/optimization): Revert `perf(es/optimization): Rely on resolver from inline_globals`

.changeset/spicy-eagles-cover.md, crates/swc_ecma_lexer/src/token.rs
**Description:** The token was wrong here.
**Related issue (if exists):** None. I'm lazy.
=> fix(es/lexer): Fix token for `&&=`

crates/swc_ecma_minifier/src/compress/optimize/mod.rs, crates/swc_ecma_minifier/tests/fixture/issues/8737/output.js, crates/swc_ecma_minifier/tests/fixture/issues/8813/output.js, crates/swc_ecma_minifier/tests/fixture/issues/firebase-firestore/1/output.js, crates/swc_ecma_minifier/tests/fixture/next/target-es2015/static/chunks/main-04b5934c26266542/output.js, crates/swc_ecma_minifier/tests/fixture/next/wrap-contracts/output.js, crates/swc_html_minifier/tests/fixture/element/script/output.min.html
I was seeing this snapshot test failure when trying to upgrade swc in Turbopack:
```js
--- expected
+++ actual
@@ -1,3 +1,3 @@
-module.exports=["index.js",(t,e,o)=>{let s="Hello";console.log("Hello, world!",3,s),console.log(s)}];
+module.exports=["index.js",(o,s,t)=>{const e="Hello";console.log("Hello, world!",3,e),console.log(e)}];
```
The problem was that `is_top_level` was true here, even though the code is inside an arrow function:
https://github.com/swc-project/swc/blob/0557609d6f862f7632a67ce91163571e5284163f/crates/swc_ecma_minifier/src/compress/optimize/mod.rs#L2836
Probably caused by https://github.com/swc-project/swc/pull/11035
=> fix(es/minifier): Make `const_to_let` work in arrows again

crates/swc_ecma_lexer/src/lexer/state.rs, crates/swc_ecma_parser/src/lexer/capturing.rs, crates/swc_ecma_parser/src/lexer/state.rs, crates/swc_ecma_parser/tests/jsx/errors/adjacent-tags/input.js.swc-stderr, crates/swc_ts_fast_strip/src/lib.rs
For `/a/g`, before:
After:
Also revert some of https://github.com/swc-project/swc/pull/11058, which is a mistake in this case.
=> fix(es/lexer): Update regexp token span

bindings/binding_core_wasm/src/types.rs, bindings/binding_minifier_wasm/src/types.rs, packages/types/index.ts
Add TypeScript definition for `react.runtime: 'preserve'`.
- https://github.com/swc-project/swc/issues/9929#issuecomment-3227285828
- https://github.com/swc-project/swc/pull/11025
=> feat(@swc/types): Add `preserve` to `react.runtime`

.changeset/dry-queens-clean.md, crates/swc_ecma_minifier/src/compress/optimize/util.rs, crates/swc_ecma_minifier/tests/fixture/issues/11105/input.js, crates/swc_ecma_minifier/tests/fixture/issues/11105/output.js
When minifying object shorthand properties, the `__proto__` property should be converted to a computed property `["__proto__"]` instead of a regular key-value pair to preserve the original object behavior. This prevents changing the object's prototype chain during minification.
- Closes: #11105
=> fix(es/minifier): Preserve `__proto__` shorthand property behavior

.changeset/tender-buses-allow.md, crates/swc/tests/fixture/issues-10xxx/11118/input/.swcrc, crates/swc/tests/fixture/issues-10xxx/11118/input/index.js, crates/swc/tests/fixture/issues-10xxx/11118/output/index.js, crates/swc_ecma_compat_es2015/src/lib.rs, crates/swc_ecma_compat_es2015/src/spread.rs, crates/swc_ecma_preset_env/src/lib.rs, crates/swc_ecma_transforms_compat/tests/es2015_classes.rs, crates/swc_ecma_transforms_compat/tests/es2015_destructuring.rs, crates/swc_ecma_transforms_compat/tests/es2015_parameters.rs, crates/swc_ecma_transforms_compat/tests/es2015_spread.rs, crates/swc_ecma_transforms_compat/tests/es2018_object_rest_spread.rs, crates/swc_ecma_transforms_typescript/benches/compat.rs
=> fix(es/compat): Apply `Array.prototype.slice` to `arguments` in loose spread

.changeset/light-cheetahs-protect.md, crates/swc_ecma_parser/src/lexer/state.rs, crates/swc_ecma_parser/tests/jsx/basic/issue-11134/input.jsx, crates/swc_ecma_parser/tests/jsx/basic/issue-11134/input.jsx.json
This PR fixes a bug in the JSX lexer where attributes with keyword prefixes (like `if-abc`, `for-test`, etc.) were incorrectly parsed. The lexer was reusing stale identifier values from previous tokens instead of using the keyword itself.
For example, `<Component mod={{ helloworld: undefined }} if-abc="test" />` would incorrectly parse the attribute name as `helloworld-abc` instead of `if-abc`.
None
Fixes #11134
=> fix(es/parser): Handle JSX attributes with keyword prefixes correctly

.changeset/spotty-geese-relate.md, crates/swc_ecma_transforms_react/src/jsx/mod.rs
- Will fix .. https://github.com/denoland/deno/issues/30216
The expression span for `@jsxFrag null` wasn't being adjusted. This was leading to a source map panic when trying to format the error for `error: pragmaFrag cannot be set when runtime is automatic`.
If it needs a test, please let me know how to add fixtures for expected parse failures.
=> fix(es/transforms): Correct span for @jsxFrag as null literal
